In [1]:
import numpy as np
import pandas as pd

In [5]:
employees = pd.read_csv('employees.csv')

In [6]:
employees

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [8]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    object
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: float64(1), object(5)
memory usage: 47.1+ KB

In [9]:
employees = pd.read_csv('employees.csv', parse_dates = ['Start Date'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_6255/3936571947.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv('employees.csv', parse_dates = ['Start Date'])

In [10]:
employees

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

[1001 rows x 6 columns]

In [11]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [12]:
employees['Mgmt'].dtype

dtype('O')

In [13]:
employees.dtypes

First Name            object
Gender                object
Start Date    datetime64[ns]
Salary               float64
Mgmt                  object
Team                  object
dtype: object

In [14]:
employees['Mgmt'].astype(np.bool)

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [15]:
employees['Mgmt'] = employees['Mgmt'].astype(np.bool)

In [16]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [17]:
employees

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       NaN   True     Marketing
1        Thomas    Male 1996-03-31   61933.0   True           NaN
2         Maria  Female        NaT  130590.0  False       Finance
3         Jerry     NaN 2005-03-04  138705.0   True       Finance
4         Larry    Male 1998-01-24  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN   True           NaN

[1001 rows x 6 columns]

In [21]:
employees['Salary'] = employees['Salary'].fillna(0).astype(np.int64)

In [22]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int64(1), object(3)
memory usage: 40.2+ KB

In [23]:
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [26]:
employees['Gender'] = employees['Gender'].astype("category")

In [27]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [28]:
employees['Team'] = employees['Team'].astype("category")

In [29]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

In [30]:
employees

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
2         Maria  Female        NaT  130590  False       Finance
3         Jerry     NaN 2005-03-04  138705   True       Finance
4         Larry    Male 1998-01-24  101004   True            IT
...         ...     ...        ...     ...    ...           ...
996     Phillip    Male 1984-01-31   42392  False       Finance
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[1001 rows x 6 columns]

In [31]:
employees[employees['First Name'] == 'Maria']

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [32]:
employees[employees['Team'] != 'Finance']

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [33]:
employees[employees['Mgmt']]

     First Name  Gender Start Date  Salary  Mgmt         Team
0       Douglas    Male 1993-08-06       0  True    Marketing
1        Thomas    Male 1996-03-31   61933  True          NaN
3         Jerry     NaN 2005-03-04  138705  True      Finance
4         Larry    Male 1998-01-24  101004  True           IT
6          Ruby  Female 1987-08-17   65476  True      Product
...         ...     ...        ...     ...   ...          ...
992     Anthony    Male 2011-10-16  112769  True      Finance
993        Tina  Female 1997-05-15   56450  True  Engineering
994      George    Male 2013-06-21   98874  True    Marketing
999      Albert    Male 2012-05-15  129949  True        Sales
1000        NaN     NaN        NaT       0  True          NaN

[536 rows x 6 columns]

In [35]:
employees[employees['Salary'] >= 10000].sort_values(by=['Salary'], ascending=True)

    First Name  Gender Start Date  Salary   Mgmt     Team
576    Michael    Male 1993-07-30   35013  False  Product
238      Kevin    Male 1982-03-25   35061  False    Legal
82      Steven    Male 1980-03-30   35095   True       IT
63     Matthew    Male 2013-01-02   35203  False       HR
650    Cynthia  Female 1986-07-05   35381  False  Finance
..         ...     ...        ...     ...    ...      ...
160      Kathy  Female 2000-03-18  149563   True  Finance
186        NaN  Female 2005-02-23  149654   True    Sales
828    Cynthia  Female 2006-07-12  149684  False  Product
429       Rose  Female 2015-05-28  149903  False       HR
644  Katherine  Female 1996-08-13  149908  False  Finance

[999 rows x 6 columns]

In [41]:
employees[((employees['Gender'] == 'Female') & (employees['Team'] == 'Business Dev')) | ~(employees['Mgmt'])].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
2       Maria  Female        NaT  130590  False       Finance
5      Dennis    Male 1987-04-18  115163  False         Legal
9     Frances  Female 2002-08-08  139852   True  Business Dev
13       Gary    Male 2008-01-27  109831  False         Sales
15    Lillian  Female 2016-06-05   59414  False       Product

In [42]:
team_lst = ['Legal', 'Marketing', 'Sales']

In [44]:
employees[employees['Team'].isin(team_lst)]

    First Name  Gender Start Date  Salary   Mgmt       Team
0      Douglas    Male 1993-08-06       0   True  Marketing
5       Dennis    Male 1987-04-18  115163  False      Legal
11       Julie  Female 1997-10-26  102508   True      Legal
13        Gary    Male 2008-01-27  109831  False      Sales
20        Lois     NaN 1995-04-22   64714   True      Legal
..         ...     ...        ...     ...    ...        ...
986      Donna  Female 1982-11-26   82871  False  Marketing
989     Justin     NaN 1991-02-10   38344  False      Legal
991       Rose  Female 2002-08-25  134505   True  Marketing
994     George    Male 2013-06-21   98874   True  Marketing
999     Albert    Male 2012-05-15  129949   True      Sales

[280 rows x 6 columns]

In [47]:
employees[employees['Salary'].between(80000, 90000, inclusive='both')]

    First Name  Gender Start Date  Salary   Mgmt         Team
19       Donna  Female 2010-07-22   81014  False      Product
31       Joyce     NaN 2005-02-20   88657  False      Product
35     Theresa  Female 2006-10-10   85182  False        Sales
45       Roger    Male 1980-04-17   88010   True        Sales
54        Sara  Female 2007-08-15   83677  False  Engineering
..         ...     ...        ...     ...    ...          ...
930      Nancy  Female 2001-09-10   85213   True    Marketing
956    Beverly  Female 1986-10-17   80838  False  Engineering
963        Ann  Female 1994-09-23   89443   True        Sales
985    Stephen     NaN 1983-07-10   85668  False        Legal
986      Donna  Female 1982-11-26   82871  False    Marketing

[94 rows x 6 columns]

In [52]:
len(employees[employees['Team'].isnull()])

44

In [53]:
employees.dropna()

    First Name  Gender Start Date  Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       0   True     Marketing
4        Larry    Male 1998-01-24  101004   True            IT
5       Dennis    Male 1987-04-18  115163  False         Legal
6         Ruby  Female 1987-08-17   65476   True       Product
8       Angela  Female 2005-11-22   95570   True   Engineering
..         ...     ...        ...     ...    ...           ...
994     George    Male 2013-06-21   98874   True     Marketing
996    Phillip    Male 1984-01-31   42392  False       Finance
997    Russell    Male 2013-05-20   96914  False       Product
998      Larry    Male 2013-04-20   60500  False  Business Dev
999     Albert    Male 2012-05-15  129949   True         Sales

[762 rows x 6 columns]

In [54]:
employees.dropna(how='all')

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
2         Maria  Female        NaT  130590  False       Finance
3         Jerry     NaN 2005-03-04  138705   True       Finance
4         Larry    Male 1998-01-24  101004   True            IT
...         ...     ...        ...     ...    ...           ...
996     Phillip    Male 1984-01-31   42392  False       Finance
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[1001 rows x 6 columns]

In [55]:
employees.dropna(subset=['Team', 'Gender'])

    First Name  Gender Start Date  Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       0   True     Marketing
2        Maria  Female        NaT  130590  False       Finance
4        Larry    Male 1998-01-24  101004   True            IT
5       Dennis    Male 1987-04-18  115163  False         Legal
6         Ruby  Female 1987-08-17   65476   True       Product
..         ...     ...        ...     ...    ...           ...
994     George    Male 2013-06-21   98874   True     Marketing
996    Phillip    Male 1984-01-31   42392  False       Finance
997    Russell    Male 2013-05-20   96914  False       Product
998      Larry    Male 2013-04-20   60500  False  Business Dev
999     Albert    Male 2012-05-15  129949   True         Sales

[815 rows x 6 columns]

In [57]:
employees.dropna(thresh=4)

    First Name  Gender Start Date  Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       0   True     Marketing
1       Thomas    Male 1996-03-31   61933   True           NaN
2        Maria  Female        NaT  130590  False       Finance
3        Jerry     NaN 2005-03-04  138705   True       Finance
4        Larry    Male 1998-01-24  101004   True            IT
..         ...     ...        ...     ...    ...           ...
995      Henry     NaN 2014-11-23  132483  False  Distribution
996    Phillip    Male 1984-01-31   42392  False       Finance
997    Russell    Male 2013-05-20   96914  False       Product
998      Larry    Male 2013-04-20   60500  False  Business Dev
999     Albert    Male 2012-05-15  129949   True         Sales

[999 rows x 6 columns]

In [59]:
employees['Team'].duplicated()

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [60]:
employees['Team'].duplicated(keep='first')

0       False
1       False
2       False
3        True
4       False
        ...
996      True
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [61]:
employees['Team'].duplicated(keep='last')

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [63]:
employees[~employees['Team'].duplicated(keep='first')]

   First Name  Gender Start Date  Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       0   True     Marketing
1      Thomas    Male 1996-03-31   61933   True           NaN
2       Maria  Female        NaT  130590  False       Finance
4       Larry    Male 1998-01-24  101004   True            IT
5      Dennis    Male 1987-04-18  115163  False         Legal
6        Ruby  Female 1987-08-17   65476   True       Product
8      Angela  Female 2005-11-22   95570   True   Engineering
9     Frances  Female 2002-08-08  139852   True  Business Dev
12    Brandon    Male 1980-12-01  112807   True            HR
13       Gary    Male 2008-01-27  109831  False         Sales
40    Michael    Male 2008-10-10   99283   True  Distribution

In [64]:
employees.drop_duplicates(subset=['Team'], keep='first')

   First Name  Gender Start Date  Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       0   True     Marketing
1      Thomas    Male 1996-03-31   61933   True           NaN
2       Maria  Female        NaT  130590  False       Finance
4       Larry    Male 1998-01-24  101004   True            IT
5      Dennis    Male 1987-04-18  115163  False         Legal
6        Ruby  Female 1987-08-17   65476   True       Product
8      Angela  Female 2005-11-22   95570   True   Engineering
9     Frances  Female 2002-08-08  139852   True  Business Dev
12    Brandon    Male 1980-12-01  112807   True            HR
13       Gary    Male 2008-01-27  109831  False         Sales
40    Michael    Male 2008-10-10   99283   True  Distribution

In [65]:
employees.drop_duplicates(subset=['Team'], keep='last')

     First Name  Gender Start Date  Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638  False            HR
989      Justin     NaN 1991-02-10   38344  False         Legal
990       Robin  Female 1987-07-24  100765   True            IT
993        Tina  Female 1997-05-15   56450   True   Engineering
994      George    Male 2013-06-21   98874   True     Marketing
995       Henry     NaN 2014-11-23  132483  False  Distribution
996     Phillip    Male 1984-01-31   42392  False       Finance
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

In [68]:
employees.drop_duplicates(subset=['Team'], keep=False)

Empty DataFrame
Columns: [First Name, Gender, Start Date, Salary, Mgmt, Team]
Index: []

In [69]:
employees.drop_duplicates(subset=['Team', 'First Name'], keep='first')

    First Name  Gender Start Date  Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       0   True     Marketing
1       Thomas    Male 1996-03-31   61933   True           NaN
2        Maria  Female        NaT  130590  False       Finance
3        Jerry     NaN 2005-03-04  138705   True       Finance
4        Larry    Male 1998-01-24  101004   True            IT
..         ...     ...        ...     ...    ...           ...
994     George    Male 2013-06-21   98874   True     Marketing
995      Henry     NaN 2014-11-23  132483  False  Distribution
996    Phillip    Male 1984-01-31   42392  False       Finance
998      Larry    Male 2013-04-20   60500  False  Business Dev
999     Albert    Male 2012-05-15  129949   True         Sales

[769 rows x 6 columns]

In [70]:
# Homework

In [73]:
# 1
netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_6255/3772658436.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'])

In [75]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [76]:
netflix.nunique()

title         5780
director      3024
date_added    1092
type             2
dtype: int64

In [77]:
netflix.count()

title         5837
director      3936
date_added    5195
type          5837
dtype: int64

In [78]:
netflix['type'] = netflix['type'].astype('category')

In [79]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [80]:
netflix.dtypes

title                 object
director              object
date_added    datetime64[ns]
type                category
dtype: object

In [81]:
# 2
netflix[netflix['title'] == 'Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [82]:
# 3
netflix['type'].unique()

['TV Show', 'Movie']
Categories (2, object): ['Movie', 'TV Show']

In [83]:
netflix[(netflix['director'] == 'Robert Rodriguez') & (netflix['type'] == 'Movie')]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [85]:
# 4
netflix[(netflix['director'] == 'Robert Altman') | (netflix['date_added'] == '2019-07-31')].sort_values(by=['date_added'])

                                title       director date_added     type
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
611                            Popeye  Robert Altman 2019-11-24    Movie

In [87]:
# 5
netflix[netflix['director'].isin(['Orson Welles', 'Aditya Kripalani', 'Sam Raimi'])]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [89]:
# 6
netflix[netflix['date_added'].between('2019-05-01', '2019-06-01', inclusive='both')]

,title,director,date_added,type
29,Chopsticks,Sachin Yardi,2019-05-31,Movie
60,Away From Home,NaN,2019-05-08,TV Show
82,III Smoking Barrels,Sanjib Dey,2019-06-01,Movie
108,Jailbirds,NaN,2019-05-10,TV Show
124,Pegasus,Han Han,2019-05-31,Movie
...,...,...,...,...
5671,Satan & Adam,V. Scott Balcerek,2019-06-01,Movie
5675,Rim of the World,McG,2019-05-24,Movie
5677,Malibu Rescue,Savage Steve Holland,2019-05-13,Movie
5739,Mission Istaanbul: Darr Ke Aagey Jeet Hai,Apoorva Lakhia,2019-05-16,Movie
5829,The Kindness Diaries,NaN,2019-05-01,TV Show

In [90]:
# 7
netflix[netflix['director'].isnull()]

                                      title director date_added     type
0                               Alias Grace      NaN 2017-11-03  TV Show
2                                  Lunatics      NaN 2019-04-19  TV Show
7                                    7SEEDS      NaN 2019-06-28  TV Show
15                                   Loaded      NaN 2018-04-01  TV Show
16                         The Family Court      NaN 2017-11-01  TV Show
...                                     ...      ...        ...      ...
5824  The Disappearance of Madeleine McCann      NaN 2019-03-15  TV Show
5825               Best.Worst.Weekend.Ever.      NaN 2018-10-19  TV Show
5829                   The Kindness Diaries      NaN 2019-05-01  TV Show
5831                  The Toys That Made Us      NaN        NaT  TV Show
5836                           Age of Glory      NaN        NaT  TV Show

[1901 rows x 4 columns]

In [91]:
netflix.dropna(subset=['director'])

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

In [93]:
netflix['date_added'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5832     True
5833     True
5834     True
5835     True
5836     True
Name: date_added, Length: 5837, dtype: bool

In [95]:
netflix.drop_duplicates(subset=['date_added'], keep=False)

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie