In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customers.csv')

In [3]:
df

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [4]:
df['Address'].count()

np.int64(9961)

In [5]:
len(df)

9961

In [6]:
df.count()

Name       9961
Address    9961
dtype: int64

In [10]:
df['Address'].str.split(pat=', ').apply(len).value_counts()

Address
4    9961
Name: count, dtype: int64

In [11]:
df[['Street', 'City', 'State', 'Zip']] = df['Address'].str.strip().str.split(pat=', ', expand=True)

In [12]:
df

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",355 Griffin Valley,Davidtown,New Mexico,17581

In [14]:
df = df.drop(labels=['Address'], axis=1)

In [15]:
df

,Name,Street,City,State,Zip
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...
9956,Dana Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581