In [1]:
import numpy as np
import pandas as pd

In [2]:
inspections = pd.read_csv('chicago_food_inspections.csv')
inspections

                                      Name             Risk
0               MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                              JETS PIZZA   Risk 2 (Medium)
2                               ROOM 1520      Risk 3 (Low)
3                MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                            CHARTWELLS       Risk 1 (High)
...                                    ...              ...
153805                         WOLCOTT'S      Risk 1 (High)
153806     DUNKIN DONUTS/BASKIN-ROBBINS     Risk 2 (Medium)
153807                           Cafe 608     Risk 1 (High)
153808                        mr.daniel's     Risk 1 (High)
153809                         TEMPO CAFE     Risk 1 (High)

[153810 rows x 2 columns]

In [3]:
inspections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153810 entries, 0 to 153809
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Name    153810 non-null  object
 1   Risk    153744 non-null  object
dtypes: object(2)
memory usage: 2.3+ MB

In [4]:
inspections.nunique()

Name    92553
Risk        4
dtype: int64

In [6]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [7]:
inspections.count()

Name    153810
Risk    153744
dtype: int64

In [8]:
inspections.head()

                          Name             Risk
0   MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                  JETS PIZZA   Risk 2 (Medium)
2                   ROOM 1520      Risk 3 (Low)
3    MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                CHARTWELLS       Risk 1 (High)

In [12]:
inspections['Name'].values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       ..., ' Cafe 608 ', "  mr.daniel's ", '   TEMPO CAFE '],
      shape=(153810,), dtype=object)

In [10]:
inspections['Risk']

0           Risk 1 (High)
1         Risk 2 (Medium)
2            Risk 3 (Low)
3           Risk 1 (High)
4           Risk 1 (High)
               ...
153805      Risk 1 (High)
153806    Risk 2 (Medium)
153807      Risk 1 (High)
153808      Risk 1 (High)
153809      Risk 1 (High)
Name: Risk, Length: 153810, dtype: object

In [13]:
inspections['Name'] = inspections['Name'].str.strip()

In [14]:
inspections['Name'].values

array(['MARRIOT MARQUIS CHICAGO', 'JETS PIZZA', 'ROOM 1520', ...,
       'Cafe 608', "mr.daniel's", 'TEMPO CAFE'],
      shape=(153810,), dtype=object)

In [16]:
inspections['Risk'].values

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', ...,
       'Risk 1 (High)', 'Risk 1 (High)', 'Risk 1 (High)'],
      shape=(153810,), dtype=object)

In [17]:
for col in inspections.columns:
    inspections[col] = inspections[col].str.strip()

In [18]:
inspections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153810 entries, 0 to 153809
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Name    153810 non-null  object
 1   Risk    153744 non-null  object
dtypes: object(2)
memory usage: 2.3+ MB

In [19]:
inspections.head()

                      Name             Risk
0  MARRIOT MARQUIS CHICAGO    Risk 1 (High)
1               JETS PIZZA  Risk 2 (Medium)
2                ROOM 1520     Risk 3 (Low)
3  MARRIOT MARQUIS CHICAGO    Risk 1 (High)
4               CHARTWELLS    Risk 1 (High)

In [20]:
inspections['Name'] = inspections['Name'].str.title()

In [21]:
inspections

                                Name             Risk
0            Marriot Marquis Chicago    Risk 1 (High)
1                         Jets Pizza  Risk 2 (Medium)
2                          Room 1520     Risk 3 (Low)
3            Marriot Marquis Chicago    Risk 1 (High)
4                         Chartwells    Risk 1 (High)
...                              ...              ...
153805                     Wolcott'S    Risk 1 (High)
153806  Dunkin Donuts/Baskin-Robbins  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   Mr.Daniel'S    Risk 1 (High)
153809                    Tempo Cafe    Risk 1 (High)

[153810 rows x 2 columns]

In [23]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [25]:
inspections['Risk'].replace('All', 'Risk 4 (Extreme)').unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)', nan], dtype=object)

In [34]:
inspections = inspections.dropna(subset=['Risk'])

In [35]:
inspections['Risk'] = inspections['Risk'].replace('All', 'Risk 4 (Extreme)')

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_1257/3643058301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inspections['Risk'] = inspections['Risk'].replace('All', 'Risk 4 (Extreme)')

In [36]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [38]:
inspections['Risk'].str.slice(5, 6).astype(np.int64)

0         1
1         2
2         3
3         1
4         1
         ..
153805    1
153806    2
153807    1
153808    1
153809    1
Name: Risk, Length: 153744, dtype: int64

In [39]:
inspections['Risk'].str.slice(8, -1).unique()

array(['High', 'Medium', 'Low', 'Extreme'], dtype=object)

In [40]:
inspections[inspections['Name'].str.lower().str.contains('pizza')]

                                    Name             Risk
1                             Jets Pizza  Risk 2 (Medium)
19         Nancy'S Home Of Stuffed Pizza    Risk 1 (High)
27            Nary'S Grill & Pizza ,Inc.    Risk 1 (High)
29                   Narys Grill & Pizza    Risk 1 (High)
68                         Colutas Pizza    Risk 1 (High)
...                                  ...              ...
153756       Angelo'S Stuffed Pizza Corp    Risk 1 (High)
153764                Cochiaros Pizza #2    Risk 1 (High)
153772  Fernando'S Mexican Grill & Pizza    Risk 1 (High)
153788            Reggio'S Pizza Express    Risk 1 (High)
153801        State Street Pizza Company    Risk 1 (High)

[3992 rows x 2 columns]

In [41]:
inspections[inspections['Name'].str.lower().str.startswith('tacos')]

                         Name           Risk
69               Tacos Nietos  Risk 1 (High)
556       Tacos El Tio 2 Inc.  Risk 1 (High)
675          Tacos Don Gabino  Risk 1 (High)
958       Tacos El Tio 2 Inc.  Risk 1 (High)
1036      Tacos El Tio 2 Inc.  Risk 1 (High)
...                       ...            ...
143587          Tacos De Luna  Risk 1 (High)
144026           Tacos Garcia  Risk 1 (High)
146174        Tacos Place'S 1  Risk 1 (High)
147810  Tacos Mario'S Limited  Risk 1 (High)
151191            Tacos Reyna  Risk 1 (High)

[105 rows x 2 columns]

In [42]:
inspections[inspections['Name'].str.lower().str.endswith('tacos')]

                   Name           Risk
382        Lazo'S Tacos  Risk 1 (High)
569        Lazo'S Tacos  Risk 1 (High)
2652       Flying Tacos   Risk 3 (Low)
3250       Jony'S Tacos  Risk 1 (High)
3812       Paco'S Tacos  Risk 1 (High)
...                 ...            ...
151121      Reyes Tacos  Risk 1 (High)
151318   El Macho Tacos  Risk 1 (High)
151801   El Macho Tacos  Risk 1 (High)
153087  Raymond'S Tacos  Risk 1 (High)
153504        Mis Tacos  Risk 1 (High)

[304 rows x 2 columns]

In [43]:
customers = pd.read_csv('customers.csv')
customers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [44]:
customers['Name'].str.len()

0       13
1       17
2       15
3       19
4       14
        ..
9956    13
9957    15
9958    10
9959    16
9960    16
Name: Name, Length: 9961, dtype: int64

In [49]:
customers['Name'].str.split(n=1).str.get(0)

0           Frank
1       Elizabeth
2          Donald
3         Michael
4         Jasmine
          ...
9956         Dana
9957       Amanda
9958         Eric
9959       Taylor
9960       Sherry
Name: Name, Length: 9961, dtype: object

In [50]:
customers['Name'].str.split(n=1).str.get(-1)

0           Manning
1           Johnson
2          Stephens
3       Vincent III
4            Zamora
           ...
9956       Browning
9957       Anderson
9958          Davis
9959      Hernandez
9960      Nicholson
Name: Name, Length: 9961, dtype: object

In [52]:
customers['Name'].str.split().str.len().value_counts()

Name
2    9734
3     227
Name: count, dtype: int64

In [54]:
customers[['First Name', 'Last Name']] = customers['Name'].str.split(n=1, expand=True)

In [55]:
customers.head()

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora

In [58]:
customers = customers.drop(labels=['Name'], axis=1)

In [59]:
customers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora

In [60]:
# Homework

In [61]:
# 1
customers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora

In [62]:
df = customers.copy()

In [63]:
df

,Address,First Name,Last Name
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [64]:
df['Address']

0       6461 Quinn Groves, East Matthew, New Hampshire...
1       1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2       19120 Fleming Manors, Prestonstad, Montana, 23495
3            441 Olivia Creek, Jimmymouth, Georgia, 82991
4       4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
                              ...
9956    762 Andrew Views Apt. 254, North Paul, New Mex...
9957    44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958    73015 Michelle Squares, Watsonville, West Virg...
9959         129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     355 Griffin Valley, Davidtown, New Mexico, 17581
Name: Address, Length: 9961, dtype: object

In [65]:
df['Address'].str.split(', ', expand=True)

                               0             1              2      3
0              6461 Quinn Groves  East Matthew  New Hampshire  16656
1     1360 Tracey Ports Apt. 419      Kyleport        Vermont  31924
2           19120 Fleming Manors   Prestonstad        Montana  23495
3               441 Olivia Creek    Jimmymouth        Georgia  82991
4     4246 Chelsey Ford Apt. 310     Karamouth           Utah  76252
...                          ...           ...            ...    ...
9956   762 Andrew Views Apt. 254    North Paul     New Mexico  28889
9957    44188 Day Crest Apt. 901   Lake Marcia          Maine  37378
9958      73015 Michelle Squares   Watsonville  West Virginia  03933
9959            129 Keith Greens     Haleyfurt       Oklahoma  98916
9960          355 Griffin Valley     Davidtown     New Mexico  17581

[9961 rows x 4 columns]

In [66]:
df[['Street', 'City', 'State', 'Zip']] = df['Address'].str.split(', ', expand=True)

In [67]:
df

,Address,First Name,Last Name,Street,City,State,Zip
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581

In [68]:
df = df.drop(labels=['Address'], axis=1)

In [69]:
df

,First Name,Last Name,Street,City,State,Zip
0,Frank,Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth,Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald,Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael,Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine,Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana,Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda,Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric,Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor,Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry,Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581