In [1]:
import numpy as np
import pandas as pd

In [2]:
import datetime as dt

In [3]:
birthday = dt.date(1991, 4, 12)
birthday

datetime.date(1991, 4, 12)

In [4]:
birthday.year

1991

In [5]:
birthday.month

4

In [6]:
birthday.day

12

In [7]:
alarm_clock = dt.time(6, 43, 25)
alarm_clock

datetime.time(6, 43, 25)

In [8]:
alarm_clock.hour

6

In [9]:
dt.time()

datetime.time(0, 0)

In [10]:
dt.time(hour=9, second=42)

datetime.time(9, 0, 42)

In [11]:
dt.time(19, 43, 22)

datetime.time(19, 43, 22)

In [12]:
moon_landing = dt.datetime(1969, 7, 20, 22, 56, 20)
moon_landing

datetime.datetime(1969, 7, 20, 22, 56, 20)

In [13]:
dt.datetime(2020, 1, 1)

datetime.datetime(2020, 1, 1, 0, 0)

In [14]:
dt.timedelta(weeks=8, days=6, hours=3, minutes=58, seconds=12)

datetime.timedelta(days=62, seconds=14292)

In [15]:
60*60*24

86400

In [16]:
3*60*60 + 58*60 + 12

14292

In [17]:
pd.Timestamp(1991, 4, 12)

Timestamp('1991-04-12 00:00:00')

In [20]:
pd.Timestamp(1991, 4, 12) == dt.date(1991, 4, 12)

False

In [21]:
pd.Timestamp(1991, 4, 12) == dt.datetime(1991, 4, 12)

True

In [22]:
pd.Timestamp('2015-03-31')

Timestamp('2015-03-31 00:00:00')

In [23]:
pd.Timestamp('2015/3/31')

Timestamp('2015-03-31 00:00:00')

In [24]:
pd.Timestamp('2025-08-12 3:14 PM')

Timestamp('2025-08-12 15:14:00')

In [25]:
pd.Timestamp(dt.date(2025, 8, 12))

Timestamp('2025-08-12 00:00:00')

In [26]:
pd.Series([1, 2, 3]).index

RangeIndex(start=0, stop=3, step=1)

In [27]:
pd.Series(data=[1, 2, 3], index=['A', 'B', 'C']).index

Index(['A', 'B', 'C'], dtype='object')

In [28]:
pd.Series(data=[1, 2, 3], index=[pd.Timestamp('2025-08-10'), pd.Timestamp('2025-08-11'), pd.Timestamp('2025-08-12')]).index

DatetimeIndex(['2025-08-10', '2025-08-11', '2025-08-12'], dtype='datetime64[ns]', freq=None)

In [30]:
dt_index = pd.DatetimeIndex(['2025-08-10', '2025-08-11', '2025-08-12'])

In [31]:
pd.Series([1, 2, 3], index=dt_index)

2025-08-10    1
2025-08-11    2
2025-08-12    3
dtype: int64

In [32]:
disney = pd.read_csv('disney.csv')
disney

             Date        High         Low        Open       Close
0      1962-01-02    0.096026    0.092908    0.092908    0.092908
1      1962-01-03    0.094467    0.092908    0.092908    0.094155
2      1962-01-04    0.094467    0.093532    0.094155    0.094155
3      1962-01-05    0.094779    0.093844    0.094155    0.094467
4      1962-01-08    0.095714    0.092285    0.094467    0.094155
...           ...         ...         ...         ...         ...
14722  2020-06-26  111.199997  108.019997  110.949997  109.099998
14723  2020-06-29  111.570000  108.099998  109.000000  111.519997
14724  2020-06-30  112.050003  109.930000  111.500000  111.510002
14725  2020-07-01  115.599998  112.290001  112.820000  113.010002
14726  2020-07-02  115.099998  112.000000  115.000000  112.180000

[14727 rows x 5 columns]

In [33]:
disney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14727 entries, 0 to 14726
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14727 non-null  object
 1   High    14727 non-null  float64
 2   Low     14727 non-null  float64
 3   Open    14727 non-null  float64
 4   Close   14727 non-null  float64
dtypes: float64(4), object(1)
memory usage: 575.4+ KB

In [34]:
disney.dtypes

Date      object
High     float64
Low      float64
Open     float64
Close    float64
dtype: object

In [35]:
pd.to_datetime(disney['Date'])

0       1962-01-02
1       1962-01-03
2       1962-01-04
3       1962-01-05
4       1962-01-08
           ...
14722   2020-06-26
14723   2020-06-29
14724   2020-06-30
14725   2020-07-01
14726   2020-07-02
Name: Date, Length: 14727, dtype: datetime64[ns]

In [36]:
disney['Date'] = pd.to_datetime(disney['Date'])

In [37]:
disney.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14727 entries, 0 to 14726
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14727 non-null  datetime64[ns]
 1   High    14727 non-null  float64
 2   Low     14727 non-null  float64
 3   Open    14727 non-null  float64
 4   Close   14727 non-null  float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 575.4 KB

In [38]:
disney.dtypes

Date     datetime64[ns]
High            float64
Low             float64
Open            float64
Close           float64
dtype: object

In [39]:
disney['Date'].dt

In [45]:
pd.Series(['a', 'b', 'c']).str.upper()

0    A
1    B
2    C
dtype: object

In [46]:
disney['Date'].dt

In [47]:
disney['Date'].dt.day

0         2
1         3
2         4
3         5
4         8
         ..
14722    26
14723    29
14724    30
14725     1
14726     2
Name: Date, Length: 14727, dtype: int32

In [48]:
disney['Date'].dt.month

0        1
1        1
2        1
3        1
4        1
        ..
14722    6
14723    6
14724    6
14725    7
14726    7
Name: Date, Length: 14727, dtype: int32

In [51]:
disney['Date'].dt.year.value_counts().sort_index()

Date
1962    252
1963    251
1964    253
1965    252
1966    252
1967    251
1968    226
1969    250
1970    254
1971    253
1972    251
1973    252
1974    253
1975    253
1976    253
1977    252
1978    252
1979    253
1980    253
1981    253
1982    253
1983    253
1984    253
1985    252
1986    253
1987    253
1988    253
1989    252
1990    253
1991    253
1992    254
1993    253
1994    252
1995    252
1996    254
1997    253
1998    252
1999    252
2000    252
2001    248
2002    252
2003    252
2004    252
2005    252
2006    251
2007    251
2008    253
2009    252
2010    252
2011    252
2012    250
2013    252
2014    252
2015    252
2016    252
2017    251
2018    251
2019    252
2020    127
Name: count, dtype: int64

In [52]:
disney['Date'].dt.dayofweek

0        1
1        2
2        3
3        4
4        0
        ..
14722    4
14723    0
14724    1
14725    2
14726    3
Name: Date, Length: 14727, dtype: int32

In [53]:
disney['Date'].dt.day_name()

0          Tuesday
1        Wednesday
2         Thursday
3           Friday
4           Monday
           ...
14722       Friday
14723       Monday
14724      Tuesday
14725    Wednesday
14726     Thursday
Name: Date, Length: 14727, dtype: object

In [54]:
disney['Day of week'] = disney['Date'].dt.day_name()

In [55]:
disney

            Date        High         Low        Open       Close Day of week
0     1962-01-02    0.096026    0.092908    0.092908    0.092908     Tuesday
1     1962-01-03    0.094467    0.092908    0.092908    0.094155   Wednesday
2     1962-01-04    0.094467    0.093532    0.094155    0.094155    Thursday
3     1962-01-05    0.094779    0.093844    0.094155    0.094467      Friday
4     1962-01-08    0.095714    0.092285    0.094467    0.094155      Monday
...          ...         ...         ...         ...         ...         ...
14722 2020-06-26  111.199997  108.019997  110.949997  109.099998      Friday
14723 2020-06-29  111.570000  108.099998  109.000000  111.519997      Monday
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002     Tuesday
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002   Wednesday
14726 2020-07-02  115.099998  112.000000  115.000000  112.180000    Thursday

[14727 rows x 6 columns]

In [56]:
group = disney.groupby('Day of week')

In [57]:
group.groups

{'Friday': [3, 8, 13, 18, 23, 28, 33, 37, 42, 47, 52, 57, 62, 67, 72, 81, 86, 91, 96, 101, 105, 110, 115, 120, 125, 129, 134, 139, 144, 149, 154, 159, 164, 169, 173, 178, 183, 188, 193, 198, 203, 208, 213, 217, 222, 226, 231, 236, 241, 246, 250, 254, 259, 264, 269, 274, 279, 284, 293, 298, 303, 308, 313, 318, 327, 332, 337, 342, 347, 352, 356, 361, 366, 371, 376, 380, 385, 390, 395, 400, 405, 410, 415, 420, 424, 429, 434, 439, 444, 449, 454, 459, 464, 468, 473, 478, 481, 486, 491, 496, ...], 'Monday': [4, 9, 14, 19, 24, 29, 34, 38, 43, 48, 53, 58, 63, 68, 73, 77, 82, 87, 92, 97, 102, 106, 111, 116, 121, 126, 130, 135, 140, 145, 150, 155, 160, 165, 174, 179, 184, 189, 194, 199, 204, 209, 214, 218, 223, 227, 232, 237, 242, 247, 251, 255, 260, 265, 270, 275, 280, 285, 289, 294, 299, 304, 309, 314, 319, 323, 328, 333, 338, 343, 348, 353, 357, 362, 367, 372, 377, 381, 386, 391, 396, 401, 406, 411, 416, 425, 430, 435, 440, 445, 450, 455, 460, 465, 469, 474, 482, 487, 492, 497, ...], 'Thursday': [2, 7, 12, 17, 22, 27, 32, 41, 46, 51, 56, 61, 66, 71, 76, 80, 85, 90, 95, 100, 104, 109, 114, 119, 124, 128, 133, 138, 143, 148, 153, 158, 163, 168, 172, 177, 182, 187, 192, 197, 202, 207, 212, 216, 221, 230, 235, 240, 245, 249, 253, 258, 263, 268, 273, 278, 283, 288, 292, 297, 302, 307, 312, 317, 322, 326, 331, 336, 341, 346, 351, 360, 365, 370, 375, 384, 389, 394, 399, 404, 409, 414, 419, 423, 428, 433, 438, 443, 448, 453, 458, 463, 467, 472, 477, 485, 490, 495, 499, 503, ...], 'Tuesday': [0, 5, 10, 15, 20, 25, 30, 35, 39, 44, 49, 54, 59, 64, 69, 74, 78, 83, 88, 93, 98, 103, 107, 112, 117, 122, 127, 131, 136, 141, 146, 151, 156, 161, 166, 170, 175, 180, 185, 190, 195, 200, 205, 210, 219, 224, 228, 233, 238, 243, 256, 261, 266, 271, 276, 281, 286, 290, 295, 300, 305, 310, 315, 320, 324, 329, 334, 339, 344, 349, 354, 358, 363, 368, 373, 378, 382, 387, 392, 397, 402, 407, 412, 417, 421, 426, 431, 436, 441, 446, 451, 456, 461, 470, 475, 479, 483, 488, 493, 498, ...], 'Wednesday': [1, 6, 11, 16, 21, 26, 31, 36, 40, 45, 50, 55, 60, 65, 70, 75, 79, 84, 89, 94, 99, 108, 113, 118, 123, 132, 137, 142, 147, 152, 157, 162, 167, 171, 176, 181, 186, 191, 196, 201, 206, 211, 215, 220, 225, 229, 234, 239, 244, 248, 252, 257, 262, 267, 272, 277, 282, 287, 291, 296, 301, 306, 311, 316, 321, 325, 330, 335, 340, 345, 350, 355, 359, 364, 369, 374, 379, 383, 388, 393, 398, 403, 408, 413, 418, 422, 427, 432, 437, 442, 447, 452, 457, 462, 466, 471, 476, 480, 484, 489, ...]}

In [59]:
group.size()

Day of week
Friday       2944
Monday       2812
Thursday     2962
Tuesday      3011
Wednesday    2998
dtype: int64

In [62]:
group[['High', 'Low', 'Open', 'Close']].mean()

                  High        Low       Open      Close
Day of week
Friday       23.767304  23.318898  23.552872  23.554498
Monday       23.377271  22.930606  23.161392  23.162543
Thursday     23.770234  23.288687  23.534561  23.540359
Tuesday      23.791234  23.335267  23.571755  23.562907
Wednesday    23.842743  23.355419  23.605618  23.609873

In [63]:
disney['Date'].dt.month_name()

0        January
1        January
2        January
3        January
4        January
          ...
14722       June
14723       June
14724       June
14725       July
14726       July
Name: Date, Length: 14727, dtype: object

In [66]:
disney['Date'].dt.is_quarter_start

0        False
1        False
2        False
3        False
4        False
         ...
14722    False
14723    False
14724    False
14725     True
14726    False
Name: Date, Length: 14727, dtype: bool

In [67]:
disney[disney['Date'].dt.is_quarter_end]

            Date        High         Low        Open       Close Day of week
251   1962-12-31    0.074501    0.071290    0.074501    0.072253      Monday
440   1963-09-30    0.109825    0.105972    0.108541    0.107577      Monday
502   1963-12-31    0.101476    0.096980    0.097622    0.101476     Tuesday
564   1964-03-31    0.115605    0.112394    0.114963    0.112394     Tuesday
628   1964-06-30    0.101476    0.100191    0.101476    0.100834     Tuesday
...          ...         ...         ...         ...         ...         ...
14347 2018-12-31  109.669998  107.550003  109.110001  109.650002      Monday
14535 2019-09-30  130.860001  129.820007  130.350006  130.320007      Monday
14599 2019-12-31  144.770004  143.259995  143.669998  144.630005     Tuesday
14661 2020-03-31  103.160004   96.160004  100.220001   96.599998     Tuesday
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002     Tuesday

[163 rows x 6 columns]

In [68]:
disney[disney['Date'].dt.is_month_start]

            Date        High         Low        Open       Close Day of week
22    1962-02-01    0.096338    0.093532    0.093532    0.094779    Thursday
41    1962-03-01    0.095714    0.093532    0.093532    0.095714    Thursday
83    1962-05-01    0.087296    0.085426    0.085738    0.086673     Tuesday
105   1962-06-01    0.079814    0.077943    0.079814    0.079814      Friday
147   1962-08-01    0.068590    0.068278    0.068590    0.068590   Wednesday
...          ...         ...         ...         ...         ...         ...
14559 2019-11-01  132.800003  130.509995  130.990005  132.750000      Friday
14662 2020-04-01   97.400002   92.559998   93.500000   94.919998   Wednesday
14683 2020-05-01  106.910004  104.470001  106.360001  105.500000      Friday
14703 2020-06-01  119.650002  116.930000  117.260002  118.769997      Monday
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002   Wednesday

[448 rows x 6 columns]

In [69]:
pd.DateOffset(days=5)

In [70]:
disney['Date'] + pd.DateOffset(days=10)

0       1962-01-12
1       1962-01-13
2       1962-01-14
3       1962-01-15
4       1962-01-18
           ...
14722   2020-07-06
14723   2020-07-09
14724   2020-07-10
14725   2020-07-11
14726   2020-07-12
Name: Date, Length: 14727, dtype: datetime64[ns]

In [71]:
disney['Date'] + pd.offsets.MonthEnd()

0       1962-01-31
1       1962-01-31
2       1962-01-31
3       1962-01-31
4       1962-01-31
           ...
14722   2020-06-30
14723   2020-06-30
14724   2020-07-31
14725   2020-07-31
14726   2020-07-31
Name: Date, Length: 14727, dtype: datetime64[ns]

In [72]:
disney['Date'] - pd.offsets.MonthEnd()

0       1961-12-31
1       1961-12-31
2       1961-12-31
3       1961-12-31
4       1961-12-31
           ...
14722   2020-05-31
14723   2020-05-31
14724   2020-05-31
14725   2020-06-30
14726   2020-06-30
Name: Date, Length: 14727, dtype: datetime64[ns]

In [74]:
disney['Date'].tail() - pd.offsets.MonthBegin()

14722   2020-06-01
14723   2020-06-01
14724   2020-06-01
14725   2020-06-01
14726   2020-07-01
Name: Date, dtype: datetime64[ns]

In [75]:
disney['Date'].tail()

14722   2020-06-26
14723   2020-06-29
14724   2020-06-30
14725   2020-07-01
14726   2020-07-02
Name: Date, dtype: datetime64[ns]

In [77]:
disney['Date'].dt.is_quarter_start

0        False
1        False
2        False
3        False
4        False
         ...
14722    False
14723    False
14724    False
14725     True
14726    False
Name: Date, Length: 14727, dtype: bool

In [78]:
pd.Timedelta(days=1, hours=1)

Timedelta('1 days 01:00:00')

In [79]:
pd.to_timedelta('5 days, 4 hours, 35 seconds')

Timedelta('5 days 04:00:35')

In [81]:
pd.to_timedelta(5, unit='days')

Timedelta('5 days 00:00:00')

In [83]:
deliveries = pd.read_csv('deliveries.csv')
deliveries

    order_date delivery_date
0      5/24/98        2/5/99
1      4/22/92        3/6/98
2      2/10/91       8/26/92
3      7/21/92      11/20/97
4       9/2/93       6/10/98
..         ...           ...
496    6/24/91        2/2/96
497     9/9/91       3/30/98
498   11/16/90       4/27/98
499     6/3/93       6/13/93
500     1/4/90       10/3/91

[501 rows x 2 columns]

In [84]:
deliveries['order_date'] = pd.to_datetime(deliveries['order_date'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_1620/216300010.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  deliveries['order_date'] = pd.to_datetime(deliveries['order_date'])

In [85]:
deliveries['delivery_date'] = pd.to_datetime(deliveries['delivery_date'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_1620/4155040504.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  deliveries['delivery_date'] = pd.to_datetime(deliveries['delivery_date'])

In [86]:
deliveries

    order_date delivery_date
0   1998-05-24    1999-02-05
1   1992-04-22    1998-03-06
2   1991-02-10    1992-08-26
3   1992-07-21    1997-11-20
4   1993-09-02    1998-06-10
..         ...           ...
496 1991-06-24    1996-02-02
497 1991-09-09    1998-03-30
498 1990-11-16    1998-04-27
499 1993-06-03    1993-06-13
500 1990-01-04    1991-10-03

[501 rows x 2 columns]

In [87]:
deliveries.dtypes

order_date       datetime64[ns]
delivery_date    datetime64[ns]
dtype: object

In [91]:
(deliveries['delivery_date'] - deliveries['order_date'])

0      257 days
1     2144 days
2      563 days
3     1948 days
4     1742 days
         ...
496   1684 days
497   2394 days
498   2719 days
499     10 days
500    637 days
Length: 501, dtype: timedelta64[ns]

In [92]:
deliveries['duration'] = deliveries['delivery_date'] - deliveries['order_date']

In [93]:
deliveries

    order_date delivery_date  duration
0   1998-05-24    1999-02-05  257 days
1   1992-04-22    1998-03-06 2144 days
2   1991-02-10    1992-08-26  563 days
3   1992-07-21    1997-11-20 1948 days
4   1993-09-02    1998-06-10 1742 days
..         ...           ...       ...
496 1991-06-24    1996-02-02 1684 days
497 1991-09-09    1998-03-30 2394 days
498 1990-11-16    1998-04-27 2719 days
499 1993-06-03    1993-06-13   10 days
500 1990-01-04    1991-10-03  637 days

[501 rows x 3 columns]

In [94]:
deliveries.dtypes

order_date        datetime64[ns]
delivery_date     datetime64[ns]
duration         timedelta64[ns]
dtype: object

In [95]:
deliveries.sort_values(by='duration')

    order_date delivery_date  duration
454 1990-05-24    1990-06-01    8 days
294 1994-08-11    1994-08-20    9 days
10  1998-05-10    1998-05-19    9 days
499 1993-06-03    1993-06-13   10 days
143 1997-09-20    1997-10-06   16 days
..         ...           ...       ...
152 1990-09-18    1999-12-19 3379 days
62  1990-04-02    1999-08-16 3423 days
458 1990-02-13    1999-11-15 3562 days
145 1990-03-07    1999-12-25 3580 days
448 1990-01-20    1999-11-12 3583 days

[501 rows x 3 columns]

In [96]:
deliveries['duration'] > pd.Timedelta(days=365)

0      False
1       True
2       True
3       True
4       True
       ...
496     True
497     True
498     True
499    False
500     True
Name: duration, Length: 501, dtype: bool

In [97]:
# Homework

In [101]:
df = pd.read_csv('citibike.csv')

In [102]:
df

                       start_time                 stop_time
0        2020-06-01 00:00:03.3720  2020-06-01 00:17:46.2080
1        2020-06-01 00:00:03.5530  2020-06-01 01:03:33.9360
2        2020-06-01 00:00:09.6140  2020-06-01 00:17:06.8330
3        2020-06-01 00:00:12.1780  2020-06-01 00:03:58.8640
4        2020-06-01 00:00:21.2550  2020-06-01 00:24:18.9650
...                           ...                       ...
1882268  2020-06-30 23:59:41.1160  2020-07-01 00:11:06.7790
1882269  2020-06-30 23:59:46.4260  2020-07-01 00:07:13.0860
1882270  2020-06-30 23:59:47.4770  2020-07-01 00:07:06.5590
1882271  2020-06-30 23:59:53.3950  2020-07-01 00:14:43.4270
1882272  2020-06-30 23:59:53.9010  2020-07-01 00:07:07.0950

[1882273 rows x 2 columns]

In [104]:
df.dtypes

start_time    object
stop_time     object
dtype: object

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  object
 1   stop_time   object
dtypes: object(2)
memory usage: 28.7+ MB

In [106]:
# 1
for col in df.columns:
    df[col] = pd.to_datetime(df[col])

In [107]:
df

                     start_time               stop_time
0       2020-06-01 00:00:03.372 2020-06-01 00:17:46.208
1       2020-06-01 00:00:03.553 2020-06-01 01:03:33.936
2       2020-06-01 00:00:09.614 2020-06-01 00:17:06.833
3       2020-06-01 00:00:12.178 2020-06-01 00:03:58.864
4       2020-06-01 00:00:21.255 2020-06-01 00:24:18.965
...                         ...                     ...
1882268 2020-06-30 23:59:41.116 2020-07-01 00:11:06.779
1882269 2020-06-30 23:59:46.426 2020-07-01 00:07:13.086
1882270 2020-06-30 23:59:47.477 2020-07-01 00:07:06.559
1882271 2020-06-30 23:59:53.395 2020-07-01 00:14:43.427
1882272 2020-06-30 23:59:53.901 2020-07-01 00:07:07.095

[1882273 rows x 2 columns]

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882273 entries, 0 to 1882272
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   start_time  datetime64[ns]
 1   stop_time   datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 28.7 MB

In [112]:
# 2
df['start_time'].dt.day_name().value_counts()

start_time
Tuesday      305833
Sunday       301482
Monday       292690
Saturday     285966
Friday       258479
Wednesday    222647
Thursday     215176
Name: count, dtype: int64

In [130]:
# 3
(df['start_time'] + pd.to_timedelta(-df['start_time'].dt.dayofweek, unit='days')).dt.date.value_counts().sort_index()

start_time
2020-06-01    337590
2020-06-08    471384
2020-06-15    481211
2020-06-22    465412
2020-06-29    126676
Name: count, dtype: int64

In [131]:
# 4
df['duration'] = df['stop_time'] - df['start_time']

In [132]:
df

                     start_time               stop_time               duration
0       2020-06-01 00:00:03.372 2020-06-01 00:17:46.208 0 days 00:17:42.836000
1       2020-06-01 00:00:03.553 2020-06-01 01:03:33.936 0 days 01:03:30.383000
2       2020-06-01 00:00:09.614 2020-06-01 00:17:06.833 0 days 00:16:57.219000
3       2020-06-01 00:00:12.178 2020-06-01 00:03:58.864 0 days 00:03:46.686000
4       2020-06-01 00:00:21.255 2020-06-01 00:24:18.965 0 days 00:23:57.710000
...                         ...                     ...                    ...
1882268 2020-06-30 23:59:41.116 2020-07-01 00:11:06.779 0 days 00:11:25.663000
1882269 2020-06-30 23:59:46.426 2020-07-01 00:07:13.086 0 days 00:07:26.660000
1882270 2020-06-30 23:59:47.477 2020-07-01 00:07:06.559 0 days 00:07:19.082000
1882271 2020-06-30 23:59:53.395 2020-07-01 00:14:43.427 0 days 00:14:50.032000
1882272 2020-06-30 23:59:53.901 2020-07-01 00:07:07.095 0 days 00:07:13.194000

[1882273 rows x 3 columns]

In [133]:
# 5
df['duration'].mean()

Timedelta('0 days 00:27:19.590506853')

In [134]:
# 6
df['duration'].sort_values(ascending=False)[:5]

50593    32 days 15:01:54.940000
98339    31 days 01:47:20.632000
52306    30 days 19:32:20.696000
15171    30 days 04:26:48.424000
149761   28 days 09:24:50.696000
Name: duration, dtype: timedelta64[ns]