In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
groups1 = pd.read_csv('meetup/groups1.csv')
groups1.head()

   group_id                           name  category_id  city_id
0      6388         Alternative Health NYC           14    10001
1      6510      Alternative Energy Meetup            4    10001
2      8458              NYC Animal Rights           26    10001
3      8940  The New York City Anime Group           29    10001
4     10104             NYC Pit Bull Group           26    10001

In [4]:
len(groups1)

7999

In [5]:
groups1.count()

group_id       7999
name           7998
category_id    7999
city_id        7999
dtype: int64

In [6]:
groups1[groups1['name'].isnull()]

      group_id name  category_id  city_id
6324  17274962  NaN           21    10001

In [7]:
groups1.nunique()

group_id       7999
name           7998
category_id      33
city_id           7
dtype: int64

In [8]:
groups2 = pd.read_csv('meetup/groups2.csv')
groups2.head()

,group_id,name,category_id,city_id
0,18879327,BachataMania,5,10001
1,18880221,Photoshoot Chicago - Photography and Modeling ...,27,60601
2,18880426,Chicago Adult Push / Kick Scooter Group Riding...,31,60601
3,18880495,Chicago International Soccer Club,32,60601
4,18880695,Impact.tech San Francisco Meetup,2,94101

In [9]:
len(groups2)

8331

In [10]:
groups2.count()

group_id       8331
name           8331
category_id    8331
city_id        8331
dtype: int64

In [11]:
groups2.nunique()

group_id       8331
name           8330
category_id      33
city_id           9
dtype: int64

In [12]:
categories = pd.read_csv('meetup/categories.csv')
categories.head()

   category_id            category_name
0            1           Arts & Culture
1            3       Cars & Motorcycles
2            4  Community & Environment
3            5                  Dancing
4            6     Education & Learning

In [14]:
categories['category_id'].is_unique

True

In [15]:
categories.count()

category_id      27
category_name    27
dtype: int64

In [16]:
len(categories)

27

In [19]:
cities = pd.read_csv('meetup/cities.csv', dtype = {'zip': 'string'})
cities.head()

      id            city state    zip
0   7093   West New York    NJ  07093
1  10001        New York    NY  10001
2  13417  New York Mills    NY  13417
3  46312    East Chicago    IN  46312
4  56567  New York Mills    MN  56567

In [20]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      13 non-null     int64
 1   city    13 non-null     object
 2   state   13 non-null     object
 3   zip     13 non-null     string
dtypes: int64(1), object(2), string(1)
memory usage: 548.0+ bytes

In [22]:
cities['id'].is_unique

True

In [23]:
len(cities)

13

In [24]:
pd.concat([groups1, groups2])

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
8326,26377464,Shinect,34,94101
8327,26377698,The art of getting what you want [conference s...,14,94101
8328,26378067,Streeterville Running Group,9,60601
8329,26378128,Just Dance NYC,23,10001
8330,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [25]:
groups2.head()

,group_id,name,category_id,city_id
0,18879327,BachataMania,5,10001
1,18880221,Photoshoot Chicago - Photography and Modeling ...,27,60601
2,18880426,Chicago Adult Push / Kick Scooter Group Riding...,31,60601
3,18880495,Chicago International Soccer Club,32,60601
4,18880695,Impact.tech San Francisco Meetup,2,94101

In [26]:
pd.concat([groups1, groups2]).loc[0]

   group_id                    name  category_id  city_id
0      6388  Alternative Health NYC           14    10001
0  18879327            BachataMania            5    10001

In [27]:
pd.concat([groups1, groups2], ignore_index=True)

,group_id,name,category_id,city_id
0,6388,Alternative Health NYC,14,10001
1,6510,Alternative Energy Meetup,4,10001
2,8458,NYC Animal Rights,26,10001
3,8940,The New York City Anime Group,29,10001
4,10104,NYC Pit Bull Group,26,10001
...,...,...,...,...
16325,26377464,Shinect,34,94101
16326,26377698,The art of getting what you want [conference s...,14,94101
16327,26378067,Streeterville Running Group,9,60601
16328,26378128,Just Dance NYC,23,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [28]:
pd.concat([groups1, groups2], keys=['G1', 'G2'])

         group_id                                               name  \
G1 0         6388                             Alternative Health NYC
   1         6510                          Alternative Energy Meetup
   2         8458                                  NYC Animal Rights
   3         8940                      The New York City Anime Group
   4        10104                                 NYC Pit Bull Group
...           ...                                                ...
G2 8326  26377464                                            Shinect
   8327  26377698  The art of getting what you want [conference s...
   8328  26378067                        Streeterville Running Group
   8329  26378128                                     Just Dance NYC
   8330  26378470           FREE Arabic Chicago Evanston North Burbs

         category_id  city_id
G1 0              14    10001
   1               4    10001
   2              26    10001
   3              29    10001
   4              26    10001
...              ...      ...
G2 8326           34    94101
   8327           14    94101
   8328            9    60601
   8329           23    10001
   8330           31    60601

[16330 rows x 4 columns]

In [30]:
pd.concat([groups1, groups2], keys=['G1', 'G2']).loc[[('G1', 0), ('G2', 0)]]

      group_id                    name  category_id  city_id
G1 0      6388  Alternative Health NYC           14    10001
G2 0  18879327            BachataMania            5    10001

In [39]:
groups = pd.concat([groups1, groups2], ignore_index=True)
groups.head()

   group_id                           name  category_id  city_id
0      6388         Alternative Health NYC           14    10001
1      6510      Alternative Energy Meetup            4    10001
2      8458              NYC Animal Rights           26    10001
3      8940  The New York City Anime Group           29    10001
4     10104             NYC Pit Bull Group           26    10001

In [32]:
groups.tail()

,group_id,name,category_id,city_id
16325,26377464,Shinect,34,94101
16326,26377698,The art of getting what you want [conference s...,14,94101
16327,26378067,Streeterville Running Group,9,60601
16328,26378128,Just Dance NYC,23,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601

In [35]:
pd.concat(objs=[groups1, groups2], axis=1, keys=['G1', 'G2'])

           G1                                                            G2  \
     group_id                           name category_id  city_id  group_id
0      6388.0         Alternative Health NYC        14.0  10001.0  18879327
1      6510.0      Alternative Energy Meetup         4.0  10001.0  18880221
2      8458.0              NYC Animal Rights        26.0  10001.0  18880426
3      8940.0  The New York City Anime Group        29.0  10001.0  18880495
4     10104.0             NYC Pit Bull Group        26.0  10001.0  18880695
...       ...                            ...         ...      ...       ...
8326      NaN                            NaN         NaN      NaN  26377464
8327      NaN                            NaN         NaN      NaN  26377698
8328      NaN                            NaN         NaN      NaN  26378067
8329      NaN                            NaN         NaN      NaN  26378128
8330      NaN                            NaN         NaN      NaN  26378470


                                                   name category_id city_id
0                                          BachataMania           5   10001
1     Photoshoot Chicago - Photography and Modeling ...          27   60601
2     Chicago Adult Push / Kick Scooter Group Riding...          31   60601
3                     Chicago International Soccer Club          32   60601
4                      Impact.tech San Francisco Meetup           2   94101
...                                                 ...         ...     ...
8326                                            Shinect          34   94101
8327  The art of getting what you want [conference s...          14   94101
8328                        Streeterville Running Group           9   60601
8329                                     Just Dance NYC          23   10001
8330           FREE Arabic Chicago Evanston North Burbs          31   60601

[8331 rows x 8 columns]

In [36]:
categories.head()

   category_id            category_name
0            1           Arts & Culture
1            3       Cars & Motorcycles
2            4  Community & Environment
3            5                  Dancing
4            6     Education & Learning

In [37]:
groups.merge(categories, how='left', on='category_id')

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8458,NYC Animal Rights,26,10001,NaN
3,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
4,10104,NYC Pit Bull Group,26,10001,NaN
...,...,...,...,...,...
16325,26377464,Shinect,34,94101,NaN
16326,26377698,The art of getting what you want [conference s...,14,94101,Health & Wellbeing
16327,26378067,Streeterville Running Group,9,60601,Fitness
16328,26378128,Just Dance NYC,23,10001,Outdoors & Adventure
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601,NaN

In [40]:
groups.merge(categories, how='inner', on='category_id')

,group_id,name,category_id,city_id,category_name
0,6388,Alternative Health NYC,14,10001,Health & Wellbeing
1,6510,Alternative Energy Meetup,4,10001,Community & Environment
2,8940,The New York City Anime Group,29,10001,Sci-Fi & Fantasy
3,10359,NYC International Arabic Language & Culture Club,16,10001,Language & Ethnic Identity
4,12111,The New York City American Sign Language Meetu...,16,10001,Language & Ethnic Identity
...,...,...,...,...,...
8032,26374579,Digital Film Academy Production Pitch,20,10001,Movies & Film
8033,26374655,Vocabulary workhop,16,94101,Language & Ethnic Identity
8034,26377698,The art of getting what you want [conference s...,14,94101,Health & Wellbeing
8035,26378067,Streeterville Running Group,9,60601,Fitness
8036,26378128,Just Dance NYC,23,10001,Outdoors & Adventure

In [41]:
groups.merge(categories, how='left', on='category_id').count()

group_id         16330
name             16329
category_id      16330
city_id          16330
category_name     8037
dtype: int64

In [42]:
groups.merge(cities, how='outer', left_on='city_id', right_on='id')

,group_id,name,category_id,city_id,id,city,state,zip
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093
...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712

In [43]:
groups.merge(cities, how='outer', left_on='city_id', right_on='id', indicator=True)

,group_id,name,category_id,city_id,id,city,state,zip,_merge
0,19525264.0,West NY | Hoboken | Social Group 20s & 30s,31.0,7093.0,7093,West New York,NJ,07093,both
1,20240670.0,Nerdy NJ/NY,11.0,7093.0,7093,West New York,NJ,07093,both
2,20395344.0,The Founding Moms' Exchange: North Jersey,2.0,7093.0,7093,West New York,NJ,07093,both
3,21130076.0,West New York Playdates for little ones,25.0,7093.0,7093,West New York,NJ,07093,both
4,21825714.0,Women~Wellness~Wisdom,14.0,7093.0,7093,West New York,NJ,07093,both
...,...,...,...,...,...,...,...,...,...
16329,26373602.0,Earndotcom: SF's most awesome digital currency...,34.0,94101.0,94101,San Francisco,CA,94101,both
16330,26374655.0,Vocabulary workhop,16.0,94101.0,94101,San Francisco,CA,94101,both
16331,26377464.0,Shinect,34.0,94101.0,94101,San Francisco,CA,94101,both
16332,26377698.0,The art of getting what you want [conference s...,14.0,94101.0,94101,San Francisco,CA,94101,both
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712,right_only

In [44]:
full_join = groups.merge(cities, how='outer', left_on='city_id', right_on='id', indicator=True)

In [45]:
full_join[full_join['_merge'] == 'right_only']

,group_id,name,category_id,city_id,id,city,state,zip,_merge
8576,NaN,NaN,NaN,NaN,13417,New York Mills,NY,13417,right_only
8577,NaN,NaN,NaN,NaN,46312,East Chicago,IN,46312,right_only
8578,NaN,NaN,NaN,NaN,56567,New York Mills,MN,56567,right_only
16333,NaN,NaN,NaN,NaN,95712,Chicago Park,CA,95712,right_only

In [46]:
cities = cities.set_index('id')

In [47]:
cities.head()

                 city state    zip
id
7093    West New York    NJ  07093
10001        New York    NY  10001
13417  New York Mills    NY  13417
46312    East Chicago    IN  46312
56567  New York Mills    MN  56567

In [48]:
groups.head()

   group_id                           name  category_id  city_id
0      6388         Alternative Health NYC           14    10001
1      6510      Alternative Energy Meetup            4    10001
2      8458              NYC Animal Rights           26    10001
3      8940  The New York City Anime Group           29    10001
4     10104             NYC Pit Bull Group           26    10001

In [49]:
groups.merge(cities, how='left', left_on='city_id', right_index=True)

,group_id,name,category_id,city_id,city,state,zip
0,6388,Alternative Health NYC,14,10001,New York,NY,10001
1,6510,Alternative Energy Meetup,4,10001,New York,NY,10001
2,8458,NYC Animal Rights,26,10001,New York,NY,10001
3,8940,The New York City Anime Group,29,10001,New York,NY,10001
4,10104,NYC Pit Bull Group,26,10001,New York,NY,10001
...,...,...,...,...,...,...,...
16325,26377464,Shinect,34,94101,San Francisco,CA,94101
16326,26377698,The art of getting what you want [conference s...,14,94101,San Francisco,CA,94101
16327,26378067,Streeterville Running Group,9,60601,Chicago,IL,60290
16328,26378128,Just Dance NYC,23,10001,New York,NY,10001
16329,26378470,FREE Arabic Chicago Evanston North Burbs,31,60601,Chicago,IL,60290

In [50]:
# Homework

In [51]:
week1 = pd.read_csv('restaurant/week_1_sales.csv')
week1.head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [52]:
week2 = pd.read_csv('restaurant/week_2_sales.csv')
week2.head()

   Customer ID  Food ID
0          688       10
1          813        7
2          495       10
3          189        5
4          267        3

In [53]:
week1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  250 non-null    int64
 1   Food ID      250 non-null    int64
dtypes: int64(2)
memory usage: 4.0 KB

In [54]:
week2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  250 non-null    int64
 1   Food ID      250 non-null    int64
dtypes: int64(2)
memory usage: 4.0 KB

In [56]:
customers = pd.read_csv('restaurant/customers.csv', index_col='ID')
customers.head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [57]:
foods = pd.read_csv('restaurant/foods.csv', index_col='Food ID')
foods.head()

          Food Item  Price
Food ID
1             Sushi   3.99
2           Burrito   9.99
3              Taco   2.99
4        Quesadilla   4.25
5             Pizza   2.49

In [59]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  1000 non-null   object
 1   Last Name   1000 non-null   object
 2   Gender      1000 non-null   object
 3   Company     1000 non-null   object
 4   Occupation  1000 non-null   object
dtypes: object(5)
memory usage: 46.9+ KB

In [60]:
foods.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 10
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Food Item  10 non-null     object
 1   Price      10 non-null     float64
dtypes: float64(1), object(1)
memory usage: 240.0+ bytes

In [61]:
# 1
sales = pd.concat([week1, week2], keys=['Week 1', 'Week 2'])
sales.head()

          Customer ID  Food ID
Week 1 0          537        9
       1           97        4
       2          658        1
       3          202        2
       4          155        9

In [62]:
sales

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [63]:
sales.loc[[('Week 1', 0), ('Week 2', 0)]]

          Customer ID  Food ID
Week 1 0          537        9
Week 2 0          688       10

In [76]:
# 2
week1.merge(week2, how='inner', on='Customer ID')['Customer ID'].drop_duplicates()

0     537
1     155
2     503
5     550
6     101
7      75
8      77
9     628
10    798
11    462
12    304
13    189
14    799
15     30
16    249
17    677
18    741
19    540
20    819
21    937
23    233
24     21
25    459
26    816
27    761
30     80
31    479
32    922
34    909
35    919
37    574
38     45
40    529
41    673
42    310
43    867
44    968
46    482
47    163
48    321
51    783
53    578
56    520
57    945
58    343
61    621
Name: Customer ID, dtype: int64

In [77]:
# 3
week1.merge(week2, how='inner', on=['Customer ID', 'Food ID'])['Customer ID'].drop_duplicates()

0    304
1    540
2    937
3    233
4     21
5    922
7    578
Name: Customer ID, dtype: int64

In [75]:
# 4
full_join = week1.merge(week2, how='outer', on='Customer ID', indicator=True)

In [72]:
full_join

     Customer ID  Food ID_x  Food ID_y      _merge
0              3        2.0        NaN   left_only
1              8        NaN        6.0  right_only
2             10        2.0        NaN   left_only
3             13        NaN        2.0  right_only
4             20        1.0        NaN   left_only
..           ...        ...        ...         ...
449          985        5.0        NaN   left_only
450          991        2.0        NaN   left_only
451          994        NaN        2.0  right_only
452          996        NaN       10.0  right_only
453         1000        2.0        NaN   left_only

[454 rows x 4 columns]

In [78]:
full_join[full_join['_merge'] == 'left_only']['Customer ID'].drop_duplicates()

0         3
2        10
4        20
8        26
12       38
       ...
444     962
445     966
449     985
450     991
453    1000
Name: Customer ID, Length: 175, dtype: int64

In [74]:
full_join[full_join['_merge'] == 'right_only']['Customer ID'].drop_duplicates()

1        8
3       13
7       24
9       27
11      35
      ...
441    959
447    969
448    977
451    994
452    996
Name: Customer ID, Length: 178, dtype: int64

In [80]:
# 5
week1.merge(customers, how='left', left_on='Customer ID', right_index=True)

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III
...,...,...,...,...,...,...,...
245,413,9,Diane,Bailey,Female,Wikibox,Technical Writer
246,926,6,Anne,Wagner,Female,Skyba,Legal Assistant
247,134,3,Diana,Hall,Female,Quinu,Financial Advisor
248,396,6,Juan,Romero,Male,Zoonder,Analyst Programmer
249,535,10,Nancy,Cox,Female,Trudeo,Research Associate