In [1]:
import numpy as np
import pandas as pd

In [96]:
py_df = pd.read_csv(
    'data/2020_sharing_data_outside.csv',
    low_memory=False
)

py_df

,is.python.main,other.lang.None,other.lang.Java,other.lang.JavaScript,other.lang.C/C++,other.lang.PHP,other.lang.C#,other.lang.Ruby,other.lang.Bash / Shell,other.lang.Objective-C,...,job.role.Technical support,job.role.Data analyst,job.role.Business analyst,job.role.Team lead,job.role.Product manager,job.role.CIO / CEO / CTO,job.role.Systems analyst,job.role.Other,age,country.live
0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,Business analyst,NaN,NaN,NaN,NaN,NaN,30–39,NaN
1,Yes,NaN,Java,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,India
2,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,Technical support,Data analyst,NaN,Team lead,NaN,NaN,NaN,NaN,30–39,United States
3,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Yes,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,Objective-C,...,NaN,NaN,NaN,NaN,NaN,NaN,Systems analyst,NaN,21–29,Russian Federation
54458,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54459,Yes,NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,CIO / CEO / CTO,NaN,NaN,21–29,Russian Federation
54460,Yes,NaN,NaN,JavaScript,C/C++,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,Data analyst,NaN,NaN,NaN,NaN,NaN,NaN,30–39,Spain
54461,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Team lead,NaN,NaN,NaN,NaN,21–29,Algeria

In [97]:
sorted(list(py_df.columns))

['age',
 'are.you.datascientist',
 'bigdata.Apache Beam',
 'bigdata.Apache Flink',
 'bigdata.Apache Hadoop/MapReduce',
 'bigdata.Apache Hive',
 'bigdata.Apache Kafka',
 'bigdata.Apache Samza',
 'bigdata.Apache Spark',
 'bigdata.Apache Tez',
 'bigdata.ClickHouse',
 'bigdata.Dask',
 'bigdata.None',
 'bigdata.Other',
 'ci.AppVeyor',
 'ci.Bamboo',
 'ci.CircleCI',
 'ci.CruiseControl',
 'ci.Gitlab CI',
 'ci.Jenkins / Hudson',
 'ci.None',
 'ci.Other',
 'ci.TeamCity',
 'ci.Travis CI',
 'cloud.platform.AWS',
 'cloud.platform.DigitalOcean',
 'cloud.platform.Google Cloud Platform',
 'cloud.platform.Heroku',
 'cloud.platform.Linode',
 'cloud.platform.Microsoft Azure',
 'cloud.platform.None',
 'cloud.platform.OpenShift',
 'cloud.platform.OpenStack',
 'cloud.platform.Other',
 'cloud.platform.PythonAnywhere',
 'cloud.platform.Rackspace',
 'company.size',
 'configuration.management.Ansible',
 'configuration.management.Chef',
 'configuration.management.Custom solution',
 'configuration.management.None',
 'configuration.management.Other',
 'configuration.management.Puppet',
 'configuration.management.Salt',
 'country.live',
 'data.frameworks.Gensim',
 'data.frameworks.Keras',
 'data.frameworks.MXNet',
 'data.frameworks.Matplotlib',
 'data.frameworks.NLTK',
 'data.frameworks.None',
 'data.frameworks.NumPy',
 'data.frameworks.Other',
 'data.frameworks.Pandas',
 'data.frameworks.PyTorch',
 'data.frameworks.SciKit-Learn',
 'data.frameworks.SciPy',
 'data.frameworks.Seaborn',
 'data.frameworks.TensorFlow',
 'data.frameworks.Theano',
 'database.Amazon Redshift',
 'database.Cassandra',
 'database.Couchbase',
 'database.DB2',
 'database.HBase',
 'database.MS SQL Server',
 'database.MongoDB',
 'database.MySQL',
 'database.Neo4j',
 'database.None',
 'database.Oracle Database',
 'database.Other',
 'database.PostgreSQL',
 'database.Redis',
 'database.SQLite',
 'database.h2',
 'develop.for.cloud.Directly in the production environment',
 'develop.for.cloud.In Docker containers',
 'develop.for.cloud.In remote development environments',
 'develop.for.cloud.In virtual machines',
 'develop.for.cloud.Locally with virtualenv (or similar)',
 'develop.for.cloud.None of the following',
 'develop.for.cloud.Other',
 'develop.for.cloud.With local system interpreter',
 'devenv.os.BSD',
 'devenv.os.Linux',
 'devenv.os.Other',
 'devenv.os.Windows',
 'devenv.os.macOS',
 'employment.status',
 'first.learn.about.main.ide',
 'how.involved.Computer graphics',
 'how.involved.Data analysis',
 'how.involved.Desktop development',
 'how.involved.DevOps / System administration / Writing automation scripts',
 'how.involved.Educational purposes',
 'how.involved.Embedded development',
 'how.involved.Game development',
 'how.involved.Machine learning',
 'how.involved.Mobile development',
 'how.involved.Multimedia applications development',
 'how.involved.Network programming',
 'how.involved.Programming of web parsers / scrapers / crawlers',
 'how.involved.Software prototyping',
 'how.involved.Software testing / Writing automated tests',
 'how.involved.Web development',
 'how.often.use.main.ide',
 'ide.editor.Atom',
 'ide.editor.Eclipse + Pydev',
 'ide.editor.Emacs',
 'ide.editor.IDLE',
 'ide.editor.IntelliJ IDEA',
 'ide.editor.Jupyter Notebook',
 'ide.editor.JupyterLab',
 'ide.editor.None',
 'ide.editor.NotePad++',
 'ide.editor.Other',
 'ide.editor.PyCharm Community Edition',
 'ide.editor.PyCharm Professional Edition',
 'ide.editor.Python Tools for Visual Studio (PTVS)',
 'ide.editor.Spyder',
 'ide.editor.Sublime Text',
 'ide.editor.VS Code',
 'ide.editor.Vim',
 'ide.main',
 'is.python.main',
 'isolate.environments.Conda',
 'isolate.environments.Docker',
 'isolate.environments.None',
 'isolate.environments.Other',
 'isolate.environments.Pipenv',
 'isolate.environments.Poetry',
 'isolate.environments.Vagrant  / virtual machines',
 'isolate.environments.Virtualenv',
 'job.role.Architect',
 'job.role.Business analyst',
 'job.role.CIO / CEO / CTO',
 'job.role.DBA',
 'job.role.Data analyst',
 'job.role.Developer / Programmer',
 'job.role.Other',
 'job.role.Product manager',
 'job.role.QA engineer',
 'job.role.Systems analyst',
 'job.role.Team lead',
 'job.role.Technical support',
 'job.role.Technical writer',
 'job.team',
 'main.purposes',
 'missing.features.main.ide',
 'nps.main.ide',
 'orm.Dejavu',
 'orm.Django ORM',
 'orm.No database development',
 'orm.Other',
 'orm.Peewee',
 'orm.PonyORM',
 'orm.Raw SQL',
 'orm.SQLAlchemy',
 'orm.SQLObject',
 'orm.Tortoise ORM',
 'other.frameworks.Asyncio',
 'other.frameworks.Kivy',
 'other.frameworks.None',
 'other.frameworks.Other',
 'other.frameworks.Pillow',
 'other.frameworks.PyGTK',
 'other.frameworks.PyQT',
 'other.frameworks.Pygame',
 'other.frameworks.Requests',
 'other.frameworks.Scrapy',
 'other.frameworks.Six',
 'other.frameworks.Tkinter',
 'other.frameworks.Twisted',
 'other.frameworks.aiohttp',
 'other.frameworks.wxPython',
 'other.lang.Bash / Shell',
 'other.lang.C#',
 'other.lang.C/C++',
 'other.lang.Clojure',
 'other.lang.CoffeeScript',
 'other.lang.Go',
 'other.lang.Groovy',
 'other.lang.HTML/CSS',
 'other.lang.Java',
 'other.lang.JavaScript',
 'other.lang.Kotlin',
 'other.lang.None',
 'other.lang.Objective-C',
 'other.lang.Other',
 'other.lang.PHP',
 'other.lang.Perl',
 'other.lang.R',
 'other.lang.Ruby',
 'other.lang.Rust',
 'other.lang.SQL',
 'other.lang.Scala',
 'other.lang.Swift',
 'other.lang.TypeScript',
 'other.lang.Visual Basic',
 'other.purposes.Computer graphics',
 'other.purposes.Data analysis',
 'other.purposes.Desktop development',
 'other.purposes.DevOps / System administration / Writing automation scripts',
 'other.purposes.Educational purposes',
 'other.purposes.Embedded development',
 'other.purposes.Game development',
 'other.purposes.Machine learning',
 'other.purposes.Mobile development',
 'other.purposes.Multimedia applications development',
 'other.purposes.Network programming',
 'other.purposes.Other',
 'other.purposes.Programming of web parsers / scrapers / crawlers',
 'other.purposes.Software prototyping',
 'other.purposes.Software testing / Writing automated tests',
 'other.purposes.Web development',
 'python.version.most',
 'python.version.upgrade.ActivePython',
 'python.version.upgrade.Anaconda',
 'python.version.upgrade.Automatic upgrade via cloud provider',
 'python.version.upgrade.Build from source',
 'python.version.upgrade.I don’t update',
 'python.version.upgrade.I use Docker containers',
 'python.version.upgrade.Intel Distribution for Python',
 'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)',
 'python.version.upgrade.Other',
 'python.version.upgrade.Python_org',
 'python.version.upgrade.Somebody else manages Python updates for me',
 'python.version.upgrade.pyenv',
 'python.version.upgrade.pythonz',
 'python.years',
 'python2.version.most',
 'python3.version.most',
 'run.in.cloud.In virtual machines',
 'run.in.cloud.None of the following',
 'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)',
 'run.in.cloud.Other',
 'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)',
 'run.in.cloud.Within containers',
 'several.projects',
 'team.size',
 'unittesting.Hypothesis',
 'unittesting.None',
 'unittesting.Other',
 'unittesting.Tox',
 'unittesting.doctest',
 'unittesting.mock',
 'unittesting.nose',
 'unittesting.pytest',
 'unittesting.unittest',
 'use.python.most',
 'web.frameworks.Bottle',
 'web.frameworks.CherryPy\xa0',
 'web.frameworks.Django',
 'web.frameworks.Falcon',
 'web.frameworks.FastAPI',
 'web.frameworks.Flask\xa0',
 'web.frameworks.Hug',
 'web.frameworks.None',
 'web.frameworks.Other',
 'web.frameworks.Pyramid\xa0',
 'web.frameworks.Tornado',
 'web.frameworks.web2py',
 'years.of.coding']

In [98]:
max_num = 0
for col_name in py_df.columns:
    if col_name.count('.') > max_num:
        max_num = col_name.count('.')
print(max_num)

4

In [99]:
max_dots_lst = [col_name for col_name in py_df.columns if col_name.count('.') == 4]
print(max_dots_lst)

['first.learn.about.main.ide', 'how.often.use.main.ide']

In [100]:
name_exclusions = [
    'age',
    'are.you.datascientist',
    'is.python.main',
    'company.size',
    'country.live',
    'employment.status',
    'first.learn.about.main.ide',
    'how.often.use.main.ide',
    'main.purposes',
    'missing.features.main.ide',
    'nps.main.ide',
    'python.version.most',
    'python.years',
    'python2.version.most',
    'python3.version.most',
    'several.projects',
    'team.size',
    'use.python.most',
    'years.of.coding'
]

In [101]:
def get_tuple_from_column(column_name):
    dots_num = column_name.count('.')
    if column_name in name_exclusions:
        return ('general', column_name)
    elif dots_num >= 2:
        first, second = column_name.rsplit('.', 1)
        return (first, second)
    else:
        first, second = column_name.split('.')
        return (first, second)

In [102]:
index_tuples_lst = [get_tuple_from_column(col_name) for col_name in py_df.columns]
index_tuples_lst

[('general', 'is.python.main'),
 ('other.lang', 'None'),
 ('other.lang', 'Java'),
 ('other.lang', 'JavaScript'),
 ('other.lang', 'C/C++'),
 ('other.lang', 'PHP'),
 ('other.lang', 'C#'),
 ('other.lang', 'Ruby'),
 ('other.lang', 'Bash / Shell'),
 ('other.lang', 'Objective-C'),
 ('other.lang', 'Go'),
 ('other.lang', 'Visual Basic'),
 ('other.lang', 'Scala'),
 ('other.lang', 'SQL'),
 ('other.lang', 'Kotlin'),
 ('other.lang', 'R'),
 ('other.lang', 'Swift'),
 ('other.lang', 'Clojure'),
 ('other.lang', 'Perl'),
 ('other.lang', 'Rust'),
 ('other.lang', 'Groovy'),
 ('other.lang', 'TypeScript'),
 ('other.lang', 'CoffeeScript'),
 ('other.lang', 'HTML/CSS'),
 ('other.lang', 'Other'),
 ('general', 'python.years'),
 ('general', 'years.of.coding'),
 ('general', 'main.purposes'),
 ('other.purposes', 'Educational purposes'),
 ('other.purposes', 'Data analysis'),
 ('other.purposes',
  'DevOps / System administration / Writing automation scripts'),
 ('other.purposes', 'Software testing / Writing automated tests'),
 ('other.purposes', 'Software prototyping'),
 ('other.purposes', 'Web development'),
 ('other.purposes', 'Machine learning'),
 ('other.purposes', 'Mobile development'),
 ('other.purposes', 'Desktop development'),
 ('other.purposes', 'Computer graphics'),
 ('other.purposes', 'Network programming'),
 ('other.purposes', 'Game development'),
 ('other.purposes', 'Multimedia applications development'),
 ('other.purposes', 'Embedded development'),
 ('other.purposes', 'Programming of web parsers / scrapers / crawlers'),
 ('other.purposes', 'Other'),
 ('how.involved', 'Computer graphics'),
 ('how.involved', 'Data analysis'),
 ('how.involved',
  'DevOps / System administration / Writing automation scripts'),
 ('how.involved', 'Educational purposes'),
 ('how.involved', 'Software testing / Writing automated tests'),
 ('how.involved', 'Web development'),
 ('how.involved', 'Network programming'),
 ('how.involved', 'Desktop development'),
 ('how.involved', 'Machine learning'),
 ('how.involved', 'Software prototyping'),
 ('how.involved', 'Programming of web parsers / scrapers / crawlers'),
 ('how.involved', 'Embedded development'),
 ('how.involved', 'Mobile development'),
 ('how.involved', 'Game development'),
 ('how.involved', 'Multimedia applications development'),
 ('general', 'use.python.most'),
 ('general', 'are.you.datascientist'),
 ('general', 'python.version.most'),
 ('general', 'python2.version.most'),
 ('general', 'python3.version.most'),
 ('python.version.upgrade', 'I don’t update'),
 ('python.version.upgrade', 'Somebody else manages Python updates for me'),
 ('python.version.upgrade', 'Python_org'),
 ('python.version.upgrade', 'Build from source'),
 ('python.version.upgrade', 'Automatic upgrade via cloud provider'),
 ('python.version.upgrade', 'Anaconda'),
 ('python.version.upgrade', 'ActivePython'),
 ('python.version.upgrade', 'Intel Distribution for Python'),
 ('python.version.upgrade',
  'OS-provided Python (via apt-get, yum, homebrew, etc_)'),
 ('python.version.upgrade', 'pyenv'),
 ('python.version.upgrade', 'pythonz'),
 ('python.version.upgrade', 'I use Docker containers'),
 ('python.version.upgrade', 'Other'),
 ('isolate.environments', 'None'),
 ('isolate.environments', 'Virtualenv'),
 ('isolate.environments', 'Pipenv'),
 ('isolate.environments', 'Poetry'),
 ('isolate.environments', 'Conda'),
 ('isolate.environments', 'Docker'),
 ('isolate.environments', 'Vagrant  / virtual machines'),
 ('isolate.environments', 'Other'),
 ('web.frameworks', 'None'),
 ('web.frameworks', 'Django'),
 ('web.frameworks', 'web2py'),
 ('web.frameworks', 'Bottle'),
 ('web.frameworks', 'CherryPy\xa0'),
 ('web.frameworks', 'Flask\xa0'),
 ('web.frameworks', 'Hug'),
 ('web.frameworks', 'Pyramid\xa0'),
 ('web.frameworks', 'Tornado'),
 ('web.frameworks', 'Falcon'),
 ('web.frameworks', 'FastAPI'),
 ('web.frameworks', 'Other'),
 ('data.frameworks', 'None'),
 ('data.frameworks', 'PyTorch'),
 ('data.frameworks', 'NumPy'),
 ('data.frameworks', 'SciPy'),
 ('data.frameworks', 'Pandas'),
 ('data.frameworks', 'Matplotlib'),
 ('data.frameworks', 'Seaborn'),
 ('data.frameworks', 'SciKit-Learn'),
 ('data.frameworks', 'Keras'),
 ('data.frameworks', 'TensorFlow'),
 ('data.frameworks', 'Theano'),
 ('data.frameworks', 'NLTK'),
 ('data.frameworks', 'MXNet'),
 ('data.frameworks', 'Gensim'),
 ('data.frameworks', 'Other'),
 ('other.frameworks', 'None'),
 ('other.frameworks', 'Requests'),
 ('other.frameworks', 'aiohttp'),
 ('other.frameworks', 'PyQT'),
 ('other.frameworks', 'PyGTK'),
 ('other.frameworks', 'wxPython'),
 ('other.frameworks', 'Pillow'),
 ('other.frameworks', 'Tkinter'),
 ('other.frameworks', 'Pygame'),
 ('other.frameworks', 'Twisted'),
 ('other.frameworks', 'Asyncio'),
 ('other.frameworks', 'Kivy'),
 ('other.frameworks', 'Six'),
 ('other.frameworks', 'Scrapy'),
 ('other.frameworks', 'Other'),
 ('cloud.platform', 'None'),
 ('cloud.platform', 'Google Cloud Platform'),
 ('cloud.platform', 'AWS'),
 ('cloud.platform', 'Microsoft Azure'),
 ('cloud.platform', 'Rackspace'),
 ('cloud.platform', 'Heroku'),
 ('cloud.platform', 'DigitalOcean'),
 ('cloud.platform', 'Linode'),
 ('cloud.platform', 'PythonAnywhere'),
 ('cloud.platform', 'OpenShift'),
 ('cloud.platform', 'OpenStack'),
 ('cloud.platform', 'Other'),
 ('run.in.cloud', 'None of the following'),
 ('run.in.cloud', 'In virtual machines'),
 ('run.in.cloud', 'Within containers'),
 ('run.in.cloud',
  'On a Platform-as-a-Service (such as Heroku or Google App Engine)'),
 ('run.in.cloud', 'Serverless (such as AWS Lambda or Cloud Functions)'),
 ('run.in.cloud', 'Other'),
 ('develop.for.cloud', 'None of the following'),
 ('develop.for.cloud', 'With local system interpreter'),
 ('develop.for.cloud', 'Locally with virtualenv (or similar)'),
 ('develop.for.cloud', 'In Docker containers'),
 ('develop.for.cloud', 'In virtual machines'),
 ('develop.for.cloud', 'In remote development environments'),
 ('develop.for.cloud', 'Directly in the production environment'),
 ('develop.for.cloud', 'Other'),
 ('devenv.os', 'Windows'),
 ('devenv.os', 'Linux'),
 ('devenv.os', 'macOS'),
 ('devenv.os', 'BSD'),
 ('devenv.os', 'Other'),
 ('unittesting', 'None'),
 ('unittesting', 'pytest'),
 ('unittesting', 'nose'),
 ('unittesting', 'unittest'),
 ('unittesting', 'doctest'),
 ('unittesting', 'Tox'),
 ('unittesting', 'Hypothesis'),
 ('unittesting', 'mock'),
 ('unittesting', 'Other'),
 ('orm', 'No database development'),
 ('orm', 'Raw SQL'),
 ('orm', 'Django ORM'),
 ('orm', 'SQLAlchemy'),
 ('orm', 'Peewee'),
 ('orm', 'Dejavu'),
 ('orm', 'PonyORM'),
 ('orm', 'SQLObject'),
 ('orm', 'Tortoise ORM'),
 ('orm', 'Other'),
 ('database', 'None'),
 ('database', 'DB2'),
 ('database', 'MS SQL Server'),
 ('database', 'MySQL'),
 ('database', 'Oracle Database'),
 ('database', 'PostgreSQL'),
 ('database', 'SQLite'),
 ('database', 'Cassandra'),
 ('database', 'Couchbase'),
 ('database', 'HBase'),
 ('database', 'MongoDB'),
 ('database', 'Neo4j'),
 ('database', 'Redis'),
 ('database', 'Amazon Redshift'),
 ('database', 'h2'),
 ('database', 'Other'),
 ('bigdata', 'None'),
 ('bigdata', 'Apache Beam'),
 ('bigdata', 'Apache Flink'),
 ('bigdata', 'Apache Hadoop/MapReduce'),
 ('bigdata', 'Apache Hive'),
 ('bigdata', 'Apache Samza'),
 ('bigdata', 'Apache Kafka'),
 ('bigdata', 'Apache Spark'),
 ('bigdata', 'Apache Tez'),
 ('bigdata', 'Dask'),
 ('bigdata', 'ClickHouse'),
 ('bigdata', 'Other'),
 ('ci', 'None'),
 ('ci', 'Jenkins / Hudson'),
 ('ci', 'TeamCity'),
 ('ci', 'Bamboo'),
 ('ci', 'Travis CI'),
 ('ci', 'CircleCI'),
 ('ci', 'CruiseControl'),
 ('ci', 'Gitlab CI'),
 ('ci', 'AppVeyor'),
 ('ci', 'Other'),
 ('configuration.management', 'None'),
 ('configuration.management', 'Salt'),
 ('configuration.management', 'Puppet'),
 ('configuration.management', 'Chef'),
 ('configuration.management', 'Ansible'),
 ('configuration.management', 'Custom solution'),
 ('configuration.management', 'Other'),
 ('ide', 'main'),
 ('ide.editor', 'None'),
 ('ide.editor', 'Other'),
 ('ide.editor', 'PyCharm Professional Edition'),
 ('ide.editor', 'PyCharm Community Edition'),
 ('ide.editor', 'Sublime Text'),
 ('ide.editor', 'Vim'),
 ('ide.editor', 'Atom'),
 ('ide.editor', 'VS Code'),
 ('ide.editor', 'Eclipse + Pydev'),
 ('ide.editor', 'JupyterLab'),
 ('ide.editor', 'Jupyter Notebook'),
 ('ide.editor', 'IntelliJ IDEA'),
 ('ide.editor', 'NotePad++'),
 ('ide.editor', 'IDLE'),
 ('ide.editor', 'Emacs'),
 ('ide.editor', 'Python Tools for Visual Studio (PTVS)'),
 ('ide.editor', 'Spyder'),
 ('general', 'several.projects'),
 ('general', 'first.learn.about.main.ide'),
 ('general', 'how.often.use.main.ide'),
 ('general', 'missing.features.main.ide'),
 ('general', 'nps.main.ide'),
 ('job', 'team'),
 ('general', 'team.size'),
 ('general', 'employment.status'),
 ('general', 'company.size'),
 ('job.role', 'DBA'),
 ('job.role', 'Architect'),
 ('job.role', 'QA engineer'),
 ('job.role', 'Developer / Programmer'),
 ('job.role', 'Technical writer'),
 ('job.role', 'Technical support'),
 ('job.role', 'Data analyst'),
 ('job.role', 'Business analyst'),
 ('job.role', 'Team lead'),
 ('job.role', 'Product manager'),
 ('job.role', 'CIO / CEO / CTO'),
 ('job.role', 'Systems analyst'),
 ('job.role', 'Other'),
 ('general', 'age'),
 ('general', 'country.live')]

In [103]:
col_idx = pd.MultiIndex.from_tuples(index_tuples_lst)
col_idx

MultiIndex([(   'general',    'is.python.main'),
            ('other.lang',              'None'),
            ('other.lang',              'Java'),
            ('other.lang',        'JavaScript'),
            ('other.lang',             'C/C++'),
            ('other.lang',               'PHP'),
            ('other.lang',                'C#'),
            ('other.lang',              'Ruby'),
            ('other.lang',      'Bash / Shell'),
            ('other.lang',       'Objective-C'),
            ...
            (  'job.role', 'Technical support'),
            (  'job.role',      'Data analyst'),
            (  'job.role',  'Business analyst'),
            (  'job.role',         'Team lead'),
            (  'job.role',   'Product manager'),
            (  'job.role',   'CIO / CEO / CTO'),
            (  'job.role',   'Systems analyst'),
            (  'job.role',             'Other'),
            (   'general',               'age'),
            (   'general',      'country.live')],
           length=264)

In [104]:
py_df.columns

Index(['is.python.main', 'other.lang.None', 'other.lang.Java',
       'other.lang.JavaScript', 'other.lang.C/C++', 'other.lang.PHP',
       'other.lang.C#', 'other.lang.Ruby', 'other.lang.Bash / Shell',
       'other.lang.Objective-C',
       ...
       'job.role.Technical support', 'job.role.Data analyst',
       'job.role.Business analyst', 'job.role.Team lead',
       'job.role.Product manager', 'job.role.CIO / CEO / CTO',
       'job.role.Systems analyst', 'job.role.Other', 'age', 'country.live'],
      dtype='object', length=264)

In [105]:
col_idx

MultiIndex([(   'general',    'is.python.main'),
            ('other.lang',              'None'),
            ('other.lang',              'Java'),
            ('other.lang',        'JavaScript'),
            ('other.lang',             'C/C++'),
            ('other.lang',               'PHP'),
            ('other.lang',                'C#'),
            ('other.lang',              'Ruby'),
            ('other.lang',      'Bash / Shell'),
            ('other.lang',       'Objective-C'),
            ...
            (  'job.role', 'Technical support'),
            (  'job.role',      'Data analyst'),
            (  'job.role',  'Business analyst'),
            (  'job.role',         'Team lead'),
            (  'job.role',   'Product manager'),
            (  'job.role',   'CIO / CEO / CTO'),
            (  'job.role',   'Systems analyst'),
            (  'job.role',             'Other'),
            (   'general',               'age'),
            (   'general',      'country.live')],
           length=264)

In [106]:
py_df.columns = col_idx

In [107]:
py_df

             general other.lang                                          \
      is.python.main       None  Java  JavaScript  C/C++  PHP   C# Ruby
0                Yes        NaN   NaN         NaN    NaN  NaN  NaN  NaN
1                Yes        NaN  Java  JavaScript    NaN  NaN   C#  NaN
2                Yes        NaN   NaN         NaN  C/C++  NaN  NaN  NaN
3                Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN
4                Yes        NaN  Java  JavaScript  C/C++  NaN  NaN  NaN
...              ...        ...   ...         ...    ...  ...  ...  ...
54457            Yes        NaN   NaN         NaN  C/C++  NaN  NaN  NaN
54458            Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN
54459            Yes        NaN   NaN  JavaScript    NaN  PHP  NaN  NaN
54460            Yes        NaN   NaN  JavaScript  C/C++  PHP  NaN  NaN
54461            Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN

                                  ...           job.role                \
       Bash / Shell  Objective-C  ...  Technical support  Data analyst
0      Bash / Shell          NaN  ...                NaN           NaN
1               NaN          NaN  ...                NaN           NaN
2      Bash / Shell          NaN  ...  Technical support  Data analyst
3      Bash / Shell          NaN  ...                NaN           NaN
4      Bash / Shell          NaN  ...                NaN           NaN
...             ...          ...  ...                ...           ...
54457  Bash / Shell  Objective-C  ...                NaN           NaN
54458  Bash / Shell          NaN  ...                NaN           NaN
54459  Bash / Shell          NaN  ...                NaN           NaN
54460  Bash / Shell          NaN  ...                NaN  Data analyst
54461           NaN          NaN  ...                NaN           NaN

                                                                     \
       Business analyst  Team lead Product manager  CIO / CEO / CTO
0      Business analyst        NaN             NaN              NaN
1                   NaN        NaN             NaN              NaN
2                   NaN  Team lead             NaN              NaN
3                   NaN        NaN             NaN              NaN
4                   NaN        NaN             NaN              NaN
...                 ...        ...             ...              ...
54457               NaN        NaN             NaN              NaN
54458               NaN        NaN             NaN              NaN
54459               NaN        NaN             NaN  CIO / CEO / CTO
54460               NaN        NaN             NaN              NaN
54461               NaN  Team lead             NaN              NaN

                             general
       Systems analyst Other     age        country.live
0                  NaN   NaN   30–39                 NaN
1                  NaN   NaN   21–29               India
2                  NaN   NaN   30–39       United States
3                  NaN   NaN     NaN                 NaN
4                  NaN   NaN   21–29               Italy
...                ...   ...     ...                 ...
54457  Systems analyst   NaN   21–29  Russian Federation
54458              NaN   NaN     NaN                 NaN
54459              NaN   NaN   21–29  Russian Federation
54460              NaN   NaN   30–39               Spain
54461              NaN   NaN   21–29             Algeria

[54462 rows x 264 columns]

In [108]:
py_df = py_df.sort_index(axis=1)

In [109]:
list(py_df.columns)

[('bigdata', 'Apache Beam'),
 ('bigdata', 'Apache Flink'),
 ('bigdata', 'Apache Hadoop/MapReduce'),
 ('bigdata', 'Apache Hive'),
 ('bigdata', 'Apache Kafka'),
 ('bigdata', 'Apache Samza'),
 ('bigdata', 'Apache Spark'),
 ('bigdata', 'Apache Tez'),
 ('bigdata', 'ClickHouse'),
 ('bigdata', 'Dask'),
 ('bigdata', 'None'),
 ('bigdata', 'Other'),
 ('ci', 'AppVeyor'),
 ('ci', 'Bamboo'),
 ('ci', 'CircleCI'),
 ('ci', 'CruiseControl'),
 ('ci', 'Gitlab CI'),
 ('ci', 'Jenkins / Hudson'),
 ('ci', 'None'),
 ('ci', 'Other'),
 ('ci', 'TeamCity'),
 ('ci', 'Travis CI'),
 ('cloud.platform', 'AWS'),
 ('cloud.platform', 'DigitalOcean'),
 ('cloud.platform', 'Google Cloud Platform'),
 ('cloud.platform', 'Heroku'),
 ('cloud.platform', 'Linode'),
 ('cloud.platform', 'Microsoft Azure'),
 ('cloud.platform', 'None'),
 ('cloud.platform', 'OpenShift'),
 ('cloud.platform', 'OpenStack'),
 ('cloud.platform', 'Other'),
 ('cloud.platform', 'PythonAnywhere'),
 ('cloud.platform', 'Rackspace'),
 ('configuration.management', 'Ansible'),
 ('configuration.management', 'Chef'),
 ('configuration.management', 'Custom solution'),
 ('configuration.management', 'None'),
 ('configuration.management', 'Other'),
 ('configuration.management', 'Puppet'),
 ('configuration.management', 'Salt'),
 ('data.frameworks', 'Gensim'),
 ('data.frameworks', 'Keras'),
 ('data.frameworks', 'MXNet'),
 ('data.frameworks', 'Matplotlib'),
 ('data.frameworks', 'NLTK'),
 ('data.frameworks', 'None'),
 ('data.frameworks', 'NumPy'),
 ('data.frameworks', 'Other'),
 ('data.frameworks', 'Pandas'),
 ('data.frameworks', 'PyTorch'),
 ('data.frameworks', 'SciKit-Learn'),
 ('data.frameworks', 'SciPy'),
 ('data.frameworks', 'Seaborn'),
 ('data.frameworks', 'TensorFlow'),
 ('data.frameworks', 'Theano'),
 ('database', 'Amazon Redshift'),
 ('database', 'Cassandra'),
 ('database', 'Couchbase'),
 ('database', 'DB2'),
 ('database', 'HBase'),
 ('database', 'MS SQL Server'),
 ('database', 'MongoDB'),
 ('database', 'MySQL'),
 ('database', 'Neo4j'),
 ('database', 'None'),
 ('database', 'Oracle Database'),
 ('database', 'Other'),
 ('database', 'PostgreSQL'),
 ('database', 'Redis'),
 ('database', 'SQLite'),
 ('database', 'h2'),
 ('develop.for.cloud', 'Directly in the production environment'),
 ('develop.for.cloud', 'In Docker containers'),
 ('develop.for.cloud', 'In remote development environments'),
 ('develop.for.cloud', 'In virtual machines'),
 ('develop.for.cloud', 'Locally with virtualenv (or similar)'),
 ('develop.for.cloud', 'None of the following'),
 ('develop.for.cloud', 'Other'),
 ('develop.for.cloud', 'With local system interpreter'),
 ('devenv.os', 'BSD'),
 ('devenv.os', 'Linux'),
 ('devenv.os', 'Other'),
 ('devenv.os', 'Windows'),
 ('devenv.os', 'macOS'),
 ('general', 'age'),
 ('general', 'are.you.datascientist'),
 ('general', 'company.size'),
 ('general', 'country.live'),
 ('general', 'employment.status'),
 ('general', 'first.learn.about.main.ide'),
 ('general', 'how.often.use.main.ide'),
 ('general', 'is.python.main'),
 ('general', 'main.purposes'),
 ('general', 'missing.features.main.ide'),
 ('general', 'nps.main.ide'),
 ('general', 'python.version.most'),
 ('general', 'python.years'),
 ('general', 'python2.version.most'),
 ('general', 'python3.version.most'),
 ('general', 'several.projects'),
 ('general', 'team.size'),
 ('general', 'use.python.most'),
 ('general', 'years.of.coding'),
 ('how.involved', 'Computer graphics'),
 ('how.involved', 'Data analysis'),
 ('how.involved', 'Desktop development'),
 ('how.involved',
  'DevOps / System administration / Writing automation scripts'),
 ('how.involved', 'Educational purposes'),
 ('how.involved', 'Embedded development'),
 ('how.involved', 'Game development'),
 ('how.involved', 'Machine learning'),
 ('how.involved', 'Mobile development'),
 ('how.involved', 'Multimedia applications development'),
 ('how.involved', 'Network programming'),
 ('how.involved', 'Programming of web parsers / scrapers / crawlers'),
 ('how.involved', 'Software prototyping'),
 ('how.involved', 'Software testing / Writing automated tests'),
 ('how.involved', 'Web development'),
 ('ide', 'main'),
 ('ide.editor', 'Atom'),
 ('ide.editor', 'Eclipse + Pydev'),
 ('ide.editor', 'Emacs'),
 ('ide.editor', 'IDLE'),
 ('ide.editor', 'IntelliJ IDEA'),
 ('ide.editor', 'Jupyter Notebook'),
 ('ide.editor', 'JupyterLab'),
 ('ide.editor', 'None'),
 ('ide.editor', 'NotePad++'),
 ('ide.editor', 'Other'),
 ('ide.editor', 'PyCharm Community Edition'),
 ('ide.editor', 'PyCharm Professional Edition'),
 ('ide.editor', 'Python Tools for Visual Studio (PTVS)'),
 ('ide.editor', 'Spyder'),
 ('ide.editor', 'Sublime Text'),
 ('ide.editor', 'VS Code'),
 ('ide.editor', 'Vim'),
 ('isolate.environments', 'Conda'),
 ('isolate.environments', 'Docker'),
 ('isolate.environments', 'None'),
 ('isolate.environments', 'Other'),
 ('isolate.environments', 'Pipenv'),
 ('isolate.environments', 'Poetry'),
 ('isolate.environments', 'Vagrant  / virtual machines'),
 ('isolate.environments', 'Virtualenv'),
 ('job', 'team'),
 ('job.role', 'Architect'),
 ('job.role', 'Business analyst'),
 ('job.role', 'CIO / CEO / CTO'),
 ('job.role', 'DBA'),
 ('job.role', 'Data analyst'),
 ('job.role', 'Developer / Programmer'),
 ('job.role', 'Other'),
 ('job.role', 'Product manager'),
 ('job.role', 'QA engineer'),
 ('job.role', 'Systems analyst'),
 ('job.role', 'Team lead'),
 ('job.role', 'Technical support'),
 ('job.role', 'Technical writer'),
 ('orm', 'Dejavu'),
 ('orm', 'Django ORM'),
 ('orm', 'No database development'),
 ('orm', 'Other'),
 ('orm', 'Peewee'),
 ('orm', 'PonyORM'),
 ('orm', 'Raw SQL'),
 ('orm', 'SQLAlchemy'),
 ('orm', 'SQLObject'),
 ('orm', 'Tortoise ORM'),
 ('other.frameworks', 'Asyncio'),
 ('other.frameworks', 'Kivy'),
 ('other.frameworks', 'None'),
 ('other.frameworks', 'Other'),
 ('other.frameworks', 'Pillow'),
 ('other.frameworks', 'PyGTK'),
 ('other.frameworks', 'PyQT'),
 ('other.frameworks', 'Pygame'),
 ('other.frameworks', 'Requests'),
 ('other.frameworks', 'Scrapy'),
 ('other.frameworks', 'Six'),
 ('other.frameworks', 'Tkinter'),
 ('other.frameworks', 'Twisted'),
 ('other.frameworks', 'aiohttp'),
 ('other.frameworks', 'wxPython'),
 ('other.lang', 'Bash / Shell'),
 ('other.lang', 'C#'),
 ('other.lang', 'C/C++'),
 ('other.lang', 'Clojure'),
 ('other.lang', 'CoffeeScript'),
 ('other.lang', 'Go'),
 ('other.lang', 'Groovy'),
 ('other.lang', 'HTML/CSS'),
 ('other.lang', 'Java'),
 ('other.lang', 'JavaScript'),
 ('other.lang', 'Kotlin'),
 ('other.lang', 'None'),
 ('other.lang', 'Objective-C'),
 ('other.lang', 'Other'),
 ('other.lang', 'PHP'),
 ('other.lang', 'Perl'),
 ('other.lang', 'R'),
 ('other.lang', 'Ruby'),
 ('other.lang', 'Rust'),
 ('other.lang', 'SQL'),
 ('other.lang', 'Scala'),
 ('other.lang', 'Swift'),
 ('other.lang', 'TypeScript'),
 ('other.lang', 'Visual Basic'),
 ('other.purposes', 'Computer graphics'),
 ('other.purposes', 'Data analysis'),
 ('other.purposes', 'Desktop development'),
 ('other.purposes',
  'DevOps / System administration / Writing automation scripts'),
 ('other.purposes', 'Educational purposes'),
 ('other.purposes', 'Embedded development'),
 ('other.purposes', 'Game development'),
 ('other.purposes', 'Machine learning'),
 ('other.purposes', 'Mobile development'),
 ('other.purposes', 'Multimedia applications development'),
 ('other.purposes', 'Network programming'),
 ('other.purposes', 'Other'),
 ('other.purposes', 'Programming of web parsers / scrapers / crawlers'),
 ('other.purposes', 'Software prototyping'),
 ('other.purposes', 'Software testing / Writing automated tests'),
 ('other.purposes', 'Web development'),
 ('python.version.upgrade', 'ActivePython'),
 ('python.version.upgrade', 'Anaconda'),
 ('python.version.upgrade', 'Automatic upgrade via cloud provider'),
 ('python.version.upgrade', 'Build from source'),
 ('python.version.upgrade', 'I don’t update'),
 ('python.version.upgrade', 'I use Docker containers'),
 ('python.version.upgrade', 'Intel Distribution for Python'),
 ('python.version.upgrade',
  'OS-provided Python (via apt-get, yum, homebrew, etc_)'),
 ('python.version.upgrade', 'Other'),
 ('python.version.upgrade', 'Python_org'),
 ('python.version.upgrade', 'Somebody else manages Python updates for me'),
 ('python.version.upgrade', 'pyenv'),
 ('python.version.upgrade', 'pythonz'),
 ('run.in.cloud', 'In virtual machines'),
 ('run.in.cloud', 'None of the following'),
 ('run.in.cloud',
  'On a Platform-as-a-Service (such as Heroku or Google App Engine)'),
 ('run.in.cloud', 'Other'),
 ('run.in.cloud', 'Serverless (such as AWS Lambda or Cloud Functions)'),
 ('run.in.cloud', 'Within containers'),
 ('unittesting', 'Hypothesis'),
 ('unittesting', 'None'),
 ('unittesting', 'Other'),
 ('unittesting', 'Tox'),
 ('unittesting', 'doctest'),
 ('unittesting', 'mock'),
 ('unittesting', 'nose'),
 ('unittesting', 'pytest'),
 ('unittesting', 'unittest'),
 ('web.frameworks', 'Bottle'),
 ('web.frameworks', 'CherryPy\xa0'),
 ('web.frameworks', 'Django'),
 ('web.frameworks', 'Falcon'),
 ('web.frameworks', 'FastAPI'),
 ('web.frameworks', 'Flask\xa0'),
 ('web.frameworks', 'Hug'),
 ('web.frameworks', 'None'),
 ('web.frameworks', 'Other'),
 ('web.frameworks', 'Pyramid\xa0'),
 ('web.frameworks', 'Tornado'),
 ('web.frameworks', 'web2py')]

In [110]:
[col for col in py_df.columns if 'ide' in col[0]]

[('ide', 'main'),
 ('ide.editor', 'Atom'),
 ('ide.editor', 'Eclipse + Pydev'),
 ('ide.editor', 'Emacs'),
 ('ide.editor', 'IDLE'),
 ('ide.editor', 'IntelliJ IDEA'),
 ('ide.editor', 'Jupyter Notebook'),
 ('ide.editor', 'JupyterLab'),
 ('ide.editor', 'None'),
 ('ide.editor', 'NotePad++'),
 ('ide.editor', 'Other'),
 ('ide.editor', 'PyCharm Community Edition'),
 ('ide.editor', 'PyCharm Professional Edition'),
 ('ide.editor', 'Python Tools for Visual Studio (PTVS)'),
 ('ide.editor', 'Spyder'),
 ('ide.editor', 'Sublime Text'),
 ('ide.editor', 'VS Code'),
 ('ide.editor', 'Vim')]

In [111]:
py_df[[col for col in py_df.columns if 'ide' in col[0]]]

                                ide ide.editor                              \
                               main       Atom Eclipse + Pydev  Emacs IDLE
0         PyCharm Community Edition        NaN             NaN  Emacs  NaN
1                           VS Code        NaN             NaN    NaN  NaN
2                               Vim        NaN             NaN    NaN  NaN
3      PyCharm Professional Edition        NaN             NaN    NaN  NaN
4                           VS Code        NaN             NaN    NaN  NaN
...                             ...        ...             ...    ...  ...
54457                           Vim        NaN             NaN    NaN  NaN
54458                           NaN        NaN             NaN    NaN  NaN
54459  PyCharm Professional Edition        NaN             NaN    NaN  NaN
54460                         Other        NaN             NaN    NaN  NaN
54461                       VS Code        NaN             NaN    NaN  NaN

                                                                         \
      IntelliJ IDEA  Jupyter Notebook JupyterLab None  NotePad++  Other
0               NaN               NaN        NaN  NaN        NaN    NaN
1               NaN  Jupyter Notebook        NaN  NaN  NotePad++    NaN
2               NaN               NaN        NaN  NaN        NaN    NaN
3               NaN               NaN        NaN  NaN        NaN    NaN
4               NaN               NaN        NaN  NaN        NaN    NaN
...             ...               ...        ...  ...        ...    ...
54457           NaN               NaN        NaN  NaN        NaN  Other
54458           NaN               NaN        NaN  NaN        NaN    NaN
54459           NaN               NaN        NaN  NaN        NaN    NaN
54460           NaN               NaN        NaN  NaN        NaN    NaN
54461           NaN               NaN        NaN  NaN        NaN    NaN

                                                              \
      PyCharm Community Edition PyCharm Professional Edition
0                           NaN                          NaN
1                           NaN                          NaN
2                           NaN                          NaN
3                           NaN                          NaN
4                           NaN                          NaN
...                         ...                          ...
54457                       NaN                          NaN
54458                       NaN                          NaN
54459                       NaN                          NaN
54460                       NaN                          NaN
54461                       NaN                          NaN

                                                                            \
      Python Tools for Visual Studio (PTVS)  Spyder  Sublime Text  VS Code
0                                       NaN     NaN           NaN      NaN
1                                       NaN     NaN  Sublime Text      NaN
2                                       NaN     NaN           NaN  VS Code
3                                       NaN     NaN  Sublime Text      NaN
4                                       NaN     NaN           NaN      NaN
...                                     ...     ...           ...      ...
54457                                   NaN     NaN           NaN      NaN
54458                                   NaN     NaN           NaN      NaN
54459                                   NaN     NaN           NaN  VS Code
54460                                   NaN  Spyder           NaN      NaN
54461                                   NaN     NaN  Sublime Text      NaN


       Vim
0      NaN
1      NaN
2      NaN
3      Vim
4      Vim
...    ...
54457  NaN
54458  NaN
54459  NaN
54460  NaN
54461  NaN

[54462 rows x 18 columns]

In [112]:
len(py_df[('ide', 'main')].value_counts())

16

In [113]:
py_df[('ide', 'main')].value_counts().iloc[:10]

(ide, main)
VS Code                         8010
PyCharm Professional Edition    5144
PyCharm Community Edition       3815
Vim                             2176
Sublime Text                    1201
Jupyter Notebook                1167
Atom                             784
Other                            711
Emacs                            636
Spyder                           580
Name: count, dtype: int64

In [114]:
py_df[('other.lang')]['Bash / Shell'].apply(lambda v: 1 if pd.notnull(v) else 0)

0        1
1        0
2        1
3        1
4        1
        ..
54457    1
54458    1
54459    1
54460    1
54461    0
Name: Bash / Shell, Length: 54462, dtype: int64

In [115]:
other_lang_data = []
other_lang_idx = []

for col_name in py_df[('other.lang')].columns:
    other_lang_idx.append(col_name)
    other_lang_data.append(py_df[('other.lang')][col_name].apply(lambda v: 1 if pd.notnull(v) else 0).sum())

other_lang = pd.Series(data=other_lang_data, index=other_lang_idx)
other_lang

Bash / Shell    13793
C#               4460
C/C++           11623
Clojure           361
CoffeeScript      319
Go               3398
Groovy            719
HTML/CSS        15469
Java             8109
JavaScript      16662
Kotlin           1384
None                0
Objective-C       583
Other            3592
PHP              4060
Perl              886
R                2465
Ruby             1165
Rust             1853
SQL             13391
Scala             927
Swift             854
TypeScript       3717
Visual Basic     1604
dtype: int64

In [116]:
other_lang.sort_values(ascending=False).iloc[:10]

JavaScript      16662
HTML/CSS        15469
Bash / Shell    13793
SQL             13391
C/C++           11623
Java             8109
C#               4460
PHP              4060
TypeScript       3717
Other            3592
dtype: int64

In [117]:
py_df[('general')].columns

Index(['age', 'are.you.datascientist', 'company.size', 'country.live',
       'employment.status', 'first.learn.about.main.ide',
       'how.often.use.main.ide', 'is.python.main', 'main.purposes',
       'missing.features.main.ide', 'nps.main.ide', 'python.version.most',
       'python.years', 'python2.version.most', 'python3.version.most',
       'several.projects', 'team.size', 'use.python.most', 'years.of.coding'],
      dtype='object')

In [118]:
py_df[('general', 'country.live')].value_counts().iloc[:10]

(general, country.live)
United States         3975
India                 2800
Germany               1807
China                 1155
United Kingdom        1110
France                1078
Russian Federation     935
Other country          880
Brazil                 812
Canada                 644
Name: count, dtype: int64

In [125]:
(py_df[('general', 'python.years')].value_counts(normalize=True) * 100).round(2)

(general, python.years)
3–5 years           28.43
Less than 1 year    23.95
1–2 years           22.48
6–10 years          15.49
11+ years            9.64
Name: proportion, dtype: float64

In [126]:
py_df.loc[py_df[('general', 'python.years')] == '11+ years'][('general', 'country.live')].value_counts().head(1)

(general, country.live)
United States    691
Name: count, dtype: int64

In [121]:
py_df[('general', 'is.python.main')].value_counts()

(general, is.python.main)
Yes                                               33528
No, I use Python as a secondary language           5992
No, I don’t use Python for my current projects     2212
Name: count, dtype: int64

In [127]:
df1 = py_df.groupby(by=[('general', 'country.live'), ('general', 'python.years')])[[('general', 'python.years')]].count().groupby(by=[('general', 'country.live')]).transform(lambda v: v / v.sum())

In [128]:
df1.head()

                                                     general
                                                python.years
(general, country.live) (general, python.years)
Algeria                 11+ years                   0.078947
                        1–2 years                   0.289474
                        3–5 years                   0.210526
                        6–10 years                  0.105263
                        Less than 1 year            0.315789

In [129]:
df1.loc[(slice(None), '11+ years'), :].loc[lambda df_: df_[('general', 'python.years')] == df_[('general', 'python.years')].max()]

                                                     general
                                                python.years
(general, country.live) (general, python.years)
Norway                  11+ years                    0.27044

In [186]:
so_df = pd.read_csv(
    'data/so_2021_survey_results.csv',
    low_memory=False
)

so_df

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83435,83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [187]:
so_df.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'Country', 'US_State',
       'UK_Country', 'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'Currency', 'CompTotal',
       'CompFreq', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [188]:
so_df['DevType'].value_counts()

DevType
Developer, full-stack                                                                                                                                                                                                                                                                                                                                                                                          8601
Developer, back-end                                                                                                                                                                                                                                                                                                                                                                                            5467
Developer, front-end                                                                                                                                                                                                                                                                                                                                                                                           2402
Developer, front-end;Developer, full-stack;Developer, back-end                                                                                                                                                                                                                                                                                                                                                 2141
Developer, full-stack;Developer, back-end                                                                                                                                                                                                                                                                                                                                                                      1774
                                                                                                                                                                                                                                                                                                                                                                                                               ...
Developer, mobile;Developer, desktop or enterprise applications;Developer, full-stack;Engineer, data                                                                                                                                                                                                                                                                                                              1
Developer, mobile;Developer, front-end;Developer, desktop or enterprise applications;Developer, full-stack;Engineer, data;Developer, back-end;Scientist;Developer, QA or test;Developer, game or graphics;Developer, embedded applications or devices;DevOps specialist;Engineering manager;Engineer, site reliability;Product manager;Senior Executive (C-Suite, VP, etc.);Marketing or sales professional       1
Developer, back-end;Student;Developer, embedded applications or devices;Designer                                                                                                                                                                                                                                                                                                                                  1
Developer, front-end;Developer, full-stack;Engineer, data;Data scientist or machine learning specialist;Developer, back-end;Database administrator;Designer;Engineering manager;Engineer, site reliability;Product manager;Senior Executive (C-Suite, VP, etc.);Marketing or sales professional                                                                                                                   1
Developer, mobile;Developer, desktop or enterprise applications;Data scientist or machine learning specialist;Developer, back-end;Engineering manager                                                                                                                                                                                                                                                             1
Name: count, Length: 8626, dtype: int64

In [189]:
so_df['Employment'].value_counts()

Employment
Employed full-time                                      53584
Student, full-time                                      11781
Independent contractor, freelancer, or self-employed     8041
Not employed, but looking for work                       2961
Employed part-time                                       2461
Student, part-time                                       2051
Not employed, and not looking for work                   1228
I prefer not to say                                       890
Retired                                                   326
Name: count, dtype: int64

In [190]:
so_df[['Currency', 'CompTotal', 'CompFreq', 'ConvertedCompYearly']]

                          Currency  CompTotal CompFreq  ConvertedCompYearly
0                EUR European Euro     4800.0  Monthly              62268.0
1                              NaN        NaN      NaN                  NaN
2                              NaN        NaN      NaN                  NaN
3                EUR European Euro        NaN  Monthly                  NaN
4              GBP\tPound sterling        NaN      NaN                  NaN
...                            ...        ...      ...                  ...
83434    USD\tUnited States dollar   160500.0   Yearly             160500.0
83435  XOF\tWest African CFA franc   200000.0  Monthly               3960.0
83436    USD\tUnited States dollar     1800.0   Weekly              90000.0
83437         CAD\tCanadian dollar    90000.0  Monthly             816816.0
83438          BRL\tBrazilian real     7700.0  Monthly              21168.0

[83439 rows x 4 columns]

In [218]:
so_df.groupby('Employment')['ConvertedCompYearly'].mean().sort_values(ascending=False).round(2)

Employment
I prefer not to say                                     1455643.25
Employed full-time                                       121369.67
Independent contractor, freelancer, or self-employed     107433.97
Retired                                                   69533.25
Employed part-time                                        41136.12
Not employed, and not looking for work                         NaN
Not employed, but looking for work                             NaN
Student, full-time                                             NaN
Student, part-time                                             NaN
Name: ConvertedCompYearly, dtype: float64

In [192]:
so_df.pivot_table(index='Country', columns='EdLevel', values='ConvertedCompYearly', aggfunc='mean').round(2)

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else
Country,,,,,,,,,
Afghanistan,NaN,30288.00,10176704.00,NaN,NaN,NaN,100.0,NaN,NaN
Albania,NaN,19152.86,80127.62,NaN,NaN,5298.00,19890.0,22884.00,128522.0
Algeria,NaN,21770.67,15052.57,NaN,NaN,12912.00,NaN,6288.00,NaN
Andorra,NaN,94045.50,22056.00,146981.0,NaN,NaN,NaN,NaN,NaN
Angola,NaN,31500.00,NaN,NaN,NaN,NaN,18678.0,6904.00,NaN
...,...,...,...,...,...,...,...,...,...
"Venezuela, Bolivarian Republic of...",NaN,30108.77,28680.00,NaN,7200.0,14833.29,10200.0,17720.57,NaN
Viet Nam,7827.0,18463.11,50599.80,2592.0,10479.0,30000.00,NaN,18866.19,NaN
Yemen,NaN,5628.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,NaN,40173.00,4908.00,NaN,NaN,NaN,4482.0,12105.33,8184.0
Zimbabwe,36000.0,8399.27,NaN,NaN,NaN,NaN,NaN,20000.00,NaN

In [193]:
oecd_locations = pd.read_csv('data/oecd_locations.csv', header=None, names=['country_short', 'country'])

oecd_locations

   country_short         country
0            AUS       Australia
1            AUT         Austria
2            BEL         Belgium
3            CAN          Canada
4            DNK         Denmark
5            FIN         Finland
6            FRA          France
7            DEU         Germany
8            HUN         Hungary
9            ITA           Italy
10           JPN           Japan
11           KOR           Korea
12           GBR  United Kingdom
13           USA   United States
14           BRA          Brazil
15           ISR          Israel

In [194]:
piv_t = so_df.merge(right=oecd_locations, how='inner', left_on='Country', right_on='country').pivot_table(index='Country', columns='EdLevel', values='ConvertedCompYearly', aggfunc='mean').round(2)

In [195]:
piv_t

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else
Country,,,,,,,,,
Australia,117049.64,180794.16,106794.32,150234.96,153327.50,108725.00,158931.28,127063.53,231987.17
Austria,43623.38,66096.13,77645.66,74783.17,86877.00,38915.33,47438.83,53906.05,45772.53
Belgium,35664.00,68474.70,88580.41,80832.44,11342349.25,71000.20,43224.13,88006.29,27035.50
Brazil,25347.42,47681.23,42056.01,43123.21,7880.00,25449.67,15072.89,39978.02,20288.71
Canada,87930.35,140668.24,144733.35,102989.35,73787.83,82953.40,180584.81,155090.08,60795.17
Denmark,80217.33,80430.94,115751.85,102785.19,91056.57,114144.89,90411.74,85131.35,95479.86
Finland,282353.67,69381.34,74360.98,61508.25,77832.00,83016.00,59424.32,89255.56,35024.00
France,54394.89,65062.38,94585.73,140402.86,34181.00,78342.27,53981.81,55119.45,42884.04
Germany,98530.52,102751.23,110611.98,108718.46,74943.67,97330.14,82865.84,95737.77,109333.99
Hungary,51041.00,48756.45,46771.71,52833.60,48100.00,9852.00,33440.80,37102.89,28911.00
Israel,146420.90,124973.40,128492.71,131812.62,100514.57,132336.00,97938.78,130049.04,96142.50
Italy,36427.94,73697.22,79132.19,93490.78,525992.17,117121.37,75114.40,81531.72,32690.22
Japan,143196.83,85821.47,130143.19,157239.40,44965.00,NaN,57916.40,91163.04,194514.00

In [196]:
piv_t['Associate degree (A.A., A.S., etc.)'].sort_values(ascending=False).head(1)

Country
Finland    282353.67
Name: Associate degree (A.A., A.S., etc.), dtype: float64

In [197]:
piv_t['Other doctoral degree (Ph.D., Ed.D., etc.)'].sort_values(ascending=False).head(1)

Country
Japan    157239.4
Name: Other doctoral degree (Ph.D., Ed.D., etc.), dtype: float64

In [198]:
df1 = so_df.dropna(subset=['LanguageHaveWorkedWith'])

In [199]:
len(so_df)

83439

In [200]:
len(df1)

82357

In [201]:
df1['LanguageHaveWorkedWith'].apply(lambda x: 'Python' in x).sum()

np.int64(39792)

In [202]:
df2 = df1.loc[df1['LanguageHaveWorkedWith'].apply(lambda x: 'Python' in x)]

In [203]:
len(df2)

39792

In [204]:
df3 = df2.dropna(subset=['YearsCode'])

In [205]:
len(df3)

38997

In [206]:
df3['YearsCode'].value_counts()

YearsCode
5                     3387
6                     3016
10                    2935
4                     2793
7                     2563
3                     2498
8                     2367
2                     1850
9                     1543
15                    1519
12                    1416
20                    1405
11                    1101
13                     888
1                      883
25                     792
14                     762
30                     680
16                     603
Less than 1 year       601
18                     568
17                     543
35                     389
22                     364
21                     344
40                     336
23                     313
19                     267
24                     233
26                     205
28                     184
27                     173
38                     139
32                     137
33                     136
37                     124
34                     109
36                      88
39                      88
42                      84
31                      82
29                      74
41                      72
More than 50 years      72
45                      70
43                      59
44                      35
46                      30
50                      22
47                      22
49                      20
48                      13
Name: count, dtype: int64

In [207]:
df3['YearsCode'].dtype

dtype('O')

In [208]:
def convert_years(val):
    if val == 'Less than 1 year':
        return 0
    elif val == 'More than 50 years':
        return 51
    else:
        return val

In [209]:
df3.loc[:, 'YearsCode'] = df3['YearsCode'].apply(convert_years)

In [210]:
df3['YearsCode'].value_counts()

YearsCode
5     3387
6     3016
10    2935
4     2793
7     2563
3     2498
8     2367
2     1850
9     1543
15    1519
12    1416
20    1405
11    1101
13     888
1      883
25     792
14     762
30     680
16     603
0      601
18     568
17     543
35     389
22     364
21     344
40     336
23     313
19     267
24     233
26     205
28     184
27     173
38     139
32     137
33     136
37     124
34     109
36      88
39      88
42      84
31      82
29      74
41      72
51      72
45      70
43      59
44      35
46      30
50      22
47      22
49      20
48      13
Name: count, dtype: int64

In [211]:
df3.loc[:, 'YearsCode'] = df3['YearsCode'].astype(np.int32)

In [212]:
df3.dtypes

ResponseId                        int64
MainBranch                       object
Employment                       object
Country                          object
US_State                         object
UK_Country                       object
EdLevel                          object
Age1stCode                       object
LearnCode                        object
YearsCode                        object
YearsCodePro                     object
DevType                          object
OrgSize                          object
Currency                         object
CompTotal                       float64
CompFreq                         object
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
DatabaseHaveWorkedWith           object
DatabaseWantToWorkWith           object
PlatformHaveWorkedWith           object
PlatformWantToWorkWith           object
WebframeHaveWorkedWith           object
WebframeWantToWorkWith           object
MiscTechHaveWorkedWith           object
MiscTechWantToWorkWith           object
ToolsTechHaveWorkedWith          object
ToolsTechWantToWorkWith          object
NEWCollabToolsHaveWorkedWith     object
NEWCollabToolsWantToWorkWith     object
OpSys                            object
NEWStuck                         object
NEWSOSites                       object
SOVisitFreq                      object
SOAccount                        object
SOPartFreq                       object
SOComm                           object
NEWOtherComms                    object
Age                              object
Gender                           object
Trans                            object
Sexuality                        object
Ethnicity                        object
Accessibility                    object
MentalHealth                     object
SurveyLength                     object
SurveyEase                       object
ConvertedCompYearly             float64
dtype: object

In [213]:
df3['YearsCode'].value_counts()

YearsCode
5     3387
6     3016
10    2935
4     2793
7     2563
3     2498
8     2367
2     1850
9     1543
15    1519
12    1416
20    1405
11    1101
13     888
1      883
25     792
14     762
30     680
16     603
0      601
18     568
17     543
35     389
22     364
21     344
40     336
23     313
19     267
24     233
26     205
28     184
27     173
38     139
32     137
33     136
37     124
34     109
36      88
39      88
42      84
31      82
29      74
41      72
51      72
45      70
43      59
44      35
46      30
50      22
47      22
49      20
48      13
Name: count, dtype: int64

In [214]:
df3.loc[:, 'experience'] = pd.cut(df3['YearsCode'], bins=[0, 1, 3, 6, 11, df3['YearsCode'].max() + 1], include_lowest=True, right=False, labels=['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11+ years'])

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_4379/3950354257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.loc[:, 'experience'] = pd.cut(df3['YearsCode'], bins=[0, 1, 3, 6, 11, df3['YearsCode'].max() + 1], include_lowest=True, right=False, labels=['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11+ years'])

In [215]:
df3

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly,experience
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN,6-10 years
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN,11+ years
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,...,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0,6-10 years
13,14,I am a student who is learning to code,Employed full-time,Peru,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,School,10,...,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Too long,Neither easy nor difficult,NaN,6-10 years
15,16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,...,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN,6-10 years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83429,83430,I code primarily as a hobby,"Not employed, but looking for work",United States of America,Washington,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",6,...,"Man;Or, in your own words:",Yes,Queer,White or of European descent,I am unable to / find it difficult to walk or ...,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN,6-10 years
83430,83431,I am a developer by profession,Employed full-time,United States of America,Illinois,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",23,...,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,125000.0,11+ years
83431,83432,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Pakistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",9,...,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Easy,11676.0,6-10 years
83436,83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,...,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0,6-10 years
83437,83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,...,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0,3-5 years

In [216]:
(df3['experience'].value_counts(normalize=True) * 100).round(2)

experience
11+ years           37.34
6-10 years          31.86
3-5 years           22.25
1-2 years            7.01
Less than 1 year     1.54
Name: proportion, dtype: float64

In [222]:
(df3['YearsCode'] >= 11).sum() / len(df3)

np.float64(0.37338769648947356)

In [229]:
df3.groupby(by=['experience', 'YearsCode'])['YearsCode'].count()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_4379/3631810850.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df3.groupby(by=['experience', 'YearsCode'])['YearsCode'].count()

experience        YearsCode
Less than 1 year  0             601
                  1               0
                  2               0
                  3               0
                  4               0
                  5               0
                  6               0
                  7               0
                  8               0
                  9               0
                  10              0
                  11              0
                  12              0
                  13              0
                  14              0
                  15              0
                  16              0
                  17              0
                  18              0
                  19              0
                  20              0
                  21              0
                  22              0
                  23              0
                  24              0
                  25              0
                  26              0
                  27              0
                  28              0
                  29              0
                  30              0
                  31              0
                  32              0
                  33              0
                  34              0
                  35              0
                  36              0
                  37              0
                  38              0
                  39              0
                  40              0
                  41              0
                  42              0
                  43              0
                  44              0
                  45              0
                  46              0
                  47              0
                  48              0
                  49              0
                  50              0
                  51              0
1-2 years         0               0
                  1             883
                  2            1850
                  3               0
                  4               0
                  5               0
                  6               0
                  7               0
                  8               0
                  9               0
                  10              0
                  11              0
                  12              0
                  13              0
                  14              0
                  15              0
                  16              0
                  17              0
                  18              0
                  19              0
                  20              0
                  21              0
                  22              0
                  23              0
                  24              0
                  25              0
                  26              0
                  27              0
                  28              0
                  29              0
                  30              0
                  31              0
                  32              0
                  33              0
                  34              0
                  35              0
                  36              0
                  37              0
                  38              0
                  39              0
                  40              0
                  41              0
                  42              0
                  43              0
                  44              0
                  45              0
                  46              0
                  47              0
                  48              0
                  49              0
                  50              0
                  51              0
3-5 years         0               0
                  1               0
                  2               0
                  3            2498
                  4            2793
                  5            3387
                  6               0
                  7               0
                  8               0
                  9               0
                  10              0
                  11              0
                  12              0
                  13              0
                  14              0
                  15              0
                  16              0
                  17              0
                  18              0
                  19              0
                  20              0
                  21              0
                  22              0
                  23              0
                  24              0
                  25              0
                  26              0
                  27              0
                  28              0
                  29              0
                  30              0
                  31              0
                  32              0
                  33              0
                  34              0
                  35              0
                  36              0
                  37              0
                  38              0
                  39              0
                  40              0
                  41              0
                  42              0
                  43              0
                  44              0
                  45              0
                  46              0
                  47              0
                  48              0
                  49              0
                  50              0
                  51              0
6-10 years        0               0
                  1               0
                  2               0
                  3               0
                  4               0
                  5               0
                  6            3016
                  7            2563
                  8            2367
                  9            1543
                  10           2935
                  11              0
                  12              0
                  13              0
                  14              0
                  15              0
                  16              0
                  17              0
                  18              0
                  19              0
                  20              0
                  21              0
                  22              0
                  23              0
                  24              0
                  25              0
                  26              0
                  27              0
                  28              0
                  29              0
                  30              0
                  31              0
                  32              0
                  33              0
                  34              0
                  35              0
                  36              0
                  37              0
                  38              0
                  39              0
                  40              0
                  41              0
                  42              0
                  43              0
                  44              0
                  45              0
                  46              0
                  47              0
                  48              0
                  49              0
                  50              0
                  51              0
11+ years         0               0
                  1               0
                  2               0
                  3               0
                  4               0
                  5               0
                  6               0
                  7               0
                  8               0
                  9               0
                  10              0
                  11           1101
                  12           1416
                  13            888
                  14            762
                  15           1519
                  16            603
                  17            543
                  18            568
                  19            267
                  20           1405
                  21            344
                  22            364
                  23            313
                  24            233
                  25            792
                  26            205
                  27            173
                  28            184
                  29             74
                  30            680
                  31             82
                  32            137
                  33            136
                  34            109
                  35            389
                  36             88
                  37            124
                  38            139
                  39             88
                  40            336
                  41             72
                  42             84
                  43             59
                  44             35
                  45             70
                  46             30
                  47             22
                  48             13
                  49             20
                  50             22
                  51             72
Name: YearsCode, dtype: int64

In [228]:
pd.set_option('display.max_rows', None)

In [230]:
pd.reset_option('display.max_rows')