In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
py_df = pd.read_csv('data/2020_sharing_data_outside.csv', low_memory=False)
py_df

,is.python.main,other.lang.None,other.lang.Java,other.lang.JavaScript,other.lang.C/C++,other.lang.PHP,other.lang.C#,other.lang.Ruby,other.lang.Bash / Shell,other.lang.Objective-C,...,job.role.Technical support,job.role.Data analyst,job.role.Business analyst,job.role.Team lead,job.role.Product manager,job.role.CIO / CEO / CTO,job.role.Systems analyst,job.role.Other,age,country.live
0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,Business analyst,NaN,NaN,NaN,NaN,NaN,30–39,NaN
1,Yes,NaN,Java,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,India
2,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,Technical support,Data analyst,NaN,Team lead,NaN,NaN,NaN,NaN,30–39,United States
3,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Yes,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54457,Yes,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,Objective-C,...,NaN,NaN,NaN,NaN,NaN,NaN,Systems analyst,NaN,21–29,Russian Federation
54458,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54459,Yes,NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,NaN,NaN,NaN,NaN,CIO / CEO / CTO,NaN,NaN,21–29,Russian Federation
54460,Yes,NaN,NaN,JavaScript,C/C++,PHP,NaN,NaN,Bash / Shell,NaN,...,NaN,Data analyst,NaN,NaN,NaN,NaN,NaN,NaN,30–39,Spain
54461,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Team lead,NaN,NaN,NaN,NaN,21–29,Algeria

In [8]:
sorted(list(py_df.columns))

['age',
 'are.you.datascientist',
 'bigdata.Apache Beam',
 'bigdata.Apache Flink',
 'bigdata.Apache Hadoop/MapReduce',
 'bigdata.Apache Hive',
 'bigdata.Apache Kafka',
 'bigdata.Apache Samza',
 'bigdata.Apache Spark',
 'bigdata.Apache Tez',
 'bigdata.ClickHouse',
 'bigdata.Dask',
 'bigdata.None',
 'bigdata.Other',
 'ci.AppVeyor',
 'ci.Bamboo',
 'ci.CircleCI',
 'ci.CruiseControl',
 'ci.Gitlab CI',
 'ci.Jenkins / Hudson',
 'ci.None',
 'ci.Other',
 'ci.TeamCity',
 'ci.Travis CI',
 'cloud.platform.AWS',
 'cloud.platform.DigitalOcean',
 'cloud.platform.Google Cloud Platform',
 'cloud.platform.Heroku',
 'cloud.platform.Linode',
 'cloud.platform.Microsoft Azure',
 'cloud.platform.None',
 'cloud.platform.OpenShift',
 'cloud.platform.OpenStack',
 'cloud.platform.Other',
 'cloud.platform.PythonAnywhere',
 'cloud.platform.Rackspace',
 'company.size',
 'configuration.management.Ansible',
 'configuration.management.Chef',
 'configuration.management.Custom solution',
 'configuration.management.None',
 'configuration.management.Other',
 'configuration.management.Puppet',
 'configuration.management.Salt',
 'country.live',
 'data.frameworks.Gensim',
 'data.frameworks.Keras',
 'data.frameworks.MXNet',
 'data.frameworks.Matplotlib',
 'data.frameworks.NLTK',
 'data.frameworks.None',
 'data.frameworks.NumPy',
 'data.frameworks.Other',
 'data.frameworks.Pandas',
 'data.frameworks.PyTorch',
 'data.frameworks.SciKit-Learn',
 'data.frameworks.SciPy',
 'data.frameworks.Seaborn',
 'data.frameworks.TensorFlow',
 'data.frameworks.Theano',
 'database.Amazon Redshift',
 'database.Cassandra',
 'database.Couchbase',
 'database.DB2',
 'database.HBase',
 'database.MS SQL Server',
 'database.MongoDB',
 'database.MySQL',
 'database.Neo4j',
 'database.None',
 'database.Oracle Database',
 'database.Other',
 'database.PostgreSQL',
 'database.Redis',
 'database.SQLite',
 'database.h2',
 'develop.for.cloud.Directly in the production environment',
 'develop.for.cloud.In Docker containers',
 'develop.for.cloud.In remote development environments',
 'develop.for.cloud.In virtual machines',
 'develop.for.cloud.Locally with virtualenv (or similar)',
 'develop.for.cloud.None of the following',
 'develop.for.cloud.Other',
 'develop.for.cloud.With local system interpreter',
 'devenv.os.BSD',
 'devenv.os.Linux',
 'devenv.os.Other',
 'devenv.os.Windows',
 'devenv.os.macOS',
 'employment.status',
 'first.learn.about.main.ide',
 'how.involved.Computer graphics',
 'how.involved.Data analysis',
 'how.involved.Desktop development',
 'how.involved.DevOps / System administration / Writing automation scripts',
 'how.involved.Educational purposes',
 'how.involved.Embedded development',
 'how.involved.Game development',
 'how.involved.Machine learning',
 'how.involved.Mobile development',
 'how.involved.Multimedia applications development',
 'how.involved.Network programming',
 'how.involved.Programming of web parsers / scrapers / crawlers',
 'how.involved.Software prototyping',
 'how.involved.Software testing / Writing automated tests',
 'how.involved.Web development',
 'how.often.use.main.ide',
 'ide.editor.Atom',
 'ide.editor.Eclipse + Pydev',
 'ide.editor.Emacs',
 'ide.editor.IDLE',
 'ide.editor.IntelliJ IDEA',
 'ide.editor.Jupyter Notebook',
 'ide.editor.JupyterLab',
 'ide.editor.None',
 'ide.editor.NotePad++',
 'ide.editor.Other',
 'ide.editor.PyCharm Community Edition',
 'ide.editor.PyCharm Professional Edition',
 'ide.editor.Python Tools for Visual Studio (PTVS)',
 'ide.editor.Spyder',
 'ide.editor.Sublime Text',
 'ide.editor.VS Code',
 'ide.editor.Vim',
 'ide.main',
 'is.python.main',
 'isolate.environments.Conda',
 'isolate.environments.Docker',
 'isolate.environments.None',
 'isolate.environments.Other',
 'isolate.environments.Pipenv',
 'isolate.environments.Poetry',
 'isolate.environments.Vagrant  / virtual machines',
 'isolate.environments.Virtualenv',
 'job.role.Architect',
 'job.role.Business analyst',
 'job.role.CIO / CEO / CTO',
 'job.role.DBA',
 'job.role.Data analyst',
 'job.role.Developer / Programmer',
 'job.role.Other',
 'job.role.Product manager',
 'job.role.QA engineer',
 'job.role.Systems analyst',
 'job.role.Team lead',
 'job.role.Technical support',
 'job.role.Technical writer',
 'job.team',
 'main.purposes',
 'missing.features.main.ide',
 'nps.main.ide',
 'orm.Dejavu',
 'orm.Django ORM',
 'orm.No database development',
 'orm.Other',
 'orm.Peewee',
 'orm.PonyORM',
 'orm.Raw SQL',
 'orm.SQLAlchemy',
 'orm.SQLObject',
 'orm.Tortoise ORM',
 'other.frameworks.Asyncio',
 'other.frameworks.Kivy',
 'other.frameworks.None',
 'other.frameworks.Other',
 'other.frameworks.Pillow',
 'other.frameworks.PyGTK',
 'other.frameworks.PyQT',
 'other.frameworks.Pygame',
 'other.frameworks.Requests',
 'other.frameworks.Scrapy',
 'other.frameworks.Six',
 'other.frameworks.Tkinter',
 'other.frameworks.Twisted',
 'other.frameworks.aiohttp',
 'other.frameworks.wxPython',
 'other.lang.Bash / Shell',
 'other.lang.C#',
 'other.lang.C/C++',
 'other.lang.Clojure',
 'other.lang.CoffeeScript',
 'other.lang.Go',
 'other.lang.Groovy',
 'other.lang.HTML/CSS',
 'other.lang.Java',
 'other.lang.JavaScript',
 'other.lang.Kotlin',
 'other.lang.None',
 'other.lang.Objective-C',
 'other.lang.Other',
 'other.lang.PHP',
 'other.lang.Perl',
 'other.lang.R',
 'other.lang.Ruby',
 'other.lang.Rust',
 'other.lang.SQL',
 'other.lang.Scala',
 'other.lang.Swift',
 'other.lang.TypeScript',
 'other.lang.Visual Basic',
 'other.purposes.Computer graphics',
 'other.purposes.Data analysis',
 'other.purposes.Desktop development',
 'other.purposes.DevOps / System administration / Writing automation scripts',
 'other.purposes.Educational purposes',
 'other.purposes.Embedded development',
 'other.purposes.Game development',
 'other.purposes.Machine learning',
 'other.purposes.Mobile development',
 'other.purposes.Multimedia applications development',
 'other.purposes.Network programming',
 'other.purposes.Other',
 'other.purposes.Programming of web parsers / scrapers / crawlers',
 'other.purposes.Software prototyping',
 'other.purposes.Software testing / Writing automated tests',
 'other.purposes.Web development',
 'python.version.most',
 'python.version.upgrade.ActivePython',
 'python.version.upgrade.Anaconda',
 'python.version.upgrade.Automatic upgrade via cloud provider',
 'python.version.upgrade.Build from source',
 'python.version.upgrade.I don’t update',
 'python.version.upgrade.I use Docker containers',
 'python.version.upgrade.Intel Distribution for Python',
 'python.version.upgrade.OS-provided Python (via apt-get, yum, homebrew, etc_)',
 'python.version.upgrade.Other',
 'python.version.upgrade.Python_org',
 'python.version.upgrade.Somebody else manages Python updates for me',
 'python.version.upgrade.pyenv',
 'python.version.upgrade.pythonz',
 'python.years',
 'python2.version.most',
 'python3.version.most',
 'run.in.cloud.In virtual machines',
 'run.in.cloud.None of the following',
 'run.in.cloud.On a Platform-as-a-Service (such as Heroku or Google App Engine)',
 'run.in.cloud.Other',
 'run.in.cloud.Serverless (such as AWS Lambda or Cloud Functions)',
 'run.in.cloud.Within containers',
 'several.projects',
 'team.size',
 'unittesting.Hypothesis',
 'unittesting.None',
 'unittesting.Other',
 'unittesting.Tox',
 'unittesting.doctest',
 'unittesting.mock',
 'unittesting.nose',
 'unittesting.pytest',
 'unittesting.unittest',
 'use.python.most',
 'web.frameworks.Bottle',
 'web.frameworks.CherryPy\xa0',
 'web.frameworks.Django',
 'web.frameworks.Falcon',
 'web.frameworks.FastAPI',
 'web.frameworks.Flask\xa0',
 'web.frameworks.Hug',
 'web.frameworks.None',
 'web.frameworks.Other',
 'web.frameworks.Pyramid\xa0',
 'web.frameworks.Tornado',
 'web.frameworks.web2py',
 'years.of.coding']

In [6]:
name_exclusions = [
    'age',
    'are.you.datascientist',
    'is.python.main',
    'company.size',
    'country.live',
    'employment.status',
    'first.learn.about.main.ide',
    'how.often.use.main.ide',
    'main.purposes',
    'missing.features.main.ide',
    'nps.main.ide',
    'python.version.most',
    'python.years',
    'python2.version.most',
    'python3.version.most',
    'several.projects',
    'team.size',
    'use.python.most',
    'years.of.coding'
]

In [9]:
def get_col_name_tuple(col_name):
    if col_name in name_exclusions:
        return ('general', col_name)
    else:
        first, second = col_name.rsplit('.', 1)
        return (first, second)

In [12]:
py_df.columns = pd.MultiIndex.from_tuples([get_col_name_tuple(x) for x in py_df.columns])

In [13]:
py_df

             general other.lang                                          \
      is.python.main       None  Java  JavaScript  C/C++  PHP   C# Ruby
0                Yes        NaN   NaN         NaN    NaN  NaN  NaN  NaN
1                Yes        NaN  Java  JavaScript    NaN  NaN   C#  NaN
2                Yes        NaN   NaN         NaN  C/C++  NaN  NaN  NaN
3                Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN
4                Yes        NaN  Java  JavaScript  C/C++  NaN  NaN  NaN
...              ...        ...   ...         ...    ...  ...  ...  ...
54457            Yes        NaN   NaN         NaN  C/C++  NaN  NaN  NaN
54458            Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN
54459            Yes        NaN   NaN  JavaScript    NaN  PHP  NaN  NaN
54460            Yes        NaN   NaN  JavaScript  C/C++  PHP  NaN  NaN
54461            Yes        NaN   NaN  JavaScript    NaN  NaN  NaN  NaN

                                  ...           job.role                \
       Bash / Shell  Objective-C  ...  Technical support  Data analyst
0      Bash / Shell          NaN  ...                NaN           NaN
1               NaN          NaN  ...                NaN           NaN
2      Bash / Shell          NaN  ...  Technical support  Data analyst
3      Bash / Shell          NaN  ...                NaN           NaN
4      Bash / Shell          NaN  ...                NaN           NaN
...             ...          ...  ...                ...           ...
54457  Bash / Shell  Objective-C  ...                NaN           NaN
54458  Bash / Shell          NaN  ...                NaN           NaN
54459  Bash / Shell          NaN  ...                NaN           NaN
54460  Bash / Shell          NaN  ...                NaN  Data analyst
54461           NaN          NaN  ...                NaN           NaN

                                                                     \
       Business analyst  Team lead Product manager  CIO / CEO / CTO
0      Business analyst        NaN             NaN              NaN
1                   NaN        NaN             NaN              NaN
2                   NaN  Team lead             NaN              NaN
3                   NaN        NaN             NaN              NaN
4                   NaN        NaN             NaN              NaN
...                 ...        ...             ...              ...
54457               NaN        NaN             NaN              NaN
54458               NaN        NaN             NaN              NaN
54459               NaN        NaN             NaN  CIO / CEO / CTO
54460               NaN        NaN             NaN              NaN
54461               NaN  Team lead             NaN              NaN

                             general
       Systems analyst Other     age        country.live
0                  NaN   NaN   30–39                 NaN
1                  NaN   NaN   21–29               India
2                  NaN   NaN   30–39       United States
3                  NaN   NaN     NaN                 NaN
4                  NaN   NaN   21–29               Italy
...                ...   ...     ...                 ...
54457  Systems analyst   NaN   21–29  Russian Federation
54458              NaN   NaN     NaN                 NaN
54459              NaN   NaN   21–29  Russian Federation
54460              NaN   NaN   30–39               Spain
54461              NaN   NaN   21–29             Algeria

[54462 rows x 264 columns]

In [15]:
py_df = py_df.sort_index(axis=1)
py_df.head()

       bigdata                                                                \
   Apache Beam Apache Flink Apache Hadoop/MapReduce Apache Hive Apache Kafka
0  Apache Beam          NaN                     NaN         NaN          NaN
1          NaN          NaN                     NaN         NaN          NaN
2          NaN          NaN                     NaN         NaN          NaN
3          NaN          NaN                     NaN         NaN          NaN
4          NaN          NaN                     NaN         NaN          NaN

                                                        ... web.frameworks  \
  Apache Samza Apache Spark Apache Tez ClickHouse Dask  ...         Django
0          NaN          NaN        NaN        NaN  NaN  ...            NaN
1          NaN          NaN        NaN        NaN  NaN  ...            NaN
2          NaN          NaN        NaN        NaN  NaN  ...            NaN
3          NaN          NaN        NaN        NaN  NaN  ...         Django
4          NaN          NaN        NaN        NaN  NaN  ...            NaN


  Falcon FastAPI  Flask   Hug None Other Pyramid   Tornado web2py
0    NaN     NaN     NaN  NaN  NaN   NaN      NaN      NaN    NaN
1    NaN     NaN     NaN  NaN  NaN   NaN      NaN  Tornado    NaN
2    NaN     NaN  Flask   NaN  NaN   NaN      NaN      NaN    NaN
3    NaN     NaN     NaN  NaN  NaN   NaN      NaN      NaN    NaN
4    NaN     NaN  Flask   NaN  NaN   NaN      NaN      NaN    NaN

[5 rows x 264 columns]

In [21]:
py_df.columns.get_level_values(0).value_counts()

other.lang                  24
general                     19
ide.editor                  17
other.purposes              16
database                    16
data.frameworks             15
other.frameworks            15
how.involved                15
job.role                    13
python.version.upgrade      13
bigdata                     12
cloud.platform              12
web.frameworks              12
ci                          10
orm                         10
unittesting                  9
isolate.environments         8
develop.for.cloud            8
configuration.management     7
run.in.cloud                 6
devenv.os                    5
job                          1
ide                          1
Name: count, dtype: int64

In [26]:
py_df.loc[:,('ide',)].value_counts(dropna=True).head(10)

main
VS Code                         8010
PyCharm Professional Edition    5144
PyCharm Community Edition       3815
Vim                             2176
Sublime Text                    1201
Jupyter Notebook                1167
Atom                             784
Other                            711
Emacs                            636
Spyder                           580
Name: count, dtype: int64

In [30]:
py_df.loc[:, ('other.lang',)].count().sort_values(ascending=False).head(10)

JavaScript      16662
HTML/CSS        15469
Bash / Shell    13793
SQL             13391
C/C++           11623
Java             8109
C#               4460
PHP              4060
TypeScript       3717
Other            3592
dtype: int64

In [34]:
py_df.loc[:, ('general','country.live')].value_counts().head(10)

(general, country.live)
United States         3975
India                 2800
Germany               1807
China                 1155
United Kingdom        1110
France                1078
Russian Federation     935
Other country          880
Brazil                 812
Canada                 644
Name: count, dtype: int64

In [42]:
(py_df.loc[:, ('general', 'python.years')].value_counts(normalize=True) * 100).round(2)

(general, python.years)
3–5 years           28.43
Less than 1 year    23.95
1–2 years           22.48
6–10 years          15.49
11+ years            9.64
Name: proportion, dtype: float64

In [53]:
py_df[py_df.loc[:, ('general', 'python.years')] == '11+ years'].loc[:, ('general', 'country.live')].value_counts().head(1)

(general, country.live)
United States    691
Name: count, dtype: int64

In [60]:
country_df = py_df.loc[:, [('general', 'country.live'), ('general', 'python.years')]].dropna()
country_df

                  general
             country.live      python.years
1                   India         3–5 years
2           United States         3–5 years
4                   Italy         1–2 years
5                  France  Less than 1 year
9                 Croatia         3–5 years
...                   ...               ...
54456              Turkey         1–2 years
54457  Russian Federation        6–10 years
54459  Russian Federation         3–5 years
54460               Spain        6–10 years
54461             Algeria         1–2 years

[23417 rows x 2 columns]

In [66]:
countries_total = country_df.loc[:, ('general', 'country.live')].value_counts()

In [67]:
countries_experienced = country_df[country_df.loc[:, ('general', 'python.years')] == '11+ years'].loc[:, ('general', 'country.live')].value_counts()

In [75]:
(countries_experienced / countries_total * 100).round(2).sort_values(ascending=False).head(10)

(general, country.live)
Norway            27.04
Slovenia          23.91
Australia         23.27
Belgium           23.21
Ireland           22.77
New Zealand       20.00
Sweden            19.77
Finland           19.29
United Kingdom    19.20
Austria           19.02
Name: count, dtype: float64

In [78]:
country_experience = py_df['general'][['country.live', 'python.years']]

In [79]:
country_experience.head(10)

    country.live      python.years
0            NaN         3–5 years
1          India         3–5 years
2  United States         3–5 years
3            NaN         11+ years
4          Italy         1–2 years
5         France  Less than 1 year
6            NaN               NaN
7            NaN  Less than 1 year
8            NaN         3–5 years
9        Croatia         3–5 years

In [80]:
all_per_country = country_experience['country.live'].value_counts()
all_per_country

country.live
United States         3975
India                 2800
Germany               1807
China                 1155
United Kingdom        1110
                      ...
Kazakhstan              36
Dominican Republic      34
Uruguay                 33
Armenia                 31
Uzbekistan              31
Name: count, Length: 76, dtype: int64

In [82]:
expert_per_country = country_experience[country_experience['python.years'] == '11+ years']['country.live'].value_counts()
expert_per_country

country.live
United States     691
Germany           308
United Kingdom    207
France            166
Australia          94
                 ...
Viet Nam            1
Tunisia             1
Pakistan            1
Bangladesh          1
Egypt               1
Name: count, Length: 70, dtype: int64

In [84]:
(expert_per_country / all_per_country).sort_values(ascending=False).dropna().head(10)

country.live
Norway            0.265432
Ireland           0.225490
Australia         0.225420
Belgium           0.225108
Slovenia          0.224490
New Zealand       0.197917
Sweden            0.194030
Finland           0.190141
United Kingdom    0.186486
Austria           0.186170
Name: count, dtype: float64

In [92]:
so_df = pd.read_csv('data/so_2021_survey_results.csv', low_memory=False)
so_df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [96]:
so_df.groupby('Employment')['ConvertedCompYearly'].mean().sort_values(ascending=False).round(2)

Employment
I prefer not to say                                     1455643.25
Employed full-time                                       121369.67
Independent contractor, freelancer, or self-employed     107433.97
Retired                                                   69533.25
Employed part-time                                        41136.12
Not employed, and not looking for work                         NaN
Not employed, but looking for work                             NaN
Student, full-time                                             NaN
Student, part-time                                             NaN
Name: ConvertedCompYearly, dtype: float64

In [99]:
so_df.pivot_table(index='Country', columns='EdLevel', values='ConvertedCompYearly', aggfunc='mean', margins=True, margins_name='Total', fill_value=0).round(2)

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else,Total
Country,,,,,,,,,,
Afghanistan,0.00,30288.00,10176704.00,0.00,0.00,0.00,100.00,0.00,0.00,2794748.00
Albania,0.00,19152.86,80127.62,0.00,0.00,5298.00,19890.00,22884.00,128522.00,44998.14
Algeria,0.00,21770.67,15052.57,0.00,0.00,12912.00,0.00,6288.00,0.00,14461.14
Andorra,0.00,94045.50,22056.00,146981.00,0.00,0.00,0.00,0.00,0.00,89282.00
Angola,0.00,31500.00,0.00,0.00,0.00,0.00,18678.00,6904.00,0.00,21556.80
...,...,...,...,...,...,...,...,...,...,...
Viet Nam,7827.00,18463.11,50599.80,2592.00,10479.00,30000.00,0.00,18866.19,0.00,19952.89
Yemen,0.00,5628.67,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5628.67
Zambia,0.00,40173.00,4908.00,0.00,0.00,0.00,4482.00,12105.33,8184.00,19914.91
Zimbabwe,36000.00,8399.27,0.00,0.00,0.00,0.00,0.00,20000.00,0.00,11414.77
Total,107474.26,125598.01,117672.49,128650.71,282842.75,87416.33,78298.88,106301.96,75847.99,118403.65

In [103]:
oecd = pd.read_csv('data/oecd_locations.csv', low_memory=False, header=None)
oecd.columns = ['abbr', 'name']
oecd

   abbr            name
0   AUS       Australia
1   AUT         Austria
2   BEL         Belgium
3   CAN          Canada
4   DNK         Denmark
5   FIN         Finland
6   FRA          France
7   DEU         Germany
8   HUN         Hungary
9   ITA           Italy
10  JPN           Japan
11  KOR           Korea
12  GBR  United Kingdom
13  USA   United States
14  BRA          Brazil
15  ISR          Israel

In [105]:
short_df = pd.merge(left=so_df, right=oecd, how='inner', left_on='Country', right_on='name')
short_df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly,abbr,name
0,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN,AUT,Austria
1,13,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Other (please specify):,15,...,No,Straight / Heterosexual,White or of European descent,None of the above,Prefer not to say,Appropriate in length,Easy,77290.0,DEU,Germany
2,18,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,9,...,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,46135.0,CAN,Canada
3,20,"I used to be a developer by profession, but no...",Employed full-time,Brazil,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",12,...,No,Straight / Heterosexual,Multiracial,None of the above,None of the above,Appropriate in length,Easy,NaN,BRA,Brazil
4,21,I am a developer by profession,"Student, full-time",Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Colleague,NaN,...,No,NaN,White or of European descent,NaN,NaN,Too long,Easy,NaN,DEU,Germany

In [107]:
pivot = short_df.pivot_table(index='Country', columns='EdLevel', values='ConvertedCompYearly', aggfunc='mean', margins=True, margins_name='Total', fill_value=0).round(2)
pivot

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else,Total
Country,,,,,,,,,,
Australia,117049.64,180794.16,106794.32,150234.96,153327.50,108725.00,158931.28,127063.53,231987.17,160468.93
Austria,43623.38,66096.13,77645.66,74783.17,86877.00,38915.33,47438.83,53906.05,45772.53,65634.76
Belgium,35664.00,68474.70,88580.41,80832.44,11342349.25,71000.20,43224.13,88006.29,27035.50,180778.91
Brazil,25347.42,47681.23,42056.01,43123.21,7880.00,25449.67,15072.89,39978.02,20288.71,42214.02
Canada,87930.35,140668.24,144733.35,102989.35,73787.83,82953.40,180584.81,155090.08,60795.17,135732.56
Denmark,80217.33,80430.94,115751.85,102785.19,91056.57,114144.89,90411.74,85131.35,95479.86,98191.94
Finland,282353.67,69381.34,74360.98,61508.25,77832.00,83016.00,59424.32,89255.56,35024.00,75220.18
France,54394.89,65062.38,94585.73,140402.86,34181.00,78342.27,53981.81,55119.45,42884.04,90241.56
Germany,98530.52,102751.23,110611.98,108718.46,74943.67,97330.14,82865.84,95737.77,109333.99,103032.23
Hungary,51041.00,48756.45,46771.71,52833.60,48100.00,9852.00,33440.80,37102.89,28911.00,44116.39
Israel,146420.90,124973.40,128492.71,131812.62,100514.57,132336.00,97938.78,130049.04,96142.50,123342.92
Italy,36427.94,73697.22,79132.19,93490.78,525992.17,117121.37,75114.40,81531.72,32690.22,80750.32
Japan,143196.83,85821.47,130143.19,157239.40,44965.00,0.00,57916.40,91163.04,194514.00,105349.91
Total,78626.84,102083.75,99225.54,111104.98,838288.37,81280.18,80949.36,90280.10,81725.51,100837.03

In [109]:
pivot.sort_values('Associate degree (A.A., A.S., etc.)', ascending=False).head(1)

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else,Total
Country,,,,,,,,,,
Finland,282353.67,69381.34,74360.98,61508.25,77832.0,83016.0,59424.32,89255.56,35024.0,75220.18

In [110]:
pivot.sort_values('Other doctoral degree (Ph.D., Ed.D., etc.)', ascending=False).head(1)

EdLevel,"Associate degree (A.A., A.S., etc.)","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other doctoral degree (Ph.D., Ed.D., etc.)",Primary/elementary school,"Professional degree (JD, MD, etc.)","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",Some college/university study without earning a degree,Something else,Total
Country,,,,,,,,,,
Japan,143196.83,85821.47,130143.19,157239.4,44965.0,0.0,57916.4,91163.04,194514.0,105349.91

In [111]:
sorted(list(so_df.columns))

['Accessibility',
 'Age',
 'Age1stCode',
 'CompFreq',
 'CompTotal',
 'ConvertedCompYearly',
 'Country',
 'Currency',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DevType',
 'EdLevel',
 'Employment',
 'Ethnicity',
 'Gender',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LearnCode',
 'MainBranch',
 'MentalHealth',
 'MiscTechHaveWorkedWith',
 'MiscTechWantToWorkWith',
 'NEWCollabToolsHaveWorkedWith',
 'NEWCollabToolsWantToWorkWith',
 'NEWOtherComms',
 'NEWSOSites',
 'NEWStuck',
 'OpSys',
 'OrgSize',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'ResponseId',
 'SOAccount',
 'SOComm',
 'SOPartFreq',
 'SOVisitFreq',
 'Sexuality',
 'SurveyEase',
 'SurveyLength',
 'ToolsTechHaveWorkedWith',
 'ToolsTechWantToWorkWith',
 'Trans',
 'UK_Country',
 'US_State',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'YearsCode',
 'YearsCodePro']

In [114]:
so_df_shortened = so_df.dropna(subset='LanguageHaveWorkedWith')
so_df_shortened.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [115]:
len(so_df)

83439

In [116]:
len(so_df_shortened)

82357

In [117]:
len(so_df) - len(so_df_shortened)

1082

In [121]:
so_df_shortened = so_df_shortened[so_df_shortened['LanguageHaveWorkedWith'].str.contains('Python')]
so_df_shortened.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
5,6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0

In [122]:
len(so_df_shortened)

39792

In [126]:
so_df_shortened = so_df_shortened[so_df_shortened['YearsCode'].notnull()]
so_df_shortened.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
9,10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0
13,14,I am a student who is learning to code,Employed full-time,Peru,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,School,10,...,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,Too long,Neither easy nor difficult,NaN
15,16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN

In [127]:
len(so_df_shortened)

38997

In [128]:
so_df_shortened['YearsCode'].value_counts(dropna=False)

YearsCode
5                     3387
6                     3016
10                    2935
4                     2793
7                     2563
3                     2498
8                     2367
2                     1850
9                     1543
15                    1519
12                    1416
20                    1405
11                    1101
13                     888
1                      883
25                     792
14                     762
30                     680
16                     603
Less than 1 year       601
18                     568
17                     543
35                     389
22                     364
21                     344
40                     336
23                     313
19                     267
24                     233
26                     205
28                     184
27                     173
38                     139
32                     137
33                     136
37                     124
34                     109
36                      88
39                      88
42                      84
31                      82
29                      74
41                      72
More than 50 years      72
45                      70
43                      59
44                      35
46                      30
50                      22
47                      22
49                      20
48                      13
Name: count, dtype: int64

In [129]:
so_df_shortened['YearsCode'].dtype

dtype('O')

In [132]:
so_df_shortened.dtypes

ResponseId                        int64
MainBranch                       object
Employment                       object
Country                          object
US_State                         object
UK_Country                       object
EdLevel                          object
Age1stCode                       object
LearnCode                        object
YearsCode                        object
YearsCodePro                     object
DevType                          object
OrgSize                          object
Currency                         object
CompTotal                       float64
CompFreq                         object
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
DatabaseHaveWorkedWith           object
DatabaseWantToWorkWith           object
PlatformHaveWorkedWith           object
PlatformWantToWorkWith           object
WebframeHaveWorkedWith           object
WebframeWantToWorkWith           object
MiscTechHaveWorkedWith           object
MiscTechWantToWorkWith           object
ToolsTechHaveWorkedWith          object
ToolsTechWantToWorkWith          object
NEWCollabToolsHaveWorkedWith     object
NEWCollabToolsWantToWorkWith     object
OpSys                            object
NEWStuck                         object
NEWSOSites                       object
SOVisitFreq                      object
SOAccount                        object
SOPartFreq                       object
SOComm                           object
NEWOtherComms                    object
Age                              object
Gender                           object
Trans                            object
Sexuality                        object
Ethnicity                        object
Accessibility                    object
MentalHealth                     object
SurveyLength                     object
SurveyEase                       object
ConvertedCompYearly             float64
dtype: object

In [136]:
so_df_shortened.loc[so_df_shortened['YearsCode'] == 'Less than 1 year', 'YearsCode'] = '0'

In [137]:
so_df_shortened.loc[so_df_shortened['YearsCode'] == 'More than 50 years', 'YearsCode'] = '51'

In [138]:
so_df_shortened['YearsCode'].value_counts(dropna=False)

YearsCode
5     3387
6     3016
10    2935
4     2793
7     2563
3     2498
8     2367
2     1850
9     1543
15    1519
12    1416
20    1405
11    1101
13     888
1      883
25     792
14     762
30     680
16     603
0      601
18     568
17     543
35     389
22     364
21     344
40     336
23     313
19     267
24     233
26     205
28     184
27     173
38     139
32     137
33     136
37     124
34     109
36      88
39      88
42      84
31      82
29      74
41      72
51      72
45      70
43      59
44      35
46      30
50      22
47      22
49      20
48      13
Name: count, dtype: int64

In [139]:
so_df_shortened['YearsCode'] = so_df_shortened['YearsCode'].astype(np.int8)

In [143]:
so_df_shortened['YearsCode'].value_counts()

YearsCode
5     3387
6     3016
10    2935
4     2793
7     2563
3     2498
8     2367
2     1850
9     1543
15    1519
12    1416
20    1405
11    1101
13     888
1      883
25     792
14     762
30     680
16     603
0      601
18     568
17     543
35     389
22     364
21     344
40     336
23     313
19     267
24     233
26     205
28     184
27     173
38     139
32     137
33     136
37     124
34     109
36      88
39      88
42      84
31      82
29      74
41      72
51      72
45      70
43      59
44      35
46      30
50      22
47      22
49      20
48      13
Name: count, dtype: int64

In [153]:
so_df_shortened['experience'] = pd.cut(so_df_shortened['YearsCode'], bins=[-1, 0, 2, 5, 10, 51], include_lowest=True, labels=['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11+ years'])

In [154]:
s = so_df_shortened.groupby(by=['experience', 'YearsCode'])['YearsCode'].value_counts()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3968/1010417287.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  s = so_df_shortened.groupby(by=['experience', 'YearsCode'])['YearsCode'].value_counts()

In [155]:
s[s > 0]

experience        YearsCode
Less than 1 year  0             601
1-2 years         1             883
                  2            1850
3-5 years         3            2498
                  4            2793
                  5            3387
6-10 years        6            3016
                  7            2563
                  8            2367
                  9            1543
                  10           2935
11+ years         11           1101
                  12           1416
                  13            888
                  14            762
                  15           1519
                  16            603
                  17            543
                  18            568
                  19            267
                  20           1405
                  21            344
                  22            364
                  23            313
                  24            233
                  25            792
                  26            205
                  27            173
                  28            184
                  29             74
                  30            680
                  31             82
                  32            137
                  33            136
                  34            109
                  35            389
                  36             88
                  37            124
                  38            139
                  39             88
                  40            336
                  41             72
                  42             84
                  43             59
                  44             35
                  45             70
                  46             30
                  47             22
                  48             13
                  49             20
                  50             22
                  51             72
Name: count, dtype: int64

In [159]:
(so_df_shortened['experience'].value_counts(normalize=True) * 100).round(2)

experience
11+ years           37.34
6-10 years          31.86
3-5 years           22.25
1-2 years            7.01
Less than 1 year     1.54
Name: proportion, dtype: float64