In [2]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.read_csv('taxi-distance.csv', header=None).squeeze()
s1

0       1.63
1       0.46
2       0.87
3       2.13
4       1.40
        ...
9994    2.70
9995    4.50
9996    5.59
9997    1.54
9998    5.80
Name: 0, Length: 9999, dtype: float64

In [4]:
s2 = pd.read_csv('taxi-passenger-count.csv', header=None).squeeze()
s2

0       1
1       1
2       1
3       1
4       1
       ..
9994    1
9995    1
9996    1
9997    6
9998    1
Name: 0, Length: 9999, dtype: int64

In [5]:
df = pd.concat([s1, s2], axis=1)
df

         0  0
0     1.63  1
1     0.46  1
2     0.87  1
3     2.13  1
4     1.40  1
...    ... ..
9994  2.70  1
9995  4.50  1
9996  5.59  1
9997  1.54  6
9998  5.80  1

[9999 rows x 2 columns]

In [6]:
df.columns = ['distance', 'passengers_cnt']

In [7]:
df

      distance  passengers_cnt
0         1.63               1
1         0.46               1
2         0.87               1
3         2.13               1
4         1.40               1
...        ...             ...
9994      2.70               1
9995      4.50               1
9996      5.59               1
9997      1.54               6
9998      5.80               1

[9999 rows x 2 columns]

In [10]:
iqr = df['distance'].quantile(0.75) - df['distance'].quantile(0.25)

In [11]:
iqr

np.float64(2.3)

In [13]:
outliers = df.loc[(df['distance'] < df['distance'].quantile(0.25) - 1.5 * iqr) | (df['distance'] > df['distance'].quantile(0.75) + 1.5 * iqr)]

In [14]:
len(outliers)

1219

In [15]:
outliers['passengers_cnt'].mean()

np.float64(1.7301066447908122)

In [16]:
df['passengers_cnt'].mean()

np.float64(1.6594659465946595)

In [17]:
df.loc[(df['distance'] < df['distance'].quantile(0.25) - 1.5 * iqr)]

Empty DataFrame
Columns: [distance, passengers_cnt]
Index: []

In [18]:
df.loc[(df['distance'] > df['distance'].quantile(0.75) + 1.5 * iqr)]

      distance  passengers_cnt
7        11.90               4
60        9.30               1
73       12.65               1
82       10.24               3
88       23.76               2
...        ...             ...
9975      7.60               1
9976     12.60               1
9979     11.30               1
9980      9.13               1
9982      9.30               1

[1219 rows x 2 columns]

In [19]:
# 12.1

In [21]:
df.loc[(df['distance'] > df['distance'].quantile(0.9)) | (df['distance'] < df['distance'].quantile(0.1))].count()

distance          1984
passengers_cnt    1984
dtype: int64

In [22]:
# 12.2

In [23]:
import scipy

In [24]:
scipy.stats.trimboth(df['distance'], 0.1)

array([0.63, 0.63, 0.63, ..., 8.2 , 8.2 , 8.2 ], shape=(8001,))

In [25]:
len(df)

9999

In [26]:
# 12.3

In [28]:
s = pd.Series(data=scipy.stats.zscore(df['distance']), name='zscore')
s

0      -0.378596
1      -0.668393
2      -0.566840
3      -0.254751
4      -0.435565
          ...
9994   -0.113568
9995    0.332273
9996    0.602254
9997   -0.400888
9998    0.654269
Name: zscore, Length: 9999, dtype: float64

In [31]:
s.loc[s.abs() > 3]

88      5.102771
238     3.755340
379     3.274823
509     3.383806
641     4.102106
          ...
9897    3.207947
9899    3.547281
9906    3.601773
9955    3.054379
9964    3.812309
Name: zscore, Length: 306, dtype: float64