In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.read_csv('data/nyc-temps.txt').squeeze()
s

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
723    2
724    2
725    2
726    2
727    2
Name: -1, Length: 728, dtype: int64

In [3]:
idx = list(range(0, 22, 3))
idx

[0, 3, 6, 9, 12, 15, 18, 21]

In [4]:
idx *= 91

In [5]:
s.name = 'temp'

In [6]:
s1 = pd.Series(data=idx, name='hour')
s1

0       0
1       3
2       6
3       9
4      12
       ..
723     9
724    12
725    15
726    18
727    21
Name: hour, Length: 728, dtype: int64

In [7]:
df = pd.concat([s, s1], axis=1)
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [8]:
df.loc[df['temp'] < 0, 'temp'] = 0

In [9]:
df

     temp  hour
0       0     0
1       0     3
2       0     6
3       0     9
4       0    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [10]:
df['temp'].value_counts()

temp
0     423
1      88
2      57
5      48
3      48
8      16
4      16
6      16
12      8
9       8
Name: count, dtype: int64

In [11]:
# 14.1

In [12]:
df = pd.concat([s, s1], axis=1)
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [13]:
df.loc[df['temp'] % 2 != 0, 'temp'] = df['temp'].mean()
df

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_7848/3052076133.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-1.0508241758241759' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['temp'] % 2 != 0, 'temp'] = df['temp'].mean()

         temp  hour
0   -1.050824     0
1   -1.050824     3
2   -1.050824     6
3   -1.050824     9
4   -1.050824    12
..        ...   ...
723  2.000000     9
724  2.000000    12
725  2.000000    15
726  2.000000    18
727  2.000000    21

[728 rows x 2 columns]

In [14]:
# 14.2

In [15]:
df = pd.concat([s, s1], axis=1)
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [16]:
df.loc[(df['temp'] % 2 == 0) & (df['hour'].isin([9, 18])), 'temp'] = 3
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     3     9
724     2    12
725     2    15
726     3    18
727     2    21

[728 rows x 2 columns]

In [17]:
# 14.3

In [18]:
df = pd.concat([s, s1], axis=1)
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [19]:
df.loc[df['hour'] % 2 != 0, 'temp'] = 5
df

     temp  hour
0      -1     0
1       5     3
2      -1     6
3       5     9
4      -1    12
..    ...   ...
723     5     9
724     2    12
725     5    15
726     2    18
727     5    21

[728 rows x 2 columns]