In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    data=[
        {'product_id': 23, 'name': 'computer',       'wholesale_price': 500, 'retail_price': 1000, 'sales': 100},
        {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 1000},
        {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 500},
        {'product_id': 15, 'name': 'banana',         'wholesale_price': 0.5, 'retail_price': 1,    'sales': 200},
        {'product_id': 87, 'name': 'sandwich',       'wholesale_price': 3.0, 'retail_price': 5,    'sales': 300},
    ]
)
df

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [3]:
df['current_net'] = (df['retail_price'] - df['wholesale_price']) * df['sales']
df

,product_id,name,wholesale_price,retail_price,sales,current_net
0,23,computer,500.0,1000,100,50000.0
1,96,Python Workout,35.0,75,1000,40000.0
2,97,Pandas Workout,35.0,75,500,20000.0
3,15,banana,0.5,1,200,100.0
4,87,sandwich,3.0,5,300,600.0

In [4]:
df['after_15'] = (df['retail_price'] - df['wholesale_price']) * df['sales'] * 0.85

In [5]:
df['after_20'] = (df['retail_price'] - df['wholesale_price']) * df['sales'] * 0.8

In [6]:
df['after_25'] = (df['retail_price'] - df['wholesale_price']) * df['sales'] * 0.75

In [7]:
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25
0,23,computer,500.0,1000,100,50000.0,42500.0,40000.0,37500.0
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0
3,15,banana,0.5,1,200,100.0,85.0,80.0,75.0
4,87,sandwich,3.0,5,300,600.0,510.0,480.0,450.0

In [11]:
df[['current_net', 'after_15', 'after_20', 'after_25']].sum()

current_net    110700.0
after_15        94095.0
after_20        88560.0
after_25        83025.0
dtype: float64

In [15]:
# 9.1

In [12]:
def get_alter_25(profit):
    if profit > 20000:
        return profit * 0.75
    else:
        return profit

In [13]:
df['alter_after_25'] = df['current_net'].apply(get_alter_25)
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25,alter_after_25
0,23,computer,500.0,1000,100,50000.0,42500.0,40000.0,37500.0,37500.0
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0,30000.0
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0,20000.0
3,15,banana,0.5,1,200,100.0,85.0,80.0,75.0,100.0
4,87,sandwich,3.0,5,300,600.0,510.0,480.0,450.0,600.0

In [14]:
df[['current_net', 'after_15', 'after_20', 'after_25', 'alter_after_25']].sum()

current_net       110700.0
after_15           94095.0
after_20           88560.0
after_25           83025.0
alter_after_25     88200.0
dtype: float64

In [16]:
# 9.2

In [17]:
def get_tax_rate(retail_price):
    if retail_price > 80:
        return 0.25
    elif 30 <= retail_price <= 80:
        return 0.1
    else:
        return 0.0

In [18]:
df['new_tax'] = (1 - df['retail_price'].apply(get_tax_rate)) * df['current_net']
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25,alter_after_25,new_tax
0,23,computer,500.0,1000,100,50000.0,42500.0,40000.0,37500.0,37500.0,37500.0
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0,30000.0,36000.0
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0,20000.0,18000.0
3,15,banana,0.5,1,200,100.0,85.0,80.0,75.0,100.0,100.0
4,87,sandwich,3.0,5,300,600.0,510.0,480.0,450.0,600.0,600.0

In [19]:
df[['current_net', 'after_15', 'after_20', 'after_25', 'alter_after_25', 'new_tax']].sum()

current_net       110700.0
after_15           94095.0
after_20           88560.0
after_25           83025.0
alter_after_25     88200.0
new_tax            92200.0
dtype: float64

In [20]:
# 9.3

In [23]:
pd.options.display.float_format = '{:,.2f}'.format
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25,alter_after_25,new_tax
0,23,computer,500.00,1000,100,"50,000.00","42,500.00","40,000.00","37,500.00","37,500.00","37,500.00"
1,96,Python Workout,35.00,75,1000,"40,000.00","34,000.00","32,000.00","30,000.00","30,000.00","36,000.00"
2,97,Pandas Workout,35.00,75,500,"20,000.00","17,000.00","16,000.00","15,000.00","20,000.00","18,000.00"
3,15,banana,0.50,1,200,100.00,85.00,80.00,75.00,100.00,100.00
4,87,sandwich,3.00,5,300,600.00,510.00,480.00,450.00,600.00,600.00