In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    'data/sat-scores.csv',
    usecols=[
        'Year',
        'State.Code',
        'Total.Math',
        'Family Income.Less than 20k.Math',
        'Family Income.Between 20-40k.Math',
        'Family Income.Between 40-60k.Math',
        'Family Income.Between 60-80k.Math',
        'Family Income.Between 80-100k.Math',
        'Family Income.More than 100k.Math'
    ]
)
df

,Year,State.Code,Total.Math,Family Income.Between 20-40k.Math,Family Income.Between 40-60k.Math,Family Income.Between 60-80k.Math,Family Income.Between 80-100k.Math,Family Income.Less than 20k.Math,Family Income.More than 100k.Math
0,2005,AL,559,513,539,550,566,462,588
1,2005,AK,519,492,517,513,528,464,541
2,2005,AZ,530,498,520,524,534,485,554
3,2005,AR,552,513,543,553,570,489,572
4,2005,CA,522,477,506,521,535,451,566
...,...,...,...,...,...,...,...,...,...
572,2015,VA,517,469,488,496,514,441,549
573,2015,WA,511,483,503,521,534,449,560
574,2015,WV,500,468,483,487,503,448,522
575,2015,WI,606,551,596,590,605,573,615
576,2015,WY,587,533,550,561,598,0,573

In [3]:
df = df.rename(columns={
        'Family Income.Less than 20k.Math': 'income<20k',
        'Family Income.Between 20-40k.Math': '20k<income<40k',
        'Family Income.Between 40-60k.Math': '40k<income<60k',
        'Family Income.Between 60-80k.Math': '60k<income<80k',
        'Family Income.Between 80-100k.Math': '80k<income<100k',
        'Family Income.More than 100k.Math': 'income>100k'
    }
)

In [4]:
df

,Year,State.Code,Total.Math,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income<20k,income>100k
0,2005,AL,559,513,539,550,566,462,588
1,2005,AK,519,492,517,513,528,464,541
2,2005,AZ,530,498,520,524,534,485,554
3,2005,AR,552,513,543,553,570,489,572
4,2005,CA,522,477,506,521,535,451,566
...,...,...,...,...,...,...,...,...,...
572,2015,VA,517,469,488,496,514,441,549
573,2015,WA,511,483,503,521,534,449,560
574,2015,WV,500,468,483,487,503,448,522
575,2015,WI,606,551,596,590,605,573,615
576,2015,WY,587,533,550,561,598,0,573

In [6]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().sort_index()

,income<20k,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income>100k
Year,,,,,,
2005,427.596154,488.653846,522.673077,536.076923,548.942308,572.173077
2006,461.019231,502.923077,523.769231,534.903846,550.461538,572.519231
2007,457.924528,494.849057,519.490566,533.188679,545.698113,565.169811
2008,478.641509,523.622642,547.471698,549.188679,557.641509,564.566038
2009,482.058824,527.823529,550.980392,553.941176,565.333333,585.784314
2010,477.039216,499.274510,522.000000,534.235294,547.627451,569.274510
2011,460.452830,494.886792,513.415094,528.660377,541.849057,563.245283
2012,458.773585,492.056604,512.452830,525.773585,538.301887,557.320755
2013,469.358491,490.132075,511.377358,520.320755,537.396226,556.339623
2014,459.415094,497.641509,514.943396,527.169811,543.132075,555.433962
2015,447.490566,491.603774,513.754717,527.132075,542.037736,563.433962

In [9]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose()

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,427.596154,461.019231,457.924528,478.641509,482.058824,477.039216,460.452830,458.773585,469.358491,459.415094,447.490566
20k<income<40k,488.653846,502.923077,494.849057,523.622642,527.823529,499.274510,494.886792,492.056604,490.132075,497.641509,491.603774
40k<income<60k,522.673077,523.769231,519.490566,547.471698,550.980392,522.000000,513.415094,512.452830,511.377358,514.943396,513.754717
60k<income<80k,536.076923,534.903846,533.188679,549.188679,553.941176,534.235294,528.660377,525.773585,520.320755,527.169811,527.132075
80k<income<100k,548.942308,550.461538,545.698113,557.641509,565.333333,547.627451,541.849057,538.301887,537.396226,543.132075,542.037736
income>100k,572.173077,572.519231,565.169811,564.566038,585.784314,569.274510,563.245283,557.320755,556.339623,555.433962,563.433962

In [8]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change()

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20k<income<40k,0.142793,0.090894,0.080635,0.093977,0.094936,0.046611,0.074783,0.072548,0.044260,0.083207,0.098579
40k<income<60k,0.069618,0.041450,0.049796,0.045546,0.043872,0.045517,0.037439,0.041451,0.043346,0.034768,0.045059
60k<income<80k,0.025645,0.021259,0.026368,0.003136,0.005374,0.023439,0.029694,0.025994,0.017489,0.023743,0.026038
80k<income<100k,0.023999,0.029085,0.023462,0.015391,0.020566,0.025068,0.024947,0.023828,0.032817,0.030279,0.028277
income>100k,0.042319,0.040071,0.035682,0.012418,0.036175,0.039529,0.039487,0.035331,0.035250,0.022650,0.039474

In [11]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change().transpose().mean()

income<20k              NaN
20k<income<40k     0.083929
40k<income<60k     0.045260
60k<income<80k     0.020744
80k<income<100k    0.025247
income>100k        0.034399
dtype: float64

In [12]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change().mean(axis=1)

income<20k              NaN
20k<income<40k     0.083929
40k<income<60k     0.045260
60k<income<80k     0.020744
80k<income<100k    0.025247
income>100k        0.034399
dtype: float64

In [14]:
df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change()

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20k<income<40k,0.142793,0.090894,0.080635,0.093977,0.094936,0.046611,0.074783,0.072548,0.044260,0.083207,0.098579
40k<income<60k,0.069618,0.041450,0.049796,0.045546,0.043872,0.045517,0.037439,0.041451,0.043346,0.034768,0.045059
60k<income<80k,0.025645,0.021259,0.026368,0.003136,0.005374,0.023439,0.029694,0.025994,0.017489,0.023743,0.026038
80k<income<100k,0.023999,0.029085,0.023462,0.015391,0.020566,0.025068,0.024947,0.023828,0.032817,0.030279,0.028277
income>100k,0.042319,0.040071,0.035682,0.012418,0.036175,0.039529,0.039487,0.035331,0.035250,0.022650,0.039474

In [15]:
# 33.1

In [16]:
change = df.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change()

In [17]:
change

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20k<income<40k,0.142793,0.090894,0.080635,0.093977,0.094936,0.046611,0.074783,0.072548,0.044260,0.083207,0.098579
40k<income<60k,0.069618,0.041450,0.049796,0.045546,0.043872,0.045517,0.037439,0.041451,0.043346,0.034768,0.045059
60k<income<80k,0.025645,0.021259,0.026368,0.003136,0.005374,0.023439,0.029694,0.025994,0.017489,0.023743,0.026038
80k<income<100k,0.023999,0.029085,0.023462,0.015391,0.020566,0.025068,0.024947,0.023828,0.032817,0.030279,0.028277
income>100k,0.042319,0.040071,0.035682,0.012418,0.036175,0.039529,0.039487,0.035331,0.035250,0.022650,0.039474

In [19]:
change.transpose().describe()

,income<20k,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income>100k
count,0.0,11.000000,11.000000,11.000000,11.000000,11.000000
mean,NaN,0.083929,0.045260,0.020744,0.025247,0.034399
std,NaN,0.026723,0.009055,0.008745,0.004821,0.008947
min,NaN,0.044260,0.034768,0.003136,0.015391,0.012418
25%,NaN,0.073665,0.041450,0.019374,0.023645,0.035291
50%,NaN,0.083207,0.043872,0.023743,0.024947,0.036175
75%,NaN,0.094456,0.045532,0.026016,0.028681,0.039508
max,NaN,0.142793,0.069618,0.029694,0.032817,0.042319

In [20]:
# 33.2

In [21]:
df

,Year,State.Code,Total.Math,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income<20k,income>100k
0,2005,AL,559,513,539,550,566,462,588
1,2005,AK,519,492,517,513,528,464,541
2,2005,AZ,530,498,520,524,534,485,554
3,2005,AR,552,513,543,553,570,489,572
4,2005,CA,522,477,506,521,535,451,566
...,...,...,...,...,...,...,...,...,...
572,2015,VA,517,469,488,496,514,441,549
573,2015,WA,511,483,503,521,534,449,560
574,2015,WV,500,468,483,487,503,448,522
575,2015,WI,606,551,596,590,605,573,615
576,2015,WY,587,533,550,561,598,0,573

In [22]:
df['rich_vs_poor'] = df['income>100k'] - df['income<20k']

In [23]:
df

,Year,State.Code,Total.Math,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income<20k,income>100k,rich_vs_poor
0,2005,AL,559,513,539,550,566,462,588,126
1,2005,AK,519,492,517,513,528,464,541,77
2,2005,AZ,530,498,520,524,534,485,554,69
3,2005,AR,552,513,543,553,570,489,572,83
4,2005,CA,522,477,506,521,535,451,566,115
...,...,...,...,...,...,...,...,...,...,...
572,2015,VA,517,469,488,496,514,441,549,108
573,2015,WA,511,483,503,521,534,449,560,111
574,2015,WV,500,468,483,487,503,448,522,74
575,2015,WI,606,551,596,590,605,573,615,42
576,2015,WY,587,533,550,561,598,0,573,573

In [26]:
df.groupby('State.Code')['rich_vs_poor'].mean().sort_values(ascending=False).head(5)

State.Code
ND    341.909091
WY    246.454545
DC    208.818182
SD    157.000000
MS    140.000000
Name: rich_vs_poor, dtype: float64

In [27]:
# 33.3

In [32]:
dfv = pd.read_csv(
    'data/sat-scores.csv',
    usecols=[
        'Year',
        'State.Code',
        'Total.Verbal',
        'Family Income.Less than 20k.Verbal',
        'Family Income.Between 20-40k.Verbal',
        'Family Income.Between 40-60k.Verbal',
        'Family Income.Between 60-80k.Verbal',
        'Family Income.Between 80-100k.Verbal',
        'Family Income.More than 100k.Verbal'
    ]
)
dfv

,Year,State.Code,Total.Verbal,Family Income.Between 20-40k.Verbal,Family Income.Between 40-60k.Verbal,Family Income.Between 60-80k.Verbal,Family Income.Between 80-100k.Verbal,Family Income.Less than 20k.Verbal,Family Income.More than 100k.Verbal
0,2005,AL,567,527,551,564,577,474,590
1,2005,AK,523,500,522,519,534,467,544
2,2005,AZ,526,495,518,523,533,474,546
3,2005,AR,563,526,555,570,580,486,589
4,2005,CA,504,458,494,511,525,421,551
...,...,...,...,...,...,...,...,...,...
572,2015,VA,518,472,494,505,518,446,550
573,2015,WA,502,473,499,517,530,437,552
574,2015,WV,509,481,492,501,511,455,532
575,2015,WI,591,544,579,580,595,532,603
576,2015,WY,588,560,572,604,587,0,591

In [33]:
dfv = dfv.rename(columns={
        'Family Income.Less than 20k.Verbal': 'income<20k',
        'Family Income.Between 20-40k.Verbal': '20k<income<40k',
        'Family Income.Between 40-60k.Verbal': '40k<income<60k',
        'Family Income.Between 60-80k.Verbal': '60k<income<80k',
        'Family Income.Between 80-100k.Verbal': '80k<income<100k',
        'Family Income.More than 100k.Verbal': 'income>100k'
    }
)
dfv

,Year,State.Code,Total.Verbal,20k<income<40k,40k<income<60k,60k<income<80k,80k<income<100k,income<20k,income>100k
0,2005,AL,567,527,551,564,577,474,590
1,2005,AK,523,500,522,519,534,467,544
2,2005,AZ,526,495,518,523,533,474,546
3,2005,AR,563,526,555,570,580,486,589
4,2005,CA,504,458,494,511,525,421,551
...,...,...,...,...,...,...,...,...,...
572,2015,VA,518,472,494,505,518,446,550
573,2015,WA,502,473,499,517,530,437,552
574,2015,WV,509,481,492,501,511,455,532
575,2015,WI,591,544,579,580,595,532,603
576,2015,WY,588,560,572,604,587,0,591

In [37]:
changev = dfv.groupby('Year')[['income<20k', '20k<income<40k', '40k<income<60k', '60k<income<80k', '80k<income<100k', 'income>100k']].mean().transpose().pct_change()

In [38]:
changev

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20k<income<40k,0.094510,0.109827,0.097677,0.101287,0.104675,0.064151,0.091395,0.089307,0.061552,0.098486,0.117115
40k<income<60k,0.047626,0.043428,0.052054,0.039726,0.038260,0.046060,0.042502,0.044335,0.046856,0.031610,0.045470
60k<income<80k,0.021503,0.017874,0.020550,0.002915,0.005520,0.023127,0.029320,0.026009,0.018316,0.035071,0.027498
80k<income<100k,0.022665,0.021635,0.018083,0.013979,0.022816,0.024813,0.016756,0.015382,0.026149,0.018215,0.021182
income>100k,0.034856,0.033777,0.031631,0.008258,0.024956,0.034019,0.039516,0.030898,0.032486,0.016395,0.035395

In [39]:
changev[changev <= 0]

Year,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
income<20k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20k<income<40k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40k<income<60k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60k<income<80k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80k<income<100k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
income>100k,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN