In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    'data/wti-daily.csv',
    parse_dates=['Date'],
    index_col=['Date']
)

df

            Price
Date
1986-01-02  25.56
1986-01-03  26.00
1986-01-06  26.53
1986-01-07  25.85
1986-01-08  25.87
...           ...
2021-12-14  70.57
2021-12-15  70.89
2021-12-16  72.34
2021-12-17  70.93
2021-12-20  68.69

[9064 rows x 1 columns]

In [4]:
df.loc['1992-06'].mean()

Price    22.384545
dtype: float64

In [5]:
df.loc['1987'].mean()

Price    19.200512
dtype: float64

In [6]:
df.loc['2003-09':'2014-07'].mean()

Price    76.457834
dtype: float64

In [12]:
df

            Price
Date
1986-01-02  25.56
1986-01-03  26.00
1986-01-06  26.53
1986-01-07  25.85
1986-01-08  25.87
...           ...
2021-12-14  70.57
2021-12-15  70.89
2021-12-16  72.34
2021-12-17  70.93
2021-12-20  68.69

[9064 rows x 1 columns]

In [14]:
df.loc[df.index.is_quarter_end]

            Price
Date
1986-03-31  10.25
1986-06-30  12.80
1986-09-30  14.70
1986-12-31  17.93
1987-03-31  18.82
...           ...
2020-09-30  40.05
2020-12-31  48.35
2021-03-31  59.19
2021-06-30  73.52
2021-09-30  75.22

[99 rows x 1 columns]

In [16]:
df.resample('YE').mean()

                Price
Date
1986-12-31  15.047689
1987-12-31  19.200512
1988-12-31  15.965409
1989-12-31  19.635486
1990-12-31  24.526576
1991-12-31  21.541367
1992-12-31  20.575564
1993-12-31  18.432200
1994-12-31  17.196429
1995-12-31  18.428805
1996-12-31  22.119173
1997-12-31  20.608254
1998-12-31  14.422072
1999-12-31  19.344980
2000-12-31  30.378520
2001-12-31  25.983120
2002-12-31  26.184960
2003-12-31  31.075240
2004-12-31  41.506024
2005-12-31  56.637251
2006-12-31  66.054659
2007-12-31  72.340595
2008-12-31  99.671502
2009-12-31  61.950437
2010-12-31  79.475714
2011-12-31  94.880873
2012-12-31  94.053333
2013-12-31  97.982540
2014-12-31  93.172222
2015-12-31  48.656706
2016-12-31  43.293651
2017-12-31  50.800320
2018-12-31  65.227470
2019-12-31  56.988320
2020-12-31  39.160437
2021-12-31  67.917119

In [17]:
df.resample('YS').mean()

                Price
Date
1986-01-01  15.047689
1987-01-01  19.200512
1988-01-01  15.965409
1989-01-01  19.635486
1990-01-01  24.526576
1991-01-01  21.541367
1992-01-01  20.575564
1993-01-01  18.432200
1994-01-01  17.196429
1995-01-01  18.428805
1996-01-01  22.119173
1997-01-01  20.608254
1998-01-01  14.422072
1999-01-01  19.344980
2000-01-01  30.378520
2001-01-01  25.983120
2002-01-01  26.184960
2003-01-01  31.075240
2004-01-01  41.506024
2005-01-01  56.637251
2006-01-01  66.054659
2007-01-01  72.340595
2008-01-01  99.671502
2009-01-01  61.950437
2010-01-01  79.475714
2011-01-01  94.880873
2012-01-01  94.053333
2013-01-01  97.982540
2014-01-01  93.172222
2015-01-01  48.656706
2016-01-01  43.293651
2017-01-01  50.800320
2018-01-01  65.227470
2019-01-01  56.988320
2020-01-01  39.160437
2021-01-01  67.917119

In [18]:
df.idxmax()

Price   2008-07-03
dtype: datetime64[ns]

In [19]:
df.idxmin()

Price   2020-04-20
dtype: datetime64[ns]

In [22]:
df.resample('2YE').mean()

                Price
Date
1986-12-31  15.047689
1988-12-31  17.573464
1990-12-31  22.081031
1992-12-31  21.057524
1994-12-31  17.811853
1996-12-31  20.284950
1998-12-31  17.521312
2000-12-31  24.850739
2002-12-31  26.084040
2004-12-31  36.280180
2006-12-31  61.327120
2008-12-31  86.033109
2010-12-31  70.713075
2012-12-31  94.467103
2014-12-31  95.577381
2016-12-31  45.975179
2018-12-31  57.999439
2020-12-31  48.038865
2022-12-31  67.917119

In [23]:
# 41.1

In [25]:
df.resample('QE').agg(['mean', 'std'])

                Price
                 mean       std
Date
1986-03-31  17.217213  4.856866
1986-06-30  13.866094  1.346364
1986-09-30  13.813906  1.809548
1986-12-31  15.406452  0.824353
1987-03-31  18.250328  0.661624
...               ...       ...
2020-12-31  42.524921  3.844217
2021-03-31  58.093443  4.931396
2021-06-30  66.186667  4.403607
2021-09-30  70.575469  3.078296
2021-12-31  77.701273  5.712271

[144 rows x 2 columns]

In [27]:
df.resample('QS').agg(['mean', 'std'])

                Price
                 mean       std
Date
1986-01-01  17.217213  4.856866
1986-04-01  13.866094  1.346364
1986-07-01  13.813906  1.809548
1986-10-01  15.406452  0.824353
1987-01-01  18.250328  0.661624
...               ...       ...
2020-10-01  42.524921  3.844217
2021-01-01  58.093443  4.931396
2021-04-01  66.186667  4.403607
2021-07-01  70.575469  3.078296
2021-10-01  77.701273  5.712271

[144 rows x 2 columns]

In [28]:
# 41.2

In [31]:
df.resample('QE').mean().diff().loc[lambda df_: df_['Price'] == df_['Price'].max()]

               Price
Date
2008-06-30  25.91959

In [35]:
# 41.3

In [34]:
df.resample('QE').mean().pct_change().loc[lambda df_: df_['Price'] == df_['Price'].max()]

               Price
Date
1990-09-30  0.475456