In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
[file_name for file_name in os.listdir('data') if ('+' in file_name) or (',' in file_name)]

['san+francisco,ca.csv',
 'new+york,ny.csv',
 'springfield,ma.csv',
 'boston,ma.csv',
 'springfield,il.csv',
 'albany,ny.csv',
 'los+angeles,ca.csv',
 'chicago,il.csv']

In [10]:
df_tmp = pd.read_csv(
    'data/san+francisco,ca.csv',
    # usecols=[0, 1, 2],
    # names=['date_time', 'max_temp', 'min_temp'],
    # header=0
)
list(enumerate(list(df_tmp.columns)))

[(0, 'date_time'),
 (1, 'san+francisco,ca_maxtempC'),
 (2, 'san+francisco,ca_mintempC'),
 (3, 'san+francisco,ca_totalSnow_cm'),
 (4, 'san+francisco,ca_sunHour'),
 (5, 'san+francisco,ca_uvIndex'),
 (6, 'san+francisco,ca_uvIndex.1'),
 (7, 'san+francisco,ca_moon_illumination'),
 (8, 'san+francisco,ca_moonrise'),
 (9, 'san+francisco,ca_moonset'),
 (10, 'san+francisco,ca_sunrise'),
 (11, 'san+francisco,ca_sunset'),
 (12, 'san+francisco,ca_DewPointC'),
 (13, 'san+francisco,ca_FeelsLikeC'),
 (14, 'san+francisco,ca_HeatIndexC'),
 (15, 'san+francisco,ca_WindChillC'),
 (16, 'san+francisco,ca_WindGustKmph'),
 (17, 'san+francisco,ca_cloudcover'),
 (18, 'san+francisco,ca_humidity'),
 (19, 'san+francisco,ca_precipMM'),
 (20, 'san+francisco,ca_pressure'),
 (21, 'san+francisco,ca_tempC'),
 (22, 'san+francisco,ca_visibility'),
 (23, 'san+francisco,ca_winddirDegree'),
 (24, 'san+francisco,ca_windspeedKmph')]

In [13]:
df_tmp = pd.read_csv(
    'data/san+francisco,ca.csv',
    usecols=[1, 2, 19],
    names=['max_temp', 'min_temp', 'precipMM'],
    header=0
)
df_tmp

     max_temp  min_temp  precipMM
0          13         8       0.0
1          13         8       0.0
2          13         8       0.0
3          13         8       0.0
4          13         8       0.0
..        ...       ...       ...
723        12         8       0.0
724        12         8       0.0
725        12         8       0.0
726        12         8       0.0
727        12         8       0.0

[728 rows x 3 columns]

In [14]:
dataframes = []
for file in [file_name for file_name in os.listdir('data') if ('+' in file_name) or (',' in file_name)]:
    full_name, extension = file.split('.')
    city, state = full_name.split(',')
    city = city.replace('+', ' ')
    df_tmp = pd.read_csv(
        'data/' + file,
        usecols=[1, 2, 19],
        names=['max_temp', 'min_temp', 'precipMM'],
        header=0
    )
    df_tmp['city'] = city.title()
    df_tmp['state'] = state.upper()
    dataframes.append(df_tmp)

In [15]:
df = pd.concat(objs=dataframes, ignore_index=True)
df

      max_temp  min_temp  precipMM           city state
0           13         8       0.0  San Francisco    CA
1           13         8       0.0  San Francisco    CA
2           13         8       0.0  San Francisco    CA
3           13         8       0.0  San Francisco    CA
4           13         8       0.0  San Francisco    CA
...        ...       ...       ...            ...   ...
5819         3        -2       0.0        Chicago    IL
5820         3        -2       0.0        Chicago    IL
5821         3        -2       0.0        Chicago    IL
5822         3        -2       0.0        Chicago    IL
5823         3        -2       0.0        Chicago    IL

[5824 rows x 5 columns]

In [17]:
df['precipMM'].describe()

count    5824.000000
mean        0.501082
std         1.898486
min         0.000000
25%         0.000000
50%         0.000000
75%         0.100000
max        30.800000
Name: precipMM, dtype: float64

In [25]:
df_tmp = df[['state', 'city', 'precipMM']]

In [26]:
df_tmp[df_tmp['precipMM'] >= 15]

     state           city  precipMM
515     CA  San Francisco      23.7
516     CA  San Francisco      20.4
810     NY       New York      24.8
811     NY       New York      27.9
1049    NY       New York      18.9
1085    NY       New York      15.6
2507    MA         Boston      16.0
2542    MA         Boston      20.2
2543    MA         Boston      15.8
4668    CA    Los Angeles      15.5
4795    CA    Los Angeles      15.6
4796    CA    Los Angeles      24.5
4797    CA    Los Angeles      28.2
4798    CA    Los Angeles      26.7
4891    CA    Los Angeles      21.5
4892    CA    Los Angeles      30.8
5806    IL        Chicago      15.7

In [27]:
dataframes = []
for file in [file_name for file_name in os.listdir('data') if ('+' in file_name) or (',' in file_name)]:
    full_name, extension = file.split('.')
    city, state = full_name.split(',')
    city = city.replace('+', ' ')
    df_tmp = pd.read_csv(
        'data/' + file,
        usecols=[1, 2, 3],
        names=['max_temp', 'min_temp', 'precipMM'],
        header=0
    )
    df_tmp['city'] = city.title()
    df_tmp['state'] = state.upper()
    dataframes.append(df_tmp)

In [28]:
df1 = pd.concat(objs=dataframes, ignore_index=True)
df1

      max_temp  min_temp  precipMM           city state
0           13         8       0.0  San Francisco    CA
1           13         8       0.0  San Francisco    CA
2           13         8       0.0  San Francisco    CA
3           13         8       0.0  San Francisco    CA
4           13         8       0.0  San Francisco    CA
...        ...       ...       ...            ...   ...
5819         3        -2       0.0        Chicago    IL
5820         3        -2       0.0        Chicago    IL
5821         3        -2       0.0        Chicago    IL
5822         3        -2       0.0        Chicago    IL
5823         3        -2       0.0        Chicago    IL

[5824 rows x 5 columns]

In [31]:
df1.groupby(by=['state', 'city']).filter(lambda df: len(df[df['precipMM'] >= 15.0]) >= 3)[['state', 'city']].drop_duplicates()

     state         city
2184    MA       Boston
2912    IL  Springfield
3640    NY       Albany

In [34]:
df.groupby(by=['state', 'city']).filter(lambda df: len(df[df['precipMM'] >= 15.0]) >= 3)[['state', 'city']].drop_duplicates()

     state         city
728     NY     New York
2184    MA       Boston
4368    CA  Los Angeles

In [35]:
df1.groupby(by=['state', 'city']).filter(lambda df: len(df[(df['precipMM'] >= 10.0) & (df['min_temp'] <= 0)]) >= 3)[['state', 'city']].drop_duplicates()

     state         city
728     NY     New York
2184    MA       Boston
2912    IL  Springfield
3640    NY       Albany
5096    IL      Chicago

In [36]:
df.groupby(by=['state', 'city']).filter(lambda df: len(df[(df['precipMM'] >= 10.0) & (df['min_temp'] <= 0)]) >= 3)[['state', 'city']].drop_duplicates()

     state      city
728     NY  New York
2184    MA    Boston
3640    NY    Albany

In [38]:
df1['precipMM_share'] = df1.groupby(by=['state', 'city'])['precipMM'].transform(lambda v: v / v.sum())

In [39]:
df1

      max_temp  min_temp  precipMM           city state  precipMM_share
0           13         8       0.0  San Francisco    CA             NaN
1           13         8       0.0  San Francisco    CA             NaN
2           13         8       0.0  San Francisco    CA             NaN
3           13         8       0.0  San Francisco    CA             NaN
4           13         8       0.0  San Francisco    CA             NaN
...        ...       ...       ...            ...   ...             ...
5819         3        -2       0.0        Chicago    IL             0.0
5820         3        -2       0.0        Chicago    IL             0.0
5821         3        -2       0.0        Chicago    IL             0.0
5822         3        -2       0.0        Chicago    IL             0.0
5823         3        -2       0.0        Chicago    IL             0.0

[5824 rows x 6 columns]

In [40]:
df1.groupby(by=['state', 'city'])[['precipMM', 'precipMM_share']].sum()

                     precipMM  precipMM_share
state city
CA    Los Angeles         0.0             0.0
      San Francisco       0.0             0.0
IL    Chicago           396.0             1.0
      Springfield       350.4             1.0
MA    Boston            601.6             1.0
      Springfield       156.0             1.0
NY    Albany            964.8             1.0
      New York          252.8             1.0

In [41]:
df['precipMM_share'] = df.groupby(by=['state', 'city'])['precipMM'].transform(lambda v: v / v.sum())

In [42]:
df.groupby(by=['state', 'city'])[['precipMM', 'precipMM_share']].sum()

                     precipMM  precipMM_share
state city
CA    Los Angeles       519.9             1.0
      San Francisco     419.4             1.0
IL    Chicago           274.2             1.0
      Springfield       203.8             1.0
MA    Boston            418.2             1.0
      Springfield       128.7             1.0
NY    Albany            448.2             1.0
      New York          505.9             1.0

In [44]:
df1.groupby(by=['state', 'city'])['precipMM_share'].max() * 100

state  city
CA     Los Angeles           NaN
       San Francisco         NaN
IL     Chicago          3.636364
       Springfield      4.594749
MA     Boston           3.806516
       Springfield      5.256410
NY     Albany           3.886816
       New York         4.905063
Name: precipMM_share, dtype: float64

In [45]:
df.groupby(by=['state', 'city'])['precipMM_share'].max() * 100

state  city
CA     Los Angeles      5.924216
       San Francisco    5.650930
IL     Chicago          5.725748
       Springfield      5.053974
MA     Boston           4.830225
       Springfield      6.060606
NY     Albany           2.922802
       New York         5.514924
Name: precipMM_share, dtype: float64

In [46]:
# 34.1

In [47]:
df.groupby(by=['state', 'city']).filter(lambda df: len(df[df['precipMM'] >= 15.0]) >= 3)[['state', 'city']].drop_duplicates()

     state         city
728     NY     New York
2184    MA       Boston
4368    CA  Los Angeles

In [49]:
# 34.2

In [48]:
df.groupby(by=['state', 'city']).filter(lambda df, min_mm, times: len(df[df['precipMM'] >= min_mm]) >= times, min_mm=15.0, times=3)[['state', 'city']].drop_duplicates()

     state         city
728     NY     New York
2184    MA       Boston
4368    CA  Los Angeles

In [50]:
# 34.3

In [51]:
df['precipMM_share'] = df.groupby(by=['state', 'city'])['precipMM'].transform(lambda v: v / v.sum())

In [52]:
df.groupby(by=['state', 'city'])['precipMM_share'].max() * 100

state  city
CA     Los Angeles      5.924216
       San Francisco    5.650930
IL     Chicago          5.725748
       Springfield      5.053974
MA     Boston           4.830225
       Springfield      6.060606
NY     Albany           2.922802
       New York         5.514924
Name: precipMM_share, dtype: float64