In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/nyc-parking-violations-2020.csv', usecols=['Plate ID', 'Registration State', 'Vehicle Make', 'Vehicle Color', 'Violation Time', 'Street Name'])
df

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,1106A,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [3]:
len(df)

12495734

In [4]:
df.shape

(12495734, 6)

In [5]:
df1 = df.dropna().copy()
df1

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
5,KDG0693,PA,HYUN,0525P,B 99 ST,GY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [6]:
len(df1)

12048375

In [7]:
len(df) - len(df1)

447359

In [8]:
(len(df) - len(df1)) * 100

44735900

In [9]:
df2 = df.dropna(subset=['Plate ID', 'Registration State', 'Vehicle Make', 'Street Name']).copy()
df2

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,1106A,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [10]:
len(df2)

12431949

In [11]:
len(df) - len(df2)

63785

In [12]:
(len(df) - len(df2)) * 100

6378500

In [13]:
df3 = df.dropna(subset=['Plate ID', 'Registration State', 'Street Name']).copy()
df3

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,1106A,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [14]:
len(df) - len(df3)

1618

In [15]:
(len(df) - len(df3)) * 100

161800

In [16]:
# 25.1

In [17]:
df4 = df.dropna(subset=['Plate ID', 'Registration State', 'Vehicle Make', 'Street Name'], thresh=3).copy()
df4

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,1106A,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [18]:
len(df4)

12495481

In [19]:
len(df) - len(df4)

253

In [20]:
# 25.2

In [23]:
(len(df) - df.count()).sort_values(ascending=False)

Vehicle Color         391982
Vehicle Make           62420
Street Name             1417
Violation Time           278
Plate ID                 202
Registration State         0
dtype: int64

In [24]:
# 25.3

In [25]:
df.mode()

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,BLANKPLATE,NY,TOYOT,0836A,Broadway,WH

In [27]:
df.loc[df['Plate ID'] == 'BLANKPLATE', 'Plate ID'] = np.nan

In [28]:
(len(df) - df.count()).sort_values(ascending=False)

Vehicle Color         391982
Vehicle Make           62420
Plate ID                9084
Street Name             1417
Violation Time           278
Registration State         0
dtype: int64

In [29]:
df5 = df.dropna(subset=['Plate ID', 'Registration State', 'Vehicle Make', 'Street Name'], thresh=3).copy()
df5

,Plate ID,Registration State,Vehicle Make,Violation Time,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,0523P,43 ST,BK
1,KRE6058,PA,ME/BE,0428P,UNION ST,BLK
2,444326R,NJ,LEXUS,0625A,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,1106A,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,1253A,GRAND ST,GREY
...,...,...,...,...,...,...
12495729,62161MM,NY,FORD,1111A,3RD AVE,BR
12495730,GYE7330,NY,HONDA,0444P,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,0210A,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,0225P,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,0456A,W/S/O 182 STREET,WHITE

In [30]:
len(df) - len(df5)

944