In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/nyc_taxi_2020-01.csv')
df.memory_usage()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3285/2040125520.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/nyc_taxi_2020-01.csv')

Index                         132
VendorID                 51240064
tpep_pickup_datetime     51240064
tpep_dropoff_datetime    51240064
passenger_count          51240064
trip_distance            51240064
RatecodeID               51240064
store_and_fwd_flag       51240064
PULocationID             51240064
DOLocationID             51240064
payment_type             51240064
fare_amount              51240064
extra                    51240064
mta_tax                  51240064
tip_amount               51240064
tolls_amount             51240064
improvement_surcharge    51240064
total_amount             51240064
congestion_surcharge     51240064
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 18 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               float64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           float64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
dtypes: float64(13), int64(2), object(3)
memory usage: 879.6+ MB

In [7]:
df = pd.read_csv('data/nyc_taxi_2020-01.csv', usecols=['passenger_count', 'payment_type', 'total_amount'], dtype={'passenger_count': np.int8, 'payment_type': np.int8, 'total_amount': np.float32})
df

ValueError: Integer column has NA values in column 3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 3 columns):
 #   Column           Dtype
---  ------           -----
 0   passenger_count  float64
 1   payment_type     float64
 2   total_amount     float64
dtypes: float64(3)
memory usage: 146.6 MB

In [8]:
df = pd.read_csv('data/nyc_taxi_2020-01.csv', usecols=['passenger_count', 'payment_type', 'total_amount'])
df

         passenger_count  payment_type  total_amount
0                    1.0           1.0         11.27
1                    1.0           1.0         12.30
2                    1.0           1.0         10.80
3                    1.0           1.0          8.16
4                    1.0           2.0          4.80
...                  ...           ...           ...
6405003              NaN           NaN         21.14
6405004              NaN           NaN         62.46
6405005              NaN           NaN         51.90
6405006              NaN           NaN         30.22
6405007              NaN           NaN         58.11

[6405008 rows x 3 columns]

In [9]:
df.query('passenger_count.isnull()')

         passenger_count  payment_type  total_amount
6339567              NaN           NaN         54.60
6339568              NaN           NaN         30.11
6339569              NaN           NaN         27.91
6339570              NaN           NaN         29.63
6339571              NaN           NaN         28.83
...                  ...           ...           ...
6405003              NaN           NaN         21.14
6405004              NaN           NaN         62.46
6405005              NaN           NaN         51.90
6405006              NaN           NaN         30.22
6405007              NaN           NaN         58.11

[65441 rows x 3 columns]

In [10]:
df.query('payment_type.isnull()')

         passenger_count  payment_type  total_amount
6339567              NaN           NaN         54.60
6339568              NaN           NaN         30.11
6339569              NaN           NaN         27.91
6339570              NaN           NaN         29.63
6339571              NaN           NaN         28.83
...                  ...           ...           ...
6405003              NaN           NaN         21.14
6405004              NaN           NaN         62.46
6405005              NaN           NaN         51.90
6405006              NaN           NaN         30.22
6405007              NaN           NaN         58.11

[65441 rows x 3 columns]

In [11]:
df.query('total_amount.isnull()')

Empty DataFrame
Columns: [passenger_count, payment_type, total_amount]
Index: []

In [13]:
df.query('passenger_count.isnull() & payment_type.notnull()')

Empty DataFrame
Columns: [passenger_count, payment_type, total_amount]
Index: []

In [14]:
df.query('passenger_count.notnull() & payment_type.isnull()')

Empty DataFrame
Columns: [passenger_count, payment_type, total_amount]
Index: []

In [16]:
df = df.dropna().copy()

In [17]:
df

         passenger_count  payment_type  total_amount
0                    1.0           1.0         11.27
1                    1.0           1.0         12.30
2                    1.0           1.0         10.80
3                    1.0           1.0          8.16
4                    1.0           2.0          4.80
...                  ...           ...           ...
6339562              1.0           1.0         17.76
6339563              1.0           1.0         20.16
6339564              1.0           1.0         19.56
6339565              1.0           2.0         12.30
6339566              1.0           1.0          0.00

[6339567 rows x 3 columns]

In [19]:
df['passenger_count'] = df['passenger_count'].astype(np.int8)

In [29]:
df['payment_type'] = df['payment_type'].astype(np.int8)

In [30]:
df['total_amount'] = df['total_amount'].astype(np.float16)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6339567 entries, 0 to 6339566
Data columns (total 3 columns):
 #   Column           Dtype
---  ------           -----
 0   passenger_count  int8
 1   payment_type     int8
 2   total_amount     float16
dtypes: float16(1), int8(2)
memory usage: 72.6 MB

In [31]:
df.nunique()

passenger_count      10
payment_type          5
total_amount       5851
dtype: int64

In [33]:
df['payment_type'] = df['payment_type'].astype('category')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6339567 entries, 0 to 6339566
Data columns (total 3 columns):
 #   Column           Dtype
---  ------           -----
 0   passenger_count  int8
 1   payment_type     category
 2   total_amount     float16
dtypes: category(1), float16(1), int8(1)
memory usage: 72.6 MB

In [36]:
# 17.1

In [37]:
df = pd.read_csv('data/nyc_taxi_2020-01.csv', usecols=['VendorID', 'trip_distance', 'tip_amount', 'total_amount'])
df

         VendorID  trip_distance  tip_amount  total_amount
0             1.0           1.20        1.47         11.27
1             1.0           1.20        1.50         12.30
2             1.0           0.60        1.00         10.80
3             1.0           0.80        1.36          8.16
4             2.0           0.00        0.00          4.80
...           ...            ...         ...           ...
6405003       NaN           3.24        0.00         21.14
6405004       NaN          22.13        0.00         62.46
6405005       NaN          10.51        0.00         51.90
6405006       NaN           5.49        0.00         30.22
6405007       NaN          11.60        0.00         58.11

[6405008 rows x 4 columns]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       float64
 1   trip_distance  float64
 2   tip_amount     float64
 3   total_amount   float64
dtypes: float64(4)
memory usage: 195.5 MB

In [39]:
len(df) - df.count()

VendorID         65441
trip_distance        0
tip_amount           0
total_amount         0
dtype: int64

In [41]:
df.max()

VendorID              2.00
trip_distance    210240.07
tip_amount         1100.00
total_amount       4268.30
dtype: float64

In [42]:
df.min()

VendorID            1.00
trip_distance     -30.62
tip_amount        -91.00
total_amount    -1242.30
dtype: float64

In [49]:
df = pd.read_csv(
    'data/nyc_taxi_2020-01.csv',
    usecols=['VendorID', 'trip_distance', 'tip_amount', 'total_amount'],
    dtype={'VendorID': np.float32, 'trip_distance': np.float32, 'tip_amount': np.float32, 'total_amount': np.float32}
)
df

         VendorID  trip_distance  tip_amount  total_amount
0             1.0       1.200000        1.47     11.270000
1             1.0       1.200000        1.50     12.300000
2             1.0       0.600000        1.00     10.800000
3             1.0       0.800000        1.36      8.160000
4             2.0       0.000000        0.00      4.800000
...           ...            ...         ...           ...
6405003       NaN       3.240000        0.00     21.139999
6405004       NaN      22.129999        0.00     62.459999
6405005       NaN      10.510000        0.00     51.900002
6405006       NaN       5.490000        0.00     30.219999
6405007       NaN      11.600000        0.00     58.110001

[6405008 rows x 4 columns]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       float32
 1   trip_distance  float32
 2   tip_amount     float32
 3   total_amount   float32
dtypes: float32(4)
memory usage: 97.7 MB

In [51]:
df = df.dropna().copy()

In [52]:
df['VendorID'] = df['VendorID'].astype(np.int8)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6339567 entries, 0 to 6339566
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       int8
 1   trip_distance  float32
 2   tip_amount     float32
 3   total_amount   float32
dtypes: float32(3), int8(1)
memory usage: 127.0 MB

In [54]:
# 17.2

In [55]:
df = pd.read_csv(
    'data/nyc_taxi_2020-01.csv',
    usecols=['VendorID', 'trip_distance', 'tip_amount', 'total_amount'],
    dtype={'VendorID': np.float32, 'trip_distance': np.float32, 'tip_amount': np.float32, 'total_amount': np.float32}
)
df

         VendorID  trip_distance  tip_amount  total_amount
0             1.0       1.200000        1.47     11.270000
1             1.0       1.200000        1.50     12.300000
2             1.0       0.600000        1.00     10.800000
3             1.0       0.800000        1.36      8.160000
4             2.0       0.000000        0.00      4.800000
...           ...            ...         ...           ...
6405003       NaN       3.240000        0.00     21.139999
6405004       NaN      22.129999        0.00     62.459999
6405005       NaN      10.510000        0.00     51.900002
6405006       NaN       5.490000        0.00     30.219999
6405007       NaN      11.600000        0.00     58.110001

[6405008 rows x 4 columns]

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       float32
 1   trip_distance  float32
 2   tip_amount     float32
 3   total_amount   float32
dtypes: float32(4)
memory usage: 97.7 MB

In [57]:
df.query('VendorID.isnull()')['VendorID'] = 3

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3285/1993857477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.query('VendorID.isnull()')['VendorID'] = 3

In [59]:
df.loc[df['VendorID'].isnull(), 'VendorID'] = 3

In [60]:
len(df) - df.count()

VendorID         0
trip_distance    0
tip_amount       0
total_amount     0
dtype: int64

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       float32
 1   trip_distance  float32
 2   tip_amount     float32
 3   total_amount   float32
dtypes: float32(4)
memory usage: 97.7 MB

In [62]:
df['VendorID'] = df['VendorID'].astype(np.int8)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6405008 entries, 0 to 6405007
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   VendorID       int8
 1   trip_distance  float32
 2   tip_amount     float32
 3   total_amount   float32
dtypes: float32(3), int8(1)
memory usage: 79.4 MB

In [64]:
# 17.3

In [67]:
df = pd.read_csv(
    'data/nyc_taxi_2020-01.csv',
    usecols=['VendorID', 'trip_distance', 'tip_amount', 'total_amount'],
    dtype={'VendorID': np.float32, 'trip_distance': np.float32, 'tip_amount': np.float32, 'total_amount': np.float32}
)
df.memory_usage().sum()

np.int64(102480260)

In [68]:
df = pd.read_csv(
    'data/nyc_taxi_2020-01.csv',
    usecols=['VendorID', 'trip_distance', 'tip_amount', 'total_amount'],
    dtype={'VendorID': np.float32}
)
df.memory_usage().sum()

np.int64(179340356)