In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(
    data=[
        {'product_id': 23, 'name': 'computer',       'wholesale_price': 500, 'retail_price': 1000, 'sales': 100},
        {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 1000},
        {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 500},
        {'product_id': 15, 'name': 'banana',         'wholesale_price': 0.5, 'retail_price': 1,    'sales': 200},
        {'product_id': 87, 'name': 'sandwich',       'wholesale_price': 3.0, 'retail_price': 5,    'sales': 300},
    ]
)
df

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [7]:
((df['retail_price'] - df['wholesale_price']) * df['sales']).sum()

np.float64(110700.0)

In [8]:
# 8.1

In [12]:
df.loc[df['retail_price'] > 2 * df['wholesale_price']]['name']

1    Python Workout
2    Pandas Workout
Name: name, dtype: object

In [13]:
# 8.2

In [14]:
def get_category(name):
    if name == 'computer':
        return 'computers'
    elif name in ('banana', 'sandwich'):
        return 'food'
    else:
        return 'books'

In [16]:
df['category'] = df['name'].apply(get_category)

In [17]:
df

   product_id            name  wholesale_price  retail_price  sales   category
0          23        computer            500.0          1000    100  computers
1          96  Python Workout             35.0            75   1000      books
2          97  Pandas Workout             35.0            75    500      books
3          15          banana              0.5             1    200       food
4          87        sandwich              3.0             5    300       food

In [25]:
df['profit'] = (df['retail_price'] - df['wholesale_price']) * df['sales']
df

,product_id,name,wholesale_price,retail_price,sales,category,profit
0,23,computer,500.0,1000,100,computers,50000.0
1,96,Python Workout,35.0,75,1000,books,40000.0
2,97,Pandas Workout,35.0,75,500,books,20000.0
3,15,banana,0.5,1,200,food,100.0
4,87,sandwich,3.0,5,300,food,600.0

In [26]:
cats = df.groupby('category')

In [27]:
cats['profit'].sum()

category
books        60000.0
computers    50000.0
food           700.0
Name: profit, dtype: float64

In [28]:
# 8.3

In [29]:
((df['retail_price'] - df['wholesale_price'] * 0.7) * df['sales']).sum()

np.float64(141750.0)