In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    'data/sat-scores.csv',
    usecols=['Year', 'State.Code', 'Total.Math', 'Total.Test-takers', 'Total.Verbal']
)
df

     Year State.Code  Total.Math  Total.Test-takers  Total.Verbal
0    2005         AL         559               3985           567
1    2005         AK         519               3996           523
2    2005         AZ         530              18184           526
3    2005         AR         552               1600           563
4    2005         CA         522             186552           504
..    ...        ...         ...                ...           ...
572  2015         VA         517              59621           518
573  2015         WA         511              44423           502
574  2015         WV         500               2501           509
575  2015         WI         606               2277           591
576  2015         WY         587                181           588

[577 rows x 5 columns]

In [3]:
df = df.set_index(keys=['Year', 'State.Code']).sort_index()
df

                 Total.Math  Total.Test-takers  Total.Verbal
Year State.Code
2005 AK                 519               3996           523
     AL                 559               3985           567
     AR                 552               1600           563
     AZ                 530              18184           526
     CA                 522             186552           504
...                     ...                ...           ...
2015 VT                 524               4564           522
     WA                 511              44423           502
     WI                 606               2277           591
     WV                 500               2501           509
     WY                 587                181           588

[577 rows x 3 columns]

In [6]:
df.loc[(2005,), 'Total.Test-takers'].sum()

np.int64(1344824)

In [10]:
df.loc[(2010, ['NY', 'NJ', 'MA', 'IL']), 'Total.Math'].mean()

np.float64(535.25)

In [15]:
df.loc[(slice(2012, 2015), ['AZ', 'CA', 'TX']), 'Total.Verbal'].mean()

np.float64(497.3333333333333)

In [16]:
# 22.1

In [18]:
df.loc[(slice(None), ['FL', 'IN', 'ID']), ['Total.Math', 'Total.Verbal']].mean()

Total.Math      507.090909
Total.Verbal    504.606061
dtype: float64

In [19]:
# 22.2

In [20]:
df['Total.Verbal'].idxmax()

(np.int64(2013), 'ND')

In [21]:
# 22.3

In [24]:
df.loc[(2005), 'Total.Math'].mean()

np.float64(535.6538461538462)

In [25]:
df.loc[(2015), 'Total.Math'].mean()

np.float64(533.0943396226415)

In [26]:
df.loc[(2005), 'Total.Math'].mean() - df.loc[(2015), 'Total.Math'].mean()

np.float64(2.559506531204647)