In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    data=[
        {'product_id': 23, 'name': 'computer',       'wholesale_price': 500, 'retail_price': 1000, 'sales': 100},
        {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 1000},
        {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 500},
        {'product_id': 15, 'name': 'banana',         'wholesale_price': 0.5, 'retail_price': 1,    'sales': 200},
        {'product_id': 87, 'name': 'sandwich',       'wholesale_price': 3.0, 'retail_price': 5,    'sales': 300},
    ]
)
df1

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [3]:
df2 = pd.DataFrame(
    data=[
        {'product_id': 24, 'name': 'phone', 'wholesale_price': 200, 'retail_price': 500},
        {'product_id': 16, 'name': 'apple', 'wholesale_price': 0.5, 'retail_price': 1},
        {'product_id': 17, 'name': 'pear',  'wholesale_price': 0.6, 'retail_price': 1.2},
    ]
)
df2

   product_id   name  wholesale_price  retail_price
0          24  phone            200.0         500.0
1          16  apple              0.5           1.0
2          17   pear              0.6           1.2

In [4]:
df = pd.concat([df1, df2], ignore_index=True)
df

   product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0     NaN
6          16           apple              0.5           1.0     NaN
7          17            pear              0.6           1.2     NaN

In [7]:
df.loc[df['sales'].isnull(), 'sales'] = [100, 200, 75]

In [8]:
df

   product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0   100.0
6          16           apple              0.5           1.0   200.0
7          17            pear              0.6           1.2    75.0

In [9]:
((df['retail_price'] - df['wholesale_price']) * df['sales']).sum()

np.float64(140845.0)

In [10]:
# 10.1

In [11]:
df

   product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0   100.0
6          16           apple              0.5           1.0   200.0
7          17            pear              0.6           1.2    75.0

In [15]:
df.loc[8] = [99, 'persimon', 2, 4.5, 1]
df

   product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0   100.0
6          16           apple              0.5           1.0   200.0
7          17            pear              0.6           1.2    75.0
8          99        persimon              2.0           4.5     1.0

In [14]:
# 10.2

In [16]:
def get_department(name):
    if name in ('computer', 'phone'):
        return 'electronics'
    elif 'Workout' in name:
        return 'books'
    else:
        return 'food'

In [17]:
df['department'] = df['name'].apply(get_department)
df

,product_id,name,wholesale_price,retail_price,sales,department
0,23,computer,500.0,1000.0,100.0,electronics
1,96,Python Workout,35.0,75.0,1000.0,books
2,97,Pandas Workout,35.0,75.0,500.0,books
3,15,banana,0.5,1.0,200.0,food
4,87,sandwich,3.0,5.0,300.0,food
5,24,phone,200.0,500.0,100.0,electronics
6,16,apple,0.5,1.0,200.0,food
7,17,pear,0.6,1.2,75.0,food
8,99,persimon,2.0,4.5,1.0,food

In [18]:
df['current_net'] = (df['retail_price'] - df['wholesale_price']) * df['sales']
df

,product_id,name,wholesale_price,retail_price,sales,department,current_net
0,23,computer,500.0,1000.0,100.0,electronics,50000.0
1,96,Python Workout,35.0,75.0,1000.0,books,40000.0
2,97,Pandas Workout,35.0,75.0,500.0,books,20000.0
3,15,banana,0.5,1.0,200.0,food,100.0
4,87,sandwich,3.0,5.0,300.0,food,600.0
5,24,phone,200.0,500.0,100.0,electronics,30000.0
6,16,apple,0.5,1.0,200.0,food,100.0
7,17,pear,0.6,1.2,75.0,food,45.0
8,99,persimon,2.0,4.5,1.0,food,2.5

In [19]:
dep = df.groupby('department')

In [20]:
dep['current_net'].sum()

department
books          60000.0
electronics    80000.0
food             847.5
Name: current_net, dtype: float64

In [22]:
df.query('department == "electronics"')['current_net'].describe()

count        2.000000
mean     40000.000000
std      14142.135624
min      30000.000000
25%      35000.000000
50%      40000.000000
75%      45000.000000
max      50000.000000
Name: current_net, dtype: float64

In [23]:
# 10.3

In [24]:
df.query('department == "food"')['current_net'].describe()

count      5.000000
mean     169.500000
std      244.120872
min        2.500000
25%       45.000000
50%      100.000000
75%      100.000000
max      600.000000
Name: current_net, dtype: float64