In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv(
    'data/nyc-parking-violations-2020.csv',
    low_memory=False
)

df.head()

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1477633194,J58JKX,NJ,PAS,05/08/1972 12:00:00 AM,16,SDN,HONDA,P,8730,...,BK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
1,1449715424,KRE6058,PA,PAS,08/29/1977 12:00:00 AM,98,SUBN,ME/BE,P,86530,...,BLK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
2,1455779155,444326R,NJ,PAS,10/03/1988 12:00:00 AM,20,SDN,LEXUS,P,27030,...,BLACK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
3,1458800908,F728330,OH,PAS,01/03/1990 12:00:00 AM,21,SDN,CHEVR,P,33030,...,NaN,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
4,1466038676,FMY9090,NY,PAS,02/14/1990 12:00:00 AM,21,SUBN,JEEP,S,45130,...,GREY,0.0,2015,-,0,NaN,NaN,NaN,NaN,NaN

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12495734 entries, 0 to 12495733
Data columns (total 43 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Summons Number                     int64
 1   Plate ID                           object
 2   Registration State                 object
 3   Plate Type                         object
 4   Issue Date                         object
 5   Violation Code                     int64
 6   Vehicle Body Type                  object
 7   Vehicle Make                       object
 8   Issuing Agency                     object
 9   Street Code1                       int64
 10  Street Code2                       int64
 11  Street Code3                       int64
 12  Vehicle Expiration Date            int64
 13  Violation Location                 float64
 14  Violation Precinct                 int64
 15  Issuer Precinct                    int64
 16  Issuer Code                        int64
 17  Issuer Command                     object
 18  Issuer Squad                       object
 19  Violation Time                     object
 20  Time First Observed                object
 21  Violation County                   object
 22  Violation In Front Of Or Opposite  object
 23  House Number                       object
 24  Street Name                        object
 25  Intersecting Street                object
 26  Date First Observed                int64
 27  Law Section                        int64
 28  Sub Division                       object
 29  Violation Legal Code               object
 30  Days Parking In Effect             object
 31  From Hours In Effect               object
 32  To Hours In Effect                 object
 33  Vehicle Color                      object
 34  Unregistered Vehicle?              float64
 35  Vehicle Year                       int64
 36  Meter Number                       object
 37  Feet From Curb                     int64
 38  Violation Post Code                object
 39  Violation Description              object
 40  No Standing or Stopping Violation  float64
 41  Hydrant Violation                  float64
 42  Double Parking Violation           float64
dtypes: float64(5), int64(13), object(25)
memory usage: 4.0+ GB

In [30]:
print(f'{df.memory_usage().sum():,}')

4,298,532,628

In [31]:
cols = [
    'Plate ID',
    'Registration State',
    'Vehicle Make',
    'Vehicle Color',
    'Vehicle Body Type',
    'Violation Time',
    'Street Name',
    'Violation Legal Code',
]

In [32]:
for col in cols:
    df[col] = df[col].astype('category')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12495734 entries, 0 to 12495733
Data columns (total 43 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Summons Number                     int64
 1   Plate ID                           category
 2   Registration State                 category
 3   Plate Type                         object
 4   Issue Date                         object
 5   Violation Code                     int64
 6   Vehicle Body Type                  category
 7   Vehicle Make                       category
 8   Issuing Agency                     object
 9   Street Code1                       int64
 10  Street Code2                       int64
 11  Street Code3                       int64
 12  Vehicle Expiration Date            int64
 13  Violation Location                 float64
 14  Violation Precinct                 int64
 15  Issuer Precinct                    int64
 16  Issuer Code                        int64
 17  Issuer Command                     object
 18  Issuer Squad                       object
 19  Violation Time                     category
 20  Time First Observed                object
 21  Violation County                   object
 22  Violation In Front Of Or Opposite  object
 23  House Number                       object
 24  Street Name                        category
 25  Intersecting Street                object
 26  Date First Observed                int64
 27  Law Section                        int64
 28  Sub Division                       object
 29  Violation Legal Code               category
 30  Days Parking In Effect             object
 31  From Hours In Effect               object
 32  To Hours In Effect                 object
 33  Vehicle Color                      category
 34  Unregistered Vehicle?              float64
 35  Vehicle Year                       int64
 36  Meter Number                       object
 37  Feet From Curb                     int64
 38  Violation Post Code                object
 39  Violation Description              object
 40  No Standing or Stopping Violation  float64
 41  Hydrant Violation                  float64
 42  Double Parking Violation           float64
dtypes: category(8), float64(5), int64(13), object(17)
memory usage: 3.6+ GB

In [34]:
other_objects = list(df.select_dtypes(include=['object']).columns)

In [35]:
other_objects

['Plate Type',
 'Issue Date',
 'Issuing Agency',
 'Issuer Command',
 'Issuer Squad',
 'Time First Observed',
 'Violation County',
 'Violation In Front Of Or Opposite',
 'House Number',
 'Intersecting Street',
 'Sub Division',
 'Days Parking In Effect',
 'From Hours In Effect',
 'To Hours In Effect',
 'Meter Number',
 'Violation Post Code',
 'Violation Description']

In [36]:
other_objects.remove('Issue Date')
other_objects.remove('Time First Observed')

In [37]:
other_objects

['Plate Type',
 'Issuing Agency',
 'Issuer Command',
 'Issuer Squad',
 'Violation County',
 'Violation In Front Of Or Opposite',
 'House Number',
 'Intersecting Street',
 'Sub Division',
 'Days Parking In Effect',
 'From Hours In Effect',
 'To Hours In Effect',
 'Meter Number',
 'Violation Post Code',
 'Violation Description']

In [38]:
for col in other_objects:
    df[col] = df[col].astype('category')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12495734 entries, 0 to 12495733
Data columns (total 43 columns):
 #   Column                             Dtype
---  ------                             -----
 0   Summons Number                     int64
 1   Plate ID                           category
 2   Registration State                 category
 3   Plate Type                         category
 4   Issue Date                         object
 5   Violation Code                     int64
 6   Vehicle Body Type                  category
 7   Vehicle Make                       category
 8   Issuing Agency                     category
 9   Street Code1                       int64
 10  Street Code2                       int64
 11  Street Code3                       int64
 12  Vehicle Expiration Date            int64
 13  Violation Location                 float64
 14  Violation Precinct                 int64
 15  Issuer Precinct                    int64
 16  Issuer Code                        int64
 17  Issuer Command                     category
 18  Issuer Squad                       category
 19  Violation Time                     category
 20  Time First Observed                object
 21  Violation County                   category
 22  Violation In Front Of Or Opposite  category
 23  House Number                       category
 24  Street Name                        category
 25  Intersecting Street                category
 26  Date First Observed                int64
 27  Law Section                        int64
 28  Sub Division                       category
 29  Violation Legal Code               category
 30  Days Parking In Effect             category
 31  From Hours In Effect               category
 32  To Hours In Effect                 category
 33  Vehicle Color                      category
 34  Unregistered Vehicle?              float64
 35  Vehicle Year                       int64
 36  Meter Number                       category
 37  Feet From Curb                     int64
 38  Violation Post Code                category
 39  Violation Description              category
 40  No Standing or Stopping Violation  float64
 41  Hydrant Violation                  float64
 42  Double Parking Violation           float64
dtypes: category(23), float64(5), int64(13), object(2)
memory usage: 2.5+ GB

In [40]:
print(f'{df.memory_usage().sum():,}')

2,737,878,342

In [41]:
# 48.1

In [45]:
df[list(cols)].nunique().sort_values()

Violation Legal Code          2
Registration State           68
Vehicle Body Type          1634
Violation Time             1828
Vehicle Color              1896
Vehicle Make               5210
Street Name               57757
Plate ID                3245467
dtype: int64

In [46]:
len(df)

12495734

In [47]:
# 48.2

In [48]:
# Задание без расчета

In [49]:
# 48.3

In [50]:
df1 = df.iloc[:10 ** 4]

In [51]:
df1

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,1477633194,J58JKX,NJ,PAS,05/08/1972 12:00:00 AM,16,SDN,HONDA,P,8730,...,BK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
1,1449715424,KRE6058,PA,PAS,08/29/1977 12:00:00 AM,98,SUBN,ME/BE,P,86530,...,BLK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
2,1455779155,444326R,NJ,PAS,10/03/1988 12:00:00 AM,20,SDN,LEXUS,P,27030,...,BLACK,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
3,1458800908,F728330,OH,PAS,01/03/1990 12:00:00 AM,21,SDN,CHEVR,P,33030,...,NaN,0.0,0,-,0,NaN,NaN,NaN,NaN,NaN
4,1466038676,FMY9090,NY,PAS,02/14/1990 12:00:00 AM,21,SUBN,JEEP,S,45130,...,GREY,0.0,2015,-,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,4011347061,T771775C,NY,OMT,05/30/2019 12:00:00 AM,5,4DSD,TOYOT,V,0,...,BK,NaN,2013,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9996,4011347048,T733113C,NY,OMT,05/30/2019 12:00:00 AM,5,SUBN,TOYOT,V,0,...,BK,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9997,4011342671,T720744C,NY,OMT,05/30/2019 12:00:00 AM,5,4DSD,TOYOT,V,0,...,GY,NaN,2011,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9998,4011342660,T732531C,NY,OMT,05/30/2019 12:00:00 AM,5,4DSD,HONDA,V,0,...,RD,NaN,2017,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
9999,4011342580,XBTW76,NJ,PAS,05/30/2019 12:00:00 AM,5,VAN,ISUZU,V,0,...,WHT,NaN,2015,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN

In [55]:
df1.dtypes

Summons Number                          int64
Plate ID                             category
Registration State                   category
Plate Type                           category
Issue Date                             object
Violation Code                          int64
Vehicle Body Type                    category
Vehicle Make                         category
Issuing Agency                       category
Street Code1                            int64
Street Code2                            int64
Street Code3                            int64
Vehicle Expiration Date                 int64
Violation Location                    float64
Violation Precinct                      int64
Issuer Precinct                         int64
Issuer Code                             int64
Issuer Command                       category
Issuer Squad                         category
Violation Time                       category
Time First Observed                    object
Violation County                     category
Violation In Front Of Or Opposite    category
House Number                         category
Street Name                          category
Intersecting Street                  category
Date First Observed                     int64
Law Section                             int64
Sub Division                         category
Violation Legal Code                 category
Days Parking In Effect               category
From Hours In Effect                 category
To Hours In Effect                   category
Vehicle Color                        category
Unregistered Vehicle?                 float64
Vehicle Year                            int64
Meter Number                         category
Feet From Curb                          int64
Violation Post Code                  category
Violation Description                category
No Standing or Stopping Violation     float64
Hydrant Violation                     float64
Double Parking Violation              float64
dtype: object

In [57]:
pd.concat(objs=[(df1.count() / df1.nunique()).sort_values(ascending=False), df1.dtypes], axis=1).sort_values(by=[0], ascending=[False])

                                             0         1
Violation Description              5615.000000  category
Violation Legal Code               5615.000000  category
Law Section                        3333.333333     int64
Unregistered Vehicle?              2169.000000   float64
Violation County                   1086.333333  category
Issuing Agency                      909.090909  category
Feet From Curb                      833.333333     int64
Violation In Front Of Or Opposite   796.800000  category
Date First Observed                 400.000000     int64
Plate Type                          344.827586  category
Vehicle Year                        270.270270     int64
Issuer Squad                        257.941176  category
Sub Division                        196.039216  category
Registration State                  192.307692  category
Violation Code                      175.438596     int64
Days Parking In Effect              122.181818  category
Violation Precinct                  112.359551     int64
Vehicle Body Type                   100.469388  category
From Hours In Effect                 92.583333  category
Vehicle Make                         83.033613  category
To Hours In Effect                   81.292683  category
Issuer Precinct                      77.519380     int64
Vehicle Color                        76.672131  category
Violation Post Code                  73.833333  category
Violation Location                   47.465909   float64
Meter Number                         30.890411  category
Issuer Command                       17.400794  category
Issue Date                           14.326648    object
Intersecting Street                  10.946996  category
Street Code3                          8.944544     int64
Street Code1                          8.944544     int64
Street Code2                          8.857396     int64
Issuer Code                           8.389262     int64
Violation Time                        7.642966  category
Vehicle Expiration Date               7.530120     int64
Street Name                           5.551973  category
House Number                          2.449598  category
Time First Observed                   1.225166    object
Plate ID                              1.045260  category
Summons Number                        1.000000     int64
No Standing or Stopping Violation          NaN   float64
Hydrant Violation                          NaN   float64
Double Parking Violation                   NaN   float64

In [60]:
df1['Law Section'].nunique()

3

In [62]:
df1.loc[:, 'Law Section'] = df1['Law Section'].astype('category')

In [65]:
df1.dtypes.loc['Law Section']

CategoricalDtype(categories=[0, 408, 1111], ordered=False, categories_dtype=int64)