In [3]:
import numpy as np
import pandas as pd
import time

In [2]:
df = pd.read_csv(
    'data/nyc_taxi_2019-07.csv',
    usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
    parse_dates=['tpep_pickup_datetime']
)

df

        tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0        2019-07-01 00:51:04              1.0           0.00          4.94
1        2019-07-01 00:46:04              1.0           4.16         20.30
2        2019-07-01 00:25:09              1.0          18.80         70.67
3        2019-07-01 00:33:32              1.0          18.46         66.36
4        2019-07-01 00:00:55              0.0           1.70         15.30
...                      ...              ...            ...           ...
6310414  2019-07-29 16:34:53              NaN           3.86         29.00
6310415  2019-07-29 16:07:57              NaN          15.48         54.43
6310416  2019-07-29 16:01:31              NaN          12.92         65.40
6310417  2019-07-29 16:58:00              NaN           7.12         43.00
6310418  2019-07-29 16:16:00              NaN           1.77         22.15

[6310419 rows x 4 columns]

In [8]:
df['tpep_pickup_datetime'] = df['tpep_pickup_datetime'].dt.strftime('%d/%m/%y %Hh:%Mm:%Ss')

In [9]:
df.head()

   tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0  01/07/19 00h:51m:04s              1.0           0.00          4.94
1  01/07/19 00h:46m:04s              1.0           4.16         20.30
2  01/07/19 00h:25m:09s              1.0          18.80         70.67
3  01/07/19 00h:33m:32s              1.0          18.46         66.36
4  01/07/19 00h:00m:55s              0.0           1.70         15.30

In [10]:
df.to_csv('task_40.csv', sep='\t')

In [17]:
df1 = pd.read_csv(
    'task_40.csv',
    sep='\t',
    usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
    parse_dates=['tpep_pickup_datetime'],
    date_format='%d/%m/%y %Hh:%Mm:%Ss'
)

df1

        tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0        2019-07-01 00:51:04              1.0           0.00          4.94
1        2019-07-01 00:46:04              1.0           4.16         20.30
2        2019-07-01 00:25:09              1.0          18.80         70.67
3        2019-07-01 00:33:32              1.0          18.46         66.36
4        2019-07-01 00:00:55              0.0           1.70         15.30
...                      ...              ...            ...           ...
6310414  2019-07-29 16:34:53              NaN           3.86         29.00
6310415  2019-07-29 16:07:57              NaN          15.48         54.43
6310416  2019-07-29 16:01:31              NaN          12.92         65.40
6310417  2019-07-29 16:58:00              NaN           7.12         43.00
6310418  2019-07-29 16:16:00              NaN           1.77         22.15

[6310419 rows x 4 columns]

In [18]:
df1.dtypes

tpep_pickup_datetime    datetime64[ns]
passenger_count                float64
trip_distance                  float64
total_amount                   float64
dtype: object

In [19]:
pd.to_datetime(df1['tpep_pickup_datetime'], format='%d/%m/%y %Hh:%Mm:%Ss')

0         2019-07-01 00:51:04
1         2019-07-01 00:46:04
2         2019-07-01 00:25:09
3         2019-07-01 00:33:32
4         2019-07-01 00:00:55
                  ...
6310414   2019-07-29 16:34:53
6310415   2019-07-29 16:07:57
6310416   2019-07-29 16:01:31
6310417   2019-07-29 16:58:00
6310418   2019-07-29 16:16:00
Name: tpep_pickup_datetime, Length: 6310419, dtype: datetime64[ns]

In [20]:
df = pd.read_csv(
    'data/nyc_taxi_2019-07.csv',
    usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
    parse_dates=['tpep_pickup_datetime']
)

df

        tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0        2019-07-01 00:51:04              1.0           0.00          4.94
1        2019-07-01 00:46:04              1.0           4.16         20.30
2        2019-07-01 00:25:09              1.0          18.80         70.67
3        2019-07-01 00:33:32              1.0          18.46         66.36
4        2019-07-01 00:00:55              0.0           1.70         15.30
...                      ...              ...            ...           ...
6310414  2019-07-29 16:34:53              NaN           3.86         29.00
6310415  2019-07-29 16:07:57              NaN          15.48         54.43
6310416  2019-07-29 16:01:31              NaN          12.92         65.40
6310417  2019-07-29 16:58:00              NaN           7.12         43.00
6310418  2019-07-29 16:16:00              NaN           1.77         22.15

[6310419 rows x 4 columns]

In [22]:
df.to_csv('task_40_v2.csv', sep='\t', date_format='%d/%m/%y %Hh:%Mm:%Ss', index=False)

In [23]:
# 40.1

In [24]:
df = pd.read_csv(
    'data/nyc_taxi_2019-07.csv',
    usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
    parse_dates=['tpep_pickup_datetime']
)

df

        tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0        2019-07-01 00:51:04              1.0           0.00          4.94
1        2019-07-01 00:46:04              1.0           4.16         20.30
2        2019-07-01 00:25:09              1.0          18.80         70.67
3        2019-07-01 00:33:32              1.0          18.46         66.36
4        2019-07-01 00:00:55              0.0           1.70         15.30
...                      ...              ...            ...           ...
6310414  2019-07-29 16:34:53              NaN           3.86         29.00
6310415  2019-07-29 16:07:57              NaN          15.48         54.43
6310416  2019-07-29 16:01:31              NaN          12.92         65.40
6310417  2019-07-29 16:58:00              NaN           7.12         43.00
6310418  2019-07-29 16:16:00              NaN           1.77         22.15

[6310419 rows x 4 columns]

In [26]:
df['tpep_pickup_datetime'].astype(int)

0          1561942264000000000
1          1561941964000000000
2          1561940709000000000
3          1561941212000000000
4          1561939255000000000
                  ...
6310414    1564418093000000000
6310415    1564416477000000000
6310416    1564416091000000000
6310417    1564419480000000000
6310418    1564416960000000000
Name: tpep_pickup_datetime, Length: 6310419, dtype: int64

In [27]:
# 40.2

In [28]:
df = pd.read_csv(
    'data/nyc_taxi_2019-07.csv',
    usecols=['tpep_pickup_datetime', 'passenger_count', 'trip_distance', 'total_amount'],
    # parse_dates=['tpep_pickup_datetime']
)

df

        tpep_pickup_datetime  passenger_count  trip_distance  total_amount
0        2019-07-01 00:51:04              1.0           0.00          4.94
1        2019-07-01 00:46:04              1.0           4.16         20.30
2        2019-07-01 00:25:09              1.0          18.80         70.67
3        2019-07-01 00:33:32              1.0          18.46         66.36
4        2019-07-01 00:00:55              0.0           1.70         15.30
...                      ...              ...            ...           ...
6310414  2019-07-29 16:34:53              NaN           3.86         29.00
6310415  2019-07-29 16:07:57              NaN          15.48         54.43
6310416  2019-07-29 16:01:31              NaN          12.92         65.40
6310417  2019-07-29 16:58:00              NaN           7.12         43.00
6310418  2019-07-29 16:16:00              NaN           1.77         22.15

[6310419 rows x 4 columns]

In [29]:
df.dtypes

tpep_pickup_datetime     object
passenger_count         float64
trip_distance           float64
total_amount            float64
dtype: object

In [30]:
pd.to_datetime(df['tpep_pickup_datetime'])

0         2019-07-01 00:51:04
1         2019-07-01 00:46:04
2         2019-07-01 00:25:09
3         2019-07-01 00:33:32
4         2019-07-01 00:00:55
                  ...
6310414   2019-07-29 16:34:53
6310415   2019-07-29 16:07:57
6310416   2019-07-29 16:01:31
6310417   2019-07-29 16:58:00
6310418   2019-07-29 16:16:00
Name: tpep_pickup_datetime, Length: 6310419, dtype: datetime64[ns]

In [32]:
pd.to_datetime(df['tpep_pickup_datetime'])

0         2019-07-01 00:51:04
1         2019-07-01 00:46:04
2         2019-07-01 00:25:09
3         2019-07-01 00:33:32
4         2019-07-01 00:00:55
                  ...
6310414   2019-07-29 16:34:53
6310415   2019-07-29 16:07:57
6310416   2019-07-29 16:01:31
6310417   2019-07-29 16:58:00
6310418   2019-07-29 16:16:00
Name: tpep_pickup_datetime, Length: 6310419, dtype: datetime64[ns]