In [1]:
import numpy as np
import pandas as pd

In [6]:
import os

In [11]:
[file_name for file_name in os.listdir('data') if ('+' in file_name) or (',' in file_name)]

['san+francisco,ca.csv',
 'new+york,ny.csv',
 'springfield,ma.csv',
 'boston,ma.csv',
 'springfield,il.csv',
 'albany,ny.csv',
 'los+angeles,ca.csv',
 'chicago,il.csv']

In [29]:
df_tmp = pd.read_csv(
    'data/san+francisco,ca.csv',
    usecols=[0, 1, 2],
    names=['date_time', 'max_temp', 'min_temp'],
    header=0
)
df_tmp

               date_time  max_temp  min_temp
0    2018-12-11 00:00:00        13         8
1    2018-12-11 03:00:00        13         8
2    2018-12-11 06:00:00        13         8
3    2018-12-11 09:00:00        13         8
4    2018-12-11 12:00:00        13         8
..                   ...       ...       ...
723  2019-03-11 09:00:00        12         8
724  2019-03-11 12:00:00        12         8
725  2019-03-11 15:00:00        12         8
726  2019-03-11 18:00:00        12         8
727  2019-03-11 21:00:00        12         8

[728 rows x 3 columns]

In [36]:
dataframes = []
for file in [file_name for file_name in os.listdir('data') if ('+' in file_name) or (',' in file_name)]:
    full_name, extension = file.split('.')
    city, state = full_name.split(',')
    city = city.replace('+', ' ')
    df_tmp = pd.read_csv(
        'data/' + file,
        usecols=[0, 1, 2],
        names=['date_time', 'max_temp', 'min_temp'],
        header=0
    )
    df_tmp['city'] = city.title()
    df_tmp['state'] = state.upper()
    dataframes.append(df_tmp)

In [37]:
df = pd.concat(objs=dataframes, ignore_index=True)
df

                date_time  max_temp  min_temp           city state
0     2018-12-11 00:00:00        13         8  San Francisco    CA
1     2018-12-11 03:00:00        13         8  San Francisco    CA
2     2018-12-11 06:00:00        13         8  San Francisco    CA
3     2018-12-11 09:00:00        13         8  San Francisco    CA
4     2018-12-11 12:00:00        13         8  San Francisco    CA
...                   ...       ...       ...            ...   ...
5819  2019-03-11 09:00:00         3        -2        Chicago    IL
5820  2019-03-11 12:00:00         3        -2        Chicago    IL
5821  2019-03-11 15:00:00         3        -2        Chicago    IL
5822  2019-03-11 18:00:00         3        -2        Chicago    IL
5823  2019-03-11 21:00:00         3        -2        Chicago    IL

[5824 rows x 5 columns]

In [42]:
df.groupby(['state', 'city'])['date_time'].agg(['min', 'max'])

                                     min                  max
state city
CA    Los Angeles    2018-12-11 00:00:00  2019-03-11 21:00:00
      San Francisco  2018-12-11 00:00:00  2019-03-11 21:00:00
IL    Chicago        2018-12-11 00:00:00  2019-03-11 21:00:00
      Springfield    2018-12-11 00:00:00  2019-03-11 21:00:00
MA    Boston         2018-12-11 00:00:00  2019-03-11 21:00:00
      Springfield    2018-12-11 00:00:00  2019-03-11 21:00:00
NY    Albany         2018-12-11 00:00:00  2019-03-11 21:00:00
      New York       2018-12-11 00:00:00  2019-03-11 21:00:00

In [41]:
df.groupby(['state', 'city'])['date_time'].agg(['min', 'max']).nunique()

min    1
max    1
dtype: int64

In [43]:
df.groupby(['state', 'city'])['min_temp'].min()

state  city
CA     Los Angeles       4
       San Francisco     3
IL     Chicago         -28
       Springfield     -25
MA     Boston          -14
       Springfield     -20
NY     Albany          -19
       New York        -14
Name: min_temp, dtype: int64

In [40]:
df.groupby('state')['max_temp'].max()

state
CA    23
IL    16
MA    17
NY    15
Name: max_temp, dtype: int64

In [44]:
# 32.1

In [47]:
df.groupby(by=['state', 'city']).agg({'min_temp':'min', 'max_temp':'max'}).describe()

        min_temp   max_temp
count   8.000000   8.000000
mean  -14.125000  15.375000
std    11.897629   3.925648
min   -28.000000   9.000000
25%   -21.250000  14.500000
50%   -16.500000  15.000000
75%    -9.750000  16.250000
max     4.000000  23.000000

In [56]:
df.groupby(by=['state', 'city'])[['min_temp', 'max_temp']].apply(pd.DataFrame.describe)

                           min_temp    max_temp
state city
CA    Los Angeles count  728.000000  728.000000
                  mean    10.637363   17.054945
                  std      2.705200    2.708640
                  min      4.000000   12.000000
                  25%      9.000000   15.000000
...                             ...         ...
NY    New York    min    -14.000000  -12.000000
                  25%     -4.000000    2.000000
                  50%      0.000000    4.000000
                  75%      2.000000    7.000000
                  max     12.000000   15.000000

[64 rows x 2 columns]

In [57]:
df

                date_time  max_temp  min_temp           city state
0     2018-12-11 00:00:00        13         8  San Francisco    CA
1     2018-12-11 03:00:00        13         8  San Francisco    CA
2     2018-12-11 06:00:00        13         8  San Francisco    CA
3     2018-12-11 09:00:00        13         8  San Francisco    CA
4     2018-12-11 12:00:00        13         8  San Francisco    CA
...                   ...       ...       ...            ...   ...
5819  2019-03-11 09:00:00         3        -2        Chicago    IL
5820  2019-03-11 12:00:00         3        -2        Chicago    IL
5821  2019-03-11 15:00:00         3        -2        Chicago    IL
5822  2019-03-11 18:00:00         3        -2        Chicago    IL
5823  2019-03-11 21:00:00         3        -2        Chicago    IL

[5824 rows x 5 columns]

In [58]:
df['temp_diff'] = abs(df['max_temp'] - df['min_temp'])

In [59]:
df

                date_time  max_temp  min_temp           city state  temp_diff
0     2018-12-11 00:00:00        13         8  San Francisco    CA          5
1     2018-12-11 03:00:00        13         8  San Francisco    CA          5
2     2018-12-11 06:00:00        13         8  San Francisco    CA          5
3     2018-12-11 09:00:00        13         8  San Francisco    CA          5
4     2018-12-11 12:00:00        13         8  San Francisco    CA          5
...                   ...       ...       ...            ...   ...        ...
5819  2019-03-11 09:00:00         3        -2        Chicago    IL          5
5820  2019-03-11 12:00:00         3        -2        Chicago    IL          5
5821  2019-03-11 15:00:00         3        -2        Chicago    IL          5
5822  2019-03-11 18:00:00         3        -2        Chicago    IL          5
5823  2019-03-11 21:00:00         3        -2        Chicago    IL          5

[5824 rows x 6 columns]

In [60]:
df.groupby(by=['state', 'city'])['temp_diff'].mean()

state  city
CA     Los Angeles      6.417582
       San Francisco    4.351648
IL     Chicago          4.340659
       Springfield      6.934066
MA     Boston           6.010989
       Springfield      7.505495
NY     Albany           6.318681
       New York         5.263736
Name: temp_diff, dtype: float64