In [1]:
import numpy as np
import pandas as pd

In [118]:
df1 = pd.read_csv(
    'data/nyc_taxi_2019-01.csv',
    usecols=[
        'tpep_pickup_datetime',
        'passenger_count',
        'trip_distance',
        'fare_amount',
        'extra',
        'mta_tax',
        'tip_amount',
        'tolls_amount',
        'improvement_surcharge',
        'total_amount',
        'congestion_surcharge'
    ],
    parse_dates=['tpep_pickup_datetime']
)

df1

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2019-01-01 00:46:40,1,1.50,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,2019-01-01 00:59:47,1,2.60,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2018-12-21 13:48:30,3,0.00,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2018-11-28 15:52:25,5,0.00,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2018-11-28 15:56:57,5,0.00,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7667787,2019-01-31 23:57:36,1,4.79,18.0,0.5,0.5,3.86,0.0,0.3,23.16,0.0
7667788,2019-01-31 23:32:03,1,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667789,2019-01-31 23:36:36,1,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667790,2019-01-31 23:14:53,1,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0
7667791,2019-01-31 23:12:49,1,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0

In [119]:
df2 = pd.read_csv(
    'data/nyc_taxi_2019-07.csv',
    usecols=[
        'tpep_pickup_datetime',
        'passenger_count',
        'trip_distance',
        'fare_amount',
        'extra',
        'mta_tax',
        'tip_amount',
        'tolls_amount',
        'improvement_surcharge',
        'total_amount',
        'congestion_surcharge'
    ],
    parse_dates=['tpep_pickup_datetime']
)

df2

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2019-07-01 00:51:04,1.0,0.00,2.50,0.50,0.5,1.14,0.00,0.3,4.94,0.0
1,2019-07-01 00:46:04,1.0,4.16,16.50,0.50,0.5,0.00,0.00,0.3,20.30,2.5
2,2019-07-01 00:25:09,1.0,18.80,52.00,0.00,0.5,11.75,6.12,0.3,70.67,0.0
3,2019-07-01 00:33:32,1.0,18.46,52.00,0.00,0.5,11.06,0.00,0.3,66.36,2.5
4,2019-07-01 00:00:55,0.0,1.70,9.50,3.00,0.5,2.00,0.00,0.3,15.30,2.5
...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0

In [120]:
df = pd.concat(objs=[df1, df2], ignore_index=False, axis=0)
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN
...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0

In [121]:
df['pre_tip_amount'] = df['total_amount'] - df['tip_amount']

In [122]:
df['tip_percentage'] = df['tip_amount'] / df['pre_tip_amount']

In [123]:
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN,8.30,0.198795
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN,15.30,0.065359
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN,5.80,0.000000
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN,7.55,0.000000
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN,55.55,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0,29.00,0.000000
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0,54.43,0.000000
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0,65.40,0.000000
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0,43.00,0.000000
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0,22.15,0.000000

In [9]:
df['tip_percentage'].mean()

np.float64(0.1329827884629165)

In [61]:
(df['tip_percentage'] > 1).value_counts()

tip_percentage
False    13970156
True         8055
Name: count, dtype: int64

In [63]:
df.loc[(df['tip_amount'] > df['pre_tip_amount']) & (df['pre_tip_amount'] > 0)]

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage,date_iso_str
119,2019-01-01 00:19:39,2.0,0.60,13.0,0.5,0.5,25.00,0.0,0.3,39.30,NaN,14.3,1.748252,2019-01-01
299,2019-01-01 00:24:24,2.0,1.13,5.5,0.5,0.5,13.20,0.0,0.3,20.00,NaN,6.8,1.941176,2019-01-01
947,2019-01-01 00:30:57,2.0,0.00,2.5,0.5,0.5,8.00,0.0,0.3,11.80,NaN,3.8,2.105263,2019-01-01
1131,2019-01-01 00:36:12,2.0,1.00,7.0,0.5,0.5,20.00,0.0,0.3,28.30,NaN,8.3,2.409639,2019-01-01
1354,2019-01-01 00:30:10,2.0,0.80,7.0,0.5,0.5,50.00,0.0,0.3,58.30,NaN,8.3,6.024096,2019-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6268731,2019-07-31 23:02:46,1.0,0.00,2.5,0.5,0.5,33.00,0.0,0.3,36.80,0.0,3.8,8.684211,2019-07-31
6274518,2019-07-31 23:57:16,1.0,14.10,41.0,0.5,0.5,55.55,0.0,0.3,97.85,0.0,42.3,1.313239,2019-07-31
6274752,2019-07-31 23:45:13,1.0,0.60,2.5,3.0,0.5,19.70,0.0,0.3,26.00,2.5,6.3,3.126984,2019-07-31
6275049,2019-07-31 23:35:42,1.0,3.30,2.5,3.0,0.5,9.00,0.0,0.3,15.30,2.5,6.3,1.428571,2019-07-31
6275348,2019-07-31 23:00:43,1.0,0.00,2.5,0.5,0.5,4.00,0.0,0.3,7.80,0.0,3.8,1.052632,2019-07-31

In [64]:
df.groupby(by=[df['tpep_pickup_datetime'].dt.day_name()])['tip_percentage'].mean().sort_values(ascending=False).index[0]

'Thursday'

In [20]:
df['tpep_pickup_datetime'].dt.hour

0           0
1           0
2          13
3          15
4          15
           ..
6310414    16
6310415    16
6310416    16
6310417    16
6310418    16
Name: tpep_pickup_datetime, Length: 13978211, dtype: int32

In [65]:
df.groupby(by=[df['tpep_pickup_datetime'].dt.hour])['tip_percentage'].mean().sort_values(ascending=False).index[0]

np.int32(22)

In [23]:
df['tpep_pickup_datetime'].dt.month_name()

0           January
1           January
2          December
3          November
4          November
             ...
6310414        July
6310415        July
6310416        July
6310417        July
6310418        July
Name: tpep_pickup_datetime, Length: 13978211, dtype: object

In [66]:
df.groupby(by=[df['tpep_pickup_datetime'].dt.month_name()])['tip_percentage'].mean()

tpep_pickup_datetime
April        0.074877
August       0.158099
December     0.109367
February     0.132224
January      0.136958
July         0.128154
June         0.107354
March        0.148046
May          0.200000
November     0.046026
October      0.100000
September    0.141431
Name: tip_percentage, dtype: float64

In [28]:
df = df.set_index(keys=['tpep_pickup_datetime']).sort_index()

In [ ]:
df

In [29]:
df['tip_percentage'].idxmax()

Timestamp('2019-01-12 04:18:44')

In [40]:
df = df.reset_index()

In [41]:
df1 = df.groupby(by=[df['tpep_pickup_datetime'].dt.date]).apply(lambda df_: df_['tip_amount'].sum() / df_['pre_tip_amount'])

In [42]:
df1.index

MultiIndex([(2001-02-02,        0),
            (2002-02-02,        1),
            (2002-02-02,        2),
            (2002-02-02,        3),
            (2002-02-02,        4),
            (2002-02-02,        5),
            (2002-02-02,        6),
            (2002-02-02,        7),
            (2002-02-02,        8),
            (2002-02-02,        9),
            ...
            (2019-11-06, 13978201),
            (2019-11-06, 13978202),
            (2019-11-08, 13978203),
            (2019-11-08, 13978204),
            (2019-11-27, 13978205),
            (2019-12-18, 13978206),
            (2020-01-09, 13978207),
            (2020-01-09, 13978208),
            (2088-01-24, 13978209),
            (2088-01-24, 13978210)],
           names=['tpep_pickup_datetime', None], length=13978211)

In [50]:
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN,8.30,0.198795
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN,15.30,0.065359
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN,5.80,0.000000
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN,7.55,0.000000
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN,55.55,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0,29.00,0.000000
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0,54.43,0.000000
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0,65.40,0.000000
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0,43.00,0.000000
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0,22.15,0.000000

In [59]:
df.groupby(df['tpep_pickup_datetime'].dt.strftime('%Y-%m-%d')).apply(lambda df_: df_['tip_amount'].sum() / df_['pre_tip_amount'].sum())

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_5929/2597646846.py:1: RuntimeWarning: invalid value encountered in scalar divide
  df.groupby(df['tpep_pickup_datetime'].dt.strftime('%Y-%m-%d')).apply(lambda df_: df_['tip_amount'].sum() / df_['pre_tip_amount'].sum())

tpep_pickup_datetime
2001-02-02    0.000000
2002-02-02    0.000000
2003-01-01         NaN
2008-12-31    0.026406
2009-01-01    0.038931
                ...
2019-11-08    0.156743
2019-11-27    0.200000
2019-12-18    0.200000
2020-01-09    0.155414
2088-01-24    0.000000
Length: 110, dtype: float64

In [52]:
df['tpep_pickup_datetime'].dt.date

0          2019-01-01
1          2019-01-01
2          2018-12-21
3          2018-11-28
4          2018-11-28
              ...
6310414    2019-07-29
6310415    2019-07-29
6310416    2019-07-29
6310417    2019-07-29
6310418    2019-07-29
Name: tpep_pickup_datetime, Length: 13978211, dtype: object

In [55]:
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN,8.30,0.198795
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN,15.30,0.065359
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN,5.80,0.000000
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN,7.55,0.000000
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN,55.55,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0,29.00,0.000000
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0,54.43,0.000000
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0,65.40,0.000000
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0,43.00,0.000000
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0,22.15,0.000000

In [56]:
df['date_iso_str'] = df['tpep_pickup_datetime'].dt.strftime('%Y-%m-%d')

In [57]:
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage,date_iso_str
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN,8.30,0.198795,2019-01-01
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN,15.30,0.065359,2019-01-01
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN,5.80,0.000000,2018-12-21
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN,7.55,0.000000,2018-11-28
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN,55.55,0.000000,2018-11-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0,29.00,0.000000,2019-07-29
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0,54.43,0.000000,2019-07-29
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0,65.40,0.000000,2019-07-29
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0,43.00,0.000000,2019-07-29
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0,22.15,0.000000,2019-07-29

In [58]:
df.groupby(by=['date_iso_str']).apply(

date_iso_str
2001-02-02     1
2002-02-02     9
2003-01-01     2
2008-12-31    34
2009-01-01    82
              ..
2019-11-08     2
2019-11-27     1
2019-12-18     1
2020-01-09     2
2088-01-24     2
Name: date_iso_str, Length: 110, dtype: int64

In [67]:
df

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage,date_iso_str
0,2019-01-01 00:46:40,1.0,1.50,7.00,0.50,0.5,1.65,0.00,0.3,9.95,NaN,8.30,0.198795,2019-01-01
1,2019-01-01 00:59:47,1.0,2.60,14.00,0.50,0.5,1.00,0.00,0.3,16.30,NaN,15.30,0.065359,2019-01-01
2,2018-12-21 13:48:30,3.0,0.00,4.50,0.50,0.5,0.00,0.00,0.3,5.80,NaN,5.80,0.000000,2018-12-21
3,2018-11-28 15:52:25,5.0,0.00,3.50,0.50,0.5,0.00,0.00,0.3,7.55,NaN,7.55,0.000000,2018-11-28
4,2018-11-28 15:56:57,5.0,0.00,52.00,0.00,0.5,0.00,0.00,0.3,55.55,NaN,55.55,0.000000,2018-11-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310414,2019-07-29 16:34:53,NaN,3.86,19.83,2.75,0.0,0.00,6.12,0.3,29.00,0.0,29.00,0.000000,2019-07-29
6310415,2019-07-29 16:07:57,NaN,15.48,51.38,2.75,0.0,0.00,0.00,0.3,54.43,0.0,54.43,0.000000,2019-07-29
6310416,2019-07-29 16:01:31,NaN,12.92,62.35,2.75,0.0,0.00,0.00,0.3,65.40,0.0,65.40,0.000000,2019-07-29
6310417,2019-07-29 16:58:00,NaN,7.12,39.45,2.75,0.5,0.00,0.00,0.3,43.00,0.0,43.00,0.000000,2019-07-29
6310418,2019-07-29 16:16:00,NaN,1.77,18.60,2.75,0.5,0.00,0.00,0.3,22.15,0.0,22.15,0.000000,2019-07-29

In [68]:
df = df.set_index(keys=['tpep_pickup_datetime']).sort_index()

In [71]:
df.resample('1D')['tip_percentage'].mean().sort_values(ascending=False)

tpep_pickup_datetime
2019-02-13    0.358127
2019-02-25    0.250000
2019-08-20    0.241865
2019-08-10    0.200000
2019-05-20    0.200000
                ...
2088-01-19         NaN
2088-01-20         NaN
2088-01-21         NaN
2088-01-22         NaN
2088-01-23         NaN
Name: tip_percentage, Length: 31768, dtype: float64

In [72]:
# 42.1

In [74]:
df = df.reset_index()

In [78]:
df.loc[df['tip_amount'] > 0, 'tip_percentage'].mean()

np.float64(0.19579838412516462)

In [79]:
# 42.2

In [88]:
df['tpep_pickup_datetime'].dt.month_name().value_counts().iloc[2:].sum()

np.int64(728)

In [91]:
df['tpep_pickup_datetime'].dt.month_name().value_counts().iloc[2:].sum() / len(df) * 100

np.float64(0.005208105672464094)

In [92]:
df['tpep_pickup_datetime'].dt.month_name().value_counts().iloc[:2].sum() / len(df) * 100

np.float64(99.99479189432753)

In [97]:
df.loc[df['tpep_pickup_datetime'].dt.month.isin([1, 7])]

,tpep_pickup_datetime,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage,date_iso_str
10,2003-01-01 00:05:12,1.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,NaN,0.0,NaN,2003-01-01
11,2003-01-01 00:15:01,6.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,NaN,0.0,NaN,2003-01-01
46,2009-01-01 00:02:13,1.0,3.08,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,14.8,0.200000,2009-01-01
47,2009-01-01 00:03:15,2.0,17.20,46.5,2.5,0.5,11.56,8.0,0.3,69.36,0.0,57.8,0.200000,2009-01-01
48,2009-01-01 00:03:34,2.0,0.03,2.5,0.5,0.5,0.00,0.0,0.3,3.80,NaN,3.8,0.000000,2009-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13978144,2019-07-31 23:59:57,0.0,1.10,5.5,3.0,0.5,2.30,0.0,0.3,11.60,2.5,9.3,0.247312,2019-07-31
13978207,2020-01-09 04:16:07,1.0,1.60,14.0,0.0,0.5,4.32,0.0,0.3,21.62,2.5,17.3,0.249711,2020-01-09
13978208,2020-01-09 04:50:49,1.0,6.90,26.5,2.5,0.5,3.00,0.0,0.3,32.80,0.0,29.8,0.100671,2020-01-09
13978209,2088-01-24 00:15:42,1.0,0.63,4.5,0.0,0.5,0.00,0.0,0.3,5.30,NaN,5.3,0.000000,2088-01-24
13978210,2088-01-24 00:25:39,1.0,4.05,14.5,0.0,0.5,0.00,0.0,0.3,15.30,NaN,15.3,0.000000,2088-01-24

In [99]:
df1 = df.groupby(by=[df['tpep_pickup_datetime'].dt.year, df['tpep_pickup_datetime'].dt.month])['tpep_pickup_datetime'].count()

In [108]:
df1.loc[[(2019, 1), (2019, 7)]]

tpep_pickup_datetime  tpep_pickup_datetime
2019                  1                       7667255
                      7                       6310140
Name: tpep_pickup_datetime, dtype: int64

In [112]:
df1.sum() - df1.loc[[(2019, 1), (2019, 7)]].sum()

np.int64(816)

In [124]:
df = df.set_index(keys=['tpep_pickup_datetime']).sort_index()

In [125]:
df = pd.concat(objs=[df.loc['2019-01'], df.loc['2019-07']])
df

,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,pre_tip_amount,tip_percentage
tpep_pickup_datetime,,,,,,,,,,,,
2019-01-01 00:00:00,2.0,7.37,23.5,0.5,0.5,0.00,0.0,0.3,24.80,NaN,24.8,0.000000
2019-01-01 00:00:01,6.0,1.73,7.0,0.5,0.5,0.00,0.0,0.3,8.30,NaN,8.3,0.000000
2019-01-01 00:00:03,1.0,0.60,5.0,0.5,0.5,0.00,0.0,0.3,6.30,NaN,6.3,0.000000
2019-01-01 00:00:05,1.0,1.53,9.0,0.5,0.5,0.00,0.0,0.3,10.30,NaN,10.3,0.000000
2019-01-01 00:00:06,1.0,3.20,26.0,0.5,0.5,5.45,0.0,0.3,32.75,NaN,27.3,0.199634
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-07-31 23:59:51,1.0,2.46,11.0,0.5,0.5,2.96,0.0,0.3,17.76,2.5,14.8,0.200000
2019-07-31 23:59:52,2.0,6.20,20.5,0.5,0.5,6.50,0.0,0.3,28.30,0.0,21.8,0.298165
2019-07-31 23:59:55,1.0,1.26,6.0,0.5,0.5,1.96,0.0,0.3,11.76,2.5,9.8,0.200000
2019-07-31 23:59:56,1.0,1.20,6.0,3.0,0.5,2.45,0.0,0.3,12.25,2.5,9.8,0.250000
2019-07-31 23:59:57,0.0,1.10,5.5,3.0,0.5,2.30,0.0,0.3,11.60,2.5,9.3,0.247312

In [128]:
df.resample('1W')['tip_percentage'].mean().dropna().sort_values(ascending=False)

tpep_pickup_datetime
2019-02-03    0.141898
2019-01-27    0.138879
2019-01-20    0.138487
2019-01-13    0.137855
2019-08-04    0.131910
2019-07-14    0.130108
2019-07-21    0.130038
2019-07-28    0.129644
2019-01-06    0.126936
2019-07-07    0.119035
Name: tip_percentage, dtype: float64