In [1]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv(
    'data/celebrity_deaths_2016.csv',
    usecols=['dateofdeath', 'age'],
)
df

     dateofdeath age
0     2016-01-01  71
1     2016-01-01  74
2     2016-01-01  79
3     2016-01-01  45
4     2016-01-01  83
...          ...  ..
6538  2016-12-27  74
6539  2016-12-27  85
6540  2016-12-27  83
6541  2016-12-27  23
6542  2016-12-27  84

[6543 rows x 2 columns]

In [9]:
df.dtypes

dateofdeath    object
age            object
dtype: object

In [10]:
df['month'] = df['dateofdeath'].str.split('-').str.get(1).astype(np.int8)

In [11]:
df

     dateofdeath age  month
0     2016-01-01  71      1
1     2016-01-01  74      1
2     2016-01-01  79      1
3     2016-01-01  45      1
4     2016-01-01  83      1
...          ...  ..    ...
6538  2016-12-27  74     12
6539  2016-12-27  85     12
6540  2016-12-27  83     12
6541  2016-12-27  23     12
6542  2016-12-27  84     12

[6543 rows x 3 columns]

In [12]:
df = df.set_index(keys=['month'])
df

      dateofdeath age
month
1      2016-01-01  71
1      2016-01-01  74
1      2016-01-01  79
1      2016-01-01  45
1      2016-01-01  83
...           ...  ..
12     2016-12-27  74
12     2016-12-27  85
12     2016-12-27  83
12     2016-12-27  23
12     2016-12-27  84

[6543 rows x 2 columns]

In [13]:
df = df.sort_index()

In [14]:
df

      dateofdeath age
month
1      2016-01-01  71
1      2016-01-21  47
1      2016-01-21  87
1      2016-01-21  90
1      2016-01-21  73
...           ...  ..
12     2016-12-10  63
12     2016-12-10  20
12     2016-12-10  57
12     2016-12-10  78
12     2016-12-27  84

[6543 rows x 2 columns]

In [15]:
df['age'].value_counts()

age
88       236
86       236
85       225
87       225
90       223
        ...
 9192      1
110        1
116        1
 7374      1
 2930      1
Name: count, Length: 138, dtype: int64

In [29]:
df['age'].str.isdigit().astype(np.bool)

month
1     True
1     True
1     True
1     True
1     True
      ...
12    True
12    True
12    True
12    True
12    True
Name: age, Length: 6543, dtype: bool

In [30]:
df.loc[~(df['age'].str.isdigit().astype(np.bool)), 'age'] = np.nan

In [31]:
df.head()

      dateofdeath age
month
1      2016-01-01  71
1      2016-01-21  47
1      2016-01-21  87
1      2016-01-21  90
1      2016-01-21  73

In [32]:
df['age'].value_counts()

age
86     236
88     236
85     225
87     225
90     223
      ...
116      1
112      1
18       1
12       1
7        1
Name: count, Length: 104, dtype: int64

In [33]:
df['age'].describe()

count     6481
unique     104
top         86
freq       236
Name: age, dtype: object

In [34]:
df['age'] = df['age'].astype(np.int8)

ValueError: cannot convert float NaN to integer

In [35]:
df = df.dropna(subset=['age']).copy()

In [36]:
df['age'] = df['age'].astype(np.int8)

In [37]:
df

      dateofdeath  age
month
1      2016-01-01   71
1      2016-01-21   47
1      2016-01-21   87
1      2016-01-21   90
1      2016-01-21   73
...           ...  ...
12     2016-12-10   63
12     2016-12-10   20
12     2016-12-10   57
12     2016-12-10   78
12     2016-12-27   84

[6481 rows x 2 columns]

In [40]:
df.loc[2:7, 'age'].mean()

np.float64(77.17887409200968)

In [41]:
# 26.1

In [42]:
df = pd.read_csv(
    'data/celebrity_deaths_2016.csv',
    usecols=['dateofdeath', 'age'],
)
df

     dateofdeath age
0     2016-01-01  71
1     2016-01-01  74
2     2016-01-01  79
3     2016-01-01  45
4     2016-01-01  83
...          ...  ..
6538  2016-12-27  74
6539  2016-12-27  85
6540  2016-12-27  83
6541  2016-12-27  23
6542  2016-12-27  84

[6543 rows x 2 columns]

In [45]:
df[['year', 'month', 'day']] = df['dateofdeath'].str.split('-', expand=True)

In [46]:
df

     dateofdeath age  year month day
0     2016-01-01  71  2016    01  01
1     2016-01-01  74  2016    01  01
2     2016-01-01  79  2016    01  01
3     2016-01-01  45  2016    01  01
4     2016-01-01  83  2016    01  01
...          ...  ..   ...   ...  ..
6538  2016-12-27  74  2016    12  27
6539  2016-12-27  85  2016    12  27
6540  2016-12-27  83  2016    12  27
6541  2016-12-27  23  2016    12  27
6542  2016-12-27  84  2016    12  27

[6543 rows x 5 columns]

In [47]:
len(df) - df.count()

dateofdeath     0
age            27
year            0
month           0
day             0
dtype: int64

In [48]:
df = df.set_index(keys=['month', 'day']).sort_index()
df

          dateofdeath age  year
month day
01    01   2016-01-01  71  2016
      01   2016-01-01  74  2016
      01   2016-01-01  79  2016
      01   2016-01-01  45  2016
      01   2016-01-01  83  2016
...               ...  ..   ...
12    29   2016-12-29  83  2016
      29   2016-12-29  88  2016
      29   2016-12-29  88  2016
      29   2016-12-29  89  2016
      29   2016-12-29  53  2016

[6543 rows x 3 columns]

In [49]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df

          dateofdeath   age  year
month day
01    01   2016-01-01  71.0  2016
      01   2016-01-01  74.0  2016
      01   2016-01-01  79.0  2016
      01   2016-01-01  45.0  2016
      01   2016-01-01  83.0  2016
...               ...   ...   ...
12    29   2016-12-29  83.0  2016
      29   2016-12-29  88.0  2016
      29   2016-12-29  88.0  2016
      29   2016-12-29  89.0  2016
      29   2016-12-29  53.0  2016

[6543 rows x 3 columns]

In [50]:
len(df) - df.count()

dateofdeath     0
age            38
year            0
dtype: int64

In [51]:
df1 = df.loc[df['age'] < 120]
df1

          dateofdeath   age  year
month day
01    01   2016-01-01  71.0  2016
      01   2016-01-01  74.0  2016
      01   2016-01-01  79.0  2016
      01   2016-01-01  45.0  2016
      01   2016-01-01  83.0  2016
...               ...   ...   ...
12    29   2016-12-29  83.0  2016
      29   2016-12-29  88.0  2016
      29   2016-12-29  88.0  2016
      29   2016-12-29  89.0  2016
      29   2016-12-29  53.0  2016

[6481 rows x 3 columns]

In [53]:
df1.loc[('02', '15'):('07', '15'), 'age'].mean()

np.float64(77.05183037332367)

In [54]:
# 26.2

In [55]:
df = pd.read_csv(
    'data/celebrity_deaths_2016.csv',
    usecols=['dateofdeath', 'age', 'causeofdeath'],
)
df

     dateofdeath age                causeofdeath
0     2016-01-01  71                brain cancer
1     2016-01-01  74                      cancer
2     2016-01-01  79                      cancer
3     2016-01-01  45   complications of a stroke
4     2016-01-01  83               heart failure
...          ...  ..                         ...
6538  2016-12-27  74                         NaN
6539  2016-12-27  85                         NaN
6540  2016-12-27  83                         NaN
6541  2016-12-27  23                  euthanized
6542  2016-12-27  84                         NaN

[6543 rows x 3 columns]

In [56]:
df['causeofdeath'].value_counts()

causeofdeath
 cancer                                                248
 heart attack                                          125
 traffic collision                                      56
 lung cancer                                            51
 pneumonia                                              50
                                                      ...
 complications from accident                             1
 septic shock                                            1
 grenade explosion                                       1
 complications from esophageal cancer and pneumonia      1
euthanized                                               1
Name: count, Length: 361, dtype: int64

In [57]:
len(df) - df.count()

dateofdeath        0
age               27
causeofdeath    5008
dtype: int64

In [58]:
df.loc[df['causeofdeath'].isnull(), 'causeofdeath'] = 'unknown'

In [59]:
df['causeofdeath'].value_counts()

causeofdeath
unknown                                                5008
 cancer                                                 248
 heart attack                                           125
 traffic collision                                       56
 lung cancer                                             51
                                                       ...
 complications from accident                              1
 septic shock                                             1
 grenade explosion                                        1
 complications from esophageal cancer and pneumonia       1
euthanized                                                1
Name: count, Length: 362, dtype: int64

In [60]:
# 26.3

In [64]:
df.loc[df['causeofdeath'].str.contains('cancer'), 'causeofdeath'].value_counts().sum()

np.int64(529)