In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(
    'data/so_2021_survey_results.csv',
    usecols=['LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'Country', 'CompTotal']
)

df

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift
1,Netherlands,NaN,JavaScript;Python,NaN
2,Russian Federation,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust
3,Austria,NaN,JavaScript;TypeScript,JavaScript;TypeScript
4,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL
...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure
83435,Benin,200000.0,NaN,NaN
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...

In [6]:
df['LanguageHaveWorkedWith'].str.split(';').explode().value_counts()

LanguageHaveWorkedWith
JavaScript     53587
HTML/CSS       46259
Python         39792
SQL            38835
Java           29162
Node.js        27975
TypeScript     24909
C#             22984
Bash/Shell     22385
C++            20057
PHP            18130
C              17329
PowerShell      8871
Go              7879
Kotlin          6866
Rust            5799
Ruby            5569
Dart            4965
Assembly        4632
Swift           4204
R               4185
VBA             3847
Matlab          3846
Groovy          2479
Objective-C     2310
Scala           2148
Perl            2028
Haskell         1749
Delphi          1731
Clojure         1552
Elixir          1438
LISP            1096
Julia           1068
F#               804
Erlang           651
APL              536
Crystal          466
COBOL            437
Name: count, dtype: int64

In [7]:
df['LanguageHaveWorkedWith'].str.split(';').explode().value_counts().head(10)

LanguageHaveWorkedWith
JavaScript    53587
HTML/CSS      46259
Python        39792
SQL           38835
Java          29162
Node.js       27975
TypeScript    24909
C#            22984
Bash/Shell    22385
C++           20057
Name: count, dtype: int64

In [8]:
df['LanguageWantToWorkWith'].str.split(';').explode().value_counts()

LanguageWantToWorkWith
JavaScript     37008
Python         34929
HTML/CSS       29353
TypeScript     26905
SQL            26631
Node.js        24100
C#             17999
Java           17222
Rust           15865
Go             15788
C++            15249
Bash/Shell     14043
Kotlin         10691
C               9702
PHP             8852
Dart            7018
Swift           6353
Ruby            4942
PowerShell      4896
R               4015
Assembly        3578
Haskell         3453
Elixir          3374
Scala           3165
Julia           2445
Clojure         2413
F#              2157
Matlab          1562
LISP            1513
Objective-C     1400
Erlang          1379
Groovy          1177
Perl            1175
VBA             1069
Delphi           975
Crystal          790
APL              568
COBOL            309
Name: count, dtype: int64

In [9]:
worked = df['LanguageHaveWorkedWith'].str.split(';').explode().value_counts()

In [10]:
wanted = df['LanguageWantToWorkWith'].str.split(';').explode().value_counts()

In [12]:
wanted.index

Index(['JavaScript', 'Python', 'HTML/CSS', 'TypeScript', 'SQL', 'Node.js',
       'C#', 'Java', 'Rust', 'Go', 'C++', 'Bash/Shell', 'Kotlin', 'C', 'PHP',
       'Dart', 'Swift', 'Ruby', 'PowerShell', 'R', 'Assembly', 'Haskell',
       'Elixir', 'Scala', 'Julia', 'Clojure', 'F#', 'Matlab', 'LISP',
       'Objective-C', 'Erlang', 'Groovy', 'Perl', 'VBA', 'Delphi', 'Crystal',
       'APL', 'COBOL'],
      dtype='object', name='LanguageWantToWorkWith')

In [18]:
worked.to_frame().reset_index()

   LanguageHaveWorkedWith  count
0              JavaScript  53587
1                HTML/CSS  46259
2                  Python  39792
3                     SQL  38835
4                    Java  29162
5                 Node.js  27975
6              TypeScript  24909
7                      C#  22984
8              Bash/Shell  22385
9                     C++  20057
10                    PHP  18130
11                      C  17329
12             PowerShell   8871
13                     Go   7879
14                 Kotlin   6866
15                   Rust   5799
16                   Ruby   5569
17                   Dart   4965
18               Assembly   4632
19                  Swift   4204
20                      R   4185
21                    VBA   3847
22                 Matlab   3846
23                 Groovy   2479
24            Objective-C   2310
25                  Scala   2148
26                   Perl   2028
27                Haskell   1749
28                 Delphi   1731
29                Clojure   1552
30                 Elixir   1438
31                   LISP   1096
32                  Julia   1068
33                     F#    804
34                 Erlang    651
35                    APL    536
36                Crystal    466
37                  COBOL    437

In [19]:
worked.to_frame().reset_index().loc[lambda df_: df_['LanguageHaveWorkedWith'].isin(wanted.index)]

   LanguageHaveWorkedWith  count
0              JavaScript  53587
1                HTML/CSS  46259
2                  Python  39792
3                     SQL  38835
4                    Java  29162
5                 Node.js  27975
6              TypeScript  24909
7                      C#  22984
8              Bash/Shell  22385
9                     C++  20057
10                    PHP  18130
11                      C  17329
12             PowerShell   8871
13                     Go   7879
14                 Kotlin   6866
15                   Rust   5799
16                   Ruby   5569
17                   Dart   4965
18               Assembly   4632
19                  Swift   4204
20                      R   4185
21                    VBA   3847
22                 Matlab   3846
23                 Groovy   2479
24            Objective-C   2310
25                  Scala   2148
26                   Perl   2028
27                Haskell   1749
28                 Delphi   1731
29                Clojure   1552
30                 Elixir   1438
31                   LISP   1096
32                  Julia   1068
33                     F#    804
34                 Erlang    651
35                    APL    536
36                Crystal    466
37                  COBOL    437

In [25]:
df_worked = worked.to_frame().reset_index().sort_values(by=['count'], ascending=False)

In [26]:
df_worked

   LanguageHaveWorkedWith  count
0              JavaScript  53587
1                HTML/CSS  46259
2                  Python  39792
3                     SQL  38835
4                    Java  29162
5                 Node.js  27975
6              TypeScript  24909
7                      C#  22984
8              Bash/Shell  22385
9                     C++  20057
10                    PHP  18130
11                      C  17329
12             PowerShell   8871
13                     Go   7879
14                 Kotlin   6866
15                   Rust   5799
16                   Ruby   5569
17                   Dart   4965
18               Assembly   4632
19                  Swift   4204
20                      R   4185
21                    VBA   3847
22                 Matlab   3846
23                 Groovy   2479
24            Objective-C   2310
25                  Scala   2148
26                   Perl   2028
27                Haskell   1749
28                 Delphi   1731
29                Clojure   1552
30                 Elixir   1438
31                   LISP   1096
32                  Julia   1068
33                     F#    804
34                 Erlang    651
35                    APL    536
36                Crystal    466
37                  COBOL    437

In [27]:
df_wanted = wanted.to_frame().reset_index().sort_values(by=['count'], ascending=False)

In [28]:
df_wanted

   LanguageWantToWorkWith  count
0              JavaScript  37008
1                  Python  34929
2                HTML/CSS  29353
3              TypeScript  26905
4                     SQL  26631
5                 Node.js  24100
6                      C#  17999
7                    Java  17222
8                    Rust  15865
9                      Go  15788
10                    C++  15249
11             Bash/Shell  14043
12                 Kotlin  10691
13                      C   9702
14                    PHP   8852
15                   Dart   7018
16                  Swift   6353
17                   Ruby   4942
18             PowerShell   4896
19                      R   4015
20               Assembly   3578
21                Haskell   3453
22                 Elixir   3374
23                  Scala   3165
24                  Julia   2445
25                Clojure   2413
26                     F#   2157
27                 Matlab   1562
28                   LISP   1513
29            Objective-C   1400
30                 Erlang   1379
31                 Groovy   1177
32                   Perl   1175
33                    VBA   1069
34                 Delphi    975
35                Crystal    790
36                    APL    568
37                  COBOL    309

In [30]:
df_worked.iloc[:10].merge(df_wanted.iloc[:10], how='inner', left_on=['LanguageHaveWorkedWith'], right_on=['LanguageWantToWorkWith'])['LanguageHaveWorkedWith']

0    JavaScript
1      HTML/CSS
2        Python
3           SQL
4          Java
5       Node.js
6    TypeScript
7            C#
Name: LanguageHaveWorkedWith, dtype: object

In [33]:
df_worked.iloc[:10].merge(df_wanted.iloc[:10], how='left', left_on=['LanguageHaveWorkedWith'], right_on=['LanguageWantToWorkWith'], indicator=True).loc[lambda df_: df_['_merge'] == 'left_only']['LanguageHaveWorkedWith']

8    Bash/Shell
9           C++
Name: LanguageHaveWorkedWith, dtype: object

In [40]:
countries = df[['Country', 'LanguageHaveWorkedWith']]

In [43]:
countries.loc[:, 'lang_lst'] = countries['LanguageHaveWorkedWith'].str.split(';')

In [47]:
countries = countries.explode(column='lang_lst')

In [80]:
top_langs = countries.groupby(by='Country').apply(lambda df_: df_['lang_lst'].value_counts().head(1)).reset_index()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_8026/694906951.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_langs = countries.groupby(by='Country').apply(lambda df_: df_['lang_lst'].value_counts().head(1)).reset_index()

In [83]:
top_langs.loc[top_langs['lang_lst'] == 'C#']

                              Country lang_lst  count
46                           Dominica       C#      1
91                      Liechtenstein       C#      1
136             Saint Kitts and Nevis       C#      1
138  Saint Vincent and the Grenadines       C#      1
178                             Yemen       C#     11

In [88]:
df.loc[df['Country'] == 'Yemen', 'LanguageHaveWorkedWith'].str.split(';').explode().value_counts()

LanguageHaveWorkedWith
C#            11
HTML/CSS      11
Java           8
JavaScript     8
PHP            8
SQL            8
Python         6
Kotlin         5
C++            5
Dart           4
Node.js        3
C              2
Assembly       1
Delphi         1
TypeScript     1
VBA            1
Go             1
Matlab         1
Name: count, dtype: int64

In [51]:
df['LanguageHaveWorkedWith'].str.split(';').str.len().mean()

np.float64(5.373678011583714)

In [52]:
df['LanguageHaveWorkedWith'].str.split(';').str.len().max()

38.0

In [54]:
len(df.loc[df['LanguageHaveWorkedWith'].str.split(';').str.len() == df['LanguageHaveWorkedWith'].str.split(';').str.len().max()])

32

In [56]:
df.dtypes

Country                    object
CompTotal                 float64
LanguageHaveWorkedWith     object
LanguageWantToWorkWith     object
dtype: object

In [58]:
len(df.loc[df['CompTotal'] >= 2 * 10 ** 6])

2369

In [62]:
df1 = df.loc[(df['CompTotal'] < 2 * 10 ** 6) | (df['CompTotal'].isnull())]

In [63]:
len(df) - len(df1)

2369

In [64]:
df1

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift
1,Netherlands,NaN,JavaScript;Python,NaN
2,Russian Federation,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust
3,Austria,NaN,JavaScript;TypeScript,JavaScript;TypeScript
4,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL
...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure
83435,Benin,200000.0,NaN,NaN
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...

In [66]:
df1 = pd.concat(objs=[df1, df1['LanguageHaveWorkedWith'].str.get_dummies(sep=';')], axis=1)

In [67]:
df1

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,APL,Assembly,Bash/Shell,C,C#,C++,...,PowerShell,Python,R,Ruby,Rust,SQL,Scala,Swift,TypeScript,VBA
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,Netherlands,NaN,JavaScript;Python,NaN,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,Russian Federation,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,0,1,0,1,0,0,...,0,1,1,0,1,0,0,0,0,0
3,Austria,NaN,JavaScript;TypeScript,JavaScript;TypeScript,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
83435,Benin,200000.0,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
langs = ['Python', 'JavaScript', 'Java']

In [69]:
import itertools

In [72]:
list(itertools.combinations(langs, 2))

[('Python', 'JavaScript'), ('Python', 'Java'), ('JavaScript', 'Java')]

In [73]:
def get_mean_comp(df, comb):
    lang1, lang2 = comb
    return df.loc[((df['LanguageHaveWorkedWith'].str.split(';').str.len() == 2) & (df[lang1] == 1) & (df[lang2] == 1))]['CompTotal'].mean()

In [75]:
for comb in list(itertools.combinations(langs, 2)):
    print(f'{get_mean_comp(df1, comb)}, {comb}')

120365.75490196078, ('Python', 'JavaScript')
189973.62037037036, ('Python', 'Java')
163080.08403361344, ('JavaScript', 'Java')

In [89]:
df.loc[df['CompTotal'] < 2 * 10 ** 6]

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift
9,Sweden,42000.0,C++;Python,Haskell;Python
11,Spain,43000.0,Bash/Shell;HTML/CSS;JavaScript;Node.js;SQL;Typ...,C++;Clojure;JavaScript;Node.js;Rust;SQL;TypeSc...
12,Germany,71500.0,C;C++;Java;Perl;Ruby,Rust
16,Turkey,9000.0,C#;HTML/CSS;Java;JavaScript;Node.js,C#;Java;JavaScript;Node.js
...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure
83435,Benin,200000.0,NaN,NaN
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...

In [90]:
# 38.1

In [93]:
df2 = pd.read_csv(
    'data/so_2021_survey_results.csv',
    usecols=['LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'Country', 'CompTotal', 'NEWStuck']
)

df2

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,NEWStuck
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,Call a coworker or friend;Visit Stack Overflow...
1,Netherlands,NaN,JavaScript;Python,NaN,Visit Stack Overflow;Google it
2,Russian Federation,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,Visit Stack Overflow;Google it;Watch help / tu...
3,Austria,NaN,JavaScript;TypeScript,JavaScript;TypeScript,Call a coworker or friend;Visit Stack Overflow...
4,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Visit Stack Overflow;Go for a walk or other ph...
...,...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure,Call a coworker or friend;Google it
83435,Benin,200000.0,NaN,NaN,Call a coworker or friend;Visit Stack Overflow...
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python,Call a coworker or friend;Visit Stack Overflow...
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Call a coworker or friend;Visit Stack Overflow...
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Call a coworker or friend;Visit Stack Overflow...

In [94]:
df2['NEWStuck'].str.split(';').explode().value_counts().head(3)

NEWStuck
Google it                            74491
Visit Stack Overflow                 66410
Do other work and come back later    39871
Name: count, dtype: int64

In [95]:
# 38.2

In [96]:
df2 = pd.read_csv(
    'data/so_2021_survey_results.csv',
    usecols=['LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'Country', 'CompTotal', 'NEWStuck', 'Gender']
)

df2

,Country,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,NEWStuck,Gender
0,Slovakia,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,Call a coworker or friend;Visit Stack Overflow...,Man
1,Netherlands,NaN,JavaScript;Python,NaN,Visit Stack Overflow;Google it,Man
2,Russian Federation,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,Visit Stack Overflow;Google it;Watch help / tu...,Man
3,Austria,NaN,JavaScript;TypeScript,JavaScript;TypeScript,Call a coworker or friend;Visit Stack Overflow...,Man
4,United Kingdom of Great Britain and Northern I...,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Visit Stack Overflow;Go for a walk or other ph...,Man
...,...,...,...,...,...,...
83434,United States of America,160500.0,Clojure;Kotlin;SQL,Clojure,Call a coworker or friend;Google it,Man
83435,Benin,200000.0,NaN,NaN,Call a coworker or friend;Visit Stack Overflow...,Man
83436,United States of America,1800.0,Groovy;Java;Python,Java;Python,Call a coworker or friend;Visit Stack Overflow...,Man
83437,Canada,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Call a coworker or friend;Visit Stack Overflow...,Man
83438,Brazil,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Call a coworker or friend;Visit Stack Overflow...,Man

In [101]:
(df2['Gender'].value_counts(normalize=True) * 100).round(2)

Gender
Man                                                                                   90.92
Woman                                                                                  5.01
Prefer not to say                                                                      1.75
Non-binary, genderqueer, or gender non-conforming                                      0.84
Or, in your own words:                                                                 0.50
Man;Or, in your own words:                                                             0.33
Man;Non-binary, genderqueer, or gender non-conforming                                  0.31
Woman;Non-binary, genderqueer, or gender non-conforming                                0.18
Man;Woman                                                                              0.05
Non-binary, genderqueer, or gender non-conforming;Or, in your own words:               0.03
Man;Woman;Non-binary, genderqueer, or gender non-conforming                            0.03
Man;Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:     0.02
Woman;Or, in your own words:                                                           0.02
Man;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:           0.01
Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:         0.01
Man;Woman;Or, in your own words:                                                       0.00
Name: proportion, dtype: float64

In [103]:
# 38.3

In [104]:
df2 = pd.read_csv(
    'data/so_2021_survey_results.csv',
    usecols=['LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'Country', 'CompTotal', 'NEWStuck', 'Gender', 'YearsCode', 'YearsCodePro']
)

df2

,Country,YearsCode,YearsCodePro,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,NEWStuck,Gender
0,Slovakia,NaN,NaN,4800.0,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,Call a coworker or friend;Visit Stack Overflow...,Man
1,Netherlands,7,NaN,NaN,JavaScript;Python,NaN,Visit Stack Overflow;Google it,Man
2,Russian Federation,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,Visit Stack Overflow;Google it;Watch help / tu...,Man
3,Austria,NaN,NaN,NaN,JavaScript;TypeScript,JavaScript;TypeScript,Call a coworker or friend;Visit Stack Overflow...,Man
4,United Kingdom of Great Britain and Northern I...,17,10,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Visit Stack Overflow;Go for a walk or other ph...,Man
...,...,...,...,...,...,...,...,...
83434,United States of America,6,5,160500.0,Clojure;Kotlin;SQL,Clojure,Call a coworker or friend;Google it,Man
83435,Benin,4,2,200000.0,NaN,NaN,Call a coworker or friend;Visit Stack Overflow...,Man
83436,United States of America,10,4,1800.0,Groovy;Java;Python,Java;Python,Call a coworker or friend;Visit Stack Overflow...,Man
83437,Canada,5,3,90000.0,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Call a coworker or friend;Visit Stack Overflow...,Man
83438,Brazil,14,4,7700.0,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Call a coworker or friend;Visit Stack Overflow...,Man

In [107]:
df2['YearsCodePro'].value_counts()

YearsCodePro
3                     5812
2                     5472
5                     5095
4                     4803
6                     3804
10                    3780
7                     3159
1                     3047
8                     2844
Less than 1 year      2699
15                    2249
20                    1835
9                     1814
12                    1733
11                    1533
13                    1267
14                    1092
16                     970
25                     907
17                     770
21                     765
18                     695
22                     653
30                     527
23                     525
24                     435
19                     392
26                     321
35                     256
27                     236
28                     222
32                     186
31                     156
40                     152
33                     148
29                     146
36                     114
34                     104
37                      91
38                      78
42                      52
More than 50 years      50
39                      43
41                      38
45                      34
43                      31
44                      29
46                      13
47                      13
50                      12
48                       9
49                       5
Name: count, dtype: int64

In [108]:
df2.loc[df2['YearsCode'] == 'Less than 1 year', 'YearsCode'] = 0
df2.loc[df2['YearsCode'] == 'More than 50 years', 'YearsCode'] = 51

df2.loc[df2['YearsCodePro'] == 'Less than 1 year', 'YearsCodePro'] = 0
df2.loc[df2['YearsCodePro'] == 'More than 50 years', 'YearsCodePro'] = 51

In [109]:
df2 = df2.dropna(subset=['YearsCodePro', 'YearsCode'])

In [111]:
df2.loc[:, 'YearsCodePro'] = df2['YearsCodePro'].astype(int)
df2.loc[:, 'YearsCode'] = df2['YearsCode'].astype(int)

In [117]:
df2.loc[:, 'years_share'] = df2['YearsCodePro'] / df2['YearsCode']

In [120]:
df2.loc[df2['YearsCode'] != 0, 'years_share'].mean()

np.float64(0.5923711657118932)