In [1]:
import numpy as np
import pandas as pd

In [2]:
oecd_df = pd.read_csv(
    'data/oecd_locations.csv',
    header=None,
    index_col=0,
    names=['LOCATION', 'Country']
)

oecd_df

                 Country
LOCATION
AUS            Australia
AUT              Austria
BEL              Belgium
CAN               Canada
DNK              Denmark
FIN              Finland
FRA               France
DEU              Germany
HUN              Hungary
ITA                Italy
JPN                Japan
KOR                Korea
GBR       United Kingdom
USA        United States
BRA               Brazil
ISR               Israel

In [3]:
oecd_tourism_df = pd.read_csv(
    'data/oecd_tourism.csv',
    usecols=['LOCATION', 'TIME', 'SUBJECT', 'Value'],
    index_col=['LOCATION']
)

oecd_tourism_df

          SUBJECT  TIME      Value
LOCATION
AUS       INT_REC  2008  31159.800
AUS       INT_REC  2009  29980.700
AUS       INT_REC  2010  35165.500
AUS       INT_REC  2011  38710.100
AUS       INT_REC  2012  38003.700
...           ...   ...        ...
SRB       INT-EXP  2015   1253.644
SRB       INT-EXP  2016   1351.098
SRB       INT-EXP  2017   1549.183
SRB       INT-EXP  2018   1837.317
SRB       INT-EXP  2019   1999.313

[1234 rows x 3 columns]

In [4]:
oecd_tourism_df = oecd_tourism_df[oecd_tourism_df['SUBJECT'] == 'INT-EXP']
oecd_tourism_df

          SUBJECT  TIME      Value
LOCATION
AUS       INT-EXP  2008  27620.000
AUS       INT-EXP  2009  25629.600
AUS       INT-EXP  2010  31916.500
AUS       INT-EXP  2011  39381.500
AUS       INT-EXP  2012  41632.800
...           ...   ...        ...
SRB       INT-EXP  2015   1253.644
SRB       INT-EXP  2016   1351.098
SRB       INT-EXP  2017   1549.183
SRB       INT-EXP  2018   1837.317
SRB       INT-EXP  2019   1999.313

[617 rows x 3 columns]

In [5]:
oecd_tourism_df = oecd_tourism_df.drop(['SUBJECT'], axis=1)
oecd_tourism_df

          TIME      Value
LOCATION
AUS       2008  27620.000
AUS       2009  25629.600
AUS       2010  31916.500
AUS       2011  39381.500
AUS       2012  41632.800
...        ...        ...
SRB       2015   1253.644
SRB       2016   1351.098
SRB       2017   1549.183
SRB       2018   1837.317
SRB       2019   1999.313

[617 rows x 2 columns]

In [6]:
len(oecd_tourism_df.groupby('LOCATION')['Value'].mean())

54

In [7]:
tourism_spending = oecd_df.join(oecd_tourism_df).groupby('Country')['Value'].mean()

In [8]:
tourism_spending

Country
Australia          36727.966667
Austria            11934.563636
Belgium            20859.883455
Brazil             21564.351833
Canada             40984.633333
Denmark            11326.169636
Finland             5877.080909
France             51394.272273
Germany            96615.075545
Hungary             2918.390182
Israel              6726.524833
Italy              34148.908455
Japan              32197.925000
Korea              25573.509091
United Kingdom     75262.227273
United States     142080.666667
Name: Value, dtype: float64

In [9]:
wine_df = pd.read_csv(
    'data/winemag-150k-reviews.csv',
    usecols=['country', 'points']
)

wine_df

       country  points
0           US      96
1        Spain      96
2           US      96
3           US      96
4       France      95
...        ...     ...
150925   Italy      91
150926  France      91
150927   Italy      91
150928  France      90
150929   Italy      90

[150930 rows x 2 columns]

In [10]:
wine_points = wine_df.groupby(by=['country'])['points'].mean().sort_values(ascending=False).to_frame()

In [11]:
wine_points

                           points
country
England                 92.888889
Austria                 89.276742
France                  88.925870
Germany                 88.626427
Italy                   88.413664
Canada                  88.239796
Slovenia                88.234043
Morocco                 88.166667
Turkey                  88.096154
Portugal                88.057685
Albania                 88.000000
US-France               88.000000
Australia               87.892475
US                      87.818789
Serbia                  87.714286
India                   87.625000
New Zealand             87.554217
Hungary                 87.329004
Switzerland             87.250000
South Africa            87.225421
Israel                  87.176190
Luxembourg              87.000000
Spain                   86.646589
Chile                   86.296768
Croatia                 86.280899
Greece                  86.117647
Tunisia                 86.000000
Argentina               85.996093
Cyprus                  85.870968
Czech Republic          85.833333
Lebanon                 85.702703
Georgia                 85.511628
Bulgaria                85.467532
Japan                   85.000000
Romania                 84.920863
Macedonia               84.812500
Mexico                  84.761905
Bosnia and Herzegovina  84.750000
Moldova                 84.718310
Ukraine                 84.600000
Uruguay                 84.478261
Lithuania               84.250000
Slovakia                83.666667
Egypt                   83.666667
Brazil                  83.240000
Montenegro              82.000000
China                   82.000000
South Korea             81.500000

In [12]:
wine_points.join(tourism_spending, how='outer').corr()

          points     Value
points  1.000000  0.288231
Value   0.288231  1.000000

In [13]:
# 35.1

In [14]:
oecd_df = pd.read_csv(
    'data/oecd_locations.csv',
    header=None,
    names=['abbrev', 'country']
)

oecd_df

   abbrev         country
0     AUS       Australia
1     AUT         Austria
2     BEL         Belgium
3     CAN          Canada
4     DNK         Denmark
5     FIN         Finland
6     FRA          France
7     DEU         Germany
8     HUN         Hungary
9     ITA           Italy
10    JPN           Japan
11    KOR           Korea
12    GBR  United Kingdom
13    USA   United States
14    BRA          Brazil
15    ISR          Israel

In [15]:
oecd_tourism_df = pd.read_csv(
    'data/oecd_tourism.csv',
    usecols=['LOCATION', 'TIME', 'SUBJECT', 'Value']
).loc[lambda df_: df_['SUBJECT'] == 'INT-EXP'].drop('SUBJECT', axis=1)

oecd_tourism_df

     LOCATION  TIME      Value
12        AUS  2008  27620.000
13        AUS  2009  25629.600
14        AUS  2010  31916.500
15        AUS  2011  39381.500
16        AUS  2012  41632.800
...       ...   ...        ...
1229      SRB  2015   1253.644
1230      SRB  2016   1351.098
1231      SRB  2017   1549.183
1232      SRB  2018   1837.317
1233      SRB  2019   1999.313

[617 rows x 3 columns]

In [16]:
wine_df = pd.read_csv(
    'data/winemag-150k-reviews.csv',
    usecols=['country', 'points']
)

wine_df

       country  points
0           US      96
1        Spain      96
2           US      96
3           US      96
4       France      95
...        ...     ...
150925   Italy      91
150926  France      91
150927   Italy      91
150928  France      90
150929   Italy      90

[150930 rows x 2 columns]

In [17]:
tourism_spendings = oecd_df.merge(oecd_tourism_df, left_on='abbrev', right_on='LOCATION').groupby('country')['Value'].mean().to_frame()

In [18]:
tourism_spendings

                        Value
country
Australia        36727.966667
Austria          11934.563636
Belgium          20859.883455
Brazil           21564.351833
Canada           40984.633333
Denmark          11326.169636
Finland           5877.080909
France           51394.272273
Germany          96615.075545
Hungary           2918.390182
Israel            6726.524833
Italy            34148.908455
Japan            32197.925000
Korea            25573.509091
United Kingdom   75262.227273
United States   142080.666667

In [19]:
tourism_spendings.merge(wine_df.groupby('country')['points'].mean(), left_on='country', right_on='country', how='outer')

                                Value     points
country
Albania                           NaN  88.000000
Argentina                         NaN  85.996093
Australia                36727.966667  87.892475
Austria                  11934.563636  89.276742
Belgium                  20859.883455        NaN
Bosnia and Herzegovina            NaN  84.750000
Brazil                   21564.351833  83.240000
Bulgaria                          NaN  85.467532
Canada                   40984.633333  88.239796
Chile                             NaN  86.296768
China                             NaN  82.000000
Croatia                           NaN  86.280899
Cyprus                            NaN  85.870968
Czech Republic                    NaN  85.833333
Denmark                  11326.169636        NaN
Egypt                             NaN  83.666667
England                           NaN  92.888889
Finland                   5877.080909        NaN
France                   51394.272273  88.925870
Georgia                           NaN  85.511628
Germany                  96615.075545  88.626427
Greece                            NaN  86.117647
Hungary                   2918.390182  87.329004
India                             NaN  87.625000
Israel                    6726.524833  87.176190
Italy                    34148.908455  88.413664
Japan                    32197.925000  85.000000
Korea                    25573.509091        NaN
Lebanon                           NaN  85.702703
Lithuania                         NaN  84.250000
Luxembourg                        NaN  87.000000
Macedonia                         NaN  84.812500
Mexico                            NaN  84.761905
Moldova                           NaN  84.718310
Montenegro                        NaN  82.000000
Morocco                           NaN  88.166667
New Zealand                       NaN  87.554217
Portugal                          NaN  88.057685
Romania                           NaN  84.920863
Serbia                            NaN  87.714286
Slovakia                          NaN  83.666667
Slovenia                          NaN  88.234043
South Africa                      NaN  87.225421
South Korea                       NaN  81.500000
Spain                             NaN  86.646589
Switzerland                       NaN  87.250000
Tunisia                           NaN  86.000000
Turkey                            NaN  88.096154
US                                NaN  87.818789
US-France                         NaN  88.000000
Ukraine                           NaN  84.600000
United Kingdom           75262.227273        NaN
United States           142080.666667        NaN
Uruguay                           NaN  84.478261