In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.read_csv('data/nyc-temps.txt').squeeze()
s

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
723    2
724    2
725    2
726    2
727    2
Name: -1, Length: 728, dtype: int64

In [5]:
idx = list(range(0, 22, 3))
idx

[0, 3, 6, 9, 12, 15, 18, 21]

In [7]:
728 / len(idx)

91.0

In [8]:
idx *= 91

In [9]:
idx

[0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21]

In [10]:
s.name = 'temp'

In [11]:
s1 = pd.Series(data=idx, name='hour')
s1

0       0
1       3
2       6
3       9
4      12
       ..
723     9
724    12
725    15
726    18
727    21
Name: hour, Length: 728, dtype: int64

In [12]:
df = pd.concat([s, s1], axis=1)
df

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [13]:
df['temp'].describe()

count    728.000000
mean      -1.050824
std        5.026357
min      -14.000000
25%       -4.000000
50%        0.000000
75%        2.000000
max       12.000000
Name: temp, dtype: float64

In [19]:
df1 = df.copy()

In [20]:
df1

     temp  hour
0      -1     0
1      -1     3
2      -1     6
3      -1     9
4      -1    12
..    ...   ...
723     2     9
724     2    12
725     2    15
726     2    18
727     2    21

[728 rows x 2 columns]

In [21]:
df1.loc[df1['hour'].isin([3, 6]), 'temp'] = np.nan

In [22]:
df1

     temp  hour
0    -1.0     0
1     NaN     3
2     NaN     6
3    -1.0     9
4    -1.0    12
..    ...   ...
723   2.0     9
724   2.0    12
725   2.0    15
726   2.0    18
727   2.0    21

[728 rows x 2 columns]

In [23]:
df1['temp'].interpolate()

0     -1.0
1     -1.0
2     -1.0
3     -1.0
4     -1.0
      ...
723    2.0
724    2.0
725    2.0
726    2.0
727    2.0
Name: temp, Length: 728, dtype: float64

In [24]:
df1['temp'] = df1['temp'].interpolate()

In [25]:
df1

     temp  hour
0    -1.0     0
1    -1.0     3
2    -1.0     6
3    -1.0     9
4    -1.0    12
..    ...   ...
723   2.0     9
724   2.0    12
725   2.0    15
726   2.0    18
727   2.0    21

[728 rows x 2 columns]

In [26]:
df1['temp'].describe()

count    728.000000
mean      -1.050824
std        5.026357
min      -14.000000
25%       -4.000000
50%        0.000000
75%        2.000000
max       12.000000
Name: temp, dtype: float64

In [27]:
# 13.1

In [28]:
df1 = df.copy()

In [29]:
df1.loc[df1['hour'].isin([3, 6]), 'temp'] = np.nan

In [30]:
df1

     temp  hour
0    -1.0     0
1     NaN     3
2     NaN     6
3    -1.0     9
4    -1.0    12
..    ...   ...
723   2.0     9
724   2.0    12
725   2.0    15
726   2.0    18
727   2.0    21

[728 rows x 2 columns]

In [31]:
df1 = df1.interpolate(method='nearest')

In [32]:
df1

     temp  hour
0    -1.0     0
1    -1.0     3
2    -1.0     6
3    -1.0     9
4    -1.0    12
..    ...   ...
723   2.0     9
724   2.0    12
725   2.0    15
726   2.0    18
727   2.0    21

[728 rows x 2 columns]

In [33]:
df1['temp'].describe()

count    728.000000
mean      -1.050824
std        5.026357
min      -14.000000
25%       -4.000000
50%        0.000000
75%        2.000000
max       12.000000
Name: temp, dtype: float64

In [34]:
# 13.2

In [35]:
df1 = df.copy()

In [37]:
df1.loc[df1['temp'] < 0, 'temp'] = np.nan

In [38]:
df1 = df1.interpolate()

In [39]:
df1['temp'].describe()

count    721.000000
mean       2.022191
std        2.345483
min        0.000000
25%        0.209524
50%        1.000000
75%        3.000000
max       12.000000
Name: temp, dtype: float64

In [40]:
# 13.3

In [41]:
df1 = df.copy()

In [42]:
df1.loc[df1['temp'] < 0, 'temp'] = np.nan

In [43]:
df1['temp'] = df1['temp'].fillna(df1['temp'].mean())

In [44]:
df1['temp'].describe()

count    728.000000
mean       2.763926
std        1.935689
min        0.000000
25%        2.000000
50%        2.763926
75%        2.763926
max       12.000000
Name: temp, dtype: float64