In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])
df

         passenger_count  trip_distance  total_amount
0                      1           1.50          9.95
1                      1           2.60         16.30
2                      3           0.00          5.80
3                      5           0.00          7.55
4                      5           0.00         55.55
...                  ...            ...           ...
7667787                1           4.79         23.16
7667788                1           0.00          0.00
7667789                1           0.00          0.00
7667790                1           0.00          0.00
7667791                1           0.00          0.00

[7667792 rows x 3 columns]

In [3]:
len(df) - df.count()

passenger_count    0
trip_distance      0
total_amount       0
dtype: int64

In [5]:
df.groupby('passenger_count')['total_amount'].mean().sort_values()

passenger_count
6    15.437892
5    15.546940
3    15.604015
1    15.609601
4    15.650307
2    15.831294
0    18.663658
9    31.094444
7    48.278421
8    64.105517
Name: total_amount, dtype: float64

In [13]:
df.groupby('passenger_count')['total_amount'].mean().sort_index(ascending=False)

passenger_count
9    31.094444
8    64.105517
7    48.278421
6    15.437892
5    15.546940
4    15.650307
3    15.604015
2    15.831294
1    15.609601
0    18.663658
Name: total_amount, dtype: float64

In [6]:
df1 = df.sort_values(by=['passenger_count'], ascending=[True])

In [7]:
df1

         passenger_count  trip_distance  total_amount
863013                 0           3.60         15.95
1858862                0           1.70         12.95
5174501                0           0.60          6.95
5174500                0           3.10         24.80
3062230                0           2.10         10.30
...                  ...            ...           ...
7286548                9           0.00         10.30
4852210                9           0.00         12.74
7373737                9          13.38         90.80
2012030                9           0.00         11.30
4997772                9           0.00          9.80

[7667792 rows x 3 columns]

In [8]:
def get_distance_category(dist):
    if 0 <= dist < 2:
        return 'short'
    elif 2 <= dist <= 10:
        return 'medium'
    else:
        return 'long'

In [9]:
df1['trip_distance_group'] = df['trip_distance'].apply(get_distance_category)
df1

         passenger_count  trip_distance  total_amount trip_distance_group
863013                 0           3.60         15.95              medium
1858862                0           1.70         12.95               short
5174501                0           0.60          6.95               short
5174500                0           3.10         24.80              medium
3062230                0           2.10         10.30              medium
...                  ...            ...           ...                 ...
7286548                9           0.00         10.30               short
4852210                9           0.00         12.74               short
7373737                9          13.38         90.80                long
2012030                9           0.00         11.30               short
4997772                9           0.00          9.80               short

[7667792 rows x 4 columns]

In [11]:
df1.groupby('trip_distance_group')['passenger_count'].mean().sort_values(ascending=False)

trip_distance_group
long      1.590035
medium    1.576764
short     1.559943
Name: passenger_count, dtype: float64

In [14]:
# 30.1

In [17]:
df1 = pd.read_csv('data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])
df1['year'] = 2019

In [18]:
df2 = pd.read_csv('data/nyc_taxi_2020-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])
df2['year'] = 2020

In [19]:
df = pd.concat(objs=[df1, df2], ignore_index=True)
df

          passenger_count  trip_distance  total_amount  year
0                     1.0           1.50          9.95  2019
1                     1.0           2.60         16.30  2019
2                     3.0           0.00          5.80  2019
3                     5.0           0.00          7.55  2019
4                     5.0           0.00         55.55  2019
...                   ...            ...           ...   ...
14072795              NaN           3.24         21.14  2020
14072796              NaN          22.13         62.46  2020
14072797              NaN          10.51         51.90  2020
14072798              NaN           5.49         30.22  2020
14072799              NaN          11.60         58.11  2020

[14072800 rows x 4 columns]

In [20]:
df.groupby('year')['total_amount'].mean()

year
2019    15.682222
2020    18.663149
Name: total_amount, dtype: float64

In [21]:
# 30.2

In [22]:
df.groupby(by=['year', 'passenger_count'])['total_amount'].mean()

year  passenger_count
2019  0.0                18.663658
      1.0                15.609601
      2.0                15.831294
      3.0                15.604015
      4.0                15.650307
      5.0                15.546940
      6.0                15.437892
      7.0                48.278421
      8.0                64.105517
      9.0                31.094444
2020  0.0                18.059724
      1.0                18.343110
      2.0                19.050504
      3.0                18.736862
      4.0                19.128092
      5.0                18.234443
      6.0                18.367962
      7.0                71.143103
      8.0                58.197059
      9.0                81.244211
Name: total_amount, dtype: float64

In [23]:
# 30.3

In [26]:
df.corr().sort_values('passenger_count', ascending=False)

                 passenger_count  trip_distance  total_amount      year
passenger_count         1.000000       0.008974     -0.000136 -0.021602
trip_distance           0.008974       1.000000      0.004331  0.001140
total_amount           -0.000136       0.004331      1.000000  0.007657
year                   -0.021602       0.001140      0.007657  1.000000

In [27]:
df.corr().sort_values('trip_distance', ascending=False)

                 passenger_count  trip_distance  total_amount      year
trip_distance           0.008974       1.000000      0.004331  0.001140
passenger_count         1.000000       0.008974     -0.000136 -0.021602
total_amount           -0.000136       0.004331      1.000000  0.007657
year                   -0.021602       0.001140      0.007657  1.000000

In [28]:
df.corr().sort_values('total_amount', ascending=False)

                 passenger_count  trip_distance  total_amount      year
total_amount           -0.000136       0.004331      1.000000  0.007657
year                   -0.021602       0.001140      0.007657  1.000000
trip_distance           0.008974       1.000000      0.004331  0.001140
passenger_count         1.000000       0.008974     -0.000136 -0.021602

In [29]:
df.corr().sort_values('year', ascending=False)

                 passenger_count  trip_distance  total_amount      year
year                   -0.021602       0.001140      0.007657  1.000000
total_amount           -0.000136       0.004331      1.000000  0.007657
trip_distance           0.008974       1.000000      0.004331  0.001140
passenger_count         1.000000       0.008974     -0.000136 -0.021602