In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.DataFrame(
    data=[
        {'product_id': 23, 'name': 'computer',       'wholesale_price': 500, 'retail_price': 1000, 'sales': 100},
        {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 1000},
        {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35,  'retail_price': 75,   'sales': 500},
        {'product_id': 15, 'name': 'banana',         'wholesale_price': 0.5, 'retail_price': 1,    'sales': 200},
        {'product_id': 87, 'name': 'sandwich',       'wholesale_price': 3.0, 'retail_price': 5,    'sales': 300},
    ]
)
df1

   product_id            name  wholesale_price  retail_price  sales
0          23        computer            500.0          1000    100
1          96  Python Workout             35.0            75   1000
2          97  Pandas Workout             35.0            75    500
3          15          banana              0.5             1    200
4          87        sandwich              3.0             5    300

In [3]:
df2 = pd.DataFrame(
    data=[
        {'product_id': 24, 'name': 'phone', 'wholesale_price': 200, 'retail_price': 500},
        {'product_id': 16, 'name': 'apple', 'wholesale_price': 0.5, 'retail_price': 1},
        {'product_id': 17, 'name': 'pear',  'wholesale_price': 0.6, 'retail_price': 1.2},
    ]
)
df2

   product_id   name  wholesale_price  retail_price
0          24  phone            200.0         500.0
1          16  apple              0.5           1.0
2          17   pear              0.6           1.2

In [4]:
df = pd.concat([df1, df2], ignore_index=True)
df

   product_id            name  wholesale_price  retail_price   sales
0          23        computer            500.0        1000.0   100.0
1          96  Python Workout             35.0          75.0  1000.0
2          97  Pandas Workout             35.0          75.0   500.0
3          15          banana              0.5           1.0   200.0
4          87        sandwich              3.0           5.0   300.0
5          24           phone            200.0         500.0     NaN
6          16           apple              0.5           1.0     NaN
7          17            pear              0.6           1.2     NaN

In [7]:
df.loc[df['sales'] > df['sales'].mean(), ['product_id', 'name']]

   product_id            name
1          96  Python Workout
2          97  Pandas Workout

In [8]:
# 11.1

In [9]:
df['current_net'] = (df['retail_price'] - df['wholesale_price']) * df['sales']
df

,product_id,name,wholesale_price,retail_price,sales,current_net
0,23,computer,500.0,1000.0,100.0,50000.0
1,96,Python Workout,35.0,75.0,1000.0,40000.0
2,97,Pandas Workout,35.0,75.0,500.0,20000.0
3,15,banana,0.5,1.0,200.0,100.0
4,87,sandwich,3.0,5.0,300.0,600.0
5,24,phone,200.0,500.0,NaN,NaN
6,16,apple,0.5,1.0,NaN,NaN
7,17,pear,0.6,1.2,NaN,NaN

In [11]:
df.loc[df['current_net'] >= df['current_net'].quantile(0.75), ['product_id', 'name']]

   product_id            name
0          23        computer
1          96  Python Workout

In [13]:
df.query('current_net >= current_net.quantile(0.75)')[['product_id', 'name']]

   product_id            name
0          23        computer
1          96  Python Workout

In [14]:
# 11.2

In [16]:
df.query('(sales < sales.mean()) & (wholesale_price > wholesale_price.mean())')[['product_id', 'name']]

   product_id      name
0          23  computer

In [17]:
# 11.3

In [18]:
df.query('product_id.between(80, 100) & sales < 400')[['name', 'wholesale_price', 'retail_price']]

       name  wholesale_price  retail_price
4  sandwich              3.0           5.0