In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv('data/nyc_taxi_2019-07.csv', usecols=['passenger_count', 'total_amount', 'payment_type'])
df1['year'] = 2019
df1

         passenger_count  payment_type  total_amount  year
0                    1.0           1.0          4.94  2019
1                    1.0           2.0         20.30  2019
2                    1.0           1.0         70.67  2019
3                    1.0           1.0         66.36  2019
4                    0.0           1.0         15.30  2019
...                  ...           ...           ...   ...
6310414              NaN           NaN         29.00  2019
6310415              NaN           NaN         54.43  2019
6310416              NaN           NaN         65.40  2019
6310417              NaN           NaN         43.00  2019
6310418              NaN           NaN         22.15  2019

[6310419 rows x 4 columns]

In [3]:
df1.count()

passenger_count    6276460
payment_type       6276460
total_amount       6310419
year               6310419
dtype: int64

In [4]:
df2 = pd.read_csv('data/nyc_taxi_2020-07.csv', usecols=['passenger_count', 'total_amount', 'payment_type'])
df2['year'] = 2020
df2

        passenger_count  payment_type  total_amount  year
0                   1.0           2.0          9.30  2020
1                   1.0           1.0         27.80  2020
2                   1.0           2.0         22.30  2020
3                   1.0           1.0         14.16  2020
4                   1.0           2.0          7.80  2020
...                 ...           ...           ...   ...
800407              NaN           NaN         83.50  2020
800408              NaN           NaN         19.78  2020
800409              NaN           NaN         38.45  2020
800410              NaN           NaN         29.77  2020
800411              NaN           NaN         51.90  2020

[800412 rows x 4 columns]

In [5]:
df = pd.concat(objs=[df1, df2], ignore_index=True)
df

         passenger_count  payment_type  total_amount  year
0                    1.0           1.0          4.94  2019
1                    1.0           2.0         20.30  2019
2                    1.0           1.0         70.67  2019
3                    1.0           1.0         66.36  2019
4                    0.0           1.0         15.30  2019
...                  ...           ...           ...   ...
7110826              NaN           NaN         83.50  2020
7110827              NaN           NaN         19.78  2020
7110828              NaN           NaN         38.45  2020
7110829              NaN           NaN         29.77  2020
7110830              NaN           NaN         51.90  2020

[7110831 rows x 4 columns]

In [6]:
df['year'].value_counts()

year
2019    6310419
2020     800412
Name: count, dtype: int64

In [8]:
(df['year'].value_counts().loc[2020] - df['year'].value_counts().loc[2019]) / df['year'].value_counts().loc[2019] * 100

np.float64(-87.31602449853172)

In [9]:
years = df.groupby('year')

In [11]:
tay = years['total_amount'].sum()

In [13]:
(tay.loc[2020] - tay.loc[2019]) / tay.loc[2019] * 100

np.float64(-87.9503681436268)

In [15]:
df.query('(year == 2019) & (passenger_count > 1)')['passenger_count'].count()

np.int64(1778686)

In [16]:
df.query('(year == 2020) & (passenger_count > 1)')['passenger_count'].count()

np.int64(152050)

In [17]:
df.query('(year == 2019) & (passenger_count > 1)')['passenger_count'].count() / df.query('(year == 2019)')['passenger_count'].count()

np.float64(0.2833900000955953)

In [18]:
df.query('(year == 2020) & (passenger_count > 1)')['passenger_count'].count() / df.query('(year == 2020)')['passenger_count'].count()

np.float64(0.2061513222563435)

In [20]:
df.query('(year == 2019) & (payment_type == 2)')['passenger_count'].count() / df.query('(year == 2019)')['passenger_count'].count()

np.float64(0.2870595845428793)

In [21]:
df.query('(year == 2020) & (payment_type == 2)')['passenger_count'].count() / df.query('(year == 2020)')['passenger_count'].count()

np.float64(0.320558865998251)

In [22]:
df.query('(year == 2019) & (payment_type == 2)')['total_amount'].sum() / df.query('(year == 2019)')['total_amount'].sum()

np.float64(0.24093007365036218)

In [23]:
df.query('(year == 2020) & (payment_type == 2)')['total_amount'].sum() / df.query('(year == 2020)')['total_amount'].sum()

np.float64(0.22869734501462227)

In [24]:
df.query('(year == 2019)')['total_amount'].sum()

np.float64(123761823.33000001)

In [25]:
df.query('(year == 2020)')['total_amount'].sum()

np.float64(14912844.090000005)

In [26]:
df.query('(year == 2019)')['total_amount'].sum() - df.query('(year == 2020)')['total_amount'].sum()

np.float64(108848979.24000001)

In [27]:
# 16.1

In [28]:
df

         passenger_count  payment_type  total_amount  year
0                    1.0           1.0          4.94  2019
1                    1.0           2.0         20.30  2019
2                    1.0           1.0         70.67  2019
3                    1.0           1.0         66.36  2019
4                    0.0           1.0         15.30  2019
...                  ...           ...           ...   ...
7110826              NaN           NaN         83.50  2020
7110827              NaN           NaN         19.78  2020
7110828              NaN           NaN         38.45  2020
7110829              NaN           NaN         29.77  2020
7110830              NaN           NaN         51.90  2020

[7110831 rows x 4 columns]

In [29]:
df.corr()

                 passenger_count  payment_type  total_amount      year
passenger_count         1.000000      0.016410      0.014943 -0.049558
payment_type            0.016410      1.000000     -0.138561  0.029277
total_amount            0.014943     -0.138561      1.000000 -0.019706
year                   -0.049558      0.029277     -0.019706  1.000000

In [30]:
# 16.2

In [31]:
(df.query('year == 2019')['total_amount'].describe() - df.query('year == 2020')['total_amount'].describe()).round(2)

count    5510007.00
mean           0.98
std            0.75
min          -53.20
25%            0.50
50%            0.60
75%            0.75
max         4672.45
Name: total_amount, dtype: float64

In [32]:
# 16.3

In [37]:
(df.query('(year == 2019) & ((passenger_count == 0) | (passenger_count.isnull()))')['year'].count() / df.query('(year == 2019)')['year'].count() * 100).round(2)

np.float64(2.39)

In [38]:
(df.query('(year == 2020) & ((passenger_count == 0) | (passenger_count.isnull()))')['year'].count() / df.query('(year == 2020)')['year'].count() * 100).round(2)

np.float64(10.29)

In [41]:
(df.query('(year == 2019) & (passenger_count == 0)')['passenger_count'].count() / df.query('(year == 2019)')['passenger_count'].count() * 100).round(2)

np.float64(1.86)

In [42]:
(df.query('(year == 2020) & (passenger_count == 0)')['passenger_count'].count() / df.query('(year == 2020)')['passenger_count'].count() * 100).round(2)

np.float64(2.64)