In [1]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('data/olympic_athlete_events.csv', usecols=['Age', 'Height', 'Team', 'Year', 'Season', 'Sport', 'Medal'])
df

         Age  Height            Team  Year  Season          Sport Medal
0       24.0   180.0           China  1992  Summer     Basketball   NaN
1       23.0   170.0           China  2012  Summer           Judo   NaN
2       24.0     NaN         Denmark  1920  Summer       Football   NaN
3       34.0     NaN  Denmark/Sweden  1900  Summer     Tug-Of-War  Gold
4       21.0   185.0     Netherlands  1988  Winter  Speed Skating   NaN
...      ...     ...             ...   ...     ...            ...   ...
271111  29.0   179.0        Poland-1  1976  Winter           Luge   NaN
271112  27.0   176.0          Poland  2014  Winter    Ski Jumping   NaN
271113  27.0   176.0          Poland  2014  Winter    Ski Jumping   NaN
271114  30.0   185.0          Poland  1998  Winter      Bobsleigh   NaN
271115  34.0   185.0          Poland  2002  Winter      Bobsleigh   NaN

[271116 rows x 7 columns]

In [16]:
df = df.query('Year >= 1980').copy()

In [17]:
df = df.query('Team.isin(["Great Britain", "France", "United States", "Russia", "China", "India"])').copy()

In [18]:
df['Team'].unique()

array(['China', 'United States', 'France', 'Russia', 'Great Britain',
       'India'], dtype=object)

In [19]:
sorted(df['Year'].unique())

[np.int64(1980),
 np.int64(1984),
 np.int64(1988),
 np.int64(1992),
 np.int64(1994),
 np.int64(1996),
 np.int64(1998),
 np.int64(2000),
 np.int64(2002),
 np.int64(2004),
 np.int64(2006),
 np.int64(2008),
 np.int64(2010),
 np.int64(2012),
 np.int64(2014),
 np.int64(2016)]

In [20]:
df.pivot_table(index='Team', columns='Year', values='Age', aggfunc='mean')

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Team,,,,,,,,,,,,,,,,
China,21.868421,22.076336,22.358447,21.955752,20.627907,22.021531,21.784091,22.515306,23.127451,23.006122,23.457143,23.903955,23.239669,23.894168,23.400000,23.873706
France,23.524590,24.369830,24.520076,25.140187,24.601307,25.296629,25.462069,25.982833,25.737805,26.139073,26.303226,26.285714,25.911458,26.606635,25.708995,27.095238
Great Britain,22.882507,24.445423,25.439560,25.584055,25.282051,26.746032,27.243902,26.406948,26.833333,26.303977,26.851852,25.200969,26.147059,25.922619,25.628571,26.653191
India,25.506667,24.905660,24.000000,24.184615,NaN,24.629630,16.000000,25.400000,20.000000,24.728395,25.200000,25.402985,25.666667,25.637363,25.000000,26.100000
Russia,NaN,NaN,NaN,NaN,24.042553,24.268116,25.435028,25.229236,25.518692,26.053356,25.745098,25.432432,25.506173,25.454713,25.842271,25.366834
United States,22.770992,24.437118,24.904977,25.474866,24.976744,26.273277,25.146154,26.576203,25.726316,26.439093,25.637288,26.225806,25.841584,26.461883,26.189189,26.217454

In [21]:
df.pivot_table(index='Year', columns='Team', values='Age', aggfunc='mean')

Team      China     France  Great Britain      India     Russia  United States
Year
1980  21.868421  23.524590      22.882507  25.506667        NaN      22.770992
1984  22.076336  24.369830      24.445423  24.905660        NaN      24.437118
1988  22.358447  24.520076      25.439560  24.000000        NaN      24.904977
1992  21.955752  25.140187      25.584055  24.184615        NaN      25.474866
1994  20.627907  24.601307      25.282051        NaN  24.042553      24.976744
1996  22.021531  25.296629      26.746032  24.629630  24.268116      26.273277
1998  21.784091  25.462069      27.243902  16.000000  25.435028      25.146154
2000  22.515306  25.982833      26.406948  25.400000  25.229236      26.576203
2002  23.127451  25.737805      26.833333  20.000000  25.518692      25.726316
2004  23.006122  26.139073      26.303977  24.728395  26.053356      26.439093
2006  23.457143  26.303226      26.851852  25.200000  25.745098      25.637288
2008  23.903955  26.285714      25.200969  25.402985  25.432432      26.225806
2010  23.239669  25.911458      26.147059  25.666667  25.506173      25.841584
2012  23.894168  26.606635      25.922619  25.637363  25.454713      26.461883
2014  23.400000  25.708995      25.628571  25.000000  25.842271      26.189189
2016  23.873706  27.095238      26.653191  26.100000  25.366834      26.217454

In [27]:
df.pivot_table(index='Sport', columns='Year', values='Height', aggfunc='max', fill_value=0)

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Sport,,,,,,,,,,,,,,,,
Alpine Skiing,180.0,182.0,185.0,185.0,188.0,0.0,188.0,0.0,189.0,0.0,193.0,0.0,193.0,0.0,193.0,0.0
Archery,183.0,188.0,188.0,191.0,0.0,191.0,0.0,191.0,0.0,193.0,0.0,193.0,0.0,193.0,0.0,188.0
Athletics,197.0,203.0,203.0,198.0,0.0,202.0,0.0,203.0,0.0,203.0,0.0,203.0,0.0,208.0,0.0,203.0
Badminton,0.0,0.0,0.0,186.0,0.0,189.0,0.0,187.0,0.0,190.0,0.0,190.0,0.0,201.0,0.0,201.0
Baseball,0.0,0.0,0.0,198.0,0.0,195.0,0.0,206.0,0.0,0.0,0.0,198.0,0.0,0.0,0.0,0.0
Basketball,196.0,216.0,216.0,216.0,0.0,216.0,0.0,226.0,0.0,226.0,0.0,226.0,0.0,221.0,0.0,218.0
Beach Volleyball,0.0,0.0,0.0,0.0,0.0,193.0,0.0,208.0,0.0,192.0,0.0,202.0,0.0,210.0,0.0,188.0
Biathlon,190.0,190.0,188.0,184.0,188.0,0.0,186.0,0.0,187.0,0.0,187.0,0.0,185.0,0.0,188.0,0.0
Bobsleigh,0.0,184.0,0.0,0.0,180.0,0.0,198.0,0.0,190.0,0.0,193.0,0.0,191.0,0.0,189.0,0.0
Boxing,190.0,195.0,196.0,193.0,0.0,191.0,0.0,198.0,0.0,196.0,0.0,203.0,0.0,201.0,0.0,200.0
Canoeing,203.0,203.0,203.0,203.0,0.0,205.0,0.0,203.0,0.0,190.0,0.0,200.0,0.0,196.0,0.0,192.0
Cross Country Skiing,185.0,189.0,186.0,190.0,190.0,0.0,185.0,0.0,188.0,0.0,188.0,0.0,193.0,0.0,193.0,0.0
Curling,0.0,0.0,0.0,0.0,0.0,0.0,188.0,0.0,193.0,0.0,183.0,0.0,189.0,0.0,197.0,0.0
Cycling,187.0,188.0,195.0,191.0,0.0,189.0,0.0,192.0,0.0,192.0,0.0,196.0,0.0,196.0,0.0,196.0
Diving,176.0,175.0,178.0,183.0,0.0,183.0,0.0,183.0,0.0,182.0,0.0,185.0,0.0,178.0,0.0,188.0
Equestrianism,179.0,187.0,187.0,184.0,0.0,196.0,0.0,187.0,0.0,196.0,0.0,196.0,0.0,196.0,0.0,196.0
Fencing,193.0,208.0,208.0,193.0,0.0,200.0,0.0,196.0,0.0,196.0,0.0,196.0,0.0,197.0,0.0,197.0
Figure Skating,183.0,182.0,180.0,182.0,182.0,0.0,182.0,0.0,180.0,0.0,188.0,0.0,188.0,0.0,193.0,0.0
Football,0.0,188.0,190.0,193.0,0.0,191.0,0.0,193.0,0.0,180.0,0.0,193.0,0.0,195.0,0.0,188.0
Freestyle Skiing,0.0,0.0,0.0,183.0,183.0,0.0,193.0,0.0,193.0,0.0,185.0,0.0,180.0,0.0,188.0,0.0
Golf,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,193.0
Gymnastics,180.0,179.0,181.0,176.0,0.0,180.0,0.0,175.0,0.0,176.0,0.0,184.0,0.0,184.0,0.0,184.0
Handball,0.0,200.0,200.0,198.0,0.0,206.0,0.0,203.0,0.0,203.0,0.0,203.0,0.0,204.0,0.0,202.0
Hockey,179.0,190.0,189.0,193.0,0.0,196.0,0.0,196.0,0.0,196.0,0.0,189.0,0.0,189.0,0.0,193.0
Ice Hockey,193.0,193.0,195.0,194.0,195.0,0.0,195.0,0.0,195.0,0.0,199.0,0.0,199.0,0.0,196.0,0.0
Judo,190.0,198.0,198.0,196.0,0.0,205.0,0.0,202.0,0.0,202.0,0.0,203.0,0.0,203.0,0.0,210.0
Luge,188.0,188.0,183.0,188.0,188.0,0.0,189.0,0.0,186.0,0.0,188.0,0.0,189.0,0.0,189.0,0.0
Modern Pentathlon,185.0,188.0,190.0,190.0,0.0,188.0,0.0,188.0,0.0,195.0,0.0,195.0,0.0,195.0,0.0,194.0
Nordic Combined,193.0,183.0,193.0,183.0,180.0,0.0,184.0,0.0,184.0,0.0,184.0,0.0,190.0,0.0,190.0,0.0
Rhythmic Gymnastics,0.0,172.0,170.0,172.0,0.0,176.0,0.0,176.0,0.0,178.0,0.0,177.0,0.0,176.0,0.0,177.0
Rowing,198.0,205.0,205.0,205.0,0.0,205.0,0.0,204.0,0.0,207.0,0.0,207.0,0.0,206.0,0.0,207.0
Rugby Sevens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0
Sailing,0.0,198.0,198.0,195.0,0.0,203.0,0.0,201.0,0.0,198.0,0.0,194.0,0.0,195.0,0.0,197.0
Shooting,183.0,189.0,190.0,190.0,0.0,195.0,0.0,188.0,0.0,192.0,0.0,192.0,0.0,198.0,0.0,200.0
Short Track Speed Skating,0.0,0.0,0.0,182.0,183.0,0.0,183.0,0.0,188.0,0.0,186.0,0.0,186.0,0.0,189.0,0.0
Skeleton,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,188.0,0.0,186.0,0.0,186.0,0.0,190.0,0.0
Ski Jumping,185.0,180.0,180.0,190.0,185.0,0.0,185.0,0.0,185.0,0.0,190.0,0.0,190.0,0.0,190.0,0.0
Snowboarding,0.0,0.0,0.0,0.0,0.0,0.0,190.0,0.0,190.0,0.0,186.0,0.0,190.0,0.0,188.0,0.0
Softball,0.0,0.0,0.0,0.0,0.0,182.0,0.0,185.0,0.0,188.0,0.0,191.0,0.0,0.0,0.0,0.0
Speed Skating,185.0,190.0,193.0,193.0,188.0,0.0,189.0,0.0,193.0,0.0,197.0,0.0,194.0,0.0,193.0,0.0
Swimming,191.0,200.0,200.0,201.0,0.0,201.0,0.0,201.0,0.0,202.0,0.0,203.0,0.0,203.0,0.0,206.0
Synchronized Swimming,0.0,178.0,180.0,180.0,0.0,181.0,0.0,181.0,0.0,177.0,0.0,177.0,0.0,178.0,0.0,177.0
Table Tennis,0.0,0.0,185.0,193.0,0.0,193.0,0.0,188.0,0.0,193.0,0.0,192.0,0.0,192.0,0.0,192.0
Taekwondo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,198.0,0.0,198.0,0.0,201.0,0.0,201.0,0.0,197.0
Tennis,0.0,0.0,193.0,190.0,0.0,191.0,0.0,198.0,0.0,193.0,0.0,198.0,0.0,206.0,0.0,196.0
Trampolining,0.0,0.0,0.0,0.0,0.0,0.0,0.0,175.0,0.0,173.0,0.0,179.0,0.0,179.0,0.0,178.0
Triathlon,0.0,0.0,0.0,0.0,0.0,0.0,0.0,192.0,0.0,191.0,0.0,196.0,0.0,191.0,0.0,191.0
Volleyball,0.0,203.0,203.0,202.0,0.0,217.0,0.0,217.0,0.0,217.0,0.0,210.0,0.0,219.0,0.0,210.0
Water Polo,0.0,198.0,205.0,205.0,0.0,200.0,0.0,200.0,0.0,203.0,0.0,201.0,0.0,203.0,0.0,206.0
Weightlifting,180.0,188.0,190.0,190.0,0.0,195.0,0.0,187.0,0.0,182.0,0.0,187.0,0.0,192.0,0.0,187.0
Wrestling,205.0,190.0,193.0,193.0,0.0,194.0,0.0,196.0,0.0,195.0,0.0,203.0,0.0,203.0,0.0,200.0

In [28]:
df.query('Medal.notnull()').pivot_table(index='Year', columns='Team', values='Medal', aggfunc='count')

Team  China  France  Great Britain  India  Russia  United States
Year
1980    NaN    30.0           48.0   16.0     NaN           30.0
1984   74.0    70.0           71.0    NaN     NaN          359.0
1988   50.0    31.0           54.0    NaN     NaN          212.0
1992   73.0    65.0           50.0    NaN     NaN          236.0
1994    3.0    11.0            3.0    NaN    28.0           19.0
1996   94.0    49.0           26.0    1.0   115.0          255.0
1998   14.0    13.0            4.0    NaN    44.0           30.0
2000   65.0    64.0           52.0    1.0   187.0          240.0
2002   14.0    13.0            6.0    NaN    34.0           70.0
2004   82.0    53.0           55.0    1.0   189.0          259.0
2006    9.0    15.0            1.0    NaN    33.0           48.0
2008  170.0    77.0           81.0    3.0   142.0          309.0
2010   15.0    14.0            1.0    NaN    21.0           89.0
2012  117.0    78.0          122.0    6.0   138.0          238.0
2014   12.0    18.0           10.0    NaN    56.0           52.0
2016  109.0    96.0          145.0    2.0   113.0          256.0

In [29]:
df.pivot_table(index='Year', columns='Team', values='Medal', aggfunc='count')

Team  China  France  Great Britain  India  Russia  United States
Year
1980    0.0    30.0           48.0   16.0     NaN           30.0
1984   74.0    70.0           71.0    0.0     NaN          359.0
1988   50.0    31.0           54.0    0.0     NaN          212.0
1992   73.0    65.0           50.0    0.0     NaN          236.0
1994    3.0    11.0            3.0    NaN    28.0           19.0
1996   94.0    49.0           26.0    1.0   115.0          255.0
1998   14.0    13.0            4.0    0.0    44.0           30.0
2000   65.0    64.0           52.0    1.0   187.0          240.0
2002   14.0    13.0            6.0    0.0    34.0           70.0
2004   82.0    53.0           55.0    1.0   189.0          259.0
2006    9.0    15.0            1.0    0.0    33.0           48.0
2008  170.0    77.0           81.0    3.0   142.0          309.0
2010   15.0    14.0            1.0    0.0    21.0           89.0
2012  117.0    78.0          122.0    6.0   138.0          238.0
2014   12.0    18.0           10.0    0.0    56.0           52.0
2016  109.0    96.0          145.0    2.0   113.0          256.0

In [30]:
# 24.1

In [31]:
df.pivot_table(index=['Year', 'Season'], columns='Team', values='Medal', aggfunc='count')

Team         China  France  Great Britain  India  Russia  United States
Year Season
1980 Summer    NaN    29.0           47.0   16.0     NaN            NaN
     Winter    0.0     1.0            1.0    NaN     NaN           30.0
1984 Summer   74.0    67.0           71.0    0.0     NaN          352.0
     Winter    0.0     3.0            0.0    NaN     NaN            7.0
1988 Summer   50.0    29.0           54.0    0.0     NaN          207.0
     Winter    0.0     2.0            0.0    0.0     NaN            5.0
1992 Summer   70.0    55.0           50.0    0.0     NaN          222.0
     Winter    3.0    10.0            0.0    0.0     NaN           14.0
1994 Winter    3.0    11.0            3.0    NaN    28.0           19.0
1996 Summer   94.0    49.0           26.0    1.0   115.0          255.0
1998 Winter   14.0    13.0            4.0    0.0    44.0           30.0
2000 Summer   65.0    64.0           52.0    1.0   187.0          240.0
2002 Winter   14.0    13.0            6.0    0.0    34.0           70.0
2004 Summer   82.0    53.0           55.0    1.0   189.0          259.0
2006 Winter    9.0    15.0            1.0    0.0    33.0           48.0
2008 Summer  170.0    77.0           81.0    3.0   142.0          309.0
2010 Winter   15.0    14.0            1.0    0.0    21.0           89.0
2012 Summer  117.0    78.0          122.0    6.0   138.0          238.0
2014 Winter   12.0    18.0           10.0    0.0    56.0           52.0
2016 Summer  109.0    96.0          145.0    2.0   113.0          256.0

In [32]:
# 24.2

In [33]:
df.pivot_table(index='Year', columns='Team', values=['Age', 'Height'], aggfunc='max')

       Age                                                 Height         \
Team China France Great Britain India Russia United States  China France
Year
1980  32.0   34.0          37.0  56.0    NaN          32.0  170.0  203.0
1984  30.0   50.0          47.0  45.0    NaN          49.0  216.0  214.0
1988  34.0   43.0          55.0  36.0    NaN          52.0  210.0  203.0
1992  35.0   47.0          48.0  38.0    NaN          54.0  215.0  203.0
1994  29.0   33.0          36.0   NaN   34.0          36.0  181.0  195.0
1996  39.0   53.0          48.0  46.0   46.0          50.0  215.0  201.0
1998  29.0   34.0          36.0  16.0   34.0          40.0  185.0  198.0
2000  39.0   46.0          52.0  38.0   51.0          46.0  226.0  218.0
2002  30.0   38.0          40.0  20.0   41.0          48.0  188.0  190.0
2004  43.0   50.0          48.0  43.0   45.0          52.0  226.0  202.0
2006  32.0   38.0          40.0  29.0   39.0          44.0  188.0  190.0
2008  45.0   51.0          53.0  42.0   48.0          58.0  226.0  203.0
2010  34.0   38.0          45.0  28.0   40.0          40.0  194.0  191.0
2012  41.0   49.0          56.0  39.0   51.0          54.0  221.0  208.0
2014  32.0   37.0          41.0  30.0   42.0          45.0  193.0  191.0
2016  38.0   53.0          60.0  43.0   51.0          52.0  218.0  215.0


Team Great Britain  India Russia United States
Year
1980         205.0  196.0    NaN         193.0
1984         203.0  188.0    NaN         213.0
1988         205.0  193.0    NaN         216.0
1992         205.0  188.0    NaN         216.0
1994         185.0    NaN  195.0         193.0
1996         205.0  191.0  217.0         216.0
1998         185.0  183.0  191.0         195.0
2000         204.0  195.0  217.0         207.0
2002         193.0  183.0  195.0         193.0
2004         207.0  195.0  217.0         213.0
2006         193.0  183.0  199.0         195.0
2008         207.0  192.0  215.0         211.0
2010         193.0  183.0  199.0         193.0
2012         211.0  196.0  219.0         216.0
2014         193.0  173.0  197.0         196.0
2016         207.0  200.0  210.0         211.0

In [34]:
# 24.3

In [35]:
df.pivot_table(index=['Year', 'Season'], columns='Team', values=['Age', 'Height'], aggfunc='max')

              Age                                                 Height  \
Team        China France Great Britain India Russia United States  China
Year Season
1980 Summer   NaN   34.0          37.0  56.0    NaN           NaN    NaN
     Winter  32.0   29.0          36.0   NaN    NaN          32.0  170.0
1984 Summer  30.0   50.0          47.0  45.0    NaN          49.0  216.0
     Winter  28.0   36.0          34.0   NaN    NaN          34.0  176.0
1988 Summer  34.0   43.0          55.0  36.0    NaN          52.0  210.0
     Winter  24.0   39.0          29.0  24.0    NaN          39.0  181.0
1992 Summer  35.0   47.0          48.0  38.0    NaN          54.0  215.0
     Winter  29.0   32.0          30.0  21.0    NaN          36.0  181.0
1994 Winter  29.0   33.0          36.0   NaN   34.0          36.0  181.0
1996 Summer  39.0   53.0          48.0  46.0   46.0          50.0  215.0
1998 Winter  29.0   34.0          36.0  16.0   34.0          40.0  185.0
2000 Summer  39.0   46.0          52.0  38.0   51.0          46.0  226.0
2002 Winter  30.0   38.0          40.0  20.0   41.0          48.0  188.0
2004 Summer  43.0   50.0          48.0  43.0   45.0          52.0  226.0
2006 Winter  32.0   38.0          40.0  29.0   39.0          44.0  188.0
2008 Summer  45.0   51.0          53.0  42.0   48.0          58.0  226.0
2010 Winter  34.0   38.0          45.0  28.0   40.0          40.0  194.0
2012 Summer  41.0   49.0          56.0  39.0   51.0          54.0  221.0
2014 Winter  32.0   37.0          41.0  30.0   42.0          45.0  193.0
2016 Summer  38.0   53.0          60.0  43.0   51.0          52.0  218.0


Team        France Great Britain  India Russia United States
Year Season
1980 Summer  203.0         205.0  196.0    NaN           NaN
     Winter  185.0         183.0    NaN    NaN         193.0
1984 Summer  214.0         203.0  188.0    NaN         213.0
     Winter  185.0         189.0    NaN    NaN         193.0
1988 Summer  203.0         205.0  193.0    NaN         216.0
     Winter  195.0         186.0    NaN    NaN         193.0
1992 Summer  203.0         205.0  188.0    NaN         216.0
     Winter  194.0         184.0    NaN    NaN         193.0
1994 Winter  195.0         185.0    NaN  195.0         193.0
1996 Summer  201.0         205.0  191.0  217.0         216.0
1998 Winter  198.0         185.0  183.0  191.0         195.0
2000 Summer  218.0         204.0  195.0  217.0         207.0
2002 Winter  190.0         193.0  183.0  195.0         193.0
2004 Summer  202.0         207.0  195.0  217.0         213.0
2006 Winter  190.0         193.0  183.0  199.0         195.0
2008 Summer  203.0         207.0  192.0  215.0         211.0
2010 Winter  191.0         193.0  183.0  199.0         193.0
2012 Summer  208.0         211.0  196.0  219.0         216.0
2014 Winter  191.0         193.0  173.0  197.0         196.0
2016 Summer  215.0         207.0  200.0  210.0         211.0