In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('data/olympic_athlete_events.csv', usecols=['Age', 'Height', 'Team', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'], index_col=['Year', 'Season', 'Sport', 'Event'])
df = df.sort_index()
df

                                                                  Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres               24.0     NaN
                      Athletics Men's 1,500 metres                NaN     NaN
                      Athletics Men's 1,500 metres               22.0     NaN
                      Athletics Men's 1,500 metres               23.0   154.0
                      Athletics Men's 1,500 metres               21.0     NaN
...                                                               ...     ...
2016 Summer Wrestling Wrestling Women's Middleweight, Freestyle  33.0   161.0
                      Wrestling Women's Middleweight, Freestyle  26.0   170.0
                      Wrestling Women's Middleweight, Freestyle  25.0   170.0
                      Wrestling Women's Middleweight, Freestyle  21.0   170.0
                      Wrestling Women's Middleweight, Freestyle  25.0   163.0

                                                                          Team  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres               United States
                      Athletics Men's 1,500 metres                      Greece
                      Athletics Men's 1,500 metres                   Australia
                      Athletics Men's 1,500 metres                     Germany
                      Athletics Men's 1,500 metres                      Greece
...                                                                        ...
2016 Summer Wrestling Wrestling Women's Middleweight, Freestyle        Hungary
                      Wrestling Women's Middleweight, Freestyle       Mongolia
                      Wrestling Women's Middleweight, Freestyle         Russia
                      Wrestling Women's Middleweight, Freestyle          China
                      Wrestling Women's Middleweight, Freestyle       Bulgaria

                                                                           City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres                       Athina
                      Athletics Men's 1,500 metres                       Athina
                      Athletics Men's 1,500 metres                       Athina
                      Athletics Men's 1,500 metres                       Athina
                      Athletics Men's 1,500 metres                       Athina
...                                                                         ...
2016 Summer Wrestling Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
                      Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
                      Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
                      Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
                      Wrestling Women's Middleweight, Freestyle  Rio de Janeiro

                                                                  Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres               Silver
                      Athletics Men's 1,500 metres                  NaN
                      Athletics Men's 1,500 metres                 Gold
                      Athletics Men's 1,500 metres                  NaN
                      Athletics Men's 1,500 metres                  NaN
...                                                                 ...
2016 Summer Wrestling Wrestling Women's Middleweight, Freestyle     NaN
                      Wrestling Women's Middleweight, Freestyle     NaN
                      Wrestling Women's Middleweight, Freestyle     NaN
                      Wrestling Women's Middleweight, Freestyle     NaN
                      Wrestling Women's Middleweight, Freestyle     NaN

[271116 rows x 5 columns]

In [7]:
df.index.is_monotonic_increasing

True

In [8]:
df.index.is_monotonic_decreasing

False

In [11]:
df.loc[(slice(1936, 2000), 'Summer'), ['Medal', 'Age']].query('Medal == "Gold"')['Age'].mean()

np.float64(25.1371932032725)

In [22]:
df.loc[(slice(1936, 2000), 'Summer'), ['Age']].mean()

Age    25.026884
dtype: float64

In [16]:
df.loc[(slice(None), slice(None), 'Archery'), ['Medal', 'Team']].query('Medal.notnull()')['Team'].value_counts().head(1)

Team
South Korea    69
Name: count, dtype: int64

In [19]:
df.loc[(slice(1980, None), slice(None), slice(None), "Table Tennis Women's Team"), 'Height'].mean()

np.float64(165.04827586206898)

In [18]:
df.loc[(slice(1980, None), slice(None), slice(None), ["Table Tennis Women's Team", "Table Tennis Men's Team"]), 'Height'].mean()

np.float64(171.26643598615917)

In [21]:
df.loc[(slice(1980, 2016), slice(None), 'Tennis'), 'Height'].max()

208.0

In [23]:
# 23.1

In [24]:
df1 = df.copy()

In [25]:
df1 = df1.reset_index().set_index(keys=['Year', 'Sport', 'Event']).sort_index()
df1

                                                          Season   Age  \
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres               Summer  24.0
               Athletics Men's 1,500 metres               Summer   NaN
               Athletics Men's 1,500 metres               Summer  22.0
               Athletics Men's 1,500 metres               Summer  23.0
               Athletics Men's 1,500 metres               Summer  21.0
...                                                          ...   ...
2016 Wrestling Wrestling Women's Middleweight, Freestyle  Summer  33.0
               Wrestling Women's Middleweight, Freestyle  Summer  26.0
               Wrestling Women's Middleweight, Freestyle  Summer  25.0
               Wrestling Women's Middleweight, Freestyle  Summer  21.0
               Wrestling Women's Middleweight, Freestyle  Summer  25.0

                                                          Height  \
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres                  NaN
               Athletics Men's 1,500 metres                  NaN
               Athletics Men's 1,500 metres                  NaN
               Athletics Men's 1,500 metres                154.0
               Athletics Men's 1,500 metres                  NaN
...                                                          ...
2016 Wrestling Wrestling Women's Middleweight, Freestyle   161.0
               Wrestling Women's Middleweight, Freestyle   170.0
               Wrestling Women's Middleweight, Freestyle   170.0
               Wrestling Women's Middleweight, Freestyle   170.0
               Wrestling Women's Middleweight, Freestyle   163.0

                                                                   Team  \
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres               United States
               Athletics Men's 1,500 metres                      Greece
               Athletics Men's 1,500 metres                   Australia
               Athletics Men's 1,500 metres                     Germany
               Athletics Men's 1,500 metres                      Greece
...                                                                 ...
2016 Wrestling Wrestling Women's Middleweight, Freestyle        Hungary
               Wrestling Women's Middleweight, Freestyle       Mongolia
               Wrestling Women's Middleweight, Freestyle         Russia
               Wrestling Women's Middleweight, Freestyle          China
               Wrestling Women's Middleweight, Freestyle       Bulgaria

                                                                    City  \
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres                       Athina
               Athletics Men's 1,500 metres                       Athina
               Athletics Men's 1,500 metres                       Athina
               Athletics Men's 1,500 metres                       Athina
               Athletics Men's 1,500 metres                       Athina
...                                                                  ...
2016 Wrestling Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
               Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
               Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
               Wrestling Women's Middleweight, Freestyle  Rio de Janeiro
               Wrestling Women's Middleweight, Freestyle  Rio de Janeiro

                                                           Medal
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres               Silver
               Athletics Men's 1,500 metres                  NaN
               Athletics Men's 1,500 metres                 Gold
               Athletics Men's 1,500 metres                  NaN
               Athletics Men's 1,500 metres                  NaN
...                                                          ...
2016 Wrestling Wrestling Women's Middleweight, Freestyle     NaN
               Wrestling Women's Middleweight, Freestyle     NaN
               Wrestling Women's Middleweight, Freestyle     NaN
               Wrestling Women's Middleweight, Freestyle     NaN
               Wrestling Women's Middleweight, Freestyle     NaN

[271116 rows x 6 columns]

In [26]:
df1.loc[(slice(1980, 2016), 'Tennis'), 'Height'].max()

208.0

In [27]:
# 23.2

In [28]:
df.head()

                                                     Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  24.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  22.0     NaN
                      Athletics Men's 1,500 metres  23.0   154.0
                      Athletics Men's 1,500 metres  21.0     NaN

                                                             Team    City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  United States  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres      Australia  Athina
                      Athletics Men's 1,500 metres        Germany  Athina
                      Athletics Men's 1,500 metres         Greece  Athina

                                                     Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  Silver
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres    Gold
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN

In [33]:
df.loc[(slice(1980, None)), ('Medal', 'City')].query('Medal == "Gold"')['City'].value_counts().head(1)

City
Beijing    671
Name: count, dtype: int64

In [34]:
# 23.3

In [35]:
df.head()

                                                     Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  24.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  22.0     NaN
                      Athletics Men's 1,500 metres  23.0   154.0
                      Athletics Men's 1,500 metres  21.0     NaN

                                                             Team    City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  United States  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres      Australia  Athina
                      Athletics Men's 1,500 metres        Germany  Athina
                      Athletics Men's 1,500 metres         Greece  Athina

                                                     Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  Silver
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres    Gold
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN

In [37]:
df.loc[(slice(1980, None)), ['Medal', 'Team']].query('(Medal == "Gold") & (Team == "United States")').count()

Medal    1257
Team     1257
dtype: int64