In [161]:
import numpy as np
import pandas as pd
import datetime as dt
from collections import Counter

In [3]:
df = pd.read_csv('pokemon.csv')

In [4]:
df

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df['Pokemon']

0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
          ...
804      Stakataka
805    Blacephalon
806        Zeraora
807         Meltan
808       Melmetal
Name: Pokemon, Length: 809, dtype: object

In [7]:
type(df['Pokemon'])

pandas.core.series.Series

In [8]:
pok = df['Pokemon']

In [9]:
len(pok)

809

In [10]:
pok.nunique()

809

In [11]:
pok.is_unique

True

In [12]:
t = df['Type']

In [13]:
t.is_unique

False

In [14]:
len(t)

809

In [15]:
t.nunique()

159

In [16]:
t.unique()

array(['Grass / Poison', 'Fire', 'Fire / Flying', 'Water', 'Bug',
       'Bug / Flying', 'Bug / Poison', 'Normal / Flying', 'Normal',
       'Poison', 'Electric', 'Ground', 'Poison / Ground', 'Fairy',
       'Normal / Fairy', 'Poison / Flying', 'Bug / Grass', 'Fighting',
       'Water / Fighting', 'Psychic', 'Water / Poison', 'Rock / Ground',
       'Water / Psychic', 'Electric / Steel', 'Water / Ice',
       'Ghost / Poison', 'Grass / Psychic', 'Ground / Rock', 'Grass',
       'Psychic / Fairy', 'Ice / Psychic', 'Water / Flying',
       'Rock / Water', 'Rock / Flying', 'Ice / Flying',
       'Electric / Flying', 'Dragon', 'Dragon / Flying',
       'Water / Electric', 'Fairy / Flying', 'Psychic / Flying',
       'Water / Fairy', 'Rock', 'Grass / Flying', 'Water / Ground',
       'Dark', 'Dark / Flying', 'Ghost', 'Normal / Psychic',
       'Bug / Steel', 'Ground / Flying', 'Steel / Ground', 'Bug / Rock',
       'Bug / Fighting', 'Dark / Ice', 'Fire / Rock', 'Ice / Ground',
       'Water / Rock', 'Steel / Flying', 'Dark / Fire', 'Water / Dragon',
       'Rock / Dark', 'Psychic / Grass', 'Fire / Fighting',
       'Water / Grass', 'Grass / Dark', 'Bug / Water', 'Grass / Fighting',
       'Bug / Ground', 'Bug / Ghost', 'Dark / Ghost', 'Steel / Fairy',
       'Steel / Rock', 'Fighting / Psychic', 'Water / Dark',
       'Fire / Ground', 'Ground / Dragon', 'Rock / Psychic',
       'Ground / Psychic', 'Rock / Grass', 'Rock / Bug', 'Ice',
       'Ice / Water', 'Steel / Psychic', 'Steel', 'Dragon / Psychic',
       'Grass / Ground', 'Water / Steel', 'Normal / Water',
       'Rock / Steel', 'Ghost / Flying', 'Poison / Dark', 'Ghost / Dark',
       'Dragon / Ground', 'Fighting / Steel', 'Poison / Bug',
       'Poison / Fighting', 'Grass / Ice', 'Psychic / Fighting',
       'Ice / Ghost', 'Electric / Ghost', 'Steel / Dragon',
       'Fire / Steel', 'Ghost / Dragon', 'Psychic / Fire',
       'Ground / Steel', 'Grass / Fairy', 'Ground / Dark',
       'Dark / Fighting', 'Normal / Grass', 'Water / Ghost',
       'Bug / Electric', 'Grass / Steel', 'Ghost / Fire',
       'Ground / Electric', 'Ground / Ghost', 'Dark / Steel',
       'Dark / Dragon', 'Bug / Fire', 'Steel / Fighting',
       'Rock / Fighting', 'Flying', 'Dragon / Fire', 'Dragon / Electric',
       'Dragon / Ice', 'Fire / Psychic', 'Normal / Ground',
       'Fire / Normal', 'Fighting / Dark', 'Steel / Ghost',
       'Dark / Psychic', 'Poison / Water', 'Poison / Dragon',
       'Electric / Normal', 'Rock / Dragon', 'Rock / Ice',
       'Fighting / Flying', 'Electric / Fairy', 'Rock / Fairy',
       'Ghost / Grass', 'Flying / Dragon', 'Psychic / Ghost',
       'Fire / Water', 'Grass / Ghost', 'Fire / Dark', 'Fighting / Ice',
       'Bug / Fairy', 'Water / Bug', 'Poison / Fire', 'Normal / Fighting',
       'Ghost / Ground', 'Fire / Dragon', 'Ghost / Fairy',
       'Normal / Dragon', 'Dragon / Fighting', 'Psychic / Steel',
       'Rock / Poison', 'Fighting / Ghost', 'Fire / Ghost'], dtype=object)

In [20]:
# Ошибка, squeeze - deprecated parameter!!!
# pokemon = pd.read_csv('pokemon.csv', index_col='Pokemon', squeeze=True)

In [22]:
pokemon = pd.read_csv('pokemon.csv', index_col='Pokemon')

In [23]:
pokemon

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

In [24]:
type(pokemon)

pandas.core.frame.DataFrame

In [25]:
pokemon['Type']

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [26]:
pokemon = pokemon['Type']

In [27]:
type(pokemon)

pandas.core.series.Series

In [29]:
pd.read_csv('google_stocks.csv').head()

         Date  Close
0  2004-08-19  49.98
1  2004-08-20  53.95
2  2004-08-23  54.50
3  2004-08-24  52.24
4  2004-08-25  52.80

In [30]:
pd.read_csv('google_stocks.csv', parse_dates = ['Date']).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [31]:
google = pd.read_csv('google_stocks.csv', parse_dates=['Date'], index_col=['Date'])

In [34]:
google = google['Close']

In [35]:
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [36]:
pd.read_csv('revolutionary_war.csv').tail(5)

                         Battle  Start Date     State
227         Siege of Fort Henry   9/11/1782  Virginia
228  Grand Assault on Gibraltar   9/13/1782       NaN
229   Action of 18 October 1782  10/18/1782       NaN
230   Action of 6 December 1782   12/6/1782       NaN
231   Action of 22 January 1783   1/22/1783  Virginia

In [37]:
pd.read_csv('revolutionary_war.csv', parse_dates=['Start Date'], index_col=['Start Date'])

                                       Battle          State
Start Date
1774-09-01                       Powder Alarm  Massachusetts
1774-12-14  Storming of Fort William and Mary  New Hampshire
1775-04-19   Battles of Lexington and Concord  Massachusetts
1775-04-19                    Siege of Boston  Massachusetts
1775-04-20                 Gunpowder Incident       Virginia
...                                       ...            ...
1782-09-11                Siege of Fort Henry       Virginia
1782-09-13         Grand Assault on Gibraltar            NaN
1782-10-18          Action of 18 October 1782            NaN
1782-12-06          Action of 6 December 1782            NaN
1783-01-22          Action of 22 January 1783       Virginia

[232 rows x 2 columns]

In [39]:
battles = pd.read_csv('revolutionary_war.csv', parse_dates=['Start Date'], index_col=['Start Date'], usecols=['Start Date', 'State'])
battles = battles['State']
battles

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

In [40]:
pokemon

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [41]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [42]:
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [43]:
google.sort_values(ascending=False)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
               ...
2004-09-07      50.60
2004-09-02      50.57
2004-08-19      49.98
2004-09-01      49.94
2004-09-03      49.82
Name: Close, Length: 3824, dtype: float64

In [44]:
battles

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

In [45]:
battles.sort_values(na_position='last')

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [47]:
battles.sort_values(na_position='first')

Start Date
1775-09-17         NaN
1775-12-31         NaN
1776-03-03         NaN
1776-03-25         NaN
1776-05-18         NaN
                ...
1781-07-06    Virginia
1781-07-01    Virginia
1781-06-26    Virginia
1781-04-25    Virginia
1783-01-22    Virginia
Name: State, Length: 232, dtype: object

In [48]:
battles.dropna()

Start Date
1774-09-01     Massachusetts
1774-12-14     New Hampshire
1775-04-19     Massachusetts
1775-04-19     Massachusetts
1775-04-20          Virginia
                   ...
1782-08-15          Virginia
1782-08-19          Virginia
1782-08-26    South Carolina
1782-09-11          Virginia
1783-01-22          Virginia
Name: State, Length: 162, dtype: object

In [49]:
battles.dropna().index

DatetimeIndex(['1774-09-01', '1774-12-14', '1775-04-19', '1775-04-19',
               '1775-04-20', '1775-05-10', '1775-05-27', '1775-06-11',
               '1775-06-17', '1775-08-08',
               ...
               '1782-01-02', '1782-02-24', '1782-03-08', '1782-03-22',
               '1782-04-08', '1782-08-15', '1782-08-19', '1782-08-26',
               '1782-09-11', '1783-01-22'],
              dtype='datetime64[ns]', name='Start Date', length=162, freq=None)

In [50]:
battles.dropna().sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1781-07-06       Virginia
1781-07-01       Virginia
1781-06-26       Virginia
1781-04-25       Virginia
1783-01-22       Virginia
Name: State, Length: 162, dtype: object

In [51]:
battles.sort_index()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1783-01-22         Virginia
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
Name: State, Length: 232, dtype: object

In [52]:
pokemon.sort_index()

Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
                  ...
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground
Name: Type, Length: 809, dtype: object

In [53]:
pokemon.sort_index(ascending=True)

Pokemon
Abomasnow        Grass / Ice
Abra                 Psychic
Absol                   Dark
Accelgor                 Bug
Aegislash      Steel / Ghost
                  ...
Zoroark                 Dark
Zorua                   Dark
Zubat        Poison / Flying
Zweilous       Dark / Dragon
Zygarde      Dragon / Ground
Name: Type, Length: 809, dtype: object

In [54]:
battles.sort_index(na_position='first')

Start Date
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
1774-09-01    Massachusetts
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

In [55]:
google.nlargest()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [56]:
google.nsmallest()

Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64

In [57]:
battles

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1782-09-11         Virginia
1782-09-13              NaN
1782-10-18              NaN
1782-12-06              NaN
1783-01-22         Virginia
Name: State, Length: 232, dtype: object

In [59]:
# Ошибка!!!
# battles.nlargest()

In [62]:
battles_v2 = battles.copy()

In [63]:
battles_v2.sort_values(inplace=True)

In [64]:
battles.head()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
Name: State, dtype: object

In [65]:
battles_v2.head()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
Name: State, dtype: object

In [66]:
pokemon

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [67]:
pokemon.nunique()

159

In [68]:
pokemon.value_counts()

Type
Normal                65
Water                 61
Grass                 38
Psychic               35
Fire                  30
                      ..
Fire / Psychic         1
Normal / Ground        1
Psychic / Fighting     1
Dark / Ghost           1
Fire / Ghost           1
Name: count, Length: 159, dtype: int64

In [69]:
pokemon.value_counts(ascending=True)

Type
Fire / Ghost         1
Fighting / Dark      1
Fighting / Steel     1
Normal / Ground      1
Fire / Psychic       1
                    ..
Fire                30
Psychic             35
Grass               38
Water               61
Normal              65
Name: count, Length: 159, dtype: int64

In [70]:
pokemon.value_counts(normalize=True)

Type
Normal                0.080346
Water                 0.075402
Grass                 0.046972
Psychic               0.043263
Fire                  0.037083
                        ...
Fire / Psychic        0.001236
Normal / Ground       0.001236
Psychic / Fighting    0.001236
Dark / Ghost          0.001236
Fire / Ghost          0.001236
Name: proportion, Length: 159, dtype: float64

In [71]:
pokemon.value_counts(normalize=True) * 100.0

Type
Normal                8.034611
Water                 7.540173
Grass                 4.697157
Psychic               4.326329
Fire                  3.708282
                        ...
Fire / Psychic        0.123609
Normal / Ground       0.123609
Psychic / Fighting    0.123609
Dark / Ghost          0.123609
Fire / Ghost          0.123609
Name: proportion, Length: 159, dtype: float64

In [73]:
(pokemon.value_counts(normalize=True) * 100.0).round(2)

Type
Normal                8.03
Water                 7.54
Grass                 4.70
Psychic               4.33
Fire                  3.71
                      ...
Fire / Psychic        0.12
Normal / Ground       0.12
Psychic / Fighting    0.12
Dark / Ghost          0.12
Fire / Ghost          0.12
Name: proportion, Length: 159, dtype: float64

In [74]:
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [75]:
google.value_counts()

Close
287.68     3
194.27     3
307.10     3
288.92     3
290.41     3
          ..
292.43     1
293.41     1
296.75     1
295.46     1
1265.13    1
Name: count, Length: 3696, dtype: int64

In [76]:
google.nunique()

3696

In [77]:
len(google)

3824

In [79]:
(google.value_counts() - 1).sum()

np.int64(128)

In [80]:
len(google) == google.nunique() + 128

True

In [81]:
google.max()

1287.58

In [82]:
google.min()

49.82

In [83]:
google.max() - google.min()

1237.76

In [84]:
google.value_counts(bins=[0, 200, 400, 600, 800, 1000, 1200, 1400])

(200.0, 400.0]      1568
(-0.001, 200.0]      595
(400.0, 600.0]       575
(1000.0, 1200.0]     406
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [90]:
(google.value_counts(bins=[0, 200, 400, 600, 800, 1000, 1200, 1400], normalize=True) * 100).round(1).sort_index()

(-0.001, 200.0]     15.6
(200.0, 400.0]      41.0
(400.0, 600.0]      15.0
(600.0, 800.0]       9.9
(800.0, 1000.0]      5.4
(1000.0, 1200.0]    10.6
(1200.0, 1400.0]     2.4
Name: proportion, dtype: float64

In [93]:
(google.value_counts(bins=[0, 200, 400, 600, 800, 1000, 1200, 1400], sort=False, normalize=True) * 100).round(1)

(-0.001, 200.0]     15.6
(200.0, 400.0]      41.0
(400.0, 600.0]      15.0
(600.0, 800.0]       9.9
(800.0, 1000.0]      5.4
(1000.0, 1200.0]    10.6
(1200.0, 1400.0]     2.4
Name: proportion, dtype: float64

In [99]:
(google.value_counts(bins=15, sort=False, normalize=True) * 100).round(1)

(48.581, 132.337]        5.2
(132.337, 214.855]      14.0
(214.855, 297.372]      25.4
(297.372, 379.889]      11.0
(379.889, 462.407]       4.7
(462.407, 544.924]       6.0
(544.924, 627.441]       6.1
(627.441, 709.959]       2.6
(709.959, 792.476]       6.0
(792.476, 874.993]       2.4
(874.993, 957.511]       2.4
(957.511, 1040.028]      2.8
(1040.028, 1122.545]     4.8
(1122.545, 1205.063]     4.3
(1205.063, 1287.58]      2.1
Name: proportion, dtype: float64

In [100]:
battles.head()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
Name: State, dtype: object

In [101]:
battles.value_counts()

State
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Massachusetts     11
Pennsylvania      10
North Carolina     9
Florida            8
Georgia            6
Rhode Island       3
Connecticut        3
Vermont            3
New Hampshire      1
Delaware           1
Indiana            1
Louisiana          1
Ohio               1
Name: count, dtype: int64

In [102]:
battles.value_counts(dropna=False)

State
NaN               70
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Massachusetts     11
Pennsylvania      10
North Carolina     9
Florida            8
Georgia            6
Rhode Island       3
Connecticut        3
Vermont            3
New Hampshire      1
Delaware           1
Indiana            1
Louisiana          1
Ohio               1
Name: count, dtype: int64

In [104]:
battles.index.value_counts()

Start Date
1781-04-25    2
1781-05-22    2
1780-08-18    2
1781-09-13    2
1782-03-16    2
             ..
1778-06-30    1
1778-07-03    1
1778-07-27    1
1778-08-21    1
1783-01-22    1
Name: count, Length: 217, dtype: int64

In [106]:
funcs = [len, np.max, np.min]

In [109]:
for f in funcs:
    print(f'{f.__name__}: {f(google)}')

len: 3824
max: 1287.58
min: 49.82

In [110]:
google.apply(round)

Date
2004-08-19      50
2004-08-20      54
2004-08-23      54
2004-08-24      52
2004-08-25      53
              ...
2019-10-21    1246
2019-10-22    1243
2019-10-23    1259
2019-10-24    1261
2019-10-25    1265
Name: Close, Length: 3824, dtype: int64

In [111]:
google

Date
2004-08-19      49.98
2004-08-20      53.95
2004-08-23      54.50
2004-08-24      52.24
2004-08-25      52.80
               ...
2019-10-21    1246.15
2019-10-22    1242.80
2019-10-23    1259.13
2019-10-24    1260.99
2019-10-25    1265.13
Name: Close, Length: 3824, dtype: float64

In [112]:
def single_or_multi(pokemon_type):
    if '/' in pokemon_type:
        return 'Multi'
    else:
        return 'Single'

In [113]:
pokemon.apply(single_or_multi)

Pokemon
Bulbasaur       Multi
Ivysaur         Multi
Venusaur        Multi
Charmander     Single
Charmeleon     Single
                ...
Stakataka       Multi
Blacephalon     Multi
Zeraora        Single
Meltan         Single
Melmetal       Single
Name: Type, Length: 809, dtype: object

In [116]:
(pokemon.apply(single_or_multi).value_counts(normalize=True) * 100).round(1)

Type
Multi     50.1
Single    49.9
Name: proportion, dtype: float64

In [117]:
# Homework

In [136]:
# 1
war = pd.read_csv('revolutionary_war.csv', parse_dates=['Start Date'], usecols=['Start Date', 'State'])

In [137]:
war.head()

  Start Date          State
0 1774-09-01  Massachusetts
1 1774-12-14  New Hampshire
2 1775-04-19  Massachusetts
3 1775-04-19  Massachusetts
4 1775-04-20       Virginia

In [138]:
days = war['Start Date']

In [142]:
days

0     1774-09-01
1     1774-12-14
2     1775-04-19
3     1775-04-19
4     1775-04-20
         ...
227   1782-09-11
228   1782-09-13
229   1782-10-18
230   1782-12-06
231   1783-01-22
Name: Start Date, Length: 232, dtype: datetime64[ns]

In [143]:
days = days.dropna()

In [144]:
days.value_counts()

Start Date
1781-04-25    2
1781-05-22    2
1780-08-18    2
1781-09-13    2
1782-03-16    2
             ..
1778-06-30    1
1778-07-03    1
1778-07-27    1
1778-08-21    1
1783-01-22    1
Name: count, Length: 217, dtype: int64

In [152]:
def to_day_name(iso_date):
    return iso_date.strftime('%A')

In [153]:
days.apply(to_day_name).value_counts()

Start Date
Saturday     39
Friday       39
Wednesday    32
Thursday     31
Sunday       31
Tuesday      29
Monday       27
Name: count, dtype: int64

In [154]:
# 2 аналог flatten list
s = pd.Series(data=[[1, 2, 3], [], [5, 6, 7, 8, 9]], index=['a', 'b', 'c'])
s

a          [1, 2, 3]
b                 []
c    [5, 6, 7, 8, 9]
dtype: object

In [155]:
s.explode()

a      1
a      2
a      3
b    NaN
c      5
c      6
c      7
c      8
c      9
dtype: object

In [156]:
s.explode().dropna()

a    1
a    2
a    3
c    5
c    6
c    7
c    8
c    9
dtype: object

In [157]:
pokemon

Pokemon
Bulbasaur      Grass / Poison
Ivysaur        Grass / Poison
Venusaur       Grass / Poison
Charmander               Fire
Charmeleon               Fire
                    ...
Stakataka        Rock / Steel
Blacephalon      Fire / Ghost
Zeraora              Electric
Meltan                  Steel
Melmetal                Steel
Name: Type, Length: 809, dtype: object

In [159]:
pokemon.value_counts(dropna=False)

Type
Normal                65
Water                 61
Grass                 38
Psychic               35
Fire                  30
                      ..
Fire / Psychic         1
Normal / Ground        1
Psychic / Fighting     1
Dark / Ghost           1
Fire / Ghost           1
Name: count, Length: 159, dtype: int64

In [160]:
pokemon.sort_values(na_position='first')

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [164]:
def count_types(pokemon_type):
    c_dict = Counter(pokemon_type)
    return c_dict['/']

In [167]:
pokemon.dropna().apply(count_types).value_counts()

Type
1    405
0    404
Name: count, dtype: int64

In [168]:
def split_types(pokemon_type):
    return pokemon_type.split(' / ')

In [171]:
pokemon.dropna().apply(split_types).explode().value_counts()

Type
Water       131
Normal      109
Flying       98
Grass        97
Psychic      82
Bug          77
Poison       66
Fire         64
Ground       64
Rock         60
Fighting     54
Steel        49
Electric     48
Fairy        47
Dark         46
Dragon       45
Ghost        43
Ice          34
Name: count, dtype: int64