In [15]:
import numpy as np
import pandas as pd

In [16]:
# 1
df = pd.read_csv('revolutionary_war.csv', parse_dates=['Start Date'], usecols=['Start Date'])
df

    Start Date
0   1774-09-01
1   1774-12-14
2   1775-04-19
3   1775-04-19
4   1775-04-20
..         ...
227 1782-09-11
228 1782-09-13
229 1782-10-18
230 1782-12-06
231 1783-01-22

[232 rows x 1 columns]

In [17]:
def date_to_day_name(d):
    return d.dt.strftime('%A')

In [19]:
df = df.apply(date_to_day_name)

In [20]:
df

    Start Date
0     Thursday
1    Wednesday
2    Wednesday
3    Wednesday
4     Thursday
..         ...
227  Wednesday
228     Friday
229     Friday
230     Friday
231  Wednesday

[232 rows x 1 columns]

In [21]:
df.value_counts()

Start Date
Friday        39
Saturday      39
Wednesday     32
Sunday        31
Thursday      31
Tuesday       29
Monday        27
Name: count, dtype: int64

In [22]:
df1 = pd.read_csv('revolutionary_war.csv', parse_dates=['Start Date'], usecols=['Start Date'])

In [23]:
df1.count()

Start Date    228
dtype: int64

In [24]:
len(df1)

232

In [29]:
df1[df1['Start Date'].isnull()]['Start Date'].dt.strftime('%A')

42     NaN
58     NaN
128    NaN
214    NaN
Name: Start Date, dtype: object

In [33]:
df.value_counts(dropna=False)

Start Date
Friday        39
Saturday      39
Wednesday     32
Sunday        31
Thursday      31
Tuesday       29
Monday        27
NaN            4
Name: count, dtype: int64