In [1]:
import numpy as np
import pandas as pd

In [2]:
city_data = {
    'City': ['New York City', 'Paris', 'Barcelona', 'Rome'],
    'Country': ['United States', 'France', 'Spain', 'Italy'],
    'Population': [8600000, 2141000, 5515000, 2873000],
}

In [3]:
city_data

{'City': ['New York City', 'Paris', 'Barcelona', 'Rome'],
 'Country': ['United States', 'France', 'Spain', 'Italy'],
 'Population': [8600000, 2141000, 5515000, 2873000]}

In [5]:
cities = pd.DataFrame(city_data)

In [6]:
cities

            City        Country  Population
0  New York City  United States     8600000
1          Paris         France     2141000
2      Barcelona          Spain     5515000
3           Rome          Italy     2873000

In [8]:
cities.iloc[0,0]

'New York City'

In [9]:
cities.T

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

In [10]:
cities.transpose()

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

In [11]:
random_data = np.random.randint(1, 101, [3, 5])

In [12]:
random_data

array([[ 1, 63, 12, 29, 10],
       [19,  8, 74, 66, 91],
       [18, 23, 29, 48, 29]])

In [13]:
pd.DataFrame(random_data)

    0   1   2   3   4
0   1  63  12  29  10
1  19   8  74  66  91
2  18  23  29  48  29

In [14]:
row_labels = ['Morning', 'Afternoon', 'Evening']

In [15]:
column_labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [16]:
temperatures = pd.DataFrame(data=random_data, index=row_labels, columns=column_labels)

In [17]:
temperatures

           Monday  Tuesday  Wednesday  Thursday  Friday
Morning         1       63         12        29      10
Afternoon      19        8         74        66      91
Evening        18       23         29        48      29

In [18]:
temperatures.shape

(3, 5)

In [19]:
temperatures.size

15

In [20]:
temperatures.ndim

2

In [21]:
temperatures.index

Index(['Morning', 'Afternoon', 'Evening'], dtype='object')

In [22]:
temperatures.columns

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], dtype='object')

In [24]:
temperatures.T

           Morning  Afternoon  Evening
Monday           1         19       18
Tuesday         63          8       23
Wednesday       12         74       29
Thursday        29         66       48
Friday          10         91       29

In [26]:
pd.read_csv('nba.csv')

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [30]:
nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_3868/3729415972.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])

In [33]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [34]:
nba.dtypes.value_counts()

object            3
datetime64[ns]    1
int64             1
Name: count, dtype: int64

In [35]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [36]:
nba.count().sum() == nba.size

np.True_

In [38]:
nba.count().sum()

np.int64(2250)

In [39]:
nba.sample(5)

                        Name             Team Position   Birthday    Salary
69            Damyean Dotson  New York Knicks       SG 1994-05-06   1618520
336              Aron Baynes     Phoenix Suns        C 1986-12-09   5453280
337             Kemba Walker   Boston Celtics       PG 1990-05-08  32742000
411            Chris Clemons  Houston Rockets       SG 1997-07-23     79568
202  Rondae Hollis-Jefferson  Toronto Raptors       SF 1995-01-03   2500000

In [40]:
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [42]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [43]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [45]:
nba.describe()

                  Birthday        Salary
count                  450  4.500000e+02
mean   1993-11-24 02:01:36  7.653584e+06
min    1977-01-26 00:00:00  7.956800e+04
25%    1991-03-16 12:00:00  1.618520e+06
50%    1994-04-29 00:00:00  3.303074e+06
75%    1997-02-17 12:00:00  1.012957e+07
max    2000-12-23 00:00:00  4.023176e+07
std                    NaN  9.288810e+06

In [46]:
nba.nlargest(3, columns=['Salary'])

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482

In [47]:
nba.nsmallest(5, columns=['Birthday'])

               Name               Team Position   Birthday    Salary
98     Vince Carter      Atlanta Hawks       PF 1977-01-26   2564753
196   Udonis Haslem         Miami Heat        C 1980-06-09   2564753
262     Kyle Korver    Milwaukee Bucks       PF 1981-03-17   6004753
149  Tyson Chandler    Houston Rockets        C 1982-10-02   2564753
415  Andre Iguodala  Memphis Grizzlies       SF 1984-01-28  17185185

In [48]:
nba.nlargest(3, columns=['Salary', 'Birthday'])

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482

In [50]:
nba.mean(numeric_only=True)

Salary    7.653584e+06
dtype: float64

In [51]:
nba.sort_values(by=['Name'])

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [52]:
nba.sort_values(by=['Team', 'Salary'])

                Name                Team Position   Birthday    Salary
197    Charlie Brown       Atlanta Hawks       SG 1997-02-02     79568
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
290   Tyrone Wallace       Atlanta Hawks       PG 1994-06-10   1620564
130     Damian Jones       Atlanta Hawks        C 1995-06-30   2305057
..               ...                 ...      ...        ...       ...
226    Davis Bertans  Washington Wizards       PF 1992-11-12   7000000
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
49       Ian Mahinmi  Washington Wizards        C 1986-11-05  15450051
35      Bradley Beal  Washington Wizards       SG 1993-06-28  27093018
251        John Wall  Washington Wizards       PG 1990-09-06  38199000

[450 rows x 5 columns]

In [53]:
nba.sort_values(by=['Team', 'Salary'], ascending=False)

                Name                Team Position   Birthday    Salary
251        John Wall  Washington Wizards       PG 1990-09-06  38199000
35      Bradley Beal  Washington Wizards       SG 1993-06-28  27093018
49       Ian Mahinmi  Washington Wizards        C 1986-11-05  15450051
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
226    Davis Bertans  Washington Wizards       PF 1992-11-12   7000000
..               ...                 ...      ...        ...       ...
130     Damian Jones       Atlanta Hawks        C 1995-06-30   2305057
290   Tyrone Wallace       Atlanta Hawks       PG 1994-06-10   1620564
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
197    Charlie Brown       Atlanta Hawks       SG 1997-02-02     79568
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568

[450 rows x 5 columns]

In [54]:
nba.sort_values(by=['Team', 'Salary'], ascending=[False, True])

                  Name                Team Position   Birthday    Salary
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
..                 ...                 ...      ...        ...       ...
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512

[450 rows x 5 columns]

In [55]:
nba = nba.sort_values(by=['Team', 'Salary'], ascending=[False, True])

In [56]:
nba.head()

                  Name                Team Position   Birthday   Salary
283   Garrison Mathews  Washington Wizards       SG 1996-10-24    79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21    79568
273    Justin Robinson  Washington Wizards       PG 1997-10-12   898310
399  Admiral Schofield  Washington Wizards       SF 1997-03-30  1000000
80         Isaac Bonga  Washington Wizards       PG 1999-11-08  1416852

In [57]:
nba.sort_index()

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [58]:
nba = nba.sort_index()

In [59]:
nba.head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [60]:
nba.sort_index(axis=1)

      Birthday            Name Position    Salary                 Team
0   1996-09-26    Shake Milton       SG   1445697   Philadelphia 76ers
1   1995-09-27  Christian Wood       PF   1645357      Detroit Pistons
2   1998-08-23   PJ Washington       PF   3831840    Charlotte Hornets
3   1988-10-04    Derrick Rose       PG   7317074      Detroit Pistons
4   1995-07-26   Marial Shayok        G     79568   Philadelphia 76ers
..         ...             ...      ...       ...                  ...
445 1992-08-01   Austin Rivers       PG   2174310      Houston Rockets
446 1998-04-22     Harry Giles       PF   2578800     Sacramento Kings
447 1988-04-01     Robin Lopez        C   4767000      Milwaukee Bucks
448 1999-01-04   Collin Sexton       PG   4764960  Cleveland Cavaliers
449 1990-10-21     Ricky Rubio       PG  16200000         Phoenix Suns

[450 rows x 5 columns]

In [61]:
nba.head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [62]:
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [64]:
nba.set_index(keys=['Name'])

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [66]:
nba = nba.set_index(keys=['Name'])

In [67]:
nba

                               Team Position   Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [68]:
nba['Position']

Name
Shake Milton      SG
Christian Wood    PF
PJ Washington     PF
Derrick Rose      PG
Marial Shayok      G
                  ..
Austin Rivers     PG
Harry Giles       PF
Robin Lopez        C
Collin Sexton     PG
Ricky Rubio       PG
Name: Position, Length: 450, dtype: object

In [69]:
nba[['Salary', 'Birthday']]

                  Salary   Birthday
Name
Shake Milton     1445697 1996-09-26
Christian Wood   1645357 1995-09-27
PJ Washington    3831840 1998-08-23
Derrick Rose     7317074 1988-10-04
Marial Shayok      79568 1995-07-26
...                  ...        ...
Austin Rivers    2174310 1992-08-01
Harry Giles      2578800 1998-04-22
Robin Lopez      4767000 1988-04-01
Collin Sexton    4764960 1999-01-04
Ricky Rubio     16200000 1990-10-21

[450 rows x 2 columns]

In [70]:
nba.select_dtypes(exclude=['object'])

                 Birthday    Salary
Name
Shake Milton   1996-09-26   1445697
Christian Wood 1995-09-27   1645357
PJ Washington  1998-08-23   3831840
Derrick Rose   1988-10-04   7317074
Marial Shayok  1995-07-26     79568
...                   ...       ...
Austin Rivers  1992-08-01   2174310
Harry Giles    1998-04-22   2578800
Robin Lopez    1988-04-01   4767000
Collin Sexton  1999-01-04   4764960
Ricky Rubio    1990-10-21  16200000

[450 rows x 2 columns]

In [71]:
nba.select_dtypes(include=['datetime', 'int64'])

                 Birthday    Salary
Name
Shake Milton   1996-09-26   1445697
Christian Wood 1995-09-27   1645357
PJ Washington  1998-08-23   3831840
Derrick Rose   1988-10-04   7317074
Marial Shayok  1995-07-26     79568
...                   ...       ...
Austin Rivers  1992-08-01   2174310
Harry Giles    1998-04-22   2578800
Robin Lopez    1988-04-01   4767000
Collin Sexton  1999-01-04   4764960
Ricky Rubio    1990-10-21  16200000

[450 rows x 2 columns]

In [72]:
nba.loc['Austin Rivers']

Team            Houston Rockets
Position                     PG
Birthday    1992-08-01 00:00:00
Salary                  2174310
Name: Austin Rivers, dtype: object

In [73]:
nba.loc[['Austin Rivers', 'James Harden']]

                          Team Position   Birthday    Salary
Name
Austin Rivers  Houston Rockets       PG 1992-08-01   2174310
James Harden   Houston Rockets       PG 1989-08-26  38199000

In [77]:
nba.loc[['Austin Rivers', 'James Harden'], ['Birthday', 'Salary']].sort_values(by=['Salary'], ascending=False)

                Birthday    Salary
Name
James Harden  1989-08-26  38199000
Austin Rivers 1992-08-01   2174310

In [78]:
nba.head()

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose       Detroit Pistons       PG 1988-10-04  7317074
Marial Shayok   Philadelphia 76ers        G 1995-07-26    79568

In [79]:
nba.rename(columns={'Salary': 'Pay'})

                               Team Position   Birthday       Pay
Name
Shake Milton     Philadelphia 76ers       SG 1996-09-26   1445697
Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
PJ Washington     Charlotte Hornets       PF 1998-08-23   3831840
Derrick Rose        Detroit Pistons       PG 1988-10-04   7317074
Marial Shayok    Philadelphia 76ers        G 1995-07-26     79568
...                             ...      ...        ...       ...
Austin Rivers       Houston Rockets       PG 1992-08-01   2174310
Harry Giles        Sacramento Kings       PF 1998-04-22   2578800
Robin Lopez         Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton   Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio            Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 4 columns]

In [80]:
nba.reset_index()

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [81]:
# Homework

In [82]:
# 1
nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'])

In [83]:
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [85]:
# 2
nfl.set_index(keys=['Name']).head()

                                Team Position   Birthday   Salary
Name
Tremon Smith     Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler     New England Patriots       DT 1994-04-12   645000
Derek Wolfe           Denver Broncos       DE 1990-02-24  8000000
Jake Ryan       Jacksonville Jaguars      OLB 1992-02-27  1000000

In [86]:
pd.read_csv('nfl.csv', parse_dates=['Birthday'], index_col=['Name']).head()

                                Team Position   Birthday   Salary
Name
Tremon Smith     Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler     New England Patriots       DT 1994-04-12   645000
Derek Wolfe           Denver Broncos       DE 1990-02-24  8000000
Jake Ryan       Jacksonville Jaguars      OLB 1992-02-27  1000000

In [88]:
# 3
nfl['Team'].value_counts(ascending=False)

Team
New York Jets           58
Kansas City Chiefs      56
Washington Redskins     56
New Orleans Saints      55
San Francisco 49Ers     55
Denver Broncos          54
Minnesota Vikings       54
Los Angeles Chargers    54
Seattle Seahawks        53
Dallas Cowboys          53
Buffalo Bills           53
Atlanta Falcons         53
Detroit Lions           53
Chicago Bears           53
Los Angeles Rams        52
New York Giants         52
Philadelphia Eagles     52
Houston Texans          52
Arizona Cardinals       51
Cincinnati Bengals      51
Green Bay Packers       51
Oakland Raiders         51
Jacksonville Jaguars    50
Cleveland Browns        49
Miami Dolphins          49
Indianapolis Colts      49
Carolina Panthers       49
New England Patriots    49
Baltimore Ravens        48
Pittsburgh Steelers     47
Tampa Bay Buccaneers    47
Tennessee Titans        46
Name: count, dtype: int64

In [90]:
# 4
nfl.nlargest(5, columns=['Salary'])

                 Name                  Team Position   Birthday    Salary
180      Kirk Cousins     Minnesota Vikings       QB 1988-08-19  27500000
905    Marcus Mariota      Tennessee Titans       QB 1993-10-30  20922000
1623   Jameis Winston  Tampa Bay Buccaneers       QB 1994-01-06  20922000
1343       Derek Carr       Oakland Raiders       QB 1991-03-28  19900000
150   Jimmy Garoppolo   San Francisco 49Ers       QB 1991-11-02  17200000

In [92]:
# 5
nfl.sort_values(by=['Team', 'Salary'], ascending=[True, False])

                    Name                 Team Position   Birthday    Salary
1577      Chandler Jones    Arizona Cardinals      OLB 1990-02-27  16500000
669     Patrick Peterson    Arizona Cardinals       CB 1990-07-11  11000000
1361    Larry Fitzgerald    Arizona Cardinals       WR 1983-08-31  11000000
1594       David Johnson    Arizona Cardinals       RB 1991-12-16   5700000
948          Justin Pugh    Arizona Cardinals        G 1990-08-15   5000000
...                  ...                  ...      ...        ...       ...
1109  Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
1325       Kelvin Harmon  Washington Redskins       WR 1996-12-15    495000
1344          Wes Martin  Washington Redskins        G 1996-05-09    495000
1345      Jimmy Moreland  Washington Redskins       CB 1995-08-26    495000
1509       Jeremy Reaves  Washington Redskins       SS 1996-08-29    495000

[1655 rows x 5 columns]

In [95]:
# 6
nfl.set_index(keys=['Team']).loc['New York Jets'].nsmallest(1, columns=['Birthday'])

                     Name Position   Birthday   Salary
Team
New York Jets  Ryan Kalil        C 1985-03-29  2400000

In [96]:
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]