In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('sales_by_employee.csv', parse_dates=['Date'])
df

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_8673/2892396314.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('sales_by_employee.csv', parse_dates=['Date'])

         Date     Name           Customer  Revenue  Expenses
0  2020-01-01    Oscar      Logistics XYZ     5250       531
1  2020-01-01    Oscar        Money Corp.     4406       661
2  2020-01-02    Oscar         PaperMaven     8661      1401
3  2020-01-03    Oscar        PaperGenius     7075       906
4  2020-01-04    Oscar        Paper Pound     2524      1767
5  2020-01-05    Oscar        Paper Pound     2793       624
6  2020-01-01  Michael      Logistics XYZ     7172       412
7  2020-01-02  Michael        PaperGenius     6362       685
8  2020-01-03  Michael        PaperGenius     5982      1772
9  2020-01-04  Michael     Best Paper Co.     7917      1857
10 2020-01-05  Michael     Best Paper Co.     7837      1633
11 2020-01-01      Jim        PaperGenius     1864      1305
12 2020-01-02      Jim        Money Corp.     8278       462
13 2020-01-03      Jim        Paper Pound     4226      1923
14 2020-01-04      Jim         PaperMaven     3868      1889
15 2020-01-04      Jim  Average Paper Co.     2287       426
16 2020-01-01   Dwight        PaperGenius     2639       368
17 2020-01-03   Dwight      Logistics XYZ     4951       758
18 2020-01-03   Dwight     Best Paper Co.     2703      1321
19 2020-01-03   Dwight      Logistics XYZ     4258      1202
20 2020-01-05   Dwight        Paper Pound     7771      1475
21 2020-01-01    Creed        Money Corp.     4430       548
22 2020-01-02    Creed  Average Paper Co.     8026      1906
23 2020-01-02    Creed  Average Paper Co.     5188      1768
24 2020-01-04    Creed         PaperMaven     3144      1314
25 2020-01-05    Creed        Money Corp.      938      1053

In [4]:
df.head()

        Date   Name       Customer  Revenue  Expenses
0 2020-01-01  Oscar  Logistics XYZ     5250       531
1 2020-01-01  Oscar    Money Corp.     4406       661
2 2020-01-02  Oscar     PaperMaven     8661      1401
3 2020-01-03  Oscar    PaperGenius     7075       906
4 2020-01-04  Oscar    Paper Pound     2524      1767

In [9]:
df.pivot_table(index=['Date'], values=['Revenue', 'Expenses'], aggfunc='mean')

               Expenses      Revenue
Date
2020-01-01   637.500000  4293.500000
2020-01-02  1244.400000  7303.000000
2020-01-03  1313.666667  4865.833333
2020-01-04  1450.600000  3948.000000
2020-01-05  1196.250000  4834.750000

In [10]:
df.pivot_table(index='Date', values=['Revenue', 'Expenses'], aggfunc='mean')

               Expenses      Revenue
Date
2020-01-01   637.500000  4293.500000
2020-01-02  1244.400000  7303.000000
2020-01-03  1313.666667  4865.833333
2020-01-04  1450.600000  3948.000000
2020-01-05  1196.250000  4834.750000

In [17]:
df.pivot_table(index=['Date'], values=['Revenue', 'Expenses'], aggfunc='sum')

            Expenses  Revenue
Date
2020-01-01      3825    25761
2020-01-02      6222    36515
2020-01-03      7882    29195
2020-01-04      7253    19740
2020-01-05      4785    19339

In [21]:
df.pivot_table(
    index=['Date'],
    columns=['Name'],
    values=['Revenue'],
    aggfunc='sum',
    fill_value=0.0,
    margins=True,
    margins_name='Total'
)

                     Revenue
Name                   Creed   Dwight      Jim  Michael    Oscar   Total
Date
2020-01-01 00:00:00   4430.0   2639.0   1864.0   7172.0   9656.0   25761
2020-01-02 00:00:00  13214.0      0.0   8278.0   6362.0   8661.0   36515
2020-01-03 00:00:00      0.0  11912.0   4226.0   5982.0   7075.0   29195
2020-01-04 00:00:00   3144.0      0.0   6155.0   7917.0   2524.0   19740
2020-01-05 00:00:00    938.0   7771.0      0.0   7837.0   2793.0   19339
Total                21726.0  22322.0  20523.0  35270.0  30709.0  130550

In [23]:
df.pivot_table(
    index=['Date'],
    columns=['Name'],
    values=['Revenue'],
    aggfunc=['sum', 'count', 'mean'],
    fill_value=0.0,
    margins=True,
    margins_name='Total'
)

                         sum                                              \
                     Revenue
Name                   Creed   Dwight      Jim  Michael    Oscar   Total
Date
2020-01-01 00:00:00   4430.0   2639.0   1864.0   7172.0   9656.0   25761
2020-01-02 00:00:00  13214.0      0.0   8278.0   6362.0   8661.0   36515
2020-01-03 00:00:00      0.0  11912.0   4226.0   5982.0   7075.0   29195
2020-01-04 00:00:00   3144.0      0.0   6155.0   7917.0   2524.0   19740
2020-01-05 00:00:00    938.0   7771.0      0.0   7837.0   2793.0   19339
Total                21726.0  22322.0  20523.0  35270.0  30709.0  130550

                      count                                    mean  \
                    Revenue                                 Revenue
Name                  Creed Dwight  Jim Michael Oscar Total   Creed
Date
2020-01-01 00:00:00     1.0    1.0  1.0     1.0   2.0     6  4430.0
2020-01-02 00:00:00     2.0    0.0  1.0     1.0   1.0     5  6607.0
2020-01-03 00:00:00     0.0    3.0  1.0     1.0   1.0     6     0.0
2020-01-04 00:00:00     1.0    0.0  2.0     1.0   1.0     5  3144.0
2020-01-05 00:00:00     1.0    1.0  0.0     1.0   1.0     4   938.0
Total                   5.0    5.0  5.0     5.0   6.0    26  4345.2



Name                      Dwight     Jim Michael        Oscar        Total
Date
2020-01-01 00:00:00  2639.000000  1864.0  7172.0  4828.000000  4293.500000
2020-01-02 00:00:00     0.000000  8278.0  6362.0  8661.000000  7303.000000
2020-01-03 00:00:00  3970.666667  4226.0  5982.0  7075.000000  4865.833333
2020-01-04 00:00:00     0.000000  3077.5  7917.0  2524.000000  3948.000000
2020-01-05 00:00:00  7771.000000     0.0  7837.0  2793.000000  4834.750000
Total                4464.400000  4104.6  7054.0  5118.166667  5021.153846

In [24]:
df = pd.read_csv('video_game_sales.csv')
df

,Name,NA,EU,JP,Other
0,Wii Sports,41.49,29.02,3.77,8.46
1,Super Mario Bros.,29.08,3.58,6.81,0.77
2,Mario Kart Wii,15.85,12.88,3.79,3.31
3,Wii Sports Resort,15.75,11.01,3.28,2.96
4,Pokemon Red/Pokemon Blue,11.27,8.89,10.22,1.00
...,...,...,...,...,...
16561,Woody Woodpecker in Crazy Castle 5,0.01,0.00,0.00,0.00
16562,Men in Black II: Alien Escape,0.01,0.00,0.00,0.00
16563,SCORE International Baja 1000: The Official Game,0.00,0.00,0.00,0.00
16564,Know How 2,0.00,0.01,0.00,0.00
16565,Spirits & Spells,0.01,0.00,0.00,0.00

In [25]:
df.melt(id_vars=['Name'], value_vars=['NA', 'EU', 'JP', 'Other'], var_name='Region', value_name='Sales')

                                                   Name Region  Sales
0                                            Wii Sports     NA  41.49
1                                     Super Mario Bros.     NA  29.08
2                                        Mario Kart Wii     NA  15.85
3                                     Wii Sports Resort     NA  15.75
4                              Pokemon Red/Pokemon Blue     NA  11.27
...                                                 ...    ...    ...
66259                Woody Woodpecker in Crazy Castle 5  Other   0.00
66260                     Men in Black II: Alien Escape  Other   0.00
66261  SCORE International Baja 1000: The Official Game  Other   0.00
66262                                        Know How 2  Other   0.00
66263                                  Spirits & Spells  Other   0.00

[66264 rows x 3 columns]

In [26]:
df = pd.read_csv('recipes.csv')
df

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  Apricot preserves, Dijon mustard, curry powder...
1      Tomato Basil Salmon  Salmon filets, basil, tomato, olive oil, Parme...
2  Parmesan Cheese Chicken  Bread crumbs, Parmesan cheese, Italian seasoni...

In [27]:
df['Ingredients'] = df['Ingredients'].str.split(',')
df

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  [Apricot preserves,  Dijon mustard,  curry pow...
1      Tomato Basil Salmon  [Salmon filets,  basil,  tomato,  olive oil,  ...
2  Parmesan Cheese Chicken  [Bread crumbs,  Parmesan cheese,  Italian seas...

In [29]:
df.explode('Ingredients')

                    Recipe         Ingredients
0   Cashew Crusted Chicken   Apricot preserves
0   Cashew Crusted Chicken       Dijon mustard
0   Cashew Crusted Chicken        curry powder
0   Cashew Crusted Chicken     chicken breasts
0   Cashew Crusted Chicken             cashews
1      Tomato Basil Salmon       Salmon filets
1      Tomato Basil Salmon               basil
1      Tomato Basil Salmon              tomato
1      Tomato Basil Salmon           olive oil
1      Tomato Basil Salmon     Parmesan cheese
2  Parmesan Cheese Chicken        Bread crumbs
2  Parmesan Cheese Chicken     Parmesan cheese
2  Parmesan Cheese Chicken   Italian seasoning
2  Parmesan Cheese Chicken                 egg
2  Parmesan Cheese Chicken     chicken breasts

In [31]:
# Exercises

In [32]:
cars = pd.read_csv('used_cars.csv')
cars

       Manufacturer  Year   Fuel Transmission  Price
0             Acura  2012    Gas    Automatic  10299
1            Jaguar  2011    Gas    Automatic   9500
2             Honda  2004    Gas    Automatic   3995
3         Chevrolet  2016    Gas    Automatic  41988
4               Kia  2015    Gas    Automatic  12995
...             ...   ...    ...          ...    ...
460461        Rover  2008    Gas    Automatic   7950
460462       Nissan  2016    Gas    Automatic  13995
460463          BMW  2010    Gas    Automatic  10995
460464        Dodge  2015  Other       Manual   6495
460465          GMC  2008    Gas    Automatic   8990

[460466 rows x 5 columns]

In [33]:
min_wage = pd.read_csv('minimum_wage.csv')
min_wage

                   State  2010  2011  2012  2013   2014   2015   2016   2017
0                Alabama  0.00  0.00  0.00  0.00   0.00   0.00   0.00   0.00
1                 Alaska  8.90  8.63  8.45  8.33   8.20   9.24  10.17  10.01
2                Arizona  8.33  8.18  8.34  8.38   8.36   8.50   8.40  10.22
3               Arkansas  7.18  6.96  6.82  6.72   6.61   7.92   8.35   8.68
4             California  9.19  8.91  8.72  8.60   9.52   9.51  10.43  10.22
5               Colorado  8.31  8.19  8.33  8.36   8.46   8.69   8.67   9.50
6            Connecticut  9.47  9.18  9.00  8.87   9.20   9.67  10.02  10.32
7               Delaware  8.33  8.07  7.91  7.79   8.20   8.72   8.61   8.43
8   District of Columbia  9.47  9.18  9.00  8.87  10.05  11.09  12.00  11.75
9         Federal (FLSA)  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
10               Florida  8.33  8.07  8.37  8.37   8.39   8.50   8.40   8.27
11               Georgia  5.91  5.73  5.62  5.54   5.45   5.44   5.37   5.26
12                  Guam  8.33  8.07  7.91  7.79   7.67   8.72   8.61   8.43
13                Hawaii  8.33  8.07  7.91  7.79   7.67   8.19   8.87   9.45
14                 Idaho  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
15              Illinois  9.19  9.18  9.00  8.87   8.73   8.72   8.61   8.43
16               Indiana  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
17                  Iowa  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
18                Kansas  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
19              Kentucky  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
20             Louisiana  0.00  0.00  0.00  0.00   0.00   0.00   0.00   0.00
21                 Maine  8.61  8.35  8.18  8.06   7.93   7.92   7.82   9.19
22              Maryland  8.33  8.07  7.91  7.79   7.67   8.72   9.13   8.94
23         Massachusetts  9.19  8.91  8.72  8.60   8.46   9.51  10.43  11.24
24              Michigan  8.50  8.24  8.07  7.95   8.62   8.61   8.87   9.09
25             Minnesota  7.06  6.85  6.71  6.61   8.46   9.51   9.91   9.70
26           Mississippi  0.00  0.00  0.00  0.00   0.00   0.00   0.00   0.00
27              Missouri  8.33  8.07  7.91  7.90   7.93   8.08   7.98   7.87
28               Montana  8.33  8.18  8.34  8.38   8.36   8.50   8.40   8.33
29              Nebraska  8.33  8.07  7.91  7.79   7.67   8.45   9.39   9.19
30                Nevada  8.67  9.18  9.00  8.87   8.73   8.72   8.61   8.43
31         New Hampshire  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
32            New Jersey  8.33  8.07  7.91  7.79   8.73   8.85   8.74   8.62
33            New Mexico  8.61  8.35  8.18  8.06   7.93   7.92   7.82   7.66
34              New York  8.33  8.07  7.91  7.79   8.46   9.24   9.39   9.91
35        North Carolina  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
36          North Dakota  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
37                  Ohio  8.38  8.24  8.40  8.44   8.41   8.56   8.45   8.33
38              Oklahoma  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
39                Oregon  9.65  9.46  9.60  9.62   9.63   9.77  10.17   9.96
40          Pennsylvania  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
41           Puerto Rico  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
42          Rhode Island  8.50  8.24  8.07  8.33   8.46   9.51  10.02   9.81
43        South Carolina  0.00  0.00  0.00  0.00   0.00   0.00   0.00   0.00
44          South Dakota  8.33  8.07  7.91  7.79   7.67   8.98   8.92   8.84
45             Tennessee  0.00  0.00  0.00  0.00   0.00   0.00   0.00   0.00
46                 Texas  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
47   U.S. Virgin Islands  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
48                  Utah  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
49               Vermont  9.26  9.07  9.23  9.24   9.23   9.67  10.02  10.22
50              Virginia  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
51            Washington  9.82  9.65  9.86  9.88   9.86  10.00   9.88  11.24
52         West Virginia  8.33  8.07  7.91  7.79   7.67   8.45   9.13   8.94
53             Wisconsin  8.33  8.07  7.91  7.79   7.67   7.66   7.56   7.41
54               Wyoming  5.91  5.73  5.62  5.54   5.45   5.44   5.37   5.26

In [34]:
# 1

In [35]:
cars.head()

  Manufacturer  Year Fuel Transmission  Price
0        Acura  2012  Gas    Automatic  10299
1       Jaguar  2011  Gas    Automatic   9500
2        Honda  2004  Gas    Automatic   3995
3    Chevrolet  2016  Gas    Automatic  41988
4          Kia  2015  Gas    Automatic  12995

In [36]:
cars.pivot_table(index=['Fuel'], values=['Price'], aggfunc='sum')

                Price
Fuel
Diesel      986177143
Electric     18502957
Gas       86203853926
Hybrid       44926064
Other       242096286

In [37]:
# 2

In [44]:
cars.pivot_table(index=['Manufacturer'], columns=['Transmission'], aggfunc='count', values=['Price'], margins=True, margins_name='Total').tail(5)

                 Price
Transmission Automatic   Manual    Other   Total
Manufacturer
Tesla            179.0      NaN     59.0     238
Toyota         31480.0   1367.0   2134.0   34981
Volkswagen      7985.0   1286.0    236.0    9507
Volvo           2665.0    155.0     50.0    2870
Total         398428.0  21005.0  21738.0  441171

In [45]:
# 3

In [48]:
report = cars.pivot_table(index=['Year', 'Fuel'], columns=['Transmission'], values=['Price'], aggfunc='mean')

In [49]:
report

                      Price
Transmission      Automatic        Manual         Other
Year Fuel
2000 Diesel    11326.176962  14010.164021  11075.000000
     Electric   1500.000000           NaN           NaN
     Gas        4314.675996   6226.140327   3203.538462
     Hybrid     2600.000000   2400.000000           NaN
     Other     16014.918919  11361.952381  12984.642857
...                     ...           ...           ...
2020 Diesel    63272.595930      1.000000   1234.000000
     Electric   8015.166667   2200.000000  20247.500000
     Gas       34925.857933  36007.270833  20971.045455
     Hybrid    35753.200000           NaN   1234.000000
     Other     22210.306452           NaN   2725.925926

[102 rows x 3 columns]

In [50]:
# 4

In [51]:
report.stack()

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_8673/1233351165.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  report.stack()

                                   Price
Year Fuel     Transmission
2000 Diesel   Automatic     11326.176962
              Manual        14010.164021
              Other         11075.000000
     Electric Automatic      1500.000000
     Gas      Automatic      4314.675996
...                                  ...
2020 Gas      Other         20971.045455
     Hybrid   Automatic     35753.200000
              Other          1234.000000
     Other    Automatic     22210.306452
              Other          2725.925926

[274 rows x 1 columns]

In [52]:
# 5

In [53]:
min_wage.head()

        State  2010  2011  2012  2013  2014  2015   2016   2017
0     Alabama  0.00  0.00  0.00  0.00  0.00  0.00   0.00   0.00
1      Alaska  8.90  8.63  8.45  8.33  8.20  9.24  10.17  10.01
2     Arizona  8.33  8.18  8.34  8.38  8.36  8.50   8.40  10.22
3    Arkansas  7.18  6.96  6.82  6.72  6.61  7.92   8.35   8.68
4  California  9.19  8.91  8.72  8.60  9.52  9.51  10.43  10.22

In [56]:
cols = [str(i) for i in range(2010, 2018)]

In [57]:
min_wage.melt(id_vars=['State'], value_vars=cols, value_name='min_wage', var_name='year')

             State  year  min_wage
0          Alabama  2010      0.00
1           Alaska  2010      8.90
2          Arizona  2010      8.33
3         Arkansas  2010      7.18
4       California  2010      9.19
..             ...   ...       ...
435       Virginia  2017      7.41
436     Washington  2017     11.24
437  West Virginia  2017      8.94
438      Wisconsin  2017      7.41
439        Wyoming  2017      5.26

[440 rows x 3 columns]