In [1]:
import numpy as np
import pandas as pd

In [5]:
employees = pd.read_csv('employees.csv', parse_dates=['Start Date'])

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_9532/1717237049.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv('employees.csv', parse_dates=['Start Date'])

In [6]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [7]:
employees.head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [9]:
employees['Mgmt'] = employees['Mgmt'].astype(np.bool)

In [10]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [14]:
employees['Salary'] = employees['Salary'].fillna(0).astype(np.int64)

In [15]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), int64(1), object(3)
memory usage: 40.2+ KB

In [16]:
employees.head()

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT

In [18]:
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [19]:
employees['Team'] = employees['Team'].astype('category')

In [20]:
employees['Gender'] = employees['Gender'].astype('category')

In [21]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

In [24]:
employees[employees['First Name'] == 'Maria']

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [25]:
employees[employees['Team'] != 'Finance']

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [27]:
employees[employees['Mgmt']]

     First Name  Gender Start Date  Salary  Mgmt         Team
0       Douglas    Male 1993-08-06       0  True    Marketing
1        Thomas    Male 1996-03-31   61933  True          NaN
3         Jerry     NaN 2005-03-04  138705  True      Finance
4         Larry    Male 1998-01-24  101004  True           IT
6          Ruby  Female 1987-08-17   65476  True      Product
...         ...     ...        ...     ...   ...          ...
992     Anthony    Male 2011-10-16  112769  True      Finance
993        Tina  Female 1997-05-15   56450  True  Engineering
994      George    Male 2013-06-21   98874  True    Marketing
999      Albert    Male 2012-05-15  129949  True        Sales
1000        NaN     NaN        NaT       0  True          NaN

[536 rows x 6 columns]

In [28]:
bool_series = pd.Series(data=[True, False, False])

In [29]:
bool_series

0     True
1    False
2    False
dtype: bool

In [30]:
~bool_series

0    False
1     True
2     True
dtype: bool

In [31]:
not_bool_series = pd.Series(data=['a', 'b', 'c'])

In [32]:
not_bool_series

0    a
1    b
2    c
dtype: object

In [34]:
# ~not_bool_series - Будет ошибка!

In [36]:
help(pd.Series.between)

Help on function between in module pandas.core.series:

between(
    self,
    left,
    right,
    inclusive: "Literal['both', 'neither', 'left', 'right']" = 'both'
) -> 'Series'
    Return boolean Series equivalent to left <= series <= right.

    This function returns a boolean vector containing `True` wherever the
    corresponding Series element is between the boundary values `left` and
    `right`. NA values are treated as `False`.

    Parameters
    ----------
    left : scalar or list-like
        Left boundary.
    right : scalar or list-like
        Right boundary.
    inclusive : {"both", "neither", "left", "right"}
        Include boundaries. Whether to set each bound as closed or open.

        .. versionchanged:: 1.3.0

    Returns
    -------
    Series
        Series representing whether each element is between left and
        right (inclusive).

    See Also
    --------
    Series.gt : Greater than of series and other.
    Series.lt : Less than of series and other.

    Notes
    -----
    This function is equivalent to ``(left <= ser) & (ser <= right)``

    Examples
    --------
    >>> s = pd.Series([2, 0, 4, 8, np.nan])

    Boundary values are included by default:

    >>> s.between(1, 4)
    0     True
    1    False
    2     True
    3    False
    4    False
    dtype: bool

    With `inclusive` set to ``"neither"`` boundary values are excluded:

    >>> s.between(1, 4, inclusive="neither")
    0     True
    1    False
    2    False
    3    False
    4    False
    dtype: bool

    `left` and `right` can be any scalar value:

    >>> s = pd.Series(['Alice', 'Bob', 'Carol', 'Eve'])
    >>> s.between('Anna', 'Daniel')
    0    False
    1     True
    2     True
    3    False
    dtype: bool

In [37]:
help(pd.DataFrame.dropna)

Help on function dropna in module pandas.core.frame:

dropna(
    self,
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False
) -> 'DataFrame | None'
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [45]:
employees.dropna(subset=['Gender', 'First Name', 'Salary', 'Team'], thresh=4)

    First Name  Gender Start Date  Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       0   True     Marketing
2        Maria  Female        NaT  130590  False       Finance
4        Larry    Male 1998-01-24  101004   True            IT
5       Dennis    Male 1987-04-18  115163  False         Legal
6         Ruby  Female 1987-08-17   65476   True       Product
..         ...     ...        ...     ...    ...           ...
994     George    Male 2013-06-21   98874   True     Marketing
996    Phillip    Male 1984-01-31   42392  False       Finance
997    Russell    Male 2013-05-20   96914  False       Product
998      Larry    Male 2013-04-20   60500  False  Business Dev
999     Albert    Male 2012-05-15  129949   True         Sales

[763 rows x 6 columns]

In [47]:
employees.drop_duplicates(keep=False)

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
2         Maria  Female        NaT  130590  False       Finance
3         Jerry     NaN 2005-03-04  138705   True       Finance
4         Larry    Male 1998-01-24  101004   True            IT
...         ...     ...        ...     ...    ...           ...
996     Phillip    Male 1984-01-31   42392  False       Finance
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[1001 rows x 6 columns]

In [48]:
# Exercises

In [49]:
# 1

In [75]:
netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'], index_col=['title'])

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_9532/3093996982.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  netflix = pd.read_csv('netflix.csv', parse_dates=['date_added'], index_col=['title'])

In [76]:
netflix

                             director date_added     type
title
Alias Grace                       NaN 2017-11-03  TV Show
A Patch of Fog         Michael Lennox 2017-04-15    Movie
Lunatics                          NaN 2019-04-19  TV Show
Uriyadi 2                 Vijay Kumar 2019-08-02    Movie
Shrek the Musical         Jason Moore 2013-12-29    Movie
...                               ...        ...      ...
The Pursuit               John Papola 2019-08-07    Movie
Hurricane Bianca        Matt Kugelman 2017-01-01    Movie
Amar's Hands           Khaled Youssef 2019-04-26    Movie
Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
Age of Glory                      NaN        NaT  TV Show

[5837 rows x 3 columns]

In [77]:
netflix.memory_usage()

Index         46696
director      46696
date_added    46696
type          46696
dtype: int64

In [78]:
netflix.memory_usage().sum()

np.int64(186784)

In [79]:
netflix.count()

director      3936
date_added    5195
type          5837
dtype: int64

In [80]:
netflix.nunique()

director      3024
date_added    1092
type             2
dtype: int64

In [81]:
netflix['type'] = netflix['type'].astype('category')

In [82]:
netflix

                             director date_added     type
title
Alias Grace                       NaN 2017-11-03  TV Show
A Patch of Fog         Michael Lennox 2017-04-15    Movie
Lunatics                          NaN 2019-04-19  TV Show
Uriyadi 2                 Vijay Kumar 2019-08-02    Movie
Shrek the Musical         Jason Moore 2013-12-29    Movie
...                               ...        ...      ...
The Pursuit               John Papola 2019-08-07    Movie
Hurricane Bianca        Matt Kugelman 2017-01-01    Movie
Amar's Hands           Khaled Youssef 2019-04-26    Movie
Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
Age of Glory                      NaN        NaT  TV Show

[5837 rows x 3 columns]

In [83]:
netflix.memory_usage()

Index         46696
director      46696
date_added    46696
type           5961
dtype: int64

In [84]:
netflix.memory_usage().sum()

np.int64(146049)

In [85]:
netflix['type'].unique()

['TV Show', 'Movie']
Categories (2, object): ['Movie', 'TV Show']

In [86]:
# 2

In [88]:
netflix = netflix.reset_index()

In [89]:
netflix.head()

               title        director date_added     type
0        Alias Grace             NaN 2017-11-03  TV Show
1     A Patch of Fog  Michael Lennox 2017-04-15    Movie
2           Lunatics             NaN 2019-04-19  TV Show
3          Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4  Shrek the Musical     Jason Moore 2013-12-29    Movie

In [90]:
netflix[netflix['title'] == 'Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [91]:
# 3

In [96]:
netflix.query('(director == "Robert Rodriguez") & (type == "Movie")')

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [97]:
# 4

In [99]:
netflix[(netflix['date_added'] == '2019-07-31') | (netflix['director'] == 'Robert Altman')]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

In [100]:
# 5

In [105]:
netflix.query('(director in ["Orson Welles", "Aditya Kripalani"]) | (director == "Sam Raimi")')

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [106]:
# 6

In [107]:
netflix[netflix['date_added'].between('2019-05-01', '2019-06-01', inclusive='left')]

,title,director,date_added,type
29,Chopsticks,Sachin Yardi,2019-05-31,Movie
60,Away From Home,NaN,2019-05-08,TV Show
108,Jailbirds,NaN,2019-05-10,TV Show
124,Pegasus,Han Han,2019-05-31,Movie
154,When They See Us,NaN,2019-05-31,TV Show
...,...,...,...,...
5625,The Nutcracker and the Four Realms,Lasse Hallström,2019-05-28,Movie
5675,Rim of the World,McG,2019-05-24,Movie
5677,Malibu Rescue,Savage Steve Holland,2019-05-13,Movie
5739,Mission Istaanbul: Darr Ke Aagey Jeet Hai,Apoorva Lakhia,2019-05-16,Movie
5829,The Kindness Diaries,NaN,2019-05-01,TV Show

In [108]:
# 7

In [109]:
netflix.dropna(subset=['director'])

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

In [110]:
# 8

In [120]:
netflix.drop_duplicates(subset=['date_added'], keep=False)['date_added'].unique()

<DatetimeArray>
['2013-12-29 00:00:00', '2017-05-31 00:00:00', '2015-10-02 00:00:00',
 '2019-08-25 00:00:00', '2014-02-16 00:00:00', '2015-10-14 00:00:00',
 '2016-03-31 00:00:00', '2016-07-25 00:00:00', '2019-11-03 00:00:00',
 '2019-01-21 00:00:00',
 ...
 '2017-10-10 00:00:00', '2016-04-20 00:00:00', '2019-10-06 00:00:00',
 '2015-10-25 00:00:00', '2017-10-18 00:00:00', '2017-08-27 00:00:00',
 '2018-11-12 00:00:00', '2017-10-07 00:00:00', '2015-12-04 00:00:00',
 '2019-04-22 00:00:00']
Length: 391, dtype: datetime64[ns]