In [1]:
import numpy as np
import pandas as pd

In [2]:
dict_cities = {
    'City': ['Moscow', 'London', 'Washington'],
    'Country': ['Russia', 'UK', 'US'],
    'Population': [15000000, 10000000, 5000000]
}

In [5]:
cities = pd.DataFrame(data=dict_cities)
cities

         City Country  Population
0      Moscow  Russia    15000000
1      London      UK    10000000
2  Washington      US     5000000

In [9]:
cities.transpose()

                   0         1           2
City          Moscow    London  Washington
Country       Russia        UK          US
Population  15000000  10000000     5000000

In [10]:
random_data = np.random.randint(1, 101, (3, 5))
random_data

array([[ 81,  76,  22,  86,  37],
       [ 77,  31,  73,  56,   3],
       [ 86, 100,  40,  98,  85]])

In [11]:
df = pd.DataFrame(data=random_data)
df

    0    1   2   3   4
0  81   76  22  86  37
1  77   31  73  56   3
2  86  100  40  98  85

In [12]:
row_labels = ['First', 'Second', 'Third']

In [13]:
df = pd.DataFrame(data=random_data, index=row_labels)
df

         0    1   2   3   4
First   81   76  22  86  37
Second  77   31  73  56   3
Third   86  100  40  98  85

In [14]:
column_labels = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [15]:
df = pd.DataFrame(data=random_data, index=row_labels, columns=column_labels)
df

        Monday  Tuesday  Wednesday  Thursday  Friday
First       81       76         22        86      37
Second      77       31         73        56       3
Third       86      100         40        98      85

In [16]:
column_labels = ['Monday', 'Tuesday', 'Wednesday', 'Tuesday', 'Friday']

In [17]:
df = pd.DataFrame(data=random_data, index=row_labels, columns=column_labels)
df

        Monday  Tuesday  Wednesday  Tuesday  Friday
First       81       76         22       86      37
Second      77       31         73       56       3
Third       86      100         40       98      85

In [18]:
df['Tuesday']

        Tuesday  Tuesday
First        76       86
Second       31       56
Third       100       98

In [21]:
nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])
nba

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_3420/2576395300.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv('nba.csv', parse_dates=['Birthday'])

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [22]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [28]:
nba.dtypes.value_counts(ascending=True, normalize=False)

datetime64[ns]    1
int64             1
object            3
Name: count, dtype: int64

In [29]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [30]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [31]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [32]:
nba.ndim

2

In [33]:
nba.shape

(450, 5)

In [34]:
nba.size

2250

In [35]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [36]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [38]:
nba.count().sum() - nba.size

np.int64(0)

In [39]:
nba.sample(10)

,Name,Team,Position,Birthday,Salary
182,Shai Gilgeous-Alexander,Oklahoma City Thunder,PG,1998-07-12,3952920
382,Jae Crowder,Memphis Grizzlies,SF,1990-07-06,7815533
316,Elfrid Payton,New York Knicks,PG,1994-02-22,8000000
57,Juwan Morgan,Utah Jazz,F,1997-04-17,796806
408,LeBron James,Los Angeles Lakers,PF,1984-12-30,37436858
438,Bruno Fernando,Atlanta Hawks,C,1998-08-15,1400000
136,Sekou Doumbouya,Detroit Pistons,SF,2000-12-23,3285120
163,Rudy Gay,San Antonio Spurs,PF,1986-08-17,14500000
68,Robert Covington,Minnesota Timberwolves,PF,1990-12-14,11301219
19,Marcus Morris,New York Knicks,PF,1989-09-02,15000000

In [41]:
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [42]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [43]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [47]:
nba.nlargest(n=5, columns=['Salary', 'Birthday'])

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000
264       James Harden        Houston Rockets       PG 1989-08-26  38199000

In [49]:
nba.sum(numeric_only=True)

Salary    3444112694
dtype: int64

In [51]:
nba['Salary'].mode()

0    79568
Name: Salary, dtype: int64

In [52]:
nba['Salary'].value_counts()

Salary
79568       49
1416852     21
898310      19
2564753     11
4767000      9
            ..
3567720      1
14500000     1
3581986      1
4033440      1
16200000     1
Name: count, Length: 269, dtype: int64

In [53]:
nba.sort_values(by=['Salary', 'Birthday'], ascending=[False, True]).head(3)

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482

In [54]:
nba = nba.sort_values(by=['Salary', 'Birthday'], ascending=[False, True])

In [55]:
nba

                  Name                    Team Position   Birthday    Salary
205      Stephen Curry   Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul   Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook         Houston Rockets       PG 1988-11-12  38506482
264       James Harden         Houston Rockets       PG 1989-08-26  38199000
251          John Wall      Washington Wizards       PG 1990-09-06  38199000
..                 ...                     ...      ...        ...       ...
100        Brian Bowen          Indiana Pacers       SG 1998-10-02     79568
24        Jaylen Hoard  Portland Trail Blazers       SF 1999-03-30     79568
400         Louis King         Detroit Pistons        F 1999-04-06     79568
131      Luguentz Dort   Oklahoma City Thunder        G 1999-04-19     79568
370            Bol Bol          Denver Nuggets        C 1999-11-16     79568

[450 rows x 5 columns]

In [57]:
nba.sort_index(axis=0, ascending=True, na_position='first')

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [58]:
nba.sort_index(axis=1, ascending=False)

                       Team    Salary Position               Name   Birthday
205   Golden State Warriors  40231758       PG      Stephen Curry 1988-03-14
38    Oklahoma City Thunder  38506482       PG         Chris Paul 1985-05-06
219         Houston Rockets  38506482       PG  Russell Westbrook 1988-11-12
264         Houston Rockets  38199000       PG       James Harden 1989-08-26
251      Washington Wizards  38199000       PG          John Wall 1990-09-06
..                      ...       ...      ...                ...        ...
100          Indiana Pacers     79568       SG        Brian Bowen 1998-10-02
24   Portland Trail Blazers     79568       SF       Jaylen Hoard 1999-03-30
400         Detroit Pistons     79568        F         Louis King 1999-04-06
131   Oklahoma City Thunder     79568        G      Luguentz Dort 1999-04-19
370          Denver Nuggets     79568        C            Bol Bol 1999-11-16

[450 rows x 5 columns]

In [68]:
nba.set_index(keys=['Name', 'Team']).sort_index(axis=0, level=['Team', 'Name'], ascending=[True, False])

                                     Position   Birthday    Salary
Name              Team
Vince Carter      Atlanta Hawks            PF 1977-01-26   2564753
Tyrone Wallace    Atlanta Hawks            PG 1994-06-10   1620564
Kevin Huerter     Atlanta Hawks            SG 1998-08-27   2636280
John Collins      Atlanta Hawks            PF 1997-09-23   2686560
Jabari Parker     Atlanta Hawks            PF 1995-03-15   6500000
...                                       ...        ...       ...
Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
Davis Bertans     Washington Wizards       PF 1992-11-12   7000000
Chris Chiozza     Washington Wizards       PG 1995-11-21     79568
Bradley Beal      Washington Wizards       SG 1993-06-28  27093018
Admiral Schofield Washington Wizards       SF 1997-03-30   1000000

[450 rows x 3 columns]

In [73]:
nba[['Salary', 'Team', 'Name']].head()

       Salary                   Team               Name
205  40231758  Golden State Warriors      Stephen Curry
38   38506482  Oklahoma City Thunder         Chris Paul
219  38506482        Houston Rockets  Russell Westbrook
264  38199000        Houston Rockets       James Harden
251  38199000     Washington Wizards          John Wall

In [74]:
nba.select_dtypes(include=np.int64)

       Salary
205  40231758
38   38506482
219  38506482
264  38199000
251  38199000
..        ...
100     79568
24      79568
400     79568
131     79568
370     79568

[450 rows x 1 columns]

In [76]:
nba.select_dtypes(exclude=['object', np.int64])

      Birthday
205 1988-03-14
38  1985-05-06
219 1988-11-12
264 1989-08-26
251 1990-09-06
..         ...
100 1998-10-02
24  1999-03-30
400 1999-04-06
131 1999-04-19
370 1999-11-16

[450 rows x 1 columns]

In [77]:
nba.head()

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
264       James Harden        Houston Rockets       PG 1989-08-26  38199000
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [78]:
nba = nba.set_index(keys=['Name']).sort_index()

In [79]:
nba

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
...                                  ...      ...        ...       ...
Zach LaVine                Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell          Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith          Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson     New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham      New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 4 columns]

In [80]:
nba.loc['LeBron James']

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [82]:
nba.loc[['LeBron James', 'Zach LaVine']]

                            Team Position   Birthday    Salary
Name
LeBron James  Los Angeles Lakers       PF 1984-12-30  37436858
Zach LaVine        Chicago Bulls       PG 1995-03-10  19500000

In [83]:
nba.loc[:'LeBron James']

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
...                                  ...      ...        ...       ...
LaMarcus Aldridge      San Antonio Spurs        C 1985-07-19  26000000
Landry Shamet       Los Angeles Clippers       SG 1997-03-13   1995120
Langston Galloway        Detroit Pistons       PG 1991-12-09   7333333
Lauri Markkanen            Chicago Bulls       PF 1997-05-22   5300400
LeBron James          Los Angeles Lakers       PF 1984-12-30  37436858

[282 rows x 4 columns]

In [84]:
nba.loc['LeBron James':]

                                  Team Position   Birthday    Salary
Name
LeBron James        Los Angeles Lakers       PF 1984-12-30  37436858
Lonnie Walker        San Antonio Spurs       SG 1998-12-14   2764200
Lonzo Ball        New Orleans Pelicans       PG 1997-10-27   8719320
Louis King             Detroit Pistons        F 1999-04-06     79568
Luguentz Dort    Oklahoma City Thunder        G 1999-04-19     79568
...                                ...      ...        ...       ...
Zach LaVine              Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell        Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith        Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham    New Orleans Pelicans       SF 1995-11-17     79568

[169 rows x 4 columns]

In [85]:
nba.loc['LeBron James':'Zion Williamson']

                                   Team Position   Birthday    Salary
Name
LeBron James         Los Angeles Lakers       PF 1984-12-30  37436858
Lonnie Walker         San Antonio Spurs       SG 1998-12-14   2764200
Lonzo Ball         New Orleans Pelicans       PG 1997-10-27   8719320
Louis King              Detroit Pistons        F 1999-04-06     79568
Luguentz Dort     Oklahoma City Thunder        G 1999-04-19     79568
...                                 ...      ...        ...       ...
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440

[168 rows x 4 columns]

In [86]:
nba.iloc[0]

Team              Orlando Magic
Position                     PF
Birthday    1995-09-16 00:00:00
Salary                 19863636
Name: Aaron Gordon, dtype: object

In [87]:
nba.iloc[0:10]

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000
Al-Farouq Aminu            Orlando Magic       PF 1990-09-21   9258000
Alec Burks         Golden State Warriors       SG 1991-07-20   2320044
Alex Caruso           Los Angeles Lakers       PG 1994-02-28   2750000
Alex Len                   Atlanta Hawks        C 1993-06-16   4160000

In [89]:
nba.iloc[:100]

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
...                                  ...      ...        ...       ...
David Nwaba                Brooklyn Nets       SF 1993-01-14   1678854
Davis Bertans         Washington Wizards       PF 1992-11-12   7000000
De'Andre Hunter            Atlanta Hawks       SF 1997-12-02   7068360
De'Anthony Melton      Memphis Grizzlies       PG 1998-05-28   1416852
DeAndre Jordan             Brooklyn Nets        C 1988-07-21   9881598

[100 rows x 4 columns]

In [90]:
nba.loc['LeBron James', 'Salary']

np.int64(37436858)

In [91]:
nba.loc[['LeBron James', 'Alex Caruso'], ['Salary', 'Birthday']]

                Salary   Birthday
Name
LeBron James  37436858 1984-12-30
Alex Caruso    2750000 1994-02-28

In [99]:
nba.loc['Alex Caruso':'LeBron James', ['Birthday','Salary']]

                    Birthday    Salary
Name
Alex Caruso       1994-02-28   2750000
Alex Len          1993-06-16   4160000
Alfonzo McKinnie  1992-09-17   1588231
Alize Johnson     1996-04-22   1416852
Allen Crabbe      1992-04-09  18500000
...                      ...       ...
LaMarcus Aldridge 1985-07-19  26000000
Landry Shamet     1997-03-13   1995120
Langston Galloway 1991-12-09   7333333
Lauri Markkanen   1997-05-22   5300400
LeBron James      1984-12-30  37436858

[274 rows x 2 columns]

In [101]:
nba.iloc[1:15:3, [0, 1, 2]]

                                    Team Position   Birthday
Name
Aaron Holiday             Indiana Pacers       PG 1996-09-30
Admiral Schofield     Washington Wizards       SF 1997-03-30
Alec Burks         Golden State Warriors       SG 1991-07-20
Alfonzo McKinnie     Cleveland Cavaliers       SF 1992-09-17
Allonzo Trier            New York Knicks       PG 1996-01-17

In [102]:
nba.at['Austin Rivers', 'Birthday']

Timestamp('1992-08-01 00:00:00')

In [103]:
nba.iat[169, 2]

Timestamp('1986-11-05 00:00:00')

In [104]:
nba.columns

Index(['Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [106]:
nba_new = nba.rename(columns={'Birthday':'Date of Birth'}, index={'LeBron James':'GOAT'})

In [107]:
nba_new.loc['GOAT']

Team              Los Angeles Lakers
Position                          PF
Date of Birth    1984-12-30 00:00:00
Salary                      37436858
Name: GOAT, dtype: object

In [109]:
# nba_new.loc['LeBron James']
# Уже такого индеса нет

In [110]:
# Excercises

In [112]:
# 1

In [113]:
nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'])
nfl

                    Name                  Team Position   Birthday   Salary
0           Tremon Smith   Philadelphia Eagles       RB 1996-07-20   570000
1         Shawn Williams    Cincinnati Bengals       SS 1991-05-13  3500000
2            Adam Butler  New England Patriots       DT 1994-04-12   645000
3            Derek Wolfe        Denver Broncos       DE 1990-02-24  8000000
4              Jake Ryan  Jacksonville Jaguars      OLB 1992-02-27  1000000
...                  ...                   ...      ...        ...      ...
1650    Bashaud Breeland    Kansas City Chiefs       CB 1992-01-30   805000
1651         Craig James   Philadelphia Eagles       CB 1996-04-29   570000
1652  Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
1653         Chuma Edoga         New York Jets       OT 1997-05-25   495000
1654        Tajae Sharpe      Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 5 columns]

In [114]:
# 2

In [115]:
nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday'], index_col=['Name'])
nfl

                                    Team Position   Birthday   Salary
Name
Tremon Smith         Philadelphia Eagles       RB 1996-07-20   570000
Shawn Williams        Cincinnati Bengals       SS 1991-05-13  3500000
Adam Butler         New England Patriots       DT 1994-04-12   645000
Derek Wolfe               Denver Broncos       DE 1990-02-24  8000000
Jake Ryan           Jacksonville Jaguars      OLB 1992-02-27  1000000
...                                  ...      ...        ...      ...
Bashaud Breeland      Kansas City Chiefs       CB 1992-01-30   805000
Craig James          Philadelphia Eagles       CB 1996-04-29   570000
Jonotthan Harrison         New York Jets        C 1991-08-25  1500000
Chuma Edoga                New York Jets       OT 1997-05-25   495000
Tajae Sharpe            Tennessee Titans       WR 1994-12-23  2025000

[1655 rows x 4 columns]

In [116]:
nfl = pd.read_csv('nfl.csv', parse_dates=['Birthday']).set_index(keys=['Name']).sort_index(axis=0)
nfl

                                 Team Position   Birthday    Salary
Name
A'Shawn Robinson        Detroit Lions       DT 1995-03-21   1163678
A.J. Brown           Tennessee Titans       WR 1997-06-30    495000
A.J. Moore             Houston Texans       SS 1995-12-15    570000
Aaron Brewer        Arizona Cardinals       LS 1990-07-05    930000
Aaron Colvin      Washington Redskins       CB 1991-10-02   7500000
...                               ...      ...        ...       ...
Zack Martin            Dallas Cowboys        G 1990-11-20  10000000
Zaire Franklin     Indianapolis Colts      OLB 1996-07-02    570000
Zak DeOssie           New York Giants       LS 1984-05-24   1030000
Zane Gonzalez       Arizona Cardinals        K 1995-05-07    645000
Zay Jones             Oakland Raiders       WR 1995-03-30   1081348

[1655 rows x 4 columns]

In [117]:
# 3

In [119]:
nfl['Team'].value_counts()

Team
New York Jets           58
Washington Redskins     56
Kansas City Chiefs      56
New Orleans Saints      55
San Francisco 49Ers     55
Los Angeles Chargers    54
Minnesota Vikings       54
Denver Broncos          54
Buffalo Bills           53
Dallas Cowboys          53
Seattle Seahawks        53
Atlanta Falcons         53
Detroit Lions           53
Chicago Bears           53
Houston Texans          52
Los Angeles Rams        52
New York Giants         52
Philadelphia Eagles     52
Oakland Raiders         51
Arizona Cardinals       51
Green Bay Packers       51
Cincinnati Bengals      51
Jacksonville Jaguars    50
Carolina Panthers       49
Cleveland Browns        49
New England Patriots    49
Indianapolis Colts      49
Miami Dolphins          49
Baltimore Ravens        48
Pittsburgh Steelers     47
Tampa Bay Buccaneers    47
Tennessee Titans        46
Name: count, dtype: int64

In [120]:
# 4

In [121]:
nfl['Salary'].nlargest(5)

Name
Kirk Cousins       27500000
Jameis Winston     20922000
Marcus Mariota     20922000
Derek Carr         19900000
Jimmy Garoppolo    17200000
Name: Salary, dtype: int64

In [122]:
# 5

In [123]:
nfl.sort_values(by=['Team', 'Salary'], ascending=[True, False])

                                   Team Position   Birthday    Salary
Name
Chandler Jones        Arizona Cardinals      OLB 1990-02-27  16500000
Larry Fitzgerald      Arizona Cardinals       WR 1983-08-31  11000000
Patrick Peterson      Arizona Cardinals       CB 1990-07-11  11000000
David Johnson         Arizona Cardinals       RB 1991-12-16   5700000
Justin Pugh           Arizona Cardinals        G 1990-08-15   5000000
...                                 ...      ...        ...       ...
Ross Pierschbacher  Washington Redskins        C 1995-05-05    495000
Simeon Thomas       Washington Redskins       CB 1993-09-22    495000
Terry McLaurin      Washington Redskins       WR 1996-04-15    495000
Timon Parris        Washington Redskins       OT 1995-09-11    495000
Wes Martin          Washington Redskins        G 1996-05-09    495000

[1655 rows x 4 columns]

In [124]:
# 6

In [125]:
nfl = nfl.reset_index().set_index(keys=['Team']).sort_index(axis=0)

In [126]:
nfl.head()

                               Name Position   Birthday   Salary
Team
Arizona Cardinals       Chris Jones       CB 1995-08-13  1800000
Arizona Cardinals     Andy Isabella       WR 1996-11-18   495000
Arizona Cardinals       Miles Brown       NT 1997-09-04   495000
Arizona Cardinals  Deionte Thompson       SS 1997-02-11   495000
Arizona Cardinals     Rodney Gunter       DE 1992-01-19  1000000

In [130]:
nfl.loc['New York Jets', ['Name', 'Birthday']].sort_values(by=['Birthday'], ascending=True).head(1)

                     Name   Birthday
Team
New York Jets  Ryan Kalil 1985-03-29

In [131]:
nfl.describe()

                            Birthday        Salary
count                           1655  1.655000e+03
mean   1993-04-13 16:24:04.350453120  1.861569e+06
min              1977-08-03 00:00:00  3.780000e+05
25%              1991-06-11 12:00:00  5.700000e+05
50%              1993-12-05 00:00:00  8.000000e+05
75%              1995-09-11 12:00:00  1.839952e+06
max              1998-12-19 00:00:00  2.750000e+07
std                              NaN  2.748519e+06