In [2]:
import numpy as np
import pandas as pd

In [3]:
# Exercises

In [6]:
tv_shows_json = pd.read_json('tv_shows.json')
tv_shows_json

                                               shows
0  {'show': 'The X-Files', 'runtime': 60, 'networ...
1  {'show': 'Lost', 'runtime': 60, 'network': 'AB...
2  {'show': 'Buffy the Vampire Slayer', 'runtime'...

In [5]:
# 1

In [7]:
tv_shows = pd.json_normalize(data=tv_shows_json['shows'], meta=['show', 'runtime', 'network'], record_path='episodes')
tv_shows

,season,episode,name,air_date,show,runtime,network
0,1,1,Pilot,1993-09-11 01:00:00,The X-Files,60,FOX
1,1,2,Deep Throat,1993-09-18 01:00:00,The X-Files,60,FOX
2,1,3,Squeeze,1993-09-25 01:00:00,The X-Files,60,FOX
3,1,4,Conduit,1993-10-02 01:00:00,The X-Files,60,FOX
4,1,5,The Jersey Devil,1993-10-09 01:00:00,The X-Files,60,FOX
...,...,...,...,...,...,...,...
477,7,18,Dirty Girls,2003-04-16 00:00:00,Buffy the Vampire Slayer,60,UPN
478,7,19,Empty Places,2003-04-30 00:00:00,Buffy the Vampire Slayer,60,UPN
479,7,20,Touched,2003-05-07 00:00:00,Buffy the Vampire Slayer,60,UPN
480,7,21,End of Days,2003-05-14 00:00:00,Buffy the Vampire Slayer,60,UPN
481,7,22,Chosen,2003-05-21 00:00:00,Buffy the Vampire Slayer,60,UPN

In [8]:
# 2

In [9]:
tv_shows['show'].unique()

array(['The X-Files', 'Lost', 'Buffy the Vampire Slayer'], dtype=object)

In [10]:
df1 = tv_shows[tv_shows['show'] == 'The X-Files']

In [11]:
df2 = tv_shows[tv_shows['show'] == 'Lost']

In [12]:
df3 = tv_shows[tv_shows['show'] == 'Buffy the Vampire Slayer']

In [13]:
df1

,season,episode,name,air_date,show,runtime,network
0,1,1,Pilot,1993-09-11 01:00:00,The X-Files,60,FOX
1,1,2,Deep Throat,1993-09-18 01:00:00,The X-Files,60,FOX
2,1,3,Squeeze,1993-09-25 01:00:00,The X-Files,60,FOX
3,1,4,Conduit,1993-10-02 01:00:00,The X-Files,60,FOX
4,1,5,The Jersey Devil,1993-10-09 01:00:00,The X-Files,60,FOX
...,...,...,...,...,...,...,...
213,11,6,Kitten,2018-02-08 01:00:00,The X-Files,60,FOX
214,11,7,Rm9sbG93ZXJz,2018-03-01 01:00:00,The X-Files,60,FOX
215,11,8,Familiar,2018-03-08 01:00:00,The X-Files,60,FOX
216,11,9,Nothing Lasts Forever,2018-03-15 00:00:00,The X-Files,60,FOX
217,11,10,My Struggle IV,2018-03-22 00:00:00,The X-Files,60,FOX

In [14]:
df3

,season,episode,name,air_date,show,runtime,network
339,1,1,Welcome to the Hellmouth,1997-03-11 01:00:00,Buffy the Vampire Slayer,60,UPN
340,1,2,The Harvest,1997-03-11 01:00:00,Buffy the Vampire Slayer,60,UPN
341,1,3,Witch,1997-03-18 01:00:00,Buffy the Vampire Slayer,60,UPN
342,1,4,Teacher's Pet,1997-03-26 01:00:00,Buffy the Vampire Slayer,60,UPN
343,1,5,Never Kill a Boy on the First Date,1997-04-01 01:00:00,Buffy the Vampire Slayer,60,UPN
...,...,...,...,...,...,...,...
477,7,18,Dirty Girls,2003-04-16 00:00:00,Buffy the Vampire Slayer,60,UPN
478,7,19,Empty Places,2003-04-30 00:00:00,Buffy the Vampire Slayer,60,UPN
479,7,20,Touched,2003-05-07 00:00:00,Buffy the Vampire Slayer,60,UPN
480,7,21,End of Days,2003-05-14 00:00:00,Buffy the Vampire Slayer,60,UPN
481,7,22,Chosen,2003-05-21 00:00:00,Buffy the Vampire Slayer,60,UPN

In [15]:
df2

,season,episode,name,air_date,show,runtime,network
218,1,1,Pilot (1),2004-09-23 00:00:00,Lost,60,ABC
219,1,2,Pilot (2),2004-09-30 00:00:00,Lost,60,ABC
220,1,3,Tabula Rasa,2004-10-07 00:00:00,Lost,60,ABC
221,1,4,Walkabout,2004-10-14 00:00:00,Lost,60,ABC
222,1,5,White Rabbit,2004-10-21 00:00:00,Lost,60,ABC
...,...,...,...,...,...,...,...
334,6,14,The Candidate,2010-05-05 01:00:00,Lost,60,ABC
335,6,15,Across the Sea,2010-05-12 01:00:00,Lost,60,ABC
336,6,16,What They Died For,2010-05-19 01:00:00,Lost,60,ABC
337,6,17,The End (1),2010-05-24 01:00:00,Lost,60,ABC
338,6,18,The End (2),2010-05-24 01:00:00,Lost,60,ABC

In [16]:
# 3

In [17]:
excel_output = pd.ExcelWriter('episodes.xlsx')

In [18]:
df1.to_excel(excel_output, sheet_name='The X-Files', index=False)

In [19]:
df2.to_excel(excel_output, sheet_name='Lost', index=False)

In [20]:
df3.to_excel(excel_output, sheet_name='Buffy the Vampire Slayer', index=False)

In [22]:
excel_output.close()