In [1]:
import numpy as np
import pandas as pd

In [6]:
pd.Timestamp(year=2025, month=10, day=14)

Timestamp('2025-10-14 00:00:00')

In [7]:
pd.Timestamp('2025-10-14')

Timestamp('2025-10-14 00:00:00')

In [9]:
df = pd.read_csv('disney.csv', parse_dates=['Date'])
df

            Date        High         Low        Open       Close
0     1962-01-02    0.096026    0.092908    0.092908    0.092908
1     1962-01-03    0.094467    0.092908    0.092908    0.094155
2     1962-01-04    0.094467    0.093532    0.094155    0.094155
3     1962-01-05    0.094779    0.093844    0.094155    0.094467
4     1962-01-08    0.095714    0.092285    0.094467    0.094155
...          ...         ...         ...         ...         ...
14722 2020-06-26  111.199997  108.019997  110.949997  109.099998
14723 2020-06-29  111.570000  108.099998  109.000000  111.519997
14724 2020-06-30  112.050003  109.930000  111.500000  111.510002
14725 2020-07-01  115.599998  112.290001  112.820000  113.010002
14726 2020-07-02  115.099998  112.000000  115.000000  112.180000

[14727 rows x 5 columns]

In [10]:
# 1

In [12]:
df = pd.read_csv('citibike.csv', parse_dates=['start_time', 'stop_time'])
df

                     start_time               stop_time
0       2020-06-01 00:00:03.372 2020-06-01 00:17:46.208
1       2020-06-01 00:00:03.553 2020-06-01 01:03:33.936
2       2020-06-01 00:00:09.614 2020-06-01 00:17:06.833
3       2020-06-01 00:00:12.178 2020-06-01 00:03:58.864
4       2020-06-01 00:00:21.255 2020-06-01 00:24:18.965
...                         ...                     ...
1882268 2020-06-30 23:59:41.116 2020-07-01 00:11:06.779
1882269 2020-06-30 23:59:46.426 2020-07-01 00:07:13.086
1882270 2020-06-30 23:59:47.477 2020-07-01 00:07:06.559
1882271 2020-06-30 23:59:53.395 2020-07-01 00:14:43.427
1882272 2020-06-30 23:59:53.901 2020-07-01 00:07:07.095

[1882273 rows x 2 columns]

In [13]:
# 2

In [15]:
df['start_day_name'] = df['start_time'].dt.day_name()

In [21]:
df.pivot_table(index=['start_day_name'], values=['start_time'], aggfunc='count').sort_values(by=['start_time'], ascending=False)

                start_time
start_day_name
Tuesday             305833
Sunday              301482
Monday              292690
Saturday            285966
Friday              258479
Wednesday           222647
Thursday            215176

In [24]:
df.groupby(by=['start_day_name']).size().sort_values(ascending=False)

start_day_name
Tuesday      305833
Sunday       301482
Monday       292690
Saturday     285966
Friday       258479
Wednesday    222647
Thursday     215176
dtype: int64

In [25]:
df['start_day_name'].value_counts()

start_day_name
Tuesday      305833
Sunday       301482
Monday       292690
Saturday     285966
Friday       258479
Wednesday    222647
Thursday     215176
Name: count, dtype: int64

In [26]:
# 3

In [41]:
(df['start_time'] + pd.to_timedelta(-df['start_time'].dt.dayofweek, unit='day')).dt.date.value_counts()

start_time
2020-06-15    481211
2020-06-08    471384
2020-06-22    465412
2020-06-01    337590
2020-06-29    126676
Name: count, dtype: int64

In [42]:
# 4

In [43]:
df['duration'] = df['stop_time'] - df['start_time']

In [44]:
df

,start_time,stop_time,start_day_name,duration
0,2020-06-01 00:00:03.372,2020-06-01 00:17:46.208,Monday,0 days 00:17:42.836000
1,2020-06-01 00:00:03.553,2020-06-01 01:03:33.936,Monday,0 days 01:03:30.383000
2,2020-06-01 00:00:09.614,2020-06-01 00:17:06.833,Monday,0 days 00:16:57.219000
3,2020-06-01 00:00:12.178,2020-06-01 00:03:58.864,Monday,0 days 00:03:46.686000
4,2020-06-01 00:00:21.255,2020-06-01 00:24:18.965,Monday,0 days 00:23:57.710000
...,...,...,...,...
1882268,2020-06-30 23:59:41.116,2020-07-01 00:11:06.779,Tuesday,0 days 00:11:25.663000
1882269,2020-06-30 23:59:46.426,2020-07-01 00:07:13.086,Tuesday,0 days 00:07:26.660000
1882270,2020-06-30 23:59:47.477,2020-07-01 00:07:06.559,Tuesday,0 days 00:07:19.082000
1882271,2020-06-30 23:59:53.395,2020-07-01 00:14:43.427,Tuesday,0 days 00:14:50.032000
1882272,2020-06-30 23:59:53.901,2020-07-01 00:07:07.095,Tuesday,0 days 00:07:13.194000

In [45]:
# 5

In [46]:
df['duration'].mean()

Timedelta('0 days 00:27:19.590506853')

In [47]:
# 6

In [48]:
df.sort_values(by=['duration'], ascending=False).head()

,start_time,stop_time,start_day_name,duration
50593,2020-06-01 21:30:17.759,2020-07-04 12:32:12.699,Monday,32 days 15:01:54.940000
98339,2020-06-02 19:41:39.659,2020-07-03 21:29:00.291,Tuesday,31 days 01:47:20.632000
52306,2020-06-01 22:17:10.908,2020-07-02 17:49:31.604,Monday,30 days 19:32:20.696000
15171,2020-06-01 13:01:41.942,2020-07-01 17:28:30.366,Monday,30 days 04:26:48.424000
149761,2020-06-04 14:36:53.482,2020-07-03 00:01:44.178,Thursday,28 days 09:24:50.696000

In [49]:
df.nlargest(5, columns=['duration'])

,start_time,stop_time,start_day_name,duration
50593,2020-06-01 21:30:17.759,2020-07-04 12:32:12.699,Monday,32 days 15:01:54.940000
98339,2020-06-02 19:41:39.659,2020-07-03 21:29:00.291,Tuesday,31 days 01:47:20.632000
52306,2020-06-01 22:17:10.908,2020-07-02 17:49:31.604,Monday,30 days 19:32:20.696000
15171,2020-06-01 13:01:41.942,2020-07-01 17:28:30.366,Monday,30 days 04:26:48.424000
149761,2020-06-04 14:36:53.482,2020-07-03 00:01:44.178,Thursday,28 days 09:24:50.696000