In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('neighborhoods.csv', index_col=[0, 1, 2], header=[0, 1])
df

                                               Culture         Services  \
                                           Restaurants Museums   Police
State City               Street
MO    Fisherborough      244 Tracy View             C+       F       D-
SD    Port Curtisville   446 Cynthia Inlet          C-       B        B
WV    Jimenezview        432 John Common             A      A+        F
AK    Stevenshire        238 Andrew Rue             D-       A       A-
ND    New Joshuaport     877 Walter Neck            D+      C-        B
...                                                ...     ...      ...
MI    North Matthew      055 Clayton Isle           B-       C        B
MT    Chadton            601 Richards Road          A-       D       D+
SC    Diazmouth          385 Robin Harbors           F       D       B-
VA    Laurentown         255 Gonzalez Land          C+      B-        F
NE    South Kennethmouth 346 Wallace Pass           C-      B-        A


                                           Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [8]:
df.reset_index(level=['City', 'Street'], col_level=1, col_fill='Address')

                  Address                        Culture         Services  \
                     City             Street Restaurants Museums   Police
State
MO          Fisherborough     244 Tracy View          C+       F       D-
SD       Port Curtisville  446 Cynthia Inlet          C-       B        B
WV            Jimenezview    432 John Common           A      A+        F
AK            Stevenshire     238 Andrew Rue          D-       A       A-
ND         New Joshuaport    877 Walter Neck          D+      C-        B
...                   ...                ...         ...     ...      ...
MI          North Matthew   055 Clayton Isle          B-       C        B
MT                Chadton  601 Richards Road          A-       D       D+
SC              Diazmouth  385 Robin Harbors           F       D       B-
VA             Laurentown  255 Gonzalez Land          C+      B-        F
NE     South Kennethmouth   346 Wallace Pass          C-      B-        A


      Schools
State
MO         A+
SD         D+
WV          B
AK         A-
ND          B
...       ...
MI         C+
MT          D
SC         D+
VA         D-
NE         A-

[251 rows x 6 columns]

In [16]:
df = pd.read_csv('investments.csv')

In [10]:
df

,Name,Market,Status,State,Funding Rounds
0,#waywire,News,Acquired,NY,1
1,&TV Communications,Games,Operating,CA,2
2,-R- Ranch and Mine,Tourism,Operating,TX,2
3,004 Technologies,Software,Operating,IL,1
4,1-4 All,Software,Operating,NC,1
...,...,...,...,...,...
27794,Zynga,Technology,Operating,CA,9
27795,Zyngenia,Biotechnology,Operating,MD,1
27796,ZYOMYX,Biotechnology,Operating,MO,4
27797,Zyrra,E-Commerce,Operating,MA,4
27798,[x+1],Enterprise Software,Operating,NY,4

In [11]:
# Exercises

In [12]:
df.nunique()

Name              27763
Market              693
Status                3
State                61
Funding Rounds       16
dtype: int64

In [17]:
df = df.set_index(keys=['Status', 'Funding Rounds', 'State']).sort_index()

In [18]:
df

                                                      Name  \
Status    Funding Rounds State
Acquired  1              AB                 Hallpass Media
                         AL                      EnteGreat
                         AL       Onward Behavioral Health
                         AL                        Proxsys
                         AZ                    Envox Group
...                                                    ...
Operating 14             CA                   CNS Response
                         TN     Covenant Surgical Partners
          15             MA                      Terascala
                         PA                       InstaMed
          18             CA      Solarflare Communications

                                             Market
Status    Funding Rounds State
Acquired  1              AB                   Games
                         AL     Enterprise Software
                         AL           Biotechnology
                         AL           Biotechnology
                         AZ        Public Relations
...                                             ...
Operating 14             CA           Biotechnology
                         TN           Biotechnology
          15             MA                Software
                         PA              Technology
          18             CA     Enterprise Software

[27799 rows x 2 columns]

In [19]:
# 1

In [20]:
df.loc[('Closed',)]

                                             Name                Market
Funding Rounds State
1              AB     Cardinal Media Technologies  Social Network Media
               AB                Easy Bill Online              Tracking
               AB                   Globel Direct      Public Relations
               AB               Ph03nix New Media                 Games
               AL                           Naubo                  News
...                                           ...                   ...
8              GA                        MedShape           Health Care
               NC             Biolex Therapeutics         Biotechnology
               WA                      Cozi Group     Online Scheduling
9              NY         Blackaeon International              Robotics
11             OR                          Lecere              Software

[1498 rows x 2 columns]

In [21]:
# 2

In [22]:
df.loc[('Acquired', 10, )]

                   Name       Market
State
NY     Genesis Networks  Web Hosting
TX       ACTIVE Network     Software

In [23]:
# 3

In [24]:
df.loc[('Operating', 6, 'NJ')]

                                              Name             Market
Status    Funding Rounds State
Operating 6              NJ     Agile Therapeutics      Biotechnology
                         NJ               Agilence  Retail Technology
                         NJ      Edge Therapeutics      Biotechnology
                         NJ                Nistica        Web Hosting

In [25]:
# 4

In [27]:
df.loc[('Closed', 8,), ('Name')]

State
CA              CipherMax
CA     Dilithium Networks
CA                Moblyng
CA               SolFocus
CA               Solyndra
FL    Extreme Enterprises
GA               MedShape
NC    Biolex Therapeutics
WA             Cozi Group
Name: Name, dtype: object

In [28]:
df.columns

Index(['Name', 'Market'], dtype='object')

In [29]:
df.index

MultiIndex([( 'Acquired',  1, 'AB'),
            ( 'Acquired',  1, 'AL'),
            ( 'Acquired',  1, 'AL'),
            ( 'Acquired',  1, 'AL'),
            ( 'Acquired',  1, 'AZ'),
            ( 'Acquired',  1, 'AZ'),
            ( 'Acquired',  1, 'AZ'),
            ( 'Acquired',  1, 'AZ'),
            ( 'Acquired',  1, 'AZ'),
            ( 'Acquired',  1, 'AZ'),
            ...
            ('Operating', 13, 'MI'),
            ('Operating', 13, 'NC'),
            ('Operating', 13, 'NM'),
            ('Operating', 14, 'CA'),
            ('Operating', 14, 'CA'),
            ('Operating', 14, 'CA'),
            ('Operating', 14, 'TN'),
            ('Operating', 15, 'MA'),
            ('Operating', 15, 'PA'),
            ('Operating', 18, 'CA')],
           names=['Status', 'Funding Rounds', 'State'], length=27799)

In [30]:
# 5

In [31]:
df.xs(key='NJ', level='State')

                                              Name               Market
Status    Funding Rounds
Acquired  1                                  AkaRx        Biotechnology
          1                         Aptalis Pharma        Biotechnology
          1                                 Cadent             Software
          1                        Cancer Genetics  Health And Wellness
          1                              Clacendix           E-Commerce
...                                            ...                  ...
Operating 6                                Nistica          Web Hosting
          7               Cyclacel Pharmaceuticals        Biotechnology
          7                       PTC Therapeutics          Health Care
          8                 Svelte Medical Systems          Health Care
          11                                 Vidyo            Messaging

[512 rows x 2 columns]

In [32]:
# 6

In [35]:
df = df.reset_index()
df

,Status,Funding Rounds,State,Name,Market
0,Acquired,1,AB,Hallpass Media,Games
1,Acquired,1,AL,EnteGreat,Enterprise Software
2,Acquired,1,AL,Onward Behavioral Health,Biotechnology
3,Acquired,1,AL,Proxsys,Biotechnology
4,Acquired,1,AZ,Envox Group,Public Relations
...,...,...,...,...,...
27794,Operating,14,CA,CNS Response,Biotechnology
27795,Operating,14,TN,Covenant Surgical Partners,Biotechnology
27796,Operating,15,MA,Terascala,Software
27797,Operating,15,PA,InstaMed,Technology
27798,Operating,18,CA,Solarflare Communications,Enterprise Software

In [36]:
# 7 My draft

In [37]:
df = df.set_index(keys=['Status', 'Funding Rounds', 'State']).sort_index()

In [38]:
df

                                                      Name  \
Status    Funding Rounds State
Acquired  1              AB                 Hallpass Media
                         AL                      EnteGreat
                         AL       Onward Behavioral Health
                         AL                        Proxsys
                         AZ                    Envox Group
...                                                    ...
Operating 14             CA                   CNS Response
                         TN     Covenant Surgical Partners
          15             MA                      Terascala
                         PA                       InstaMed
          18             CA      Solarflare Communications

                                             Market
Status    Funding Rounds State
Acquired  1              AB                   Games
                         AL     Enterprise Software
                         AL           Biotechnology
                         AL           Biotechnology
                         AZ        Public Relations
...                                             ...
Operating 14             CA           Biotechnology
                         TN           Biotechnology
          15             MA                Software
                         PA              Technology
          18             CA     Enterprise Software

[27799 rows x 2 columns]

In [47]:
df.loc[('Acquired',):('Acquired', 10,)]

                                                   Name  \
Status   Funding Rounds State
Acquired 1              AB               Hallpass Media
                        AL                    EnteGreat
                        AL     Onward Behavioral Health
                        AL                      Proxsys
                        AZ                  Envox Group
...                                                 ...
         9              IL                        FanGo
                        MA                PatientKeeper
                        MO          Answers Corporation
         10             NY             Genesis Networks
                        TX               ACTIVE Network

                                               Market
Status   Funding Rounds State
Acquired 1              AB                      Games
                        AL        Enterprise Software
                        AL              Biotechnology
                        AL              Biotechnology
                        AZ           Public Relations
...                                               ...
         9              IL                   Startups
                        MA                 Physicians
                        MO     Information Technology
         10             NY                Web Hosting
                        TX                   Software

[2786 rows x 2 columns]