In [1]:
import numpy as np
import pandas as pd

In [2]:
inspections = pd.read_csv('chicago_food_inspections.csv')
inspections

                                      Name             Risk
0               MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                              JETS PIZZA   Risk 2 (Medium)
2                               ROOM 1520      Risk 3 (Low)
3                MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                            CHARTWELLS       Risk 1 (High)
...                                    ...              ...
153805                         WOLCOTT'S      Risk 1 (High)
153806     DUNKIN DONUTS/BASKIN-ROBBINS     Risk 2 (Medium)
153807                           Cafe 608     Risk 1 (High)
153808                        mr.daniel's     Risk 1 (High)
153809                         TEMPO CAFE     Risk 1 (High)

[153810 rows x 2 columns]

In [3]:
inspections['Name']

0                 MARRIOT MARQUIS CHICAGO
1                                JETS PIZZA
2                                 ROOM 1520
3                  MARRIOT MARQUIS CHICAGO
4                              CHARTWELLS
                         ...
153805                           WOLCOTT'S
153806       DUNKIN DONUTS/BASKIN-ROBBINS
153807                             Cafe 608
153808                          mr.daniel's
153809                           TEMPO CAFE
Name: Name, Length: 153810, dtype: object

In [4]:
inspections['Name'] = inspections['Name'].str.strip()
inspections

                                Name             Risk
0            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
1                         JETS PIZZA  Risk 2 (Medium)
2                          ROOM 1520     Risk 3 (Low)
3            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
4                         CHARTWELLS    Risk 1 (High)
...                              ...              ...
153805                     WOLCOTT'S    Risk 1 (High)
153806  DUNKIN DONUTS/BASKIN-ROBBINS  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   mr.daniel's    Risk 1 (High)
153809                    TEMPO CAFE    Risk 1 (High)

[153810 rows x 2 columns]

In [5]:
inspections['Name']

0              MARRIOT MARQUIS CHICAGO
1                           JETS PIZZA
2                            ROOM 1520
3              MARRIOT MARQUIS CHICAGO
4                           CHARTWELLS
                      ...
153805                       WOLCOTT'S
153806    DUNKIN DONUTS/BASKIN-ROBBINS
153807                        Cafe 608
153808                     mr.daniel's
153809                      TEMPO CAFE
Name: Name, Length: 153810, dtype: object

In [6]:
for col in inspections.columns:
    inspections[col] = inspections[col].str.strip()

In [7]:
inspections

                                Name             Risk
0            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
1                         JETS PIZZA  Risk 2 (Medium)
2                          ROOM 1520     Risk 3 (Low)
3            MARRIOT MARQUIS CHICAGO    Risk 1 (High)
4                         CHARTWELLS    Risk 1 (High)
...                              ...              ...
153805                     WOLCOTT'S    Risk 1 (High)
153806  DUNKIN DONUTS/BASKIN-ROBBINS  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   mr.daniel's    Risk 1 (High)
153809                    TEMPO CAFE    Risk 1 (High)

[153810 rows x 2 columns]

In [8]:
inspections['Name'] = inspections['Name'].str.lower().str.title()

In [9]:
inspections

                                Name             Risk
0            Marriot Marquis Chicago    Risk 1 (High)
1                         Jets Pizza  Risk 2 (Medium)
2                          Room 1520     Risk 3 (Low)
3            Marriot Marquis Chicago    Risk 1 (High)
4                         Chartwells    Risk 1 (High)
...                              ...              ...
153805                     Wolcott'S    Risk 1 (High)
153806  Dunkin Donuts/Baskin-Robbins  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   Mr.Daniel'S    Risk 1 (High)
153809                    Tempo Cafe    Risk 1 (High)

[153810 rows x 2 columns]

In [10]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [13]:
inspections['Risk'].value_counts()

Risk
Risk 1 (High)      107351
Risk 2 (Medium)     31845
Risk 3 (Low)        14529
All                    19
Name: count, dtype: int64

In [14]:
inspections = inspections.dropna(subset=['Risk'])

In [15]:
inspections

                                Name             Risk
0            Marriot Marquis Chicago    Risk 1 (High)
1                         Jets Pizza  Risk 2 (Medium)
2                          Room 1520     Risk 3 (Low)
3            Marriot Marquis Chicago    Risk 1 (High)
4                         Chartwells    Risk 1 (High)
...                              ...              ...
153805                     Wolcott'S    Risk 1 (High)
153806  Dunkin Donuts/Baskin-Robbins  Risk 2 (Medium)
153807                      Cafe 608    Risk 1 (High)
153808                   Mr.Daniel'S    Risk 1 (High)
153809                    Tempo Cafe    Risk 1 (High)

[153744 rows x 2 columns]

In [16]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All'],
      dtype=object)

In [20]:
inspections['Risk'] = inspections['Risk'].replace('All', 'Risk 4 (Extreme)')

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_2842/3643058301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inspections['Risk'] = inspections['Risk'].replace('All', 'Risk 4 (Extreme)')

In [23]:
inspections['Risk'].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [24]:
inspections['Risk Num'] = inspections['Risk'].str.slice(5, 6)

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_2842/3197029596.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inspections['Risk Num'] = inspections['Risk'].str.slice(5, 6)

In [26]:
inspections['Risk Category'] = inspections['Risk'].str.slice(8, -1)

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_2842/2358759723.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  inspections['Risk Category'] = inspections['Risk'].str.slice(8, -1)

In [27]:
inspections

                                Name             Risk Risk Num Risk Category
0            Marriot Marquis Chicago    Risk 1 (High)        1          High
1                         Jets Pizza  Risk 2 (Medium)        2        Medium
2                          Room 1520     Risk 3 (Low)        3           Low
3            Marriot Marquis Chicago    Risk 1 (High)        1          High
4                         Chartwells    Risk 1 (High)        1          High
...                              ...              ...      ...           ...
153805                     Wolcott'S    Risk 1 (High)        1          High
153806  Dunkin Donuts/Baskin-Robbins  Risk 2 (Medium)        2        Medium
153807                      Cafe 608    Risk 1 (High)        1          High
153808                   Mr.Daniel'S    Risk 1 (High)        1          High
153809                    Tempo Cafe    Risk 1 (High)        1          High

[153744 rows x 4 columns]

In [30]:
inspections[inspections['Name'].str.lower().str.contains('pizza')]

,Name,Risk,Risk Num,Risk Category
1,Jets Pizza,Risk 2 (Medium),2,Medium
19,Nancy'S Home Of Stuffed Pizza,Risk 1 (High),1,High
27,"Nary'S Grill & Pizza ,Inc.",Risk 1 (High),1,High
29,Narys Grill & Pizza,Risk 1 (High),1,High
68,Colutas Pizza,Risk 1 (High),1,High
...,...,...,...,...
153756,Angelo'S Stuffed Pizza Corp,Risk 1 (High),1,High
153764,Cochiaros Pizza #2,Risk 1 (High),1,High
153772,Fernando'S Mexican Grill & Pizza,Risk 1 (High),1,High
153788,Reggio'S Pizza Express,Risk 1 (High),1,High
153801,State Street Pizza Company,Risk 1 (High),1,High

In [31]:
customers = pd.read_csv('customers.csv')

In [32]:
customers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [34]:
customers['Name'].str.len().value_counts()

Name
13    1884
12    1694
14    1691
11    1236
15    1136
16     691
10     657
17     384
9      212
18     194
19      88
8       41
20      30
21      13
7        6
22       2
24       1
23       1
Name: count, dtype: int64

In [38]:
customers['Name'].str.split(pat=' ', n=1).str.len().value_counts()

Name
2    9961
Name: count, dtype: int64

In [39]:
customers['Name'].str.split(pat=' ', n=1).str.get(0)

0           Frank
1       Elizabeth
2          Donald
3         Michael
4         Jasmine
          ...
9956         Dana
9957       Amanda
9958         Eric
9959       Taylor
9960       Sherry
Name: Name, Length: 9961, dtype: object

In [40]:
customers['Name'].str.split(pat=' ', n=1).str.get(1)

0           Manning
1           Johnson
2          Stephens
3       Vincent III
4            Zamora
           ...
9956       Browning
9957       Anderson
9958          Davis
9959      Hernandez
9960      Nicholson
Name: Name, Length: 9961, dtype: object

In [41]:
customers[['First Name', 'Last Name']] = customers['Name'].str.split(pat=' ', n=1, expand=True)
customers

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [42]:
customers = customers.drop(labels=['Name'], axis=1)

In [43]:
customers

,Address,First Name,Last Name
0,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora
...,...,...,...
9956,"762 Andrew Views Apt. 254, North Paul, New Mex...",Dana,Browning
9957,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",Amanda,Anderson
9958,"73015 Michelle Squares, Watsonville, West Virg...",Eric,Davis
9959,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",Taylor,Hernandez
9960,"355 Griffin Valley, Davidtown, New Mexico, 17581",Sherry,Nicholson

In [44]:
# Exercises

In [45]:
customers = pd.read_csv('customers.csv')
customers

                     Name                                            Address
0           Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1       Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2         Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3     Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4          Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...
...                   ...                                                ...
9956        Dana Browning  762 Andrew Views Apt. 254, North Paul, New Mex...
9957      Amanda Anderson  44188 Day Crest Apt. 901, Lake Marcia, Maine, ...
9958           Eric Davis  73015 Michelle Squares, Watsonville, West Virg...
9959     Taylor Hernandez       129 Keith Greens, Haleyfurt, Oklahoma, 98916
9960     Sherry Nicholson   355 Griffin Valley, Davidtown, New Mexico, 17581

[9961 rows x 2 columns]

In [55]:
customers[['Street', 'City', 'State', 'Zip']] = customers['Address'].str.split(pat=',', expand=True)
customers

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",355 Griffin Valley,Davidtown,New Mexico,17581

In [56]:
for col in customers.columns:
    customers[col] = customers[col].str.strip()

In [57]:
customers

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...,...
9956,Dana Browning,"762 Andrew Views Apt. 254, North Paul, New Mex...",762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,"44188 Day Crest Apt. 901, Lake Marcia, Maine, ...",44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,"73015 Michelle Squares, Watsonville, West Virg...",73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,"129 Keith Greens, Haleyfurt, Oklahoma, 98916",129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,"355 Griffin Valley, Davidtown, New Mexico, 17581",355 Griffin Valley,Davidtown,New Mexico,17581

In [58]:
customers = customers.drop(labels=['Address'], axis=1)
customers

,Name,Street,City,State,Zip
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252
...,...,...,...,...,...
9956,Dana Browning,762 Andrew Views Apt. 254,North Paul,New Mexico,28889
9957,Amanda Anderson,44188 Day Crest Apt. 901,Lake Marcia,Maine,37378
9958,Eric Davis,73015 Michelle Squares,Watsonville,West Virginia,03933
9959,Taylor Hernandez,129 Keith Greens,Haleyfurt,Oklahoma,98916
9960,Sherry Nicholson,355 Griffin Valley,Davidtown,New Mexico,17581

In [60]:
customers['Name'].str.replace('a', '')

0              Frnk Mnning
1         Elizbeth Johnson
2           Donld Stephens
3       Michel Vincent III
4              Jsmine Zmor
               ...
9956           Dn Browning
9957         Amnd Anderson
9958             Eric Dvis
9959        Tylor Hernndez
9960      Sherry Nicholson
Name: Name, Length: 9961, dtype: object