In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('investments.csv')
df

,Name,Market,Status,State,Funding Rounds
0,#waywire,News,Acquired,NY,1
1,&TV Communications,Games,Operating,CA,2
2,-R- Ranch and Mine,Tourism,Operating,TX,2
3,004 Technologies,Software,Operating,IL,1
4,1-4 All,Software,Operating,NC,1
...,...,...,...,...,...
27794,Zynga,Technology,Operating,CA,9
27795,Zyngenia,Biotechnology,Operating,MD,1
27796,ZYOMYX,Biotechnology,Operating,MO,4
27797,Zyrra,E-Commerce,Operating,MA,4
27798,[x+1],Enterprise Software,Operating,NY,4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27799 entries, 0 to 27798
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            27799 non-null  object
 1   Market          27799 non-null  object
 2   Status          27799 non-null  object
 3   State           27799 non-null  object
 4   Funding Rounds  27799 non-null  int64
dtypes: int64(1), object(4)
memory usage: 1.1+ MB

In [5]:
df.nunique()

Name              27763
Market              693
Status                3
State                61
Funding Rounds       16
dtype: int64

In [6]:
df = df.set_index(keys=['Status', 'Funding Rounds', 'State']).sort_index()

In [7]:
df

                                                      Name  \
Status    Funding Rounds State
Acquired  1              AB                 Hallpass Media
                         AL                      EnteGreat
                         AL       Onward Behavioral Health
                         AL                        Proxsys
                         AZ                    Envox Group
...                                                    ...
Operating 14             CA                   CNS Response
                         TN     Covenant Surgical Partners
          15             MA                      Terascala
                         PA                       InstaMed
          18             CA      Solarflare Communications

                                             Market
Status    Funding Rounds State
Acquired  1              AB                   Games
                         AL     Enterprise Software
                         AL           Biotechnology
                         AL           Biotechnology
                         AZ        Public Relations
...                                             ...
Operating 14             CA           Biotechnology
                         TN           Biotechnology
          15             MA                Software
                         PA              Technology
          18             CA     Enterprise Software

[27799 rows x 2 columns]

In [8]:
# 1
df.loc[('Closed')]

                                             Name                Market
Funding Rounds State
1              AB     Cardinal Media Technologies  Social Network Media
               AB                Easy Bill Online              Tracking
               AB                   Globel Direct      Public Relations
               AB               Ph03nix New Media                 Games
               AL                           Naubo                  News
...                                           ...                   ...
8              GA                        MedShape           Health Care
               NC             Biolex Therapeutics         Biotechnology
               WA                      Cozi Group     Online Scheduling
9              NY         Blackaeon International              Robotics
11             OR                          Lecere              Software

[1498 rows x 2 columns]

In [9]:
# 2
df.loc[('Acquired', 10)]

                   Name       Market
State
NY     Genesis Networks  Web Hosting
TX       ACTIVE Network     Software

In [10]:
# 3
df.loc[('Operating', 6, 'NJ')]

                                              Name             Market
Status    Funding Rounds State
Operating 6              NJ     Agile Therapeutics      Biotechnology
                         NJ               Agilence  Retail Technology
                         NJ      Edge Therapeutics      Biotechnology
                         NJ                Nistica        Web Hosting

In [11]:
# 4
df.loc[('Closed', 8), ('Name')]

State
CA              CipherMax
CA     Dilithium Networks
CA                Moblyng
CA               SolFocus
CA               Solyndra
FL    Extreme Enterprises
GA               MedShape
NC    Biolex Therapeutics
WA             Cozi Group
Name: Name, dtype: object

In [12]:
# 5
df.xs(key='NJ', level='State')

                                              Name               Market
Status    Funding Rounds
Acquired  1                                  AkaRx        Biotechnology
          1                         Aptalis Pharma        Biotechnology
          1                                 Cadent             Software
          1                        Cancer Genetics  Health And Wellness
          1                              Clacendix           E-Commerce
...                                            ...                  ...
Operating 6                                Nistica          Web Hosting
          7               Cyclacel Pharmaceuticals        Biotechnology
          7                       PTC Therapeutics          Health Care
          8                 Svelte Medical Systems          Health Care
          11                                 Vidyo            Messaging

[512 rows x 2 columns]

In [13]:
# 6
df.reset_index()

,Status,Funding Rounds,State,Name,Market
0,Acquired,1,AB,Hallpass Media,Games
1,Acquired,1,AL,EnteGreat,Enterprise Software
2,Acquired,1,AL,Onward Behavioral Health,Biotechnology
3,Acquired,1,AL,Proxsys,Biotechnology
4,Acquired,1,AZ,Envox Group,Public Relations
...,...,...,...,...,...
27794,Operating,14,CA,CNS Response,Biotechnology
27795,Operating,14,TN,Covenant Surgical Partners,Biotechnology
27796,Operating,15,MA,Terascala,Software
27797,Operating,15,PA,InstaMed,Technology
27798,Operating,18,CA,Solarflare Communications,Enterprise Software