In [1]:
import numpy as np
import pandas as pd

In [2]:
addresses = [
    ('8809 Flair Square', 'Toddside', 'IL', '37206'),
    ('9901 Austin Street', 'Toddside', 'IL', '37206'),
    ('905 Hogan Quarter', 'Franklin', 'IL', '37206'),
]

In [3]:
row_index = pd.MultiIndex.from_tuples(tuples=addresses, names=['Street', 'City', 'State', 'Zip'])

In [4]:
row_index

MultiIndex([( '8809 Flair Square', 'Toddside', 'IL', '37206'),
            ('9901 Austin Street', 'Toddside', 'IL', '37206'),
            ( '905 Hogan Quarter', 'Franklin', 'IL', '37206')],
           names=['Street', 'City', 'State', 'Zip'])

In [5]:
data = [
    ['A', 'B+'],
    ['C+', 'C'],
    ['D-', 'A'],
]

In [6]:
columns = ['Schools', 'Cost of Living']

In [7]:
area_grades = pd.DataFrame(data=data, index=row_index, columns=columns)

In [8]:
area_grades

                                        Schools Cost of Living
Street             City     State Zip
8809 Flair Square  Toddside IL    37206       A             B+
9901 Austin Street Toddside IL    37206      C+              C
905 Hogan Quarter  Franklin IL    37206      D-              A

In [9]:
column_index = pd.MultiIndex.from_tuples(
    [
        ('Culture', 'Restaurants'),
        ('Culture', 'Museums'),
        ('Services', 'Police'),
        ('Services', 'Schools'),
    ]
)

In [11]:
column_index

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           )

In [12]:
data = [
    ['C-', 'B+', 'B-', 'A'],
    ['D+', 'C', 'A', 'C+'],
    ['A-', 'A', 'D+', 'F'],
]

In [13]:
pd.DataFrame(data=data, index=row_index, columns=column_index)

                                            Culture         Services
                                        Restaurants Museums   Police Schools
Street             City     State Zip
8809 Flair Square  Toddside IL    37206          C-      B+       B-       A
9901 Austin Street Toddside IL    37206          D+       C        A      C+
905 Hogan Quarter  Franklin IL    37206          A-       A       D+       F

In [18]:
neighborhoods = pd.read_csv('neighborhoods.csv', index_col=[0, 1, 2], header=[0, 1])

In [19]:
neighborhoods

                                               Culture         Services  \
                                           Restaurants Museums   Police
State City               Street
MO    Fisherborough      244 Tracy View             C+       F       D-
SD    Port Curtisville   446 Cynthia Inlet          C-       B        B
WV    Jimenezview        432 John Common             A      A+        F
AK    Stevenshire        238 Andrew Rue             D-       A       A-
ND    New Joshuaport     877 Walter Neck            D+      C-        B
...                                                ...     ...      ...
MI    North Matthew      055 Clayton Isle           B-       C        B
MT    Chadton            601 Richards Road          A-       D       D+
SC    Diazmouth          385 Robin Harbors           F       D       B-
VA    Laurentown         255 Gonzalez Land          C+      B-        F
NE    South Kennethmouth 346 Wallace Pass           C-      B-        A


                                           Schools
State City               Street
MO    Fisherborough      244 Tracy View         A+
SD    Port Curtisville   446 Cynthia Inlet      D+
WV    Jimenezview        432 John Common         B
AK    Stevenshire        238 Andrew Rue         A-
ND    New Joshuaport     877 Walter Neck         B
...                                            ...
MI    North Matthew      055 Clayton Isle       C+
MT    Chadton            601 Richards Road       D
SC    Diazmouth          385 Robin Harbors      D+
VA    Laurentown         255 Gonzalez Land      D-
NE    South Kennethmouth 346 Wallace Pass       A-

[251 rows x 4 columns]

In [20]:
neighborhoods.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 251 entries, ('MO', 'Fisherborough', '244 Tracy View') to ('NE', 'South Kennethmouth', '346 Wallace Pass')
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Culture, Restaurants)  251 non-null    object
 1   (Culture, Museums)      251 non-null    object
 2   (Services, Police)      251 non-null    object
 3   (Services, Schools)     251 non-null    object
dtypes: object(4)
memory usage: 27.1+ KB

In [21]:
neighborhoods.index

MultiIndex([('MO',      'Fisherborough',        '244 Tracy View'),
            ('SD',   'Port Curtisville',     '446 Cynthia Inlet'),
            ('WV',        'Jimenezview',       '432 John Common'),
            ('AK',        'Stevenshire',        '238 Andrew Rue'),
            ('ND',     'New Joshuaport',       '877 Walter Neck'),
            ('ID',         'Wellsville',   '696 Weber Stravenue'),
            ('TN',          'Jodiburgh',    '285 Justin Corners'),
            ('DC',   'Lake Christopher',   '607 Montoya Harbors'),
            ('OH',          'Port Mike',      '041 Michael Neck'),
            ('ND',         'Hardyburgh', '550 Gilmore Mountains'),
            ...
            ('AK',          'Scottstad',      '114 Jones Garden'),
            ('IA',    'Port Willieport',  '320 Jennifer Mission'),
            ('ME',         'Port Linda',        '692 Hill Glens'),
            ('KS',         'Kaylamouth',       '483 Freeman Via'),
            ('WA',     'Port Shawnfort',    '691 Winters Bridge'),
            ('MI',      'North Matthew',      '055 Clayton Isle'),
            ('MT',            'Chadton',     '601 Richards Road'),
            ('SC',          'Diazmouth',     '385 Robin Harbors'),
            ('VA',         'Laurentown',     '255 Gonzalez Land'),
            ('NE', 'South Kennethmouth',      '346 Wallace Pass')],
           names=['State', 'City', 'Street'], length=251)

In [22]:
neighborhoods.columns

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           )

In [23]:
neighborhoods.index.names

FrozenList(['State', 'City', 'Street'])

In [24]:
neighborhoods.columns.names

FrozenList([None, None])

In [25]:
neighborhoods.columns.names = ['Category', 'Subcategory']

In [26]:
neighborhoods.head()

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
State City             Street
MO    Fisherborough    244 Tracy View             C+       F       D-      A+
SD    Port Curtisville 446 Cynthia Inlet          C-       B        B      D+
WV    Jimenezview      432 John Common             A      A+        F       B
AK    Stevenshire      238 Andrew Rue             D-       A       A-      A-
ND    New Joshuaport   877 Walter Neck            D+      C-        B       B

In [27]:
neighborhoods.index.get_level_values('State')

Index(['MO', 'SD', 'WV', 'AK', 'ND', 'ID', 'TN', 'DC', 'OH', 'ND',
       ...
       'AK', 'IA', 'ME', 'KS', 'WA', 'MI', 'MT', 'SC', 'VA', 'NE'],
      dtype='object', name='State', length=251)

In [28]:
neighborhoods.index.get_level_values('City')

Index(['Fisherborough', 'Port Curtisville', 'Jimenezview', 'Stevenshire',
       'New Joshuaport', 'Wellsville', 'Jodiburgh', 'Lake Christopher',
       'Port Mike', 'Hardyburgh',
       ...
       'Scottstad', 'Port Willieport', 'Port Linda', 'Kaylamouth',
       'Port Shawnfort', 'North Matthew', 'Chadton', 'Diazmouth', 'Laurentown',
       'South Kennethmouth'],
      dtype='object', name='City', length=251)

In [29]:
neighborhoods.columns.get_level_values(0)

Index(['Culture', 'Culture', 'Services', 'Services'], dtype='object', name='Category')

In [30]:
neighborhoods.columns.get_level_values(1)

Index(['Restaurants', 'Museums', 'Police', 'Schools'], dtype='object', name='Subcategory')

In [31]:
neighborhoods.nunique()

Category  Subcategory
Culture   Restaurants    13
          Museums        13
Services  Police         13
          Schools        13
dtype: int64

In [32]:
neighborhoods.nunique().index

MultiIndex([( 'Culture', 'Restaurants'),
            ( 'Culture',     'Museums'),
            ('Services',      'Police'),
            ('Services',     'Schools')],
           names=['Category', 'Subcategory'])

In [33]:
neighborhoods.sort_index()

Category                                      Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove              C-      A-       A+       C
      Scottstad      082 Leblanc Freeway            D      C-        D      B+
                     114 Jones Garden              D-      D-        D       D
      Stevenshire    238 Andrew Rue                D-       A       A-      A-
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
...                                               ...     ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike            B      D-        B       D
                     933 Jennifer Burg              C      A+       A-       C
      Martintown     013 Bell Mills                C-       D       A-      B-
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Reneeshire     717 Patel Square               B      B+        D       A

[251 rows x 4 columns]

In [34]:
neighborhoods.sort_index(ascending=False)

Category                                      Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City           Street
WY    Reneeshire     717 Patel Square               B      B+        D       A
      Port Jason     624 Faulkner Orchard          A-       F       C+      C+
      Martintown     013 Bell Mills                C-       D       A-      B-
      Lake Nicole    933 Jennifer Burg              C      A+       A-       C
                     754 Weaver Turnpike            B      D-        B       D
...                                               ...     ...      ...     ...
AL    Clarkland      430 Douglas Mission            A       F       C+      B+
AK    Stevenshire    238 Andrew Rue                D-       A       A-      A-
      Scottstad      114 Jones Garden              D-      D-        D       D
                     082 Leblanc Freeway            D      C-        D      B+
      Rowlandchester 386 Rebecca Cove              C-      A-       A+       C

[251 rows x 4 columns]

In [35]:
neighborhoods.sort_index(level=1)

Category                                      Culture         Services
Subcategory                               Restaurants Museums   Police Schools
State City          Street
AR    Allisonland   124 Diaz Brooks                C-      A+        F      C+
GA    Amyburgh      941 Brian Expressway            B       B       D-      C+
IA    Amyburgh      163 Heather Neck                F       D       A+      A-
ID    Andrewshire   952 Ellis Drive                C+      A-       C+       A
UT    Baileyfort    919 Stewart Hills              D+      C+        A       C
...                                               ...     ...      ...     ...
NC    West Scott    348 Jack Branch                A-      D-       A-       A
SD    West Scott    139 Hardy Vista                C+      A-       D+      B-
IN    Wilsonborough 066 Carr Road                  A+      C-        B       F
NC    Wilsonshire   871 Christopher Vista          B+       B       D+       F
NV    Wilsonshire   542 Jessica Stream              A      A+       C-      C+

[251 rows x 4 columns]

In [36]:
neighborhoods = neighborhoods.sort_index()

In [37]:
neighborhoods.head()

Category                                     Culture         Services
Subcategory                              Restaurants Museums   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove             C-      A-       A+       C
      Scottstad      082 Leblanc Freeway           D      C-        D      B+
                     114 Jones Garden             D-      D-        D       D
      Stevenshire    238 Andrew Rue               D-       A       A-      A-
AL    Clarkland      430 Douglas Mission           A       F       C+      B+

In [38]:
neighborhoods = neighborhoods.sort_index(axis=1)

In [39]:
neighborhoods.head()

Category                                 Culture             Services
Subcategory                              Museums Restaurants   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A-          C-       A+       C
      Scottstad      082 Leblanc Freeway      C-           D        D      B+
                     114 Jones Garden         D-          D-        D       D
      Stevenshire    238 Andrew Rue            A          D-       A-      A-
AL    Clarkland      430 Douglas Mission       F           A       C+      B+

In [40]:
neighborhoods['Services']

Subcategory                               Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A+       C
      Scottstad      082 Leblanc Freeway       D      B+
                     114 Jones Garden          D       D
      Stevenshire    238 Andrew Rue           A-      A-
AL    Clarkland      430 Douglas Mission      C+      B+
...                                          ...     ...
WY    Lake Nicole    754 Weaver Turnpike       B       D
                     933 Jennifer Burg        A-       C
      Martintown     013 Bell Mills           A-      B-
      Port Jason     624 Faulkner Orchard     C+      C+
      Reneeshire     717 Patel Square          D       A

[251 rows x 2 columns]

In [41]:
neighborhoods['Services']['Police']

State  City            Street
AK     Rowlandchester  386 Rebecca Cove        A+
       Scottstad       082 Leblanc Freeway      D
                       114 Jones Garden         D
       Stevenshire     238 Andrew Rue          A-
AL     Clarkland       430 Douglas Mission     C+
                                               ..
WY     Lake Nicole     754 Weaver Turnpike      B
                       933 Jennifer Burg       A-
       Martintown      013 Bell Mills          A-
       Port Jason      624 Faulkner Orchard    C+
       Reneeshire      717 Patel Square         D
Name: Police, Length: 251, dtype: object

In [42]:
neighborhoods[('Services', 'Schools')]

State  City            Street
AK     Rowlandchester  386 Rebecca Cove         C
       Scottstad       082 Leblanc Freeway     B+
                       114 Jones Garden         D
       Stevenshire     238 Andrew Rue          A-
AL     Clarkland       430 Douglas Mission     B+
                                               ..
WY     Lake Nicole     754 Weaver Turnpike      D
                       933 Jennifer Burg        C
       Martintown      013 Bell Mills          B-
       Port Jason      624 Faulkner Orchard    C+
       Reneeshire      717 Patel Square         A
Name: (Services, Schools), Length: 251, dtype: object

In [49]:
neighborhoods[[('Services', 'Schools'), ('Culture', 'Museums')]]

Category                                  Services Culture
Subcategory                                Schools Museums
State City           Street
AK    Rowlandchester 386 Rebecca Cove            C      A-
      Scottstad      082 Leblanc Freeway        B+      C-
                     114 Jones Garden            D      D-
      Stevenshire    238 Andrew Rue             A-       A
AL    Clarkland      430 Douglas Mission        B+       F
...                                            ...     ...
WY    Lake Nicole    754 Weaver Turnpike         D      D-
                     933 Jennifer Burg           C      A+
      Martintown     013 Bell Mills             B-       D
      Port Jason     624 Faulkner Orchard       C+       F
      Reneeshire     717 Patel Square            A      B+

[251 rows x 2 columns]

In [50]:
neighborhoods[['Services', 'Culture']]

Category                                  Services         Culture
Subcategory                                 Police Schools Museums Restaurants
State City           Street
AK    Rowlandchester 386 Rebecca Cove           A+       C      A-          C-
      Scottstad      082 Leblanc Freeway         D      B+      C-           D
                     114 Jones Garden            D       D      D-          D-
      Stevenshire    238 Andrew Rue             A-      A-       A          D-
AL    Clarkland      430 Douglas Mission        C+      B+       F           A
...                                            ...     ...     ...         ...
WY    Lake Nicole    754 Weaver Turnpike         B       D      D-           B
                     933 Jennifer Burg          A-       C      A+           C
      Martintown     013 Bell Mills             A-      B-       D          C-
      Port Jason     624 Faulkner Orchard       C+      C+       F          A-
      Reneeshire     717 Patel Square            D       A      B+           B

[251 rows x 4 columns]

In [74]:
neighborhoods.loc[[('AK', 'Rowlandchester', '386 Rebecca Cove'), ('AL', 'Clarkland', '430 Douglas Mission')]]

Category                                 Culture             Services
Subcategory                              Museums Restaurants   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A-          C-       A+       C
AL    Clarkland      430 Douglas Mission       F           A       C+      B+

In [76]:
neighborhoods.xs(key='Lake Nicole', level='City')

Category                  Culture             Services
Subcategory               Museums Restaurants   Police Schools
State Street
OR    650 Angela Track         C-           D        D       F
WY    754 Weaver Turnpike      D-           B        B       D
      933 Jennifer Burg        A+           C       A-       C

In [77]:
neighborhoods.xs(key='Museums', level='Subcategory', axis=1)

Category                                  Culture
State City           Street
AK    Rowlandchester 386 Rebecca Cove          A-
      Scottstad      082 Leblanc Freeway       C-
                     114 Jones Garden          D-
      Stevenshire    238 Andrew Rue             A
AL    Clarkland      430 Douglas Mission        F
...                                           ...
WY    Lake Nicole    754 Weaver Turnpike       D-
                     933 Jennifer Burg         A+
      Martintown     013 Bell Mills             D
      Port Jason     624 Faulkner Orchard       F
      Reneeshire     717 Patel Square          B+

[251 rows x 1 columns]

In [79]:
neighborhoods.xs(key='Museums', level='Subcategory', axis=1).xs(key='AL', level='State')

Category                               Culture
City              Street
Clarkland         430 Douglas Mission        F
East Bobbyside    294 Mitchell Village      A-
East Connie       943 John Gardens          C-
Kathrynstad       356 Dodson Plains         D-
Lonniestad        643 Allen Estates         B-
Port Jenniferfurt 539 Horton Fork           A-
Samuelville       989 Dean Plains            F
Vegaside          191 Mindy Meadows         A-

In [81]:
neighborhoods.xs(key=('AK', '238 Andrew Rue'), level=['State', 'Street'])

Category    Culture             Services
Subcategory Museums Restaurants   Police Schools
City
Stevenshire       A          D-       A-      A-

In [82]:
neighborhoods.reset_index().head()

Category    State            City               Street Culture              \
Subcategory                                            Museums Restaurants
0              AK  Rowlandchester     386 Rebecca Cove      A-          C-
1              AK       Scottstad  082 Leblanc Freeway      C-           D
2              AK       Scottstad     114 Jones Garden      D-          D-
3              AK     Stevenshire       238 Andrew Rue       A          D-
4              AL       Clarkland  430 Douglas Mission       F           A

Category    Services
Subcategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+

In [83]:
neighborhoods.reset_index(col_level=1).head()

Category                                               Culture              \
Subcategory State            City               Street Museums Restaurants
0              AK  Rowlandchester     386 Rebecca Cove      A-          C-
1              AK       Scottstad  082 Leblanc Freeway      C-           D
2              AK       Scottstad     114 Jones Garden      D-          D-
3              AK     Stevenshire       238 Andrew Rue       A          D-
4              AL       Clarkland  430 Douglas Mission       F           A

Category    Services
Subcategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+

In [85]:
neighborhoods.reset_index(col_level=1, col_fill='Address').head()

Category    Address                                      Culture              \
Subcategory   State            City               Street Museums Restaurants
0                AK  Rowlandchester     386 Rebecca Cove      A-          C-
1                AK       Scottstad  082 Leblanc Freeway      C-           D
2                AK       Scottstad     114 Jones Garden      D-          D-
3                AK     Stevenshire       238 Andrew Rue       A          D-
4                AL       Clarkland  430 Douglas Mission       F           A

Category    Services
Subcategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+

In [86]:
neighborhoods.head()

Category                                 Culture             Services
Subcategory                              Museums Restaurants   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove         A-          C-       A+       C
      Scottstad      082 Leblanc Freeway      C-           D        D      B+
                     114 Jones Garden         D-          D-        D       D
      Stevenshire    238 Andrew Rue            A          D-       A-      A-
AL    Clarkland      430 Douglas Mission       F           A       C+      B+

In [89]:
neighborhoods = neighborhoods.reset_index()

In [90]:
neighborhoods.head()

Category    State            City               Street Culture              \
Subcategory                                            Museums Restaurants
0              AK  Rowlandchester     386 Rebecca Cove      A-          C-
1              AK       Scottstad  082 Leblanc Freeway      C-           D
2              AK       Scottstad     114 Jones Garden      D-          D-
3              AK     Stevenshire       238 Andrew Rue       A          D-
4              AL       Clarkland  430 Douglas Mission       F           A

Category    Services
Subcategory   Police Schools
0                 A+       C
1                  D      B+
2                  D       D
3                 A-      A-
4                 C+      B+

In [91]:
neighborhoods.set_index(keys=['City'])

Category       State                Street Culture             Services  \
Subcategory                                Museums Restaurants   Police
City
Rowlandchester    AK      386 Rebecca Cove      A-          C-       A+
Scottstad         AK   082 Leblanc Freeway      C-           D        D
Scottstad         AK      114 Jones Garden      D-          D-        D
Stevenshire       AK        238 Andrew Rue       A          D-       A-
Clarkland         AL   430 Douglas Mission       F           A       C+
...              ...                   ...     ...         ...      ...
Lake Nicole       WY   754 Weaver Turnpike      D-           B        B
Lake Nicole       WY     933 Jennifer Burg      A+           C       A-
Martintown        WY        013 Bell Mills       D          C-       A-
Port Jason        WY  624 Faulkner Orchard       F          A-       C+
Reneeshire        WY      717 Patel Square      B+           B        D

Category
Subcategory    Schools
City
Rowlandchester       C
Scottstad           B+
Scottstad            D
Stevenshire         A-
Clarkland           B+
...                ...
Lake Nicole          D
Lake Nicole          C
Martintown          B-
Port Jason          C+
Reneeshire           A

[251 rows x 6 columns]

In [92]:
neighborhoods.set_index(keys=('Culture', 'Museums'))

Category           State            City                Street     Culture  \
Subcategory                                                    Restaurants
(Culture, Museums)
A-                    AK  Rowlandchester      386 Rebecca Cove          C-
C-                    AK       Scottstad   082 Leblanc Freeway           D
D-                    AK       Scottstad      114 Jones Garden          D-
A                     AK     Stevenshire        238 Andrew Rue          D-
F                     AL       Clarkland   430 Douglas Mission           A
...                  ...             ...                   ...         ...
D-                    WY     Lake Nicole   754 Weaver Turnpike           B
A+                    WY     Lake Nicole     933 Jennifer Burg           C
D                     WY      Martintown        013 Bell Mills          C-
F                     WY      Port Jason  624 Faulkner Orchard          A-
B+                    WY      Reneeshire      717 Patel Square           B

Category           Services
Subcategory          Police Schools
(Culture, Museums)
A-                       A+       C
C-                        D      B+
D-                        D       D
A                        A-      A-
F                        C+      B+
...                     ...     ...
D-                        B       D
A+                       A-       C
D                        A-      B-
F                        C+      C+
B+                        D       A

[251 rows x 6 columns]

In [93]:
neighborhoods.set_index(keys=['State', 'City', 'Street'])

Category                                  Culture             Services
Subcategory                               Museums Restaurants   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove          A-          C-       A+       C
      Scottstad      082 Leblanc Freeway       C-           D        D      B+
                     114 Jones Garden          D-          D-        D       D
      Stevenshire    238 Andrew Rue             A          D-       A-      A-
AL    Clarkland      430 Douglas Mission        F           A       C+      B+
...                                           ...         ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike       D-           B        B       D
                     933 Jennifer Burg         A+           C       A-       C
      Martintown     013 Bell Mills             D          C-       A-      B-
      Port Jason     624 Faulkner Orchard       F          A-       C+      C+
      Reneeshire     717 Patel Square          B+           B        D       A

[251 rows x 4 columns]

In [94]:
neighborhoods = neighborhoods.set_index(keys=['State', 'City', 'Street'])

In [95]:
neighborhoods

Category                                  Culture             Services
Subcategory                               Museums Restaurants   Police Schools
State City           Street
AK    Rowlandchester 386 Rebecca Cove          A-          C-       A+       C
      Scottstad      082 Leblanc Freeway       C-           D        D      B+
                     114 Jones Garden          D-          D-        D       D
      Stevenshire    238 Andrew Rue             A          D-       A-      A-
AL    Clarkland      430 Douglas Mission        F           A       C+      B+
...                                           ...         ...      ...     ...
WY    Lake Nicole    754 Weaver Turnpike       D-           B        B       D
                     933 Jennifer Burg         A+           C       A-       C
      Martintown     013 Bell Mills             D          C-       A-      B-
      Port Jason     624 Faulkner Orchard       F          A-       C+      C+
      Reneeshire     717 Patel Square          B+           B        D       A

[251 rows x 4 columns]

In [96]:
neighborhoods.reorder_levels(order=['City', 'State', 'Street'])

Category                                  Culture             Services
Subcategory                               Museums Restaurants   Police Schools
City           State Street
Rowlandchester AK    386 Rebecca Cove          A-          C-       A+       C
Scottstad      AK    082 Leblanc Freeway       C-           D        D      B+
                     114 Jones Garden          D-          D-        D       D
Stevenshire    AK    238 Andrew Rue             A          D-       A-      A-
Clarkland      AL    430 Douglas Mission        F           A       C+      B+
...                                           ...         ...      ...     ...
Lake Nicole    WY    754 Weaver Turnpike       D-           B        B       D
                     933 Jennifer Burg         A+           C       A-       C
Martintown     WY    013 Bell Mills             D          C-       A-      B-
Port Jason     WY    624 Faulkner Orchard       F          A-       C+      C+
Reneeshire     WY    717 Patel Square          B+           B        D       A

[251 rows x 4 columns]

In [97]:
# Homework

In [105]:
investments = pd.read_csv('investments.csv')

In [106]:
investments

,Name,Market,Status,State,Funding Rounds
0,#waywire,News,Acquired,NY,1
1,&TV Communications,Games,Operating,CA,2
2,-R- Ranch and Mine,Tourism,Operating,TX,2
3,004 Technologies,Software,Operating,IL,1
4,1-4 All,Software,Operating,NC,1
...,...,...,...,...,...
27794,Zynga,Technology,Operating,CA,9
27795,Zyngenia,Biotechnology,Operating,MD,1
27796,ZYOMYX,Biotechnology,Operating,MO,4
27797,Zyrra,E-Commerce,Operating,MA,4
27798,[x+1],Enterprise Software,Operating,NY,4

In [107]:
investments.nunique()

Name              27763
Market              693
Status                3
State                61
Funding Rounds       16
dtype: int64

In [108]:
investments = investments.set_index(keys=['Status', 'Funding Rounds', 'State']).sort_index()

In [109]:
investments

                                                      Name  \
Status    Funding Rounds State
Acquired  1              AB                 Hallpass Media
                         AL                      EnteGreat
                         AL       Onward Behavioral Health
                         AL                        Proxsys
                         AZ                    Envox Group
...                                                    ...
Operating 14             CA                   CNS Response
                         TN     Covenant Surgical Partners
          15             MA                      Terascala
                         PA                       InstaMed
          18             CA      Solarflare Communications

                                             Market
Status    Funding Rounds State
Acquired  1              AB                   Games
                         AL     Enterprise Software
                         AL           Biotechnology
                         AL           Biotechnology
                         AZ        Public Relations
...                                             ...
Operating 14             CA           Biotechnology
                         TN           Biotechnology
          15             MA                Software
                         PA              Technology
          18             CA     Enterprise Software

[27799 rows x 2 columns]

In [111]:
# 1
investments.loc[('Closed')]

                                             Name                Market
Funding Rounds State
1              AB     Cardinal Media Technologies  Social Network Media
               AB                Easy Bill Online              Tracking
               AB                   Globel Direct      Public Relations
               AB               Ph03nix New Media                 Games
               AL                           Naubo                  News
...                                           ...                   ...
8              GA                        MedShape           Health Care
               NC             Biolex Therapeutics         Biotechnology
               WA                      Cozi Group     Online Scheduling
9              NY         Blackaeon International              Robotics
11             OR                          Lecere              Software

[1498 rows x 2 columns]

In [116]:
investments.index.levels[0]

Index(['Acquired', 'Closed', 'Operating'], dtype='object', name='Status')

In [118]:
# 2
investments.loc[('Acquired', 10)]

                   Name       Market
State
NY     Genesis Networks  Web Hosting
TX       ACTIVE Network     Software

In [119]:
# 3
investments.loc[('Operating', 6, 'NJ')]

                                              Name             Market
Status    Funding Rounds State
Operating 6              NJ     Agile Therapeutics      Biotechnology
                         NJ               Agilence  Retail Technology
                         NJ      Edge Therapeutics      Biotechnology
                         NJ                Nistica        Web Hosting

In [122]:
# 4
investments.loc[('Closed', 8), ('Name')]

State
CA              CipherMax
CA     Dilithium Networks
CA                Moblyng
CA               SolFocus
CA               Solyndra
FL    Extreme Enterprises
GA               MedShape
NC    Biolex Therapeutics
WA             Cozi Group
Name: Name, dtype: object

In [124]:
# 5
investments.xs(key='NJ', level='State')

                                              Name               Market
Status    Funding Rounds
Acquired  1                                  AkaRx        Biotechnology
          1                         Aptalis Pharma        Biotechnology
          1                                 Cadent             Software
          1                        Cancer Genetics  Health And Wellness
          1                              Clacendix           E-Commerce
...                                            ...                  ...
Operating 6                                Nistica          Web Hosting
          7               Cyclacel Pharmaceuticals        Biotechnology
          7                       PTC Therapeutics          Health Care
          8                 Svelte Medical Systems          Health Care
          11                                 Vidyo            Messaging

[512 rows x 2 columns]

In [125]:
# 6
investments.reset_index()

,Status,Funding Rounds,State,Name,Market
0,Acquired,1,AB,Hallpass Media,Games
1,Acquired,1,AL,EnteGreat,Enterprise Software
2,Acquired,1,AL,Onward Behavioral Health,Biotechnology
3,Acquired,1,AL,Proxsys,Biotechnology
4,Acquired,1,AZ,Envox Group,Public Relations
...,...,...,...,...,...
27794,Operating,14,CA,CNS Response,Biotechnology
27795,Operating,14,TN,Covenant Surgical Partners,Biotechnology
27796,Operating,15,MA,Terascala,Software
27797,Operating,15,PA,InstaMed,Technology
27798,Operating,18,CA,Solarflare Communications,Enterprise Software