In [1]:
import numpy as np
import pandas as pd

In [2]:
food_data = {
    'Item': ['Banana', 'Cucumber', 'Orange', 'Tomato', 'Watermelon'],
    'Type': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Price': [0.99, 1.25, 0.25, 0.33, 3.00]
}

In [3]:
supermarket = pd.DataFrame(food_data)
supermarket

         Item       Type  Price
0      Banana      Fruit   0.99
1    Cucumber  Vegetable   1.25
2      Orange      Fruit   0.25
3      Tomato  Vegetable   0.33
4  Watermelon      Fruit   3.00

In [4]:
groups = supermarket.groupby('Type')

In [5]:
groups

In [6]:
type(groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [8]:
groups.get_group('Fruit')

         Item   Type  Price
0      Banana  Fruit   0.99
2      Orange  Fruit   0.25
4  Watermelon  Fruit   3.00

In [10]:
groups.get_group('Vegetable')

       Item       Type  Price
1  Cucumber  Vegetable   1.25
3    Tomato  Vegetable   0.33

In [12]:
groups['Price'].mean()

Type
Fruit        1.413333
Vegetable    0.790000
Name: Price, dtype: float64

In [14]:
fortune = pd.read_csv('fortune1000.csv')
fortune

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
...,...,...,...,...,...,...
995,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers,Wholesalers: Diversified
996,Charles River Laboratories Intl,1858.0,123.4,11800,Health Care,Health Care: Pharmacy and Other Services
997,CoreLogic,1851.0,152.2,5900,Business Services,Financial Data Services
998,Ensign Group,1849.0,40.5,21301,Health Care,Health Care: Medical Facilities
999,HCP,1848.0,414.2,190,Financials,Real estate

In [15]:
retail_companies = fortune[fortune['Sector'] == 'Retailing']
retail_companies

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
14,Costco,129025.0,2679.0,182000,Retailing,General Merchandisers
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
38,Target,71879.0,2934.0,345000,Retailing,General Merchandisers
...,...,...,...,...,...,...
909,99 Cents Only Stores,2194.0,-90.3,17200,Retailing,Specialty Retailers: Other
926,Express,2138.0,19.4,9576,Retailing,Specialty Retailers: Apparel
971,Finish Line,1934.0,-18.2,8200,Retailing,Specialty Retailers: Apparel
989,Barnes & Noble Education,1874.0,5.4,13375,Retailing,Specialty Retailers: Other
992,Childrens Place,1870.0,84.7,9800,Retailing,Specialty Retailers: Apparel

In [18]:
print(retail_companies['Revenues'].mean())

21874.714285714286

In [19]:
fortune.pivot_table(index='Sector', values='Revenues', aggfunc='mean')

                                   Revenues
Sector
Aerospace & Defense            15353.400000
Apparel                         7225.521429
Business Services               5963.962264
Chemicals                       7610.636364
Energy                         14425.300935
Engineering & Construction      6399.333333
Financials                     15757.935484
Food &  Drug Stores            33789.000000
Food, Beverages & Tobacco      13790.054054
Health Care                    21239.315493
Hotels, Restaurants & Leisure   6916.346154
Household Products              8277.850000
Industrials                    10615.102041
Materials                       6184.400000
Media                           9219.496000
Motor Vehicles & Parts         22817.631579
Retailing                      21874.714286
Technology                     13347.789320
Telecommunications             46695.900000
Transportation                 11379.000000
Wholesalers                    20185.204545

In [20]:
sectors = fortune.groupby('Sector')
sectors

In [21]:
len(sectors)

21

In [22]:
fortune.nunique()

Company      1000
Revenues      951
Profits       971
Employees     754
Sector         21
Industry       74
dtype: int64

In [23]:
sectors.size()

Sector
Aerospace & Defense               25
Apparel                           14
Business Services                 53
Chemicals                         33
Energy                           107
Engineering & Construction        27
Financials                       155
Food &  Drug Stores               12
Food, Beverages & Tobacco         37
Health Care                       71
Hotels, Restaurants & Leisure     26
Household Products                28
Industrials                       49
Materials                         45
Media                             25
Motor Vehicles & Parts            19
Retailing                         77
Technology                       103
Telecommunications                10
Transportation                    40
Wholesalers                       44
dtype: int64

In [24]:
sectors.groups

{'Aerospace & Defense': [26, 50, 58, 98, 117, 118, 207, 224, 275, 380, 404, 406, 414, 540, 660, 661, 806, 829, 884, 930, 954, 955, 959, 975, 988], 'Apparel': [88, 241, 331, 420, 432, 526, 529, 554, 587, 678, 766, 774, 835, 861], 'Business Services': [142, 160, 187, 199, 201, 221, 235, 242, 253, 295, 325, 358, 364, 423, 462, 465, 486, 493, 497, 499, 502, 510, 528, 567, 577, 584, 591, 599, 604, 618, 649, 686, 691, 692, 700, 702, 712, 720, 738, 744, 771, 802, 810, 825, 879, 888, 894, 895, 898, 905, 922, 972, 997], 'Chemicals': [46, 189, 190, 198, 214, 263, 281, 309, 344, 351, 381, 447, 450, 454, 527, 593, 623, 648, 671, 672, 679, 704, 722, 740, 790, 836, 865, 872, 908, 932, 958, 963, 978], 'Energy': [1, 12, 27, 30, 40, 63, 89, 90, 91, 94, 104, 114, 124, 125, 134, 145, 166, 167, 175, 184, 205, 212, 213, 217, 218, 219, 222, 231, 232, 243, 248, 254, 256, 265, 268, 269, 270, 273, 307, 313, 326, 333, 335, 343, 352, 363, 371, 379, 383, 384, 387, 428, 437, 452, 456, 488, 490, 496, 498, 500, 517, 534, 537, 559, 563, 582, 603, 617, 635, 638, 639, 647, 653, 668, 681, 682, 689, 708, 719, 723, 739, 768, 791, 798, 805, 812, 816, 818, 820, 826, 844, 859, 860, 866, 869, 885, 890, 901, 917, 934, ...], 'Engineering & Construction': [152, 163, 210, 229, 296, 315, 338, 340, 367, 427, 443, 479, 541, 569, 588, 615, 705, 736, 737, 764, 779, 815, 841, 852, 962, 982, 986], 'Financials': [2, 19, 20, 23, 25, 31, 35, 37, 42, 51, 59, 65, 66, 67, 68, 69, 78, 83, 85, 92, 99, 100, 102, 103, 105, 111, 121, 135, 136, 155, 164, 172, 174, 204, 206, 209, 211, 216, 233, 236, 238, 240, 249, 251, 252, 258, 262, 266, 298, 301, 302, 306, 310, 312, 329, 336, 342, 347, 355, 365, 368, 374, 375, 377, 397, 411, 412, 418, 430, 434, 436, 439, 440, 449, 453, 457, 459, 461, 463, 466, 468, 469, 475, 476, 482, 483, 485, 492, 501, 513, 514, 533, 539, 543, 562, 570, 572, 576, 579, 581, ...], 'Food &  Drug Stores': [16, 18, 52, 87, 93, 179, 549, 552, 600, 667, 839, 941], 'Food, Beverages & Tobacco': [44, 47, 79, 86, 95, 107, 113, 116, 153, 181, 215, 225, 274, 320, 322, 357, 361, 378, 382, 385, 417, 445, 477, 480, 511, 538, 575, 611, 628, 633, 683, 694, 717, 734, 759, 900, 937], 'Health Care': [4, 6, 24, 28, 36, 48, 55, 56, 60, 62, 72, 77, 109, 110, 115, 128, 129, 144, 146, 151, 159, 161, 169, 178, 197, 223, 239, 244, 250, 267, 282, 285, 303, 327, 360, 366, 389, 415, 472, 474, 503, 506, 518, 542, 555, 560, 602, 605, 655, 669, 673, 718, 724, 742, 753, 754, 782, 795, 830, 845, 915, 921, 925, 935, 936, 939, 956, 960, 994, 996, 998], 'Hotels, Restaurants & Leisure': [126, 130, 131, 226, 279, 323, 395, 396, 446, 471, 478, 535, 548, 556, 583, 713, 714, 721, 741, 775, 817, 851, 891, 903, 965, 984], 'Household Products': [41, 162, 183, 195, 227, 257, 314, 370, 372, 421, 467, 484, 508, 512, 532, 608, 622, 727, 778, 794, 821, 875, 881, 882, 893, 912, 946, 967], 'Industrials': [17, 64, 76, 96, 101, 139, 148, 154, 177, 203, 255, 292, 341, 346, 359, 413, 419, 444, 546, 571, 601, 616, 619, 620, 626, 627, 631, 634, 664, 687, 730, 731, 750, 776, 803, 813, 827, 850, 853, 854, 857, 864, 878, 887, 938, 943, 951, 966, 981], 'Materials': [123, 150, 193, 245, 261, 276, 304, 311, 337, 393, 398, 399, 403, 409, 426, 435, 441, 455, 460, 516, 522, 524, 564, 594, 595, 596, 606, 609, 614, 624, 641, 662, 663, 685, 695, 707, 729, 756, 781, 786, 833, 837, 945, 957, 974], 'Media': [54, 97, 108, 196, 220, 289, 349, 376, 405, 408, 451, 592, 645, 650, 654, 710, 715, 728, 735, 767, 785, 819, 847, 961, 993], 'Motor Vehicles & Parts': [9, 10, 147, 186, 259, 288, 300, 319, 391, 392, 448, 643, 699, 716, 758, 886, 889, 920, 940], 'Retailing': [0, 7, 14, 22, 38, 39, 71, 84, 119, 122, 133, 137, 138, 156, 171, 173, 180, 182, 208, 230, 234, 247, 271, 272, 277, 278, 280, 287, 293, 294, 297, 316, 321, 328, 332, 334, 339, 362, 390, 422, 424, 433, 438, 458, 464, 470, 504, 507, 509, 545, 547, 580, 589, 610, 612, 621, 644, 665, 680, 698, 732, 745, 746, 770, 777, 792, 822, 846, 855, 856, 858, 880, 909, 926, 971, 989, 992], 'Technology': [3, 21, 29, 33, 34, 45, 57, 61, 75, 81, 106, 132, 143, 149, 157, 158, 188, 191, 194, 200, 228, 260, 284, 290, 291, 305, 308, 353, 373, 388, 400, 402, 410, 416, 431, 442, 481, 491, 494, 505, 515, 519, 523, 525, 536, 544, 550, 551, 553, 557, 558, 573, 578, 585, 586, 597, 636, 646, 656, 666, 674, 696, 697, 703, 709, 726, 752, 755, 763, 769, 780, 783, 787, 788, 797, 799, 807, 823, 824, 828, 834, 842, 843, 849, 862, 868, 871, 874, 876, 892, 897, 902, 919, 924, 927, 931, 944, 948, 969, 970, ...], 'Telecommunications': [8, 15, 32, 73, 165, 202, 324, 473, 520, 907], 'Transportation': [43, 49, 70, 74, 80, 140, 141, 185, 192, 264, 283, 354, 386, 394, 401, 407, 487, 495, 530, 531, 566, 598, 632, 637, 675, 688, 706, 762, 793, 801, 814, 848, 904, 906, 914, 918, 928, 933, 947, 968], 'Wholesalers': [5, 11, 13, 53, 82, 112, 120, 127, 168, 170, 176, 237, 246, 286, 299, 317, 318, 330, 345, 348, 350, 356, 369, 425, 429, 489, 521, 561, 565, 568, 574, 642, 652, 670, 684, 748, 757, 773, 800, 809, 870, 910, 942, 995]}

In [25]:
fortune.loc[26, 'Sector']

'Aerospace & Defense'

In [26]:
sectors.first()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,Nike,34350.0,4240.0,74400,Apparel
Business Services,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [27]:
sectors.last()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Aerojet Rocketdyne Holdings,1877.0,-9.2,5157,Aerospace and Defense
Apparel,Wolverine World Wide,2350.0,0.3,3700,Apparel
Business Services,CoreLogic,1851.0,152.2,5900,Financial Data Services
Chemicals,Stepan,1925.0,91.6,2096,Chemicals
Energy,Superior Energy Services,1874.0,-205.9,6400,"Oil and Gas Equipment, Services"
Engineering & Construction,TopBuild,1906.0,158.1,8400,"Engineering, Construction"
Financials,HCP,1848.0,414.2,190,Real estate
Food & Drug Stores,Freds,2064.0,-140.3,7324,Food and Drug Stores
"Food, Beverages & Tobacco",Universal,2071.0,106.3,24000,Tobacco
Health Care,Ensign Group,1849.0,40.5,21301,Health Care: Medical Facilities
"Hotels, Restaurants & Leisure",Vail Resorts,1907.0,210.6,20150,"Hotels, Casinos, Resorts"
Household Products,ACCO Brands,1949.0,131.7,6620,"Home Equipment, Furnishings"
Industrials,Rexnord,1918.0,74.1,8000,Industrial Machinery
Materials,Summit Materials,1933.0,121.8,6000,"Building Materials, Glass"
Media,Tribune Media,1867.0,194.1,6000,Entertainment
Motor Vehicles & Parts,Tower International,2066.0,47.6,7600,Motor Vehicles and Parts
Retailing,Childrens Place,1870.0,84.7,9800,Specialty Retailers: Apparel
Technology,VeriFone Systems,1871.0,-173.8,5600,Financial Data Services
Telecommunications,Zayo Group Holdings,2200.0,85.7,3794,Telecommunications
Transportation,Echo Global Logistics,1943.0,12.6,2453,Transportation and Logistics
Wholesalers,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers: Diversified

In [28]:
sectors.nth(0)

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
54,Disney,55137.0,8980.0,199000,Media,Entertainment
88,Nike,34350.0,4240.0,74400,Apparel,Apparel
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"

In [29]:
sectors.nth(2)

,Company,Revenues,Profits,Employees,Sector,Industry
13,Cardinal Health,129976.0,1288.0,40400,Wholesalers,Wholesalers: Health Care
14,Costco,129025.0,2679.0,182000,Retailing,General Merchandisers
20,Fannie Mae,112394.0,2463.0,7200,Financials,Diversified Financials
24,Express Scripts Holding,100065.0,4517.4,26600,Health Care,Health Care: Pharmacy and Other Services
27,Phillips 66,91568.0,5106.0,14600,Energy,Petroleum Refining
29,Microsoft,89950.0,21204.0,124000,Technology,Computer Software
32,Comcast,84526.0,22714.0,164000,Telecommunications,Telecommunications
52,Albertsons Cos.,59678.0,-373.3,273000,Food & Drug Stores,Food and Drug Stores
58,Lockheed Martin,51048.0,2002.0,100000,Aerospace & Defense,Aerospace and Defense
70,American Airlines Group,42207.0,1919.0,126600,Transportation,Airlines
76,Honeywell International,40534.0,1655.0,131000,Industrials,"Electronics, Electrical Equip."
79,Tyson Foods,38260.0,1774.0,122000,"Food, Beverages & Tobacco",Food Production
108,Twenty-First Century Fox,28500.0,2952.0,21700,Media,Entertainment
131,Starbucks,22387.0,2884.7,277000,"Hotels, Restaurants & Leisure",Food Services
147,Lear,20467.0,1313.4,165000,Motor Vehicles & Parts,Motor Vehicles and Parts
183,Colgate-Palmolive,15454.0,2024.0,35900,Household Products,Household and Personal Products
187,Omnicom Group,15274.0,1088.4,77300,Business Services,"Advertising, marketing"
190,PPG Industries,14967.0,1591.0,47200,Chemicals,Chemicals
193,WestRock,14860.0,708.2,44800,Materials,"Packaging, Containers"
210,D.R. Horton,14091.0,1038.4,7735,Engineering & Construction,Homebuilders
331,PVH,8915.0,537.8,28050,Apparel,Apparel

In [30]:
sectors.nth(3)

,Company,Revenues,Profits,Employees,Sector,Industry
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
23,Bank of America Corp.,100264.0,18232.0,209376,Financials,Commercial Banks
28,Anthem,90040.0,3842.8,56000,Health Care,Health Care: Insurance and Managed Care
30,Valero Energy,88407.0,4065.0,10015,Energy,Petroleum Refining
33,IBM,79139.0,5753.0,397800,Technology,Information Technology Services
53,Sysco,55371.0,1142.5,66500,Wholesalers,Wholesalers: Food and Grocery
73,Charter Communications,41581.0,9895.0,94800,Telecommunications,Telecommunications
74,Delta Air Lines,41244.0,3577.0,86564,Transportation,Airlines
86,Coca-Cola,35410.0,1248.0,61800,"Food, Beverages & Tobacco",Beverages
87,Publix Super Markets,34837.0,2291.9,193000,Food & Drug Stores,Food and Drug Stores
96,3M,31657.0,4858.0,91536,Industrials,Miscellaneous
98,General Dynamics,30973.0,2912.0,98600,Aerospace & Defense,Aerospace and Defense
186,Goodyear Tire & Rubber,15377.0,346.0,64000,Motor Vehicles & Parts,Motor Vehicles and Parts
195,Newell Brands,14742.0,2748.8,49000,Household Products,"Home Equipment, Furnishings"
196,CBS,14710.0,357.0,14715,Media,Entertainment
198,Monsanto,14640.0,2260.0,21900,Chemicals,Chemicals
199,Aramark,14604.0,373.9,215000,Business Services,Diversified Outsourcing Services
226,Las Vegas Sands,12882.0,2806.0,50500,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
229,Lennar,12646.0,810.5,9111,Engineering & Construction,Homebuilders
245,United States Steel,12250.0,387.0,29200,Materials,Metals
420,Ralph Lauren,6653.0,-99.3,18250,Apparel,Apparel

In [31]:
fortune[fortune['Sector'] == 'Apparel'].head()

          Company  Revenues  Profits  Employees   Sector Industry
88           Nike   34350.0   4240.0      74400  Apparel  Apparel
241            VF   12400.0    614.9      69000  Apparel  Apparel
331           PVH    8915.0    537.8      28050  Apparel  Apparel
420  Ralph Lauren    6653.0    -99.3      18250  Apparel  Apparel
432   Hanesbrands    6478.0     61.9      67200  Apparel  Apparel

In [33]:
sectors.first()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,Nike,34350.0,4240.0,74400,Apparel
Business Services,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [34]:
sectors.head(2)

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care
6,CVS Health,184765.0,6622.0,203000,Health Care,Health Care: Pharmacy and Other Services
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
10,Ford Motor,156776.0,7602.0,202000,Motor Vehicles & Parts,Motor Vehicles and Parts
11,AmerisourceBergen,153144.0,364.5,19500,Wholesalers,Wholesalers: Health Care
12,Chevron,134533.0,9195.0,51900,Energy,Petroleum Refining
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
18,Walgreens Boots Alliance,118214.0,4078.0,290000,Food & Drug Stores,Food and Drug Stores
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
47,Archer Daniels Midland,60828.0,1595.0,31300,"Food, Beverages & Tobacco",Food Production
49,FedEx,60319.0,2997.0,357000,Transportation,"Mail, Package, and Freight Delivery"
50,United Technologies,59837.0,4552.0,204700,Aerospace & Defense,Aerospace and Defense
54,Disney,55137.0,8980.0,199000,Media,Entertainment
64,Caterpillar,45462.0,754.0,98400,Industrials,Construction and Farm Machinery
88,Nike,34350.0,4240.0,74400,Apparel,Apparel
97,Time Warner,31271.0,5247.0,26000,Media,Entertainment
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
130,McDonalds,22820.0,5192.3,235000,"Hotels, Restaurants & Leisure",Food Services
142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
150,Nucor,20252.0,1318.7,25100,Materials,Metals
152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"
160,Visa,18358.0,6699.0,15000,Business Services,Financial Data Services
162,Kimberly-Clark,18259.0,2278.0,42000,Household Products,Household and Personal Products
163,AECOM,18203.0,339.4,87000,Engineering & Construction,"Engineering, Construction"
189,Sherwin-Williams,14984.0,1772.3,52695,Chemicals,Chemicals
241,VF,12400.0,614.9,69000,Apparel,Apparel

In [35]:
sectors.head(2).pivot_table(index='Sector', values='Revenues', aggfunc='count')

                               Revenues
Sector
Aerospace & Defense                   2
Apparel                               2
Business Services                     2
Chemicals                             2
Energy                                2
Engineering & Construction            2
Financials                            2
Food &  Drug Stores                   2
Food, Beverages & Tobacco             2
Health Care                           2
Hotels, Restaurants & Leisure         2
Household Products                    2
Industrials                           2
Materials                             2
Media                                 2
Motor Vehicles & Parts                2
Retailing                             2
Technology                            2
Telecommunications                    2
Transportation                        2
Wholesalers                           2

In [36]:
sectors.tail(3)

,Company,Revenues,Profits,Employees,Sector,Industry
473,Windstream Holdings,5853.0,-2116.6,12979,Telecommunications,Telecommunications
520,Telephone & Data Systems,5044.0,153.0,9900,Telecommunications,Telecommunications
667,Weis Markets,3467.0,98.4,23000,Food & Drug Stores,Food and Drug Stores
759,Hain Celestial Group,2853.0,67.4,7825,"Food, Beverages & Tobacco",Food Consumer Products
774,Fossil Group,2788.0,-478.2,12300,Apparel,Apparel
...,...,...,...,...,...,...
995,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers,Wholesalers: Diversified
996,Charles River Laboratories Intl,1858.0,123.4,11800,Health Care,Health Care: Pharmacy and Other Services
997,CoreLogic,1851.0,152.2,5900,Business Services,Financial Data Services
998,Ensign Group,1849.0,40.5,21301,Health Care,Health Care: Medical Facilities
999,HCP,1848.0,414.2,190,Financials,Real estate

In [37]:
sectors.get_group('Energy')

,Company,Revenues,Profits,Employees,Sector,Industry
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
12,Chevron,134533.0,9195.0,51900,Energy,Petroleum Refining
27,Phillips 66,91568.0,5106.0,14600,Energy,Petroleum Refining
30,Valero Energy,88407.0,4065.0,10015,Energy,Petroleum Refining
40,Marathon Petroleum,67610.0,3432.0,43800,Energy,Petroleum Refining
...,...,...,...,...,...,...
953,California Resources,2006.0,-266.0,1450,Energy,"Mining, Crude-Oil Production"
976,Ferrellgas Partners,1930.0,-54.2,3891,Energy,Energy
979,Oceaneering International,1922.0,166.4,8200,Energy,"Oil and Gas Equipment, Services"
980,Cimarex Energy,1918.0,494.3,910,Energy,"Mining, Crude-Oil Production"
990,Superior Energy Services,1874.0,-205.9,6400,Energy,"Oil and Gas Equipment, Services"

In [38]:
sectors.sum()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,BoeingUnited TechnologiesLockheed MartinGenera...,383835.0,26733.5,1010124,Aerospace and DefenseAerospace and DefenseAero...
Apparel,NikeVFPVHRalph LaurenHanesbrandsUnder ArmourLe...,101157.3,6350.7,355699,ApparelApparelApparelApparelApparelApparelAppa...
Business Services,ManpowerGroupVisaOmnicom GroupAramarkWaste Man...,316090.0,37179.2,1593999,Temporary HelpFinancial Data ServicesAdvertisi...
Chemicals,DowDuPontSherwin-WilliamsPPG IndustriesMonsant...,251151.0,20475.0,474020,ChemicalsChemicalsChemicalsChemicalsChemicalsC...
Energy,Exxon MobilChevronPhillips 66Valero EnergyMara...,1543507.2,85369.6,981207,Petroleum RefiningPetroleum RefiningPetroleum ...
Engineering & Construction,FluorAECOMD.R. HortonLennarJacobs Engineering ...,172782.0,7121.0,420745,"Engineering, ConstructionEngineering, Construc..."
Financials,Berkshire HathawayJPMorgan ChaseFannie MaeBank...,2442480.0,264253.5,3500119,Insurance: Property and Casualty (Stock)Commer...
Food & Drug Stores,KrogerWalgreens Boots AllianceAlbertsons Cos.P...,405468.0,8440.3,1398074,Food and Drug StoresFood and Drug StoresFood a...
"Food, Beverages & Tobacco",PepsiCoArcher Daniels MidlandTyson FoodsCoca-C...,510232.0,54902.5,1079316,Food Consumer ProductsFood ProductionFood Prod...
Health Care,UnitedHealth GroupCVS HealthExpress Scripts Ho...,1507991.4,92791.1,2971189,Health Care: Insurance and Managed CareHealth ...
"Hotels, Restaurants & Leisure",Marriott InternationalMcDonaldsStarbucksLas Ve...,179825.0,21305.5,2304337,"Hotels, Casinos, ResortsFood ServicesFood Serv..."
Household Products,Procter & GambleKimberly-ClarkColgate-Palmoliv...,231779.8,27726.8,674896,Household and Personal ProductsHousehold and P...
Industrials,General ElectricCaterpillarHoneywell Internati...,520140.0,19114.3,1566110,Industrial MachineryConstruction and Farm Mach...
Materials,International PaperNucorWestRockUnited States ...,278298.0,13730.4,653751,"Packaging, ContainersMetalsPackaging, Containe..."
Media,DisneyTime WarnerTwenty-First Century FoxCBSVi...,230487.4,23019.9,545985,EntertainmentEntertainmentEntertainmentEnterta...
Motor Vehicles & Parts,General MotorsFord MotorLearGoodyear Tire & Ru...,433535.0,6861.1,943582,Motor Vehicles and PartsMotor Vehicles and Par...
Retailing,WalmartAmazon.comCostcoHome DepotTargetLowesBe...,1684353.0,55707.2,6800658,General MerchandisersInternet Services and Ret...
Technology,AppleAlphabetMicrosoftIBMDell TechnologiesInte...,1374822.3,177883.9,3196807,"Computers, Office EquipmentInternet Services a..."
Telecommunications,AT&TVerizonComcastCharter CommunicationsCentur...,466959.0,91965.8,785609,TelecommunicationsTelecommunicationsTelecommun...
Transportation,UPSFedExAmerican Airlines GroupDelta Air Lines...,455160.0,52960.3,1652113,"Mail, Package, and Freight DeliveryMail, Packa..."
Wholesalers,McKessonAmerisourceBergenCardinal HealthSyscoT...,888149.0,15657.4,744175,Wholesalers: Health CareWholesalers: Health Ca...

In [39]:
sectors['Revenues'].sum()

Sector
Aerospace & Defense               383835.0
Apparel                           101157.3
Business Services                 316090.0
Chemicals                         251151.0
Energy                           1543507.2
Engineering & Construction        172782.0
Financials                       2442480.0
Food &  Drug Stores               405468.0
Food, Beverages & Tobacco         510232.0
Health Care                      1507991.4
Hotels, Restaurants & Leisure     179825.0
Household Products                231779.8
Industrials                       520140.0
Materials                         278298.0
Media                             230487.4
Motor Vehicles & Parts            433535.0
Retailing                        1684353.0
Technology                       1374822.3
Telecommunications                466959.0
Transportation                    455160.0
Wholesalers                       888149.0
Name: Revenues, dtype: float64

In [41]:
sectors[['Revenues', 'Profits']].sum()

                                Revenues   Profits
Sector
Aerospace & Defense             383835.0   26733.5
Apparel                         101157.3    6350.7
Business Services               316090.0   37179.2
Chemicals                       251151.0   20475.0
Energy                         1543507.2   85369.6
Engineering & Construction      172782.0    7121.0
Financials                     2442480.0  264253.5
Food &  Drug Stores             405468.0    8440.3
Food, Beverages & Tobacco       510232.0   54902.5
Health Care                    1507991.4   92791.1
Hotels, Restaurants & Leisure   179825.0   21305.5
Household Products              231779.8   27726.8
Industrials                     520140.0   19114.3
Materials                       278298.0   13730.4
Media                           230487.4   23019.9
Motor Vehicles & Parts          433535.0    6861.1
Retailing                      1684353.0   55707.2
Technology                     1374822.3  177883.9
Telecommunications              466959.0   91965.8
Transportation                  455160.0   52960.3
Wholesalers                     888149.0   15657.4

In [42]:
sectors['Revenues'].mean()

Sector
Aerospace & Defense              15353.400000
Apparel                           7225.521429
Business Services                 5963.962264
Chemicals                         7610.636364
Energy                           14425.300935
Engineering & Construction        6399.333333
Financials                       15757.935484
Food &  Drug Stores              33789.000000
Food, Beverages & Tobacco        13790.054054
Health Care                      21239.315493
Hotels, Restaurants & Leisure     6916.346154
Household Products                8277.850000
Industrials                      10615.102041
Materials                         6184.400000
Media                             9219.496000
Motor Vehicles & Parts           22817.631579
Retailing                        21874.714286
Technology                       13347.789320
Telecommunications               46695.900000
Transportation                   11379.000000
Wholesalers                      20185.204545
Name: Revenues, dtype: float64

In [43]:
sectors.max()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Woodward,93392.0,8197.0,204700,Aerospace and Defense
Apparel,Wolverine World Wide,34350.0,4240.0,74400,Apparel
Business Services,Worldpay,21034.0,6699.0,215000,Waste Management
Chemicals,Westlake Chemical,62683.0,3000.4,98000,Chemicals
Energy,Xcel Energy,244363.0,19710.0,71200,Utilities: Gas and Electric
Engineering & Construction,Tutor Perini,19521.0,1038.4,87000,Homebuilders
Financials,Zions Bancorp.,242137.0,44940.0,377000,Securities
Food & Drug Stores,Weis Markets,122662.0,4078.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",Universal,63525.0,10999.0,263000,Tobacco
Health Care,Zoetis,201159.0,21308.0,260000,"Scientific,Photographic and Control Equipment"
"Hotels, Restaurants & Leisure",Yum China Holdings,22894.0,5192.3,450000,"Hotels, Casinos, Resorts"
Household Products,Vista Outdoor,66217.0,15326.0,95000,"Toys, Sporting Goods"
Industrials,Zebra Technologies,122274.0,4858.0,313000,Miscellaneous
Materials,Worthington Industries,23302.0,2144.0,56000,"Packaging, Containers"
Media,iHeartMedia,55137.0,8980.0,199000,"Publishing, Printing"
Motor Vehicles & Parts,WABCO Holdings,157311.0,7602.0,202000,Motor Vehicles and Parts
Retailing,Williams-Sonoma,500343.0,9862.0,2300000,Specialty Retailers: Other
Technology,salesforce.com,229234.0,48351.0,397800,Semiconductors and Other Electronic Components
Telecommunications,Zayo Group Holdings,160546.0,30101.0,254000,Telecommunications
Transportation,YRC Worldwide,65872.0,10712.0,357000,"Trucking, Truck Leasing"
Wholesalers,Watsco,198533.0,5070.0,113600,Wholesalers: Health Care

In [44]:
sectors['Employees'].min()

Sector
Aerospace & Defense              5157
Apparel                          3700
Business Services                2338
Chemicals                        1931
Energy                            593
Engineering & Construction       1100
Financials                        152
Food &  Drug Stores              7324
Food, Beverages & Tobacco        1819
Health Care                      2298
Hotels, Restaurants & Leisure    8600
Household Products               4050
Industrials                      4125
Materials                         126
Media                            2039
Motor Vehicles & Parts           2700
Retailing                        2505
Technology                       2100
Telecommunications               3794
Transportation                   1273
Wholesalers                       981
Name: Employees, dtype: int64

In [46]:
sectors.agg({'Revenues': 'min', 'Profits': 'max', 'Employees': 'mean'})

                               Revenues  Profits      Employees
Sector
Aerospace & Defense              1877.0   8197.0   40404.960000
Apparel                          2350.0   4240.0   25407.071429
Business Services                1851.0   6699.0   30075.452830
Chemicals                        1925.0   3000.4   14364.242424
Energy                           1874.0  19710.0    9170.158879
Engineering & Construction       1906.0   1038.4   15583.148148
Financials                       1848.0  44940.0   22581.412903
Food &  Drug Stores              2064.0   4078.0  116506.166667
Food, Beverages & Tobacco        2071.0  10999.0   29170.702703
Health Care                      1849.0  21308.0   41847.732394
Hotels, Restaurants & Leisure    1907.0   5192.3   88628.346154
Household Products               1949.0  15326.0   24103.428571
Industrials                      1918.0   4858.0   31961.428571
Materials                        1933.0   2144.0   14527.800000
Media                            1867.0   8980.0   21839.400000
Motor Vehicles & Parts           2066.0   7602.0   49662.210526
Retailing                        1870.0   9862.0   88320.233766
Technology                       1871.0  48351.0   31036.961165
Telecommunications               2200.0  30101.0   78560.900000
Transportation                   1943.0  10712.0   41302.825000
Wholesalers                      1862.0   5070.0   16913.068182

In [47]:
fortune.nlargest(n=5, columns='Profits')

,Company,Revenues,Profits,Employees,Sector,Industry
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks

In [48]:
def get_largest_row(df):
    return df.nlargest(1, 'Revenues')

In [50]:
sectors[['Company', 'Revenues', 'Profits', 'Employees', 'Industry']].apply(get_largest_row)

,,Company,Revenues,Profits,Employees,Industry
Sector,,,,,,
Aerospace & Defense,26,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,88,Nike,34350.0,4240.0,74400,Apparel
Business Services,142,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,46,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,1,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,152,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,2,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,16,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",44,PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,4,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",126,Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,41,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,17,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,123,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,54,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,9,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,0,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,3,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,8,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,43,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,5,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [51]:
si = fortune.groupby(by=['Sector', 'Industry'])

In [52]:
si

In [54]:
si.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            25
Apparel              Apparel                                          14
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         2
                                                                      ..
Transportation       Trucking, Truck Leasing                          11
Wholesalers          Wholesalers: Diversified                         24
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
                     Wholesalers: Health Care                          6
Length: 82, dtype: int64

In [55]:
si.groups

{('Aerospace & Defense', 'Aerospace and Defense'): [26, 50, 58, 98, 117, 118, 207, 224, 275, 380, 404, 406, 414, 540, 660, 661, 806, 829, 884, 930, 954, 955, 959, 975, 988], ('Apparel', 'Apparel'): [88, 241, 331, 420, 432, 526, 529, 554, 587, 678, 766, 774, 835, 861], ('Business Services', 'Advertising, marketing'): [187, 358], ('Business Services', 'Diversified Outsourcing Services'): [199, 242, 465, 497, 499, 577, 618, 691, 692, 700, 702, 712, 744, 771], ('Business Services', 'Education'): [567, 810], ('Business Services', 'Financial Data Services'): [160, 221, 235, 253, 325, 364, 462, 486, 493, 528, 584, 591, 599, 604, 686, 879, 894, 895, 898, 905, 922, 972, 997], ('Business Services', 'Miscellaneous'): [423, 720, 888], ('Business Services', 'Temporary Help'): [142, 502, 510, 802, 825], ('Business Services', 'Waste Management'): [201, 295, 649, 738], ('Chemicals', 'Chemicals'): [46, 189, 190, 198, 214, 263, 281, 309, 344, 351, 381, 447, 450, 454, 527, 593, 623, 648, 671, 672, 679, 704, 722, 740, 790, 836, 865, 872, 908, 932, 958, 963, 978], ('Energy', 'Energy'): [90, 222, 268, 335, 352, 456, 488, 498, 537, 559, 617, 647, 682, 739, 860, 885, 917, 976], ('Energy', 'Mining, Crude-Oil Production'): [94, 175, 212, 219, 256, 269, 313, 384, 437, 490, 496, 500, 517, 582, 635, 708, 719, 805, 812, 866, 869, 901, 953, 980], ('Energy', 'Miscellaneous'): [689], ('Energy', 'Oil and Gas Equipment, Services'): [145, 387, 639, 859, 979, 990], ('Energy', 'Petroleum Refining'): [1, 12, 27, 30, 40, 89, 134, 205, 383, 603, 844], ('Energy', 'Pipelines'): [63, 104, 114, 217, 248, 333, 343, 638, 768, 826, 934, 949], ('Energy', 'Utilities: Gas and Electric'): [91, 124, 125, 166, 167, 184, 213, 218, 231, 232, 243, 254, 265, 270, 273, 307, 326, 363, 371, 379, 428, 452, 534, 563, 653, 668, 681, 723, 791, 798, 816, 818, 820, 890, 952], ('Engineering & Construction', 'Engineering, Construction'): [152, 163, 296, 315, 338, 367, 427, 541, 588, 736, 737, 779, 852, 986], ('Engineering & Construction', 'Homebuilders'): [210, 229, 340, 443, 479, 569, 615, 705, 764, 815, 841, 962, 982], ('Financials', 'Commercial Banks'): [19, 23, 25, 31, 66, 69, 100, 121, 164, 174, 249, 258, 262, 302, 365, 411, 434, 459, 466, 485, 543, 657, 701, 743, 784, 923, 950], ('Financials', 'Diversified Financials'): [20, 37, 85, 102, 135, 172, 211, 240, 251, 298, 306, 397, 453, 514, 625, 725, 765, 896], ('Financials', 'Insurance: Life, Health (Mutual)'): [68, 83, 92, 103, 238, 342, 475, 711, 747, 877], ('Financials', 'Insurance: Life, Health (stock)'): [42, 51, 136, 204, 209, 233, 266, 312, 336, 347, 461, 579, 590, 613, 659, 677, 760, 883, 985], ('Financials', 'Insurance: Property and Casualty (Mutual)'): [35, 65, 252, 374, 377, 658, 693, 811, 911], ('Financials', 'Insurance: Property and Casualty (Stock)'): [2, 59, 67, 78, 99, 105, 111, 155, 216, 301, 310, 368, 412, 436, 439, 449, 463, 468, 482, 483, 513, 533, 562, 676, 789, 832, 964, 987], ('Financials', 'Real estate'): [206, 355, 418, 457, 492, 501, 570, 572, 576, 651, 761, 772, 796, 804, 808, 831, 838, 863, 867, 913, 916, 999], ('Financials', 'Securities'): [236, 329, 375, 430, 440, 469, 476, 539, 581, 607, 629, 630, 640, 690, 733, 749, 751, 840, 873, 899, 929, 977], ('Food &  Drug Stores', 'Food and Drug Stores'): [16, 18, 52, 87, 93, 179, 549, 552, 600, 667, 839, 941], ('Food, Beverages & Tobacco', 'Beverages'): [86, 274, 385, 417, 575, 683, 734], ('Food, Beverages & Tobacco', 'Food Consumer Products'): [44, 113, 116, 181, 215, 225, 320, 322, 357, 361, 378, 382, 445, 511, 538, 611, 717, 759, 900], ('Food, Beverages & Tobacco', 'Food Production'): [47, 79, 95, 477, 480, 628, 633, 694], ('Food, Beverages & Tobacco', 'Tobacco'): [107, 153, 937], ('Health Care', 'Health Care: Insurance and Managed Care'): [4, 28, 48, 55, 60, 72, 151, 169, 474, 742], ('Health Care', 'Health Care: Medical Facilities'): [62, 146, 159, 178, 267, 389, 415, 503, 542, 560, 605, 753, 936, 998], ('Health Care', 'Health Care: Pharmacy and Other Services'): [6, 24, 197, 285, 303, 366, 518, 555, 669, 795, 845, 956, 994, 996], ('Health Care', 'Medical Products and Equipment'): [110, 161, 239, 250, 282, 327, 360, 602, 673, 718, 724, 754, 782, 921, 925, 939, 960], ('Health Care', 'Pharmaceuticals'): [36, 56, 77, 109, 115, 128, 129, 144, 223, 244, 472, 506, 655, 830, 935], ('Health Care', 'Scientific,Photographic and  Control Equipment'): [915], ('Hotels, Restaurants & Leisure', 'Food Services'): [130, 131, 395, 396, 471, 556, 583, 713, 741, 775, 891, 903], ('Hotels, Restaurants & Leisure', 'Hotels, Casinos, Resorts'): [126, 226, 279, 323, 446, 478, 535, 548, 714, 721, 817, 851, 965, 984], ('Household Products', 'Home Equipment, Furnishings'): [195, 227, 314, 372, 508, 608, 727, 778, 882, 912, 967], ('Household Products', 'Household and Personal Products'): [41, 162, 183, 257, 370, 421, 467, 484, 622, 794, 875, 881, 893, 946], ('Household Products', 'Miscellaneous'): [821], ('Household Products', 'Toys, Sporting Goods'): [512, 532], ('Industrials', 'Construction and Farm Machinery'): [64, 101, 154, 341, 346, 413, 571, 827], ('Industrials', 'Electronics, Electrical Equip.'): [76, 139, 292, 444, 620, 627, 631, 664, 687, 731, 850, 857, 951], ('Industrials', 'Industrial Machinery'): [17, 148, 177, 203, 255, 359, 419, 546, 601, 616, 619, 626, 634, 730, 750, 776, 803, 813, 853, 854, 864, 878, 887, 938, 943, 966, 981], ('Industrials', 'Miscellaneous'): [96], ('Materials', 'Building Materials, Glass'): [399, 441, 594, 606, 609, 614, 624, 707, 786, 945, 957, 974], ('Materials', 'Forest and Paper Products'): [393, 516, 663, 837], ('Materials', 'Metals'): [150, 245, 261, 304, 311, 460, 524, 662, 685, 729, 756, 781], ('Materials', 'Miscellaneous'): [403], ('Materials', 'Packaging, Containers'): [123, 193, 276, 337, 398, 409, 426, 435, 455, 522, 564, 595, 596, 641, 695, 833], ('Media', 'Entertainment'): [54, 97, 108, 196, 220, 289, 376, 408, 451, 650, 654, 710, 728, 735, 767, 785, 819, 847, 993], ('Media', 'Publishing, Printing'): [349, 405, 592, 645, 715, 961], ('Motor Vehicles & Parts', 'Motor Vehicles and Parts'): [9, 10, 147, 186, 259, 288, 300, 319, 391, 392, 448, 643, 699, 716, 758, 886, 889, 920, 940], ('Retailing', 'Automotive Retailing, Services'): [137, 138, 173, 272, 293, 297, 332, 334, 433, 545, 580], ('Retailing', 'General Merchandisers'): [0, 14, 38, 119, 156, 171, 182, 234, 438, 732, 822], ('Retailing', 'Internet Services and Retailing'): [7, 287, 294], ('Retailing', 'Specialty Retailers: Apparel'): [84, 180, 208, 230, 362, 422, 458, 547, 621, 644, 665, 698, 746, 770, 777, 856, 858, 880, 926, 971, 992], ('Retailing', 'Specialty Retailers: Other'): [22, 39, 71, 122, 133, 247, 271, 277, 278, 280, 316, 321, 328, 339, 390, 424, 464, 470, 504, 507, 509, 589, 610, 612, 680, 745, 792, 846, 855, 909, 989], ('Technology', 'Computer Software'): [29, 81, 284, 388, 515, 585, 597, 752, 788, 849, 902, 924, 944, 969, 970, 973], ('Technology', 'Computers, Office Equipment'): [3, 34, 57, 106, 157, 290, 431, 494, 550, 656, 823], ('Technology', 'Entertainment'): [400, 536], ('Technology', 'Financial Data Services'): [991], ('Technology', 'Information Technology Services'): [33, 188, 194, 291, 373, 416, 481, 525, 558, 573, 696, 703, 763, 783, 842, 919], ('Technology', 'Internet Services and Retailing'): [21, 75, 228, 260, 308, 544, 646, 697, 755, 828, 843, 897], ('Technology', 'Network and Other Communications Equipment'): [61, 402, 442, 523, 553, 769, 931, 948], ('Technology', 'Scientific,Photographic and  Control Equipment'): [143, 551, 557, 578, 709, 780, 787, 799, 871, 874, 892], ('Technology', 'Semiconductors and Other Electronic Components'): [45, 132, 149, 158, 191, 200, 305, 353, 410, 491, 505, 519, 586, 636, 666, 674, 726, 797, 807, 824, 834, 862, 868, 876, 927, 983], ('Telecommunications', 'Telecommunications'): [8, 15, 32, 73, 165, 202, 324, 473, 520, 907], ('Transportation', 'Airlines'): [70, 74, 80, 141, 354, 401, 706, 793, 801], ('Transportation', 'Mail, Package, and Freight Delivery'): [43, 49], ('Transportation', 'Railroads'): [140, 264, 283, 814, 906], ('Transportation', 'Shipping'): [904, 947], ('Transportation', 'Transportation Equipment'): [487, 495, 530, 632, 914], ('Transportation', 'Transportation and Logistics'): [185, 192, 407, 598, 918, 968], ('Transportation', 'Trucking, Truck Leasing'): [386, 394, 531, 566, 637, 675, 688, 762, 848, 928, 933], ('Wholesalers', 'Wholesalers: Diversified'): [176, 286, 299, 330, 345, 348, 369, 425, 429, 561, 565, 568, 574, 642, 670, 684, 748, 757, 773, 800, 809, 870, 942, 995], ('Wholesalers', 'Wholesalers: Electronics and Office Equipment'): [82, 112, 127, 168, 356, 521, 652, 910], ('Wholesalers', 'Wholesalers: Food and Grocery'): [53, 120, 170, 246, 318, 350], ('Wholesalers', 'Wholesalers: Health Care'): [5, 11, 13, 237, 317, 489]}

In [58]:
si.get_group(('Retailing', 'General Merchandisers'))

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
14,Costco,129025.0,2679.0,182000,Retailing,General Merchandisers
38,Target,71879.0,2934.0,345000,Retailing,General Merchandisers
119,Macys,24837.0,1547.0,130000,Retailing,General Merchandisers
156,Kohls,19095.0,859.0,85000,Retailing,General Merchandisers
171,Sears Holdings,16702.0,-383.0,89000,Retailing,General Merchandisers
182,Nordstrom,15478.0,437.0,76000,Retailing,General Merchandisers
234,J.C. Penney,12506.0,-116.0,98000,Retailing,General Merchandisers
438,Dillards,6423.0,221.3,31400,Retailing,General Merchandisers
732,PriceSmart,2997.0,90.7,7903,Retailing,General Merchandisers
822,Bon-Ton Stores,2541.0,-90.7,23300,Retailing,General Merchandisers

In [59]:
si['Profits'].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            26733.5
Apparel              Apparel                                           6350.7
Business Services    Advertising, marketing                            1667.4
                     Diversified Outsourcing Services                  5043.7
                     Education                                          393.5
                                                                       ...
Transportation       Trucking, Truck Leasing                           3535.5
Wholesalers          Wholesalers: Diversified                          5231.5
                     Wholesalers: Electronics and Office Equipment     1259.4
                     Wholesalers: Food and Grocery                     1794.0
                     Wholesalers: Health Care                          7372.5
Name: Profits, Length: 82, dtype: float64

In [60]:
# Homework

In [61]:
df = pd.read_csv('cereals.csv')
df

                         Name    Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran         Nabisco  Cold        70   10.0       6
1           100% Natural Bran     Quaker Oats  Cold       120    2.0       8
2                    All-Bran       Kellogg's  Cold        70    9.0       5
3   All-Bran with Extra Fiber       Kellogg's  Cold        50   14.0       0
4              Almond Delight  Ralston Purina  Cold       110    1.0       8
..                        ...             ...   ...       ...    ...     ...
72                    Triples   General Mills  Cold       110    0.0       3
73                       Trix   General Mills  Cold       110    0.0      12
74                 Wheat Chex  Ralston Purina  Cold       100    3.0       3
75                   Wheaties   General Mills  Cold       100    3.0       3
76        Wheaties Honey Gold   General Mills  Cold       110    1.0       8

[77 rows x 6 columns]

In [62]:
len(df)

77

In [63]:
df.count()

Name            77
Manufacturer    77
Type            77
Calories        77
Fiber           77
Sugars          77
dtype: int64

In [64]:
df.nunique()

Name            77
Manufacturer     7
Type             2
Calories        11
Fiber           13
Sugars          17
dtype: int64

In [65]:
df['Type'].unique()

array(['Cold', 'Hot'], dtype=object)

In [66]:
# 1
man = df.groupby(by='Manufacturer')

In [67]:
man

In [68]:
# 2
len(man)

7

In [69]:
man.size()

Manufacturer
American Home Food Products     1
General Mills                  22
Kellogg's                      23
Nabisco                         6
Post                            9
Quaker Oats                     8
Ralston Purina                  8
dtype: int64

In [70]:
man.size().sum()

np.int64(77)

In [71]:
# 3
man.get_group('Nabisco')

                         Name Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran      Nabisco  Cold        70   10.0       6
20     Cream of Wheat (Quick)      Nabisco   Hot       100    1.0       0
63             Shredded Wheat      Nabisco  Cold        80    3.0       0
64     Shredded Wheat 'n'Bran      Nabisco  Cold        90    4.0       0
65  Shredded Wheat spoon size      Nabisco  Cold        90    3.0       0
68    Strawberry Fruit Wheats      Nabisco  Cold        90    3.0       5

In [72]:
# 4
man[['Calories', 'Fiber', 'Sugars']].mean()

                               Calories     Fiber    Sugars
Manufacturer
American Home Food Products  100.000000  0.000000  3.000000
General Mills                111.363636  1.272727  7.954545
Kellogg's                    108.695652  2.739130  7.565217
Nabisco                       86.666667  4.000000  1.833333
Post                         108.888889  2.777778  8.777778
Quaker Oats                   95.000000  1.337500  5.250000
Ralston Purina               115.000000  1.875000  6.125000

In [73]:
# 5
man['Sugars'].max()

Manufacturer
American Home Food Products     3
General Mills                  14
Kellogg's                      15
Nabisco                         6
Post                           15
Quaker Oats                    12
Ralston Purina                 11
Name: Sugars, dtype: int64

In [74]:
# 6
man['Fiber'].min()

Manufacturer
American Home Food Products    0.0
General Mills                  0.0
Kellogg's                      0.0
Nabisco                        1.0
Post                           0.0
Quaker Oats                    0.0
Ralston Purina                 0.0
Name: Fiber, dtype: float64

In [75]:
# 7
def get_less_sugar(df):
    return df.nsmallest(n=1, columns='Sugars')

In [77]:
man[['Name', 'Type', 'Calories', 'Fiber', 'Sugars']].apply(get_less_sugar)

,,Name,Type,Calories,Fiber,Sugars
Manufacturer,,,,,,
American Home Food Products,43,Maypo,Hot,100,0.0,3
General Mills,11,Cheerios,Cold,110,2.0,1
Kellogg's,3,All-Bran with Extra Fiber,Cold,50,14.0,0
Nabisco,20,Cream of Wheat (Quick),Hot,100,1.0,0
Post,33,Grape-Nuts,Cold,110,3.0,3
Quaker Oats,57,Quaker Oatmeal,Hot,100,2.7,-1
Ralston Purina,61,Rice Chex,Cold,110,0.0,2