In [1]:
import numpy as np
import pandas as pd

In [4]:
sales = pd.read_csv('sales_by_employee.csv', parse_dates=['Date'])
sales.head()

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_4851/2812195795.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales = pd.read_csv('sales_by_employee.csv', parse_dates=['Date'])

        Date   Name       Customer  Revenue  Expenses
0 2020-01-01  Oscar  Logistics XYZ     5250       531
1 2020-01-01  Oscar    Money Corp.     4406       661
2 2020-01-02  Oscar     PaperMaven     8661      1401
3 2020-01-03  Oscar    PaperGenius     7075       906
4 2020-01-04  Oscar    Paper Pound     2524      1767

In [5]:
sales.count()

Date        26
Name        26
Customer    26
Revenue     26
Expenses    26
dtype: int64

In [6]:
len(sales)

26

In [7]:
sales.nunique()

Date         5
Name         5
Customer     7
Revenue     26
Expenses    26
dtype: int64

In [28]:
sales.pivot_table(index=['Date'], columns=['Name'], values=['Revenue'], aggfunc=['sum'])

                sum
            Revenue
Name          Creed   Dwight     Jim Michael   Oscar
Date
2020-01-01   4430.0   2639.0  1864.0  7172.0  9656.0
2020-01-02  13214.0      NaN  8278.0  6362.0  8661.0
2020-01-03      NaN  11912.0  4226.0  5982.0  7075.0
2020-01-04   3144.0      NaN  6155.0  7917.0  2524.0
2020-01-05    938.0   7771.0     NaN  7837.0  2793.0

In [34]:
sales.pivot_table(index='Date', columns='Name', values='Revenue', aggfunc='sum', fill_value=0, margins=True, margins_name='Total')

Name                 Creed  Dwight    Jim  Michael  Oscar   Total
Date
2020-01-01 00:00:00   4430    2639   1864     7172   9656   25761
2020-01-02 00:00:00  13214       0   8278     6362   8661   36515
2020-01-03 00:00:00      0   11912   4226     5982   7075   29195
2020-01-04 00:00:00   3144       0   6155     7917   2524   19740
2020-01-05 00:00:00    938    7771      0     7837   2793   19339
Total                21726   22322  20523    35270  30709  130550

In [35]:
sales.pivot_table(index='Date', columns='Name', values='Revenue', aggfunc='count', fill_value=0, margins=True, margins_name='Total')

Name                 Creed  Dwight  Jim  Michael  Oscar  Total
Date
2020-01-01 00:00:00      1       1    1        1      2      6
2020-01-02 00:00:00      2       0    1        1      1      5
2020-01-03 00:00:00      0       3    1        1      1      6
2020-01-04 00:00:00      1       0    2        1      1      5
2020-01-05 00:00:00      1       1    0        1      1      4
Total                    5       5    5        5      6     26

In [36]:
sales.pivot_table(index='Date', columns='Name', values='Revenue', aggfunc=['sum', 'count'], fill_value=0, margins=True, margins_name='Total')

                       sum                                      count         \
Name                 Creed Dwight    Jim Michael  Oscar   Total Creed Dwight
Date
2020-01-01 00:00:00   4430   2639   1864    7172   9656   25761     1      1
2020-01-02 00:00:00  13214      0   8278    6362   8661   36515     2      0
2020-01-03 00:00:00      0  11912   4226    5982   7075   29195     0      3
2020-01-04 00:00:00   3144      0   6155    7917   2524   19740     1      0
2020-01-05 00:00:00    938   7771      0    7837   2793   19339     1      1
Total                21726  22322  20523   35270  30709  130550     5      5


Name                Jim Michael Oscar Total
Date
2020-01-01 00:00:00   1       1     2     6
2020-01-02 00:00:00   1       1     1     5
2020-01-03 00:00:00   1       1     1     6
2020-01-04 00:00:00   2       1     1     5
2020-01-05 00:00:00   0       1     1     4
Total                 5       5     6    26

In [38]:
sales.pivot_table(index='Date', columns='Name', values=['Revenue', 'Expenses'], aggfunc={'Revenue':'max', 'Expenses':'min'}, fill_value=0, margins=True, margins_name='Total')

                    Expenses                                  Revenue         \
Name                   Creed Dwight   Jim Michael Oscar Total   Creed Dwight
Date
2020-01-01 00:00:00      548    368  1305     412   531   368    4430   2639
2020-01-02 00:00:00     1768      0   462     685  1401   462    8026      0
2020-01-03 00:00:00        0    758  1923    1772   906   758       0   4951
2020-01-04 00:00:00     1314      0   426    1857  1767   426    3144      0
2020-01-05 00:00:00     1053   1475     0    1633   624   624     938   7771
Total                    548    368   426     412   531   368    8026   7771


Name                  Jim Michael Oscar Total
Date
2020-01-01 00:00:00  1864    7172  5250  7172
2020-01-02 00:00:00  8278    6362  8661  8661
2020-01-03 00:00:00  4226    5982  7075  7075
2020-01-04 00:00:00  3868    7917  2524  7917
2020-01-05 00:00:00     0    7837  2793  7837
Total                8278    7917  8661  8661

In [39]:
sales.pivot_table(index=['Name', 'Date'], values=['Revenue', 'Expenses'], aggfunc={'Revenue':'max', 'Expenses':'min'}, fill_value=0, margins=True, margins_name='Total')

                             Expenses  Revenue
Name    Date
Creed   2020-01-01 00:00:00       548     4430
        2020-01-02 00:00:00      1768     8026
        2020-01-04 00:00:00      1314     3144
        2020-01-05 00:00:00      1053      938
Dwight  2020-01-01 00:00:00       368     2639
        2020-01-03 00:00:00       758     4951
        2020-01-05 00:00:00      1475     7771
Jim     2020-01-01 00:00:00      1305     1864
        2020-01-02 00:00:00       462     8278
        2020-01-03 00:00:00      1923     4226
        2020-01-04 00:00:00       426     3868
Michael 2020-01-01 00:00:00       412     7172
        2020-01-02 00:00:00       685     6362
        2020-01-03 00:00:00      1772     5982
        2020-01-04 00:00:00      1857     7917
        2020-01-05 00:00:00      1633     7837
Oscar   2020-01-01 00:00:00       531     5250
        2020-01-02 00:00:00      1401     8661
        2020-01-03 00:00:00       906     7075
        2020-01-04 00:00:00      1767     2524
        2020-01-05 00:00:00       624     2793
Total                             368     8661

In [40]:
sales.pivot_table(index=['Date', 'Name'], values=['Revenue', 'Expenses'], aggfunc={'Revenue':'max', 'Expenses':'min'}, fill_value=0, margins=True, margins_name='Total')

                             Expenses  Revenue
Date                Name
2020-01-01 00:00:00 Creed         548     4430
                    Dwight        368     2639
                    Jim          1305     1864
                    Michael       412     7172
                    Oscar         531     5250
2020-01-02 00:00:00 Creed        1768     8026
                    Jim           462     8278
                    Michael       685     6362
                    Oscar        1401     8661
2020-01-03 00:00:00 Dwight        758     4951
                    Jim          1923     4226
                    Michael      1772     5982
                    Oscar         906     7075
2020-01-04 00:00:00 Creed        1314     3144
                    Jim           426     3868
                    Michael      1857     7917
                    Oscar        1767     2524
2020-01-05 00:00:00 Creed        1053      938
                    Dwight       1475     7771
                    Michael      1633     7837
                    Oscar         624     2793
Total                             368     8661

In [41]:
sales.head()

        Date   Name       Customer  Revenue  Expenses
0 2020-01-01  Oscar  Logistics XYZ     5250       531
1 2020-01-01  Oscar    Money Corp.     4406       661
2 2020-01-02  Oscar     PaperMaven     8661      1401
3 2020-01-03  Oscar    PaperGenius     7075       906
4 2020-01-04  Oscar    Paper Pound     2524      1767

In [47]:
pivot = sales.pivot_table(index='Name', columns='Date', values=['Revenue'], aggfunc='sum')
pivot

           Revenue
Date    2020-01-01 2020-01-02 2020-01-03 2020-01-04 2020-01-05
Name
Creed       4430.0    13214.0        NaN     3144.0      938.0
Dwight      2639.0        NaN    11912.0        NaN     7771.0
Jim         1864.0     8278.0     4226.0     6155.0        NaN
Michael     7172.0     6362.0     5982.0     7917.0     7837.0
Oscar       9656.0     8661.0     7075.0     2524.0     2793.0

In [48]:
pivot.stack()

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_4851/1039816244.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  pivot.stack()

                    Revenue
Name    Date
Creed   2020-01-01   4430.0
        2020-01-02  13214.0
        2020-01-04   3144.0
        2020-01-05    938.0
Dwight  2020-01-01   2639.0
        2020-01-03  11912.0
        2020-01-05   7771.0
Jim     2020-01-01   1864.0
        2020-01-02   8278.0
        2020-01-03   4226.0
        2020-01-04   6155.0
Michael 2020-01-01   7172.0
        2020-01-02   6362.0
        2020-01-03   5982.0
        2020-01-04   7917.0
        2020-01-05   7837.0
Oscar   2020-01-01   9656.0
        2020-01-02   8661.0
        2020-01-03   7075.0
        2020-01-04   2524.0
        2020-01-05   2793.0

In [50]:
pivot = sales.pivot_table(index=['Customer', 'Name'], values='Revenue', aggfunc='sum')
pivot

                           Revenue
Customer          Name
Average Paper Co. Creed      13214
                  Jim         2287
Best Paper Co.    Dwight      2703
                  Michael    15754
Logistics XYZ     Dwight      9209
                  Michael     7172
                  Oscar       5250
Money Corp.       Creed       5368
                  Jim         8278
                  Oscar       4406
Paper Pound       Dwight      7771
                  Jim         4226
                  Oscar       5317
PaperGenius       Dwight      2639
                  Jim         1864
                  Michael    12344
                  Oscar       7075
PaperMaven        Creed       3144
                  Jim         3868
                  Oscar       8661

In [51]:
pivot.unstack()

                   Revenue
Name                 Creed  Dwight     Jim  Michael   Oscar
Customer
Average Paper Co.  13214.0     NaN  2287.0      NaN     NaN
Best Paper Co.         NaN  2703.0     NaN  15754.0     NaN
Logistics XYZ          NaN  9209.0     NaN   7172.0  5250.0
Money Corp.         5368.0     NaN  8278.0      NaN  4406.0
Paper Pound            NaN  7771.0  4226.0      NaN  5317.0
PaperGenius            NaN  2639.0  1864.0  12344.0  7075.0
PaperMaven          3144.0     NaN  3868.0      NaN  8661.0

In [53]:
games = pd.read_csv('video_game_sales.csv')
games

,Name,NA,EU,JP,Other
0,Wii Sports,41.49,29.02,3.77,8.46
1,Super Mario Bros.,29.08,3.58,6.81,0.77
2,Mario Kart Wii,15.85,12.88,3.79,3.31
3,Wii Sports Resort,15.75,11.01,3.28,2.96
4,Pokemon Red/Pokemon Blue,11.27,8.89,10.22,1.00
...,...,...,...,...,...
16561,Woody Woodpecker in Crazy Castle 5,0.01,0.00,0.00,0.00
16562,Men in Black II: Alien Escape,0.01,0.00,0.00,0.00
16563,SCORE International Baja 1000: The Official Game,0.00,0.00,0.00,0.00
16564,Know How 2,0.00,0.01,0.00,0.00
16565,Spirits & Spells,0.01,0.00,0.00,0.00

In [57]:
games_region = games.melt(id_vars=['Name'], value_vars=['NA', 'EU', 'JP', 'Other'], var_name='Region', value_name='Sales')

In [58]:
games_region

                                                   Name Region  Sales
0                                            Wii Sports     NA  41.49
1                                     Super Mario Bros.     NA  29.08
2                                        Mario Kart Wii     NA  15.85
3                                     Wii Sports Resort     NA  15.75
4                              Pokemon Red/Pokemon Blue     NA  11.27
...                                                 ...    ...    ...
66259                Woody Woodpecker in Crazy Castle 5  Other   0.00
66260                     Men in Black II: Alien Escape  Other   0.00
66261  SCORE International Baja 1000: The Official Game  Other   0.00
66262                                        Know How 2  Other   0.00
66263                                  Spirits & Spells  Other   0.00

[66264 rows x 3 columns]

In [59]:
games_region.pivot_table(index='Name', values='Sales', aggfunc='sum', margins=True, margins_name='Total')

                                 Sales
Name
'98 Koshien                       0.40
.hack//G.U. Vol.1//Rebirth        0.17
.hack//G.U. Vol.2//Reminisce      0.23
.hack//G.U. Vol.3//Redemption     0.17
.hack//Infection Part 1           1.26
...                                ...
thinkSMART: Chess for Kids        0.01
uDraw Studio                      2.45
uDraw Studio: Instant Artist      0.21
¡Shin Chan Flipa en colores!      0.14
Total                          8908.49

[11463 rows x 1 columns]

In [60]:
recipes = pd.read_csv('recipes.csv')
recipes

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  Apricot preserves, Dijon mustard, curry powder...
1      Tomato Basil Salmon  Salmon filets, basil, tomato, olive oil, Parme...
2  Parmesan Cheese Chicken  Bread crumbs, Parmesan cheese, Italian seasoni...

In [62]:
recipes['Ingredients'].str.split(pat=', ')

0    [Apricot preserves, Dijon mustard, curry powde...
1    [Salmon filets, basil, tomato, olive oil, Parm...
2    [Bread crumbs, Parmesan cheese, Italian season...
Name: Ingredients, dtype: object

In [63]:
recipes['Ingredients'] = recipes['Ingredients'].str.split(pat=', ')

In [64]:
recipes

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  [Apricot preserves, Dijon mustard, curry powde...
1      Tomato Basil Salmon  [Salmon filets, basil, tomato, olive oil, Parm...
2  Parmesan Cheese Chicken  [Bread crumbs, Parmesan cheese, Italian season...

In [65]:
recipes.explode('Ingredients')

                    Recipe        Ingredients
0   Cashew Crusted Chicken  Apricot preserves
0   Cashew Crusted Chicken      Dijon mustard
0   Cashew Crusted Chicken       curry powder
0   Cashew Crusted Chicken    chicken breasts
0   Cashew Crusted Chicken            cashews
1      Tomato Basil Salmon      Salmon filets
1      Tomato Basil Salmon              basil
1      Tomato Basil Salmon             tomato
1      Tomato Basil Salmon          olive oil
1      Tomato Basil Salmon    Parmesan cheese
2  Parmesan Cheese Chicken       Bread crumbs
2  Parmesan Cheese Chicken    Parmesan cheese
2  Parmesan Cheese Chicken  Italian seasoning
2  Parmesan Cheese Chicken                egg
2  Parmesan Cheese Chicken    chicken breasts

In [67]:
recipes.explode('Recipe')  # списка нет, поэтому ничего не развернулось

                    Recipe                                        Ingredients
0   Cashew Crusted Chicken  [Apricot preserves, Dijon mustard, curry powde...
1      Tomato Basil Salmon  [Salmon filets, basil, tomato, olive oil, Parm...
2  Parmesan Cheese Chicken  [Bread crumbs, Parmesan cheese, Italian season...

In [68]:
# Homework

In [69]:
cars = pd.read_csv('used_cars.csv')
cars.head()

  Manufacturer  Year Fuel Transmission  Price
0        Acura  2012  Gas    Automatic  10299
1       Jaguar  2011  Gas    Automatic   9500
2        Honda  2004  Gas    Automatic   3995
3    Chevrolet  2016  Gas    Automatic  41988
4          Kia  2015  Gas    Automatic  12995

In [71]:
wages = pd.read_csv('minimum_wage.csv')
wages.head()

        State  2010  2011  2012  2013  2014  2015   2016   2017
0     Alabama  0.00  0.00  0.00  0.00  0.00  0.00   0.00   0.00
1      Alaska  8.90  8.63  8.45  8.33  8.20  9.24  10.17  10.01
2     Arizona  8.33  8.18  8.34  8.38  8.36  8.50   8.40  10.22
3    Arkansas  7.18  6.96  6.82  6.72  6.61  7.92   8.35   8.68
4  California  9.19  8.91  8.72  8.60  9.52  9.51  10.43  10.22

In [72]:
len(cars)

460466

In [73]:
len(wages)

55

In [74]:
wages['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Federal (FLSA)', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Puerto Rico', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'U.S. Virgin Islands',
       'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype=object)

In [75]:
# 1
cars.head()

  Manufacturer  Year Fuel Transmission  Price
0        Acura  2012  Gas    Automatic  10299
1       Jaguar  2011  Gas    Automatic   9500
2        Honda  2004  Gas    Automatic   3995
3    Chevrolet  2016  Gas    Automatic  41988
4          Kia  2015  Gas    Automatic  12995

In [76]:
cars.pivot_table(index='Fuel', values='Price', aggfunc='sum')

                Price
Fuel
Diesel      986177143
Electric     18502957
Gas       86203853926
Hybrid       44926064
Other       242096286

In [80]:
# 2
cars.pivot_table(index='Manufacturer', columns='Transmission', values='Price', aggfunc='count', fill_value=0, margins=True)

Transmission     Automatic  Manual  Other     All
Manufacturer
Acura                 3443     141     48    3632
Alfa-Romeo              50       0     11      61
Aston-Martin            20       5      0      25
Audi                  4974     375     69    5418
BMW                  11641     774    627   13042
Buick                 6187      17    265    6469
Cadillac              6357      74    406    6837
Chevrolet            61006    1820   4255   67081
Chrysler              7553     133    212    7898
Dodge                14338     626    991   15955
Ferrari                 29       4      9      42
Fiat                   435     220    187     842
Ford                 75980    2979   3505   82464
GMC                  19504     137    939   20580
Harley-Davidson        115      61     10     186
Hennessey                0       1      0       1
Honda                20666    1502    921   23089
Hyundai              10350     544    334   11228
Infiniti              3555     185     76    3816
Jaguar                 882      29     50     961
Jeep                 17687    2316   1385   21388
Kia                   7615     466    587    8668
Land Rover              23       0      0      23
Lexus                 5573      30    226    5829
Lincoln               3001      10     51    3062
Mazda                 4127     746    649    5522
Mercedes-Benz         9599      74     98    9771
Mercury               1437      15      2    1454
Mini                  1411     712    138    2261
Mitsubishi            2064     247     52    2363
Nissan               22262     858   1429   24549
Pontiac               2710     213     28    2951
Porche                   9       1      0      10
Ram                  19996     837   1243   22076
Rover                 1752       9     24    1785
Saturn                1451     152     12    1615
Subaru                8317    1884    420   10621
Tesla                  179       0     59     238
Toyota               31480    1367   2134   34981
Volkswagen            7985    1286    236    9507
Volvo                 2665     155     50    2870
All                 398428   21005  21738  441171

In [83]:
# 3
cars.pivot_table(index=['Year', 'Fuel'], columns='Transmission', values='Price', aggfunc='mean', margins=True, fill_value=0)

Transmission       Automatic         Manual         Other            All
Year Fuel
2000 Diesel     11326.176962   14010.164021  11075.000000   11960.930905
     Electric    1500.000000       0.000000      0.000000    1500.000000
     Gas         4314.675996    6226.140327   3203.538462    4562.371755
     Hybrid      2600.000000    2400.000000      0.000000    2533.333333
     Other      16014.918919   11361.952381  12984.642857   14068.583333
...                      ...            ...           ...            ...
2020 Electric    8015.166667    2200.000000  20247.500000   10087.333333
     Gas        34925.857933   36007.270833  20971.045455   34630.169385
     Hybrid     35753.200000       0.000000   1234.000000   30000.000000
     Other      22210.306452       0.000000   2725.925926   13139.991379
All            195440.175965  302228.583811  24596.540139  192371.655888

[103 rows x 4 columns]

In [84]:
# 4
pivot = cars.pivot_table(index=['Year', 'Fuel'], columns='Transmission', values='Price', aggfunc='mean', margins=True, fill_value=0)

In [85]:
pivot

Transmission       Automatic         Manual         Other            All
Year Fuel
2000 Diesel     11326.176962   14010.164021  11075.000000   11960.930905
     Electric    1500.000000       0.000000      0.000000    1500.000000
     Gas         4314.675996    6226.140327   3203.538462    4562.371755
     Hybrid      2600.000000    2400.000000      0.000000    2533.333333
     Other      16014.918919   11361.952381  12984.642857   14068.583333
...                      ...            ...           ...            ...
2020 Electric    8015.166667    2200.000000  20247.500000   10087.333333
     Gas        34925.857933   36007.270833  20971.045455   34630.169385
     Hybrid     35753.200000       0.000000   1234.000000   30000.000000
     Other      22210.306452       0.000000   2725.925926   13139.991379
All            195440.175965  302228.583811  24596.540139  192371.655888

[103 rows x 4 columns]

In [86]:
pivot.stack()

Year  Fuel      Transmission
2000  Diesel    Automatic        11326.176962
                Manual           14010.164021
                Other            11075.000000
                All              11960.930905
      Electric  Automatic         1500.000000
                                    ...
2020  Other     All              13139.991379
All             Automatic       195440.175965
                Manual          302228.583811
                Other            24596.540139
                All             192371.655888
Length: 412, dtype: float64

In [87]:
type(pivot)

pandas.core.frame.DataFrame

In [88]:
# 5
wages.head()

        State  2010  2011  2012  2013  2014  2015   2016   2017
0     Alabama  0.00  0.00  0.00  0.00  0.00  0.00   0.00   0.00
1      Alaska  8.90  8.63  8.45  8.33  8.20  9.24  10.17  10.01
2     Arizona  8.33  8.18  8.34  8.38  8.36  8.50   8.40  10.22
3    Arkansas  7.18  6.96  6.82  6.72  6.61  7.92   8.35   8.68
4  California  9.19  8.91  8.72  8.60  9.52  9.51  10.43  10.22

In [97]:
years = np.arange(2010, 2018, 1).astype('str')
years

array(['2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017'],
      dtype='<U21')

In [99]:
wages.melt(id_vars='State', value_vars=years, var_name='Year', value_name='Min Wage')

             State  Year  Min Wage
0          Alabama  2010      0.00
1           Alaska  2010      8.90
2          Arizona  2010      8.33
3         Arkansas  2010      7.18
4       California  2010      9.19
..             ...   ...       ...
435       Virginia  2017      7.41
436     Washington  2017     11.24
437  West Virginia  2017      8.94
438      Wisconsin  2017      7.41
439        Wyoming  2017      5.26

[440 rows x 3 columns]